### ISSUE TITLE
it should provide ONBUILD hooks to install composer deps

### ISSUE THREAD

**Issue by docteurklein** [docker-library/php#100]
To my mind it would be cool to provide an alternative image containing `ONBUILD` instructions
 to simplify installation of vendors in an image.

The same as the official [python image does](https://github.com/docker-library/python/blob/db31004d42a1aabbb9109177b2794f088f245b33/3.4/onbuild/Dockerfile).

**Comment by docteurklein** [comment]
An example:

```

FROM php:5.6

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ONBUILD COPY . /usr/src/app
WORKDIR /usr/src/app

RUN composer install --prefer-dist

```

**Comment by yosifkit** [comment]
I would be hesitant since `composer` is not part of php upstream, nor is it endorsed by them, or even the defacto standard (ie, wordpress and other large php projects do not use it).  This would also double the number of different tags on a already long list of [tags](https://registry.hub.docker.com/_/php/).  I would also point out that `onbuild` images are more a stepping stone rather than the solution for everyone (https://github.com/docker-library/rails/issues/28#issuecomment-92425135).  Even so, I think it would be useful to have documentation for using composer with the php images ([docs/php/content.md](https://github.com/docker-library/docs/blob/master/php/content.md)).

**Comment by tianon** [comment]
Also, a nicer pattern for doing so would probably be something like the following (mimicking both `python` and `ruby` for better caching and less module re-installs during development):
```Dockerfile
FROM php:5.6
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY composer.json /usr/src/app/
RUN composer install --prefer-dist --ignore-platform-reqs
COPY . /usr/src/app
```

**Comment by thaJeztah** [comment]
> or even the defacto standard (ie, wordpress and other large php projects do not use it)

I agree with your points on the long tags list. Not sure if WordPress should be used as a "benchmark" for PHP standards :innocent:

**Comment by docteurklein** [comment]
@yosifkit I understand and agree about the fact it doubles the tag list, which is confusing.
Composer is not official, but it surely is the most used package manager out there (except pear/pecl/pickle).

Still, composer can be hard to make it work in docker (lots of diffirent constraints to manage), and having it already made by the official image could be cool.
One possible way would be to document it correctly, as you proposed.

@tianon I noticed this pattern in python (COPY the deps file first, then the rest), but I didn't understand the difference with copying all at once. Can you explain?

Cheers!

**Comment by docteurklein** [comment]
@tianon I'm trying right now to separate COPY (to favorise intermediate step caching), and I just noticed a problem: some composer files have post-install hooks that try to put stuff in your sources (symfony-standard f.e). The problem is that these files aren't here yet!

**Comment by docteurklein** [comment]
I guess it's more a problem of the child image that inherits from it to ensure all the dirs are here.

**Comment by tianon** [comment]
Given that #177 has some good discussion regarding adding `composer` to the default install, I'm going to close this issue.

I'm very strongly -1 on adding `:onbuild` variants to this image whether we have `composer` or not -- I don't think there's really a reasonable justification for doing so, especially given that the `Dockerfile` for doing what's necessary in a new image is reasonably simple and the discussion above regarding our already-bloated variants list.
