### ISSUE TITLE
PHP 7.4.5 - no matching manifest 

### ISSUE THREAD

**Issue by michaljusiega** [docker-library/php#1001]
> Deploying 'Compose: docker-compose-prod.yml'...
> docker-compose -f E:\PROJEKTY\intranet\docker-compose-prod.yml up -d
> Building intranet_prod
> Step 1/43 : ARG PHP_MAJOR
> Step 2/43 : ARG PHP_MINOR
> Step 3/43 : ARG PHP_RELEASE
> Step 4/43 : FROM php:$PHP_MAJOR.$PHP_MINOR.$PHP_RELEASE-apache-buster
> 7.4.5-apache-buster: Pulling from library/php
> Service 'intranet_prod' failed to build: no matching manifest for linux/amd64 in the manifest list entries

Trying to bump my service with PHP 7.4.5 - working on 7.4.4. Thanks :)

**Comment by GrahamCampbell** [comment]
Yes, it looks like the `linux/amd64` build failed.

**Comment by tianon** [comment]
We had a larger than normal backlog thanks to https://github.com/docker-library/official-images/pull/7794, but this is fixed/up now.
