### ISSUE TITLE
7.2.30 security update missing

### ISSUE THREAD

**Issue by GrahamCampbell** [docker-library/php#1002]
PHP 7.2.30 was released yesterday (16th April 2020).

**Comment by phy25** [comment]
As of now it's not appearing on https://www.php.net/ so it's not released yet.

**Comment by GrahamCampbell** [comment]
That website lags behind the official releases unfortunately. It was actually released yesterday: https://github.com/php/php-src/blob/PHP-7.2/NEWS#L6 and is already ready to download from the official website, even though the news feed lags behind (see https://github.com/php-build/php-build/pull/614).

**Comment by phy25** [comment]
See https://github.com/docker-library/php/issues/998#issuecomment-614278057

**Comment by GrahamCampbell** [comment]
https://github.com/docker-library/php/issues/998#issuecomment-615249447

Evidence the downloads all exist and work is at php-build/php-build#614.

**Comment by tianon** [comment]
Why isn't it included in https://www.php.net/releases/index.php?json&max=100&version=7.2 yet? :confused:

**Comment by tianon** [comment]
I believe https://github.com/php/web-php/blob/8ca4cff3bbedc3b7d1adf66af8f123b3c7890fe6/include/releases.inc needs an update.

**Comment by tianon** [comment]
@sgolemon is an official announcement / update to `web-php` for 7.2.30 in the works?  Would a PR adding at least the basic metadata be helpful or just distracting at this point? :pray: :heart:

**Comment by tianon** [comment]
... and now I see https://github.com/php/web-php/commit/04aca2a1a40e147c93b13810b258e3c2b67da639 :sweat_smile: :heart:

Thank you!! :+1:
