### ISSUE TITLE
There is a problem with the alpine tag

### ISSUE THREAD

**Issue by wojiukankan** [docker-library/php#1005]
The alpine image cannot use PECL directly, and phpize will be prompted for missing。

**Comment by phy25** [comment]
Duplicate of #412.

**Comment by yosifkit** [comment]
https://hub.docker.com/_/php/:

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile

Also duplicate #919
