### ISSUE TITLE
openssl security issue on debian stable images

### ISSUE THREAD

**Issue by dlen** [docker-library/php#1006]
Hi!

I just noticed that the openssl version bundled with the docker images on debian stable has some security upgrade https://www.debian.org/security/2020/dsa-4661 patches are already available on the debian repos.
```
docker run -ti php:7.3.17-fpm bash                                                                                          
root@ffbefd928b33:/var/www/html# dpkg -l |grep openssl
ii  openssl                   1.1.1d-0+deb10u2            amd64        Secure Sockets Layer toolkit - cryptographic utility
```

Thanks for the great job you are doing making all these images available!

**Comment by tianon** [comment]
Yep, Debian was updated in https://github.com/docker-library/official-images/pull/7858, Alpine in https://github.com/docker-library/official-images/pull/7867, and Ubuntu in https://github.com/docker-library/official-images/pull/7865, so at this point it's just a matter of waiting for the queue to process through all the downstream builds. :+1:
