### ISSUE TITLE
php:7.4.4-apache : install composer

### ISSUE THREAD

**Issue by Maels1991** [docker-library/php#1008]
Hello,

I'm used to install composer next to PHP, in the same container.
Today i've tried php:7.4.4-apache, everything works fine but I've encountered something, not too dramatic but puzzling to me :

The following fails with error "/bin/sh: 1:  php: not found"
> RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

But it works with :
> RUN curl -sS https://getcomposer.org/installer | /usr/local/bin/php -- --install-dir=/usr/local/bin --filename=composer

The defined path in the container is 
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

And "php -v" works as expected issuing 7.4.4, etc.

In others container from php images, it works the good way.

Any explanation ? Thanks :)

**Comment by wglambert** [comment]
I can't reproduce

```dockerfile
FROM php:7.4.4-apache
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
```

```console
$ docker build . -t php:test
Sending build context to Docker daemon  38.15MB
Step 1/2 : FROM php:7.4.4-apache
 ---> 40f50190fa37
Step 2/2 : RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
 ---> Running in 41458cf3acfe
All settings correct for using Composer
Downloading...

Composer (version 1.10.5) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Removing intermediate container 41458cf3acfe
 ---> 93648aac4bba
Successfully built 93648aac4bba
Successfully tagged php:test
```

**Comment by tianon** [comment]
An even easier way to install is documented on the `composer` official image description (https://hub.docker.com/_/composer):

```dockerfile
FROM php:7.4-apache
COPY --from=composer /usr/bin/composer /usr/bin/composer
```

**Comment by Maels1991** [comment]
@wglambert Thanks for your reply. Don't known what was wrong earlier this day but you're right, it now works fine without changing anything ... :)

Thanks @tianon for giving me this tips.
