### ISSUE TITLE
Update Alpine curl to 7.68.0

### ISSUE THREAD

**Issue by WouterFlorijn** [docker-library/php#1012]
Because of [this issue](https://github.com/curl/curl/issues/4624) curl version 7.67.0 is unusable for some people (including me). I currently can't upgrade to PHP 7.4.5 on Alpine because of this.

curl 7.68 was released on 2020-01-08 with a fix for this. Can the `alpine`-tagged images be updated to use this new version? I don't know enough about the way curl is installed to install it manually (I've tried a lot of things, but nothing worked). If anyone can tell me how to do that for now, that would be great as well.

**Comment by wglambert** [comment]
The latest curl in Alpine's package repo is 7.67.0 https://pkgs.alpinelinux.org/package/v3.11/main/x86_64/curl

So the image is at the latest version currently

```console
$ docker run -it --rm php:7.4-alpine ash

/ # apk add --upgrade curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
OK: 12 MiB in 31 packages

/ # curl --version
curl 7.67.0 (x86_64-alpine-linux-musl) libcurl/7.67.0 OpenSSL/1.1.1g zlib/1.2.11 nghttp2/1.40.0
Release-Date: 2019-11-06
```

**Comment by WouterFlorijn** [comment]
@wglambert then perhaps it would be a good idea to downgrade to curl 7.66.0?

**Comment by yosifkit** [comment]
> Currently, there is no way to install arbitrary older versions of a package from official repositories in Alpine Linux
>
> https://superuser.com/a/1057145

It might be possible to install curl from the Alpine `3.10` packages (see the linked superuser.com), but that is not something we would be doing in the official image.

You also could try filing a bug with Alpine to see if they'll push the curl update from edge to 3.11.
