### ISSUE TITLE
7.4.6-apache: Pulling from library/php - no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by mathieu-benoit** [docker-library/php#1017]
`docker pull php:7.4.6-apache` results with this error:
```
7.4.6-apache: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

When looking at here https://hub.docker.com/_/php?tab=tags&page=1&name=7.4.6-apache we indeed just see those 2 `OS/ARCH`:
```
linux/arm/v5
linux/s390x
```

Is the `linux/amd64` `OS/ARCH` missing?

**Comment by tianon** [comment]
The builds are still in progress; see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what for more information.
