### ISSUE TITLE
PHP 7.4.5 and 7.3.19 Missing

### ISSUE THREAD

**Issue by GrahamCampbell** [docker-library/php#1024]

**Comment by phy25** [comment]
Please be patient while the bot works through its way: 424dbd51d6699f2432f68f22cc2a910672a7bdfd

See also: "See a change merged here that doesn't show up on Docker Hub yet?" https://github.com/docker-library/php/blob/master/README.md#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
