### ISSUE TITLE
How do I install additional locales/languages?

### ISSUE THREAD

**Issue by Waldkoenig** [docker-library/php#1041]
locale -a only has
C
C.UTF-8
POSIX

and I need something like de-DE to get proper formatting for my php website.

Or am I doing something wrong? I'm using setlocale(LC_ALL, 'de_DE@euro', 'de_DE', 'deu_deu') but no matter what it returns, the language settings won't change.

**Comment by Waldkoenig** [comment]
I don't see any way to tag this as a question instead of an issue. Sorry.

**Comment by wglambert** [comment]
From https://github.com/docker-library/php/issues/359#issuecomment-271784228 the default `LANG` is `C` so changing that to `C.UTF-8` allows it to see UTF-8 characters

```console
$ docker run -it -e LC_ALL=C.UTF-8 -e LANG="de_DE@euro"--rm php bash

root@48fd94f8dfbc:/# mkdir Übersetzen

root@48fd94f8dfbc:/# touch Übersetzen/Grüße_Welt

root@48fd94f8dfbc:/# ls Übersetzen
Grüße_Welt
```

**Comment by Waldkoenig** [comment]
Thanks, but I need to install language packs for PHP so that it properly supports spitting out "0,75" (COMMA) instead of "0.75" (DOT) when I "echo 3/4".

UTF8 characters haven't been a problem so far...

**Comment by Waldkoenig** [comment]
Or is this just how PHP works? US locale settings only?

What is setlocale() for then? 

Should I use something else than docker/php for international websites?

**Comment by yosifkit** [comment]
PHP probably just uses what libc provides. So, most likely you would need to install `locales`, update `/etc/locale.gen` via `sed` to uncomment out the locales you need, and then run `locale-gen` (https://wiki.archlinux.org/index.php/Locale)

**Comment by Waldkoenig** [comment]
Neither locale.gen nor /etc/locale.gen are available in docker/php and I think that's because it is based on Alpine Linux and not Arch Linux.

I feel like I'm doing something massively wrong because I can't comprehend why it is so damn hard to get additional languages to work.

**Comment by yosifkit** [comment]
Alpine doesn't really have support for locales (https://github.com/gliderlabs/docker-alpine/issues/144). There are users in that thread and [here](https://grrr.tech/posts/2020/add-locales-to-alpine-linux-docker-image/) that are adding some locales to Alpine, but I'm not certain that their methods will work in the future.

Alternatively you could just use the non-alpine images that are Debian based and just `apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/*` to install `locale-gen` and `/etc/locale.gen`.

**Comment by Waldkoenig** [comment]
Okay, I'll try to find one that runs on a Raspberry Pi. :(

Again though, am I using something wrong here? It feels like a massive oversight that docker/php with multiple millions of downloads isn't supporting locales.

**Comment by phy25** [comment]
> Again though, am I using something wrong here? It feels like a massive oversight that docker/php with multiple millions of downloads isn't supporting locales.

If you read the comment again it's just that alpine doesn't support locales. This set of images has the Debian version as the default for these kind of customization reasons.

**Comment by Waldkoenig** [comment]
Okay, I don't know what I did wrong until now, but I was under the impression that all docker/php images were alpine. Thank you for helping me out. I probably pulled the wrong images by accident.

**Comment by wglambert** [comment]
Closing since this seems resolved
