### ISSUE TITLE
Order of php-ext-install command affects some features of GD library like freetype and jpeg - Bug PHP 7.4.x - 

### ISSUE THREAD

**Issue by shyamjos** [docker-library/php#1047]
There is a strange bug in 7.4.x image that some features of GD library won't work unless the gd extension is first one to install.

# How to reproduce ?

Install any other library before installing gd 
```
FROM php:7.4.8-fpm
.....

RUN docker-php-ext-install -j$(nproc) pdo_mysql
RUN docker-php-ext-install -j$(nproc) mysqli
RUN docker-php-ext-install -j$(nproc) pdo
RUN docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install -j$(nproc) intl
RUN docker-php-ext-install -j$(nproc) zip
```
```
php -r 'print_r(gd_info());'
Array
(
    [GD Version] => bundled (2.1.0 compatible)
    [FreeType Support] =>       <----------Support not enabled 
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] =>           <----------Support not enabled 
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 
    [XBM Support] => 1
    [WebP Support] => 
    [BMP Support] => 1
    [TGA Read Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```
# Solution 
As per this [comment](https://github.com/docker-library/php/issues/926#issuecomment-567230723) Installing gd before installing any other extensions will fix this issue

```
FROM php:7.4.8-fpm
.....
RUN docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install -j$(nproc) opcache
RUN docker-php-ext-install -j$(nproc) pdo_mysql
RUN docker-php-ext-install -j$(nproc) mysqli
RUN docker-php-ext-install -j$(nproc) intl
RUN docker-php-ext-install -j$(nproc) zip
```
```
php -r 'print_r(gd_info());'
Array
(
    [GD Version] => bundled (2.1.0 compatible)
    [FreeType Support] => 1  <----------Support enabled 
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1      <----------Support enabled 
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 
    [XBM Support] => 1
    [WebP Support] => 1
    [BMP Support] => 1
    [TGA Read Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```
Is this an expected behavior or bug ?

**Comment by tianon** [comment]
Copying from https://github.com/docker-library/php/issues/926#issuecomment-673012941 for posterity:

> I thought this was odd, but had an epiphany this morning -- it's not a "bug" of `docker-php-ext-install`, but rather a feature:
> 
> https://github.com/docker-library/php/blob/098e442542e8a10bdee2c22484a98d41583a8fb9/docker-php-ext-install#L123
> 
> When it finishes working, `docker-php-ext-install` will delete the source code (which includes all the bits configured by `docker-php-ext-configure`).  The intention is that you run `docker-php-ext-configure` some number of times, then run a *single* invocation of `docker-php-ext-install` (because there's really no reason to run those separately); also, it would be good to run them all in the same layer so the image doesn't bloat with the size of the PHP source code:
> 
> ```dockerfile
> # configure, install and enable all php packages
> RUN set -eux; \
> 	docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp; \
> 	docker-php-ext-configure intl; \
> 	docker-php-ext-configure mysqli --with-mysqli=mysqlnd; \
> 	docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd; \
> 	docker-php-ext-configure zip; \
> 	docker-php-ext-install -j "$(nproc)" \
> 		gd \
> 		intl \
> 		mysqli \
> 		opcache \
> 		pdo_mysql \
> 		zip
> ```
