### ISSUE TITLE
Pecl not available in php:8.0.0beta1-fpm-alpine3.12

### ISSUE THREAD

**Issue by adhocore** [docker-library/php#1050]
I am trying to test out PHP8 beta on top alpine but need some extensions that are installed with pecl command.

But seems like `php:8.0.0beta1-fpm-alpine3.12` tag does not have pecl already.

I tried to run:
```sh
pecl install apcu ast ds ev hrtime igbinary imagick lzf lua mongodb msgpack oauth pcov psr redis  ssh2-1.2 uuid xdebug xlswriter yaf yaml
```

Is there a way to install pecl or workaround? Thanks

**Comment by michaljusiega** [comment]
See https://github.com/docker-library/php/issues/1029#issuecomment-650576137
