### ISSUE TITLE
PHP Fatal error:  Uncaught Google\Cloud\Core\Exception\ServiceException: cURL error 6: Could not resolve host: storage.googleapis.com

### ISSUE THREAD

**Issue by samuelgeek** [docker-library/php#1051]
Dear, I am setting up an infrastructure with nginx and php-fpm using VM for NGINX and Kubernetes for php-fpm. I'm trying to use a Google API that communicates with the bucket to upload images and files but when I run the code in php I get the following error:

NOTICE: PHP message: PHP Fatal error: Uncaught Google \ Cloud \ Core \ Exception \ ServiceException: cURL error 6: Could not resolve host: storage.googleapis.com (see https://curl.haxx.se/libcurl/c/ libcurl-errors.html) in /vendor/google/cloud-core/src/RequestWrapper.php:362

When I use the php: 7.3-apache image the problem is solved and I can upload my files normally, only in the php: 7.3-fpm or php: 7.3-fpm-alpine image that gives this DNS name resolution problem , I've been searching the internet for this and it seems like a problem in the **glibc** library.

can you help me?

```
<?php
include 'vendor/autoload.php';
use Google\Cloud\Storage\StorageClient;

$storage = new StorageClient();
$bucket = $storage->bucket('proloja-static');

// Upload a file to the bucket.
$bucket->upload(
    fopen('robots.txt', 'r')
);
?>
```

**Comment by wglambert** [comment]
If you could get a minimal reproducer that would help with probing around
Seems like a DNS issue with host resolution, can you ping/curl that address in `php:fpm`

Also Alpine uses musl instead of glibc https://github.com/docker-library/docs/tree/master/php#phpversion-alpine

**Comment by samuelgeek** [comment]
I did the test with nslookup and the name is being resolved normally, I did tests with ping and telnet and I was successful.
![WhatsApp Image 2020-08-17 at 11 39 23](https://user-images.githubusercontent.com/9256333/90415589-ad3ec400-e087-11ea-809e-4acefd6a4f38.jpeg)

**Comment by samuelgeek** [comment]
I found the solution to my problem, the operating system's DNS was resolving the name normally but my php-fpm configuration was chrooted and when chroot is enabled, php-fpm has some limitations within the operating system.
[https://stackoverflow.com/questions/47915774/chrooted-php-fpm-script-cannot-resolve-dns-after-a-moment](url)
