### ISSUE TITLE
Arbitrary but non-existent user

### ISSUE THREAD

**Issue by carloscarnero** [docker-library/php#1053]
I'm trying to run the Apache version with a custom user and group IDs which do not exist in the image, by setting A`PACHE_RUN_USER` and `APACHE_RUN_GROUP`. Apache complains and it goes to run as `root`, and I'm assuming that behaviour is caused by the fact that there's no actual user with the ID.

Creating the user on image build is not an option because the same image is used hundreds of times for different users (source PHP code is mounted via shared NFS.) I was thinking on modifying `apache2-foreground` and creating the user dynamically, on container start up, but I was wondering if there's a better way, or if there's another start-up hook that I can attach to.

**Comment by yosifkit** [comment]
I was quite certain that this worked in the past but I can't find an image that will work and the code in Apache2 hasn't changed in like 12 years. :confused:

I guess the change is to add a note to using `APACHE_RUN_USER` that the user and group must exist in the container (via adduser/group or mounting `/etc/passwd:ro`) otherwise it will happily run as `root`.  The alternate is to remove suggesting `APACHE_RUN_USER` and just stick to `--user` (and `--sysctl` for "privileged" ports).

**Comment by tianon** [comment]
I think we should remove any mention of `APACHE_RUN_USER`, especially since the failure mode is that it runs as root instead with nothing but a warning (why is that not an error??).  That's pretty severe IMO, and really gives a hit to my trust of Apache2 in general. :disappointed:

**Comment by carloscarnero** [comment]
With a [simple customization](https://github.com/docker-library/php/issues/1030#issuecomment-651314611) I reconfigured Apache so that will listen in a non-privileged port. I tried running the container as:

```
docker run -it --rm \
  --user 5104:5104 \
  -p 8000:8000 \
  php:7.4.9-apache-buster
```

and `exec`ing into the container:

```
...@aa11af981d9d:/var/www/html$ ps axu
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
5104           1  0.5  0.1  83316 24392 pts/0    Ss+  18:48   0:00 apache2 -DFOREGROUND
5104          16  0.0  0.0  83340  5008 pts/0    S+   18:48   0:00 apache2 -DFOREGROUND
5104          17  0.0  0.0  83340  5008 pts/0    S+   18:48   0:00 apache2 -DFOREGROUND
5104          18  0.0  0.0  83340  5008 pts/0    S+   18:48   0:00 apache2 -DFOREGROUND
5104          19  0.0  0.0  83340  5008 pts/0    S+   18:48   0:00 apache2 -DFOREGROUND
5104          20  0.0  0.0  83340  5008 pts/0    S+   18:48   0:00 apache2 -DFOREGROUND
5104          21  1.0  0.0   3872  3152 pts/1    Ss   18:48   0:00 /bin/bash
5104          26  0.0  0.0   7644  2708 pts/1    R+   18:48   0:00 ps axu
```

Which means that this method works for me, instead of the environment variables. It's a shame, but at least it will let me configure the user ID at run-time.
