### ISSUE TITLE
php-intl missing from 7-alpine

### ISSUE THREAD

**Issue by lachlan-00** [docker-library/php#1055]
can you put it in? it's an official module right?

**Comment by phy25** [comment]
You should be able to add it in your image according to https://github.com/docker-library/php/issues/326. Does that work for you?

**Comment by lachlan-00** [comment]
that does it

i used:
```
RUN     apk add --no-cache php-intl icu-dev \
    &&  docker-php-ext-install intl
```

**Comment by tianon** [comment]
You do not want to `apk add php-intl` or your image will end up with two versions of PHP installed.

**Comment by alexandrupetrini** [comment]
`
RUN apk add --update --no-cache $PHPIZE_DEPS icu-libs icu-dev && \
    docker-php-ext-install intl
`
