### ISSUE TITLE
Installing sqlite3 extension fails

### ISSUE THREAD

**Issue by colinodell** [docker-library/php#1058]
Attempting to install sqlite3 no longer works.  The following Dockerfile demonstrates this issue:

```
FROM php:7.4

RUN docker-php-ext-install sqlite3
```

Attempting to build this results in the following output:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.4
 ---> b73215b5e2cc
Step 2/2 : RUN docker-php-ext-install sqlite3
 ---> Running in 010a2e0f48e8
Cannot find config.m4. 
Make sure that you run '/usr/local/bin/phpize' in the top level source directory of the module

The command '/bin/sh -c docker-php-ext-install sqlite3' returned a non-zero code: 1
```

This used to work just fine but has recently stopped working which suggests a regression or breaking change may have been introduced in a recent tag.  I unfortunately don't have a record of which tag (or included PHP version) this was previously working in.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions
>Many extensions are already compiled into the image, so it's worth checking the output of php -m or php -i before going through the effort of compiling more.



```console
$ docker run -it --rm php:7.4 bash
Unable to find image 'php:7.4' locally
7.4: Pulling from library/php
d121f8d1c412: Pull complete 
58b3577b786a: Pull complete 
60538287851f: Pull complete 
c53ff72fe225: Pull complete 
299e2d339089: Pull complete 
1f513124ac75: Pull complete 
8fa670f23a5f: Pull complete 
39c44fb2f532: Pull complete 
613a4f06c077: Pull complete 
Digest: sha256:e5866e36139793457d26939e5c97e503f2d0bf79a90bf85db1937d5c282c40e3
Status: Downloaded newer image for php:7.4

root@c394a3e3fd3e:/# php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib
```

**Comment by colinodell** [comment]
Gotcha, thanks for that info!  I'm still not sure what changed recently to cause this to suddenly stop working, but switching away from (re-)compiling it seems like a sensible approach.  Hopefully this issue helps anyone else experiencing the same issue.  Thanks!

**Comment by abdulrehmanjaved-1** [comment]
Thankyou, It helps me for php 8.2.
