### ISSUE TITLE
How to install ext-hash ?

### ISSUE THREAD

**Issue by Pictor13** [docker-library/php#1060]
I am using the [`hash_hmac`](https://www.php.net/manual/en/function.hash-hmac.php) function in my project code, but the required PHP extension *hash* is not available.
From what I could see it is not installed at all.

As shown in the following log, I tried to use `docker-php-ext-install` to add it, but it fails:

```
Step 11/14 : ARG PHP_EXT_INSTALL_BASE="ext-hash"
 ---> Running in 5858f16a7bf3
Removing intermediate container 5858f16a7bf3
 ---> 0ea2498d5b47
Step 12/14 : RUN test -z ${PHP_EXT_INSTALL_BASE} || docker-php-ext-install ${PHP_EXT_INSTALL_BASE}
 ---> Running in 06db03c5bdc7
tar (child): /usr/src/php.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Maybe the cleaning after the install prevents the file `/usr/src/php.tar.xz` from being there.

Is the extension supported in any way out of the box?
Do I need to run some `docker-apt-clean-install` first?
How can `php7.4-hash` be installed without using too many hacks?

**Comment by wglambert** [comment]
I can't reproduce an issue with hash
```console
$ docker run -it --rm php bash
root@3628946cfc80:/# php -m | grep -i hash
hash

root@3628946cfc80:/# php -a
Interactive shell

php > echo hash_hmac('ripemd160', 'The quick brown fox jumped over the lazy dog.', 'secret');
b8e7ae12510bdfb1812e463a7f086122cf37e4f7
```

Can you give all the commands you ran and any relevant files for reproducing the issue
