### ISSUE TITLE
8.0.0rc2 is missing on Docker Hub

### ISSUE THREAD

**Issue by shyim** [docker-library/php#1072]
Seems to be updated in this Git repository but missing at Docker Hub https://hub.docker.com/_/php/?tab=tags&page=1&name=rc2

**Comment by yosifkit** [comment]
https://github.com/docker-library/php/tree/38ac479fe93ae2f8bf423cf9232eef3c0dc24b29#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

Lowercase was a mistake on the rc1 release, try uppercase: https://hub.docker.com/_/php/?tab=tags&page=1&name=RC2
