### ISSUE TITLE
Improve security without x-powered-by and PHP version

### ISSUE THREAD

**Issue by alessandro-candon** [docker-library/php#1073]
Hello,
I notice that in the file `$PHP_INI_DIR/php.ini-production` (.ini for production) the header of ` x-powered-by` is exposed.

I think, for security reasons, is better (in production) to hide this information.

The change that I suggest is :
from `expose_php = On` to `expose_php = Off`, what do you think about this?

Regards

**Comment by jvasseur** [comment]
This file is juste a copy of [the php.ini-production provided by PHP](https://github.com/php/php-src/blob/master/php.ini-production), this should probably be reported to PHP directly.
