### ISSUE TITLE
ZTS for PHP 8 Alpine images 

### ISSUE THREAD

**Issue by WyriHaximus** [docker-library/php#1074]
Are there plans to add ZTS again for PHP 8 Alpine images? The only thing I could find on it is an MySQL related error in a PR https://github.com/docker-library/php/pull/1028#issuecomment-649763859

**Comment by tianon** [comment]
Just tested and it appears that it is indeed fixed now!  #1075

**Comment by WyriHaximus** [comment]
That is great news, thank you!

**Comment by tianon** [comment]
I made a boo-boo, and #1075 didn't test anything properly -- #1076

**Comment by tiagofiorenza** [comment]
Hey guys.

I'm looking forward to try out php 8 performance with pthreads. Any updates?

Thanks

**Comment by tianon** [comment]
I've just rebased https://github.com/docker-library/php/pull/1076 so we can see whether it's been fixed upstream in one of the intermediate 8.x releases.
