### ISSUE TITLE
Support for testing php-7.0.0alpha1

### ISSUE THREAD

**Issue by marceloandrader** [docker-library/php#108]
Hi,

I'd like to use the official image to test my apps with the next version of php 7, I'm not sure if someone is working on this already?

The reason is to just change my current Dockerfile from the line FROM php:fpm to FROM php:7-alpha1-fpm

and reuse the rest of the dockerfile unmodified.

I'd like to do this one as a contribution.

Let me know.

**Comment by thaJeztah** [comment]
I'm not aware of someone working on it, so thanks for proposing to contribute this. 

I don't think alpha/beta releases have  been used so far, so that may be the only "blocker" here; @tianon?

**Comment by md5** [comment]
There have been beta releases of other official images (e.g. `jetty:9.3.0.M2`). I skimmed the guidelines ([1](https://docs.docker.com/docker-hub/official_repos/), [2](https://github.com/docker-library/official-images/blob/master/README.md)) and didn't see any mention of tagging conventions, but I think that the normal practice for pre-release images of various sorts (alpha, beta, milestone, RC, etc) is to only give them a tag with a full version number and not use any version aliases.

In this case, that would mean having a `php:7.0.0alpha2` (plus `-cli`, `-apache`, and `-fpm` variants), but no `php:7-fpm` or such tags until PHP 7.0.0 is actually released.

**Comment by tianon** [comment]
I'm definitely a big fat +1 on PHP 7, and have been checking to see if they had an alpha/beta/RC release for a while now. :+1:

As for tagging, @md5 is right that there's not really a "convention".  Some places, we do just the full tag, some places we do more than that.  For example, [`mongo:3.1` and `mongo:3.1.4`](https://registry.hub.docker.com/_/mongo/) or [`mysql:5.7` and `mysql:5.7.7` and `mysql:5.7.7-rc`](https://registry.hub.docker.com/_/mysql/).  I think my personal gut feeling on this one would be whatever requires the least change to `generate-stackbrew-library.sh` (especially if it can be done without changing that file at all) would be my preferred method.

**Comment by marceloandrader** [comment]
Sounds good, I'll try to start working on this during the week

**Comment by thaJeztah** [comment]
Thanks @marceloandrader ! looking fwd to it

**Comment by marceloandrader** [comment]
I'm trying to execute the docker build in current 5.6 but I'm getting this error:

```
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 33CFC8B3 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

And related to this, php7 is not on the official https://secure.php.net/downloads.php page  so it doesn't have .asc file neither gpg keys to verify the integrity, I've found the file in 2 locations on github: https://github.com/php/php-src/releases/tag/php-7.0.0alpha2 and in http://downloads.php.net/~ab/

I can change the Dockerfile on 7 to use the github release, but the update.sh expects that the version has a gpg validated signature on this location: http://php.net/releases/index.php?serialize=1&version=5&max=100 that we don't have.

Is it ok to change the update.sh file to manage this exception?

**Comment by tianon** [comment]
That issue with ha.pool.sks-keyservers.net is 100% unrelated, and points to big problems with either your host, or your network. (Are you in a corporate environment?)

With the way the PHP 7 "releases" are being published, yeah, I agree that we're going to need both some `Dockerfile` changes and we're going to have to wrangle `update.sh` to handle both intelligently in some way.

**Comment by marceloandrader** [comment]
@tianon thanks, no I was doing it from an ec2 instance, looks like that server was down for a moment now is working.

Ok thanks for the direction I'll continue poking with that.
