### ISSUE TITLE
php-apache: Setting APACHE_DOCUMENT_ROOT has no effect

### ISSUE THREAD

**Issue by MagicLegend** [docker-library/php#1082]
Following the documentation merged with [#1000](https://github.com/docker-library/docs/pull/1000) to set a custom `APACHE_DOCUMENT_ROOT`, I can't seem to get it to work. Dockerfile:

```dockerfile
FROM php:7.1-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html/subfolder

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
```

This is the exact example from the documentation under `Changing DocumentRoot (or other Apache configuration)`. However, when I start it with the following command:

`docker run --rm -it -p 8082:80 -v /user/magiclegend/codebase:/var/www/html/subfolder e785 /bin/bash`
_e785 being the start of the hash from the container_

This results in the following:

```
root@9d9c344ec804:/var/www/html# service apache2 status
[FAIL] apache2 is not running ... failed!
root@9d9c344ec804:/var/www/html# service apache2 restart
[....] Restarting Apache httpd web server: apache2[Mon Nov 09 12:33:30.914062 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
[Mon Nov 09 12:33:30.914235 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
[Mon Nov 09 12:33:30.914410 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
AH00112: Warning: DocumentRoot [/etc/apache2/${APACHE_DOCUMENT_ROOT}] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Nov 09 12:33:30.926900 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
[Mon Nov 09 12:33:30.927007 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
[Mon Nov 09 12:33:30.927151 2020] [core:warn] [pid 51] AH00111: Config variable ${APACHE_DOCUMENT_ROOT} is not defined
. ok 
root@9d9c344ec804:/var/www/html# echo $APACHE_DOCUMENT_ROOT
/var/www/html/subfolder/
```

Is this documentation (or the example) incorrect? It states that the variable "can then be modified at container runtime as well". However, reading up on apache2 configuration, apache does not read runtime variables (without any trickery). [Source](https://medium.com/@william.b/setting-dynamic-environmental-variables-in-apache-from-the-os-1d5c1e2e9e6c)

How is this supposed to function? Is this documentation outdated/broken?

_I have previously put this issue in the global docker docs repo, my bad. I had not noticed that I had switched repos._

**Comment by wglambert** [comment]
I'm not able to reproduce any issue with the docs example

```console
$ docker build -t php:test - << EOF
FROM php:7.1-apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/subfolder
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-availa
ble/*.conf
EOF
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM php:7.1-apache
 ---> b9858ffdd4d2
Step 2/4 : ENV APACHE_DOCUMENT_ROOT /var/www/html/subfolder
 ---> Running in aaf249c64a0c
Removing intermediate container aaf249c64a0c
 ---> 8b83a0c7a832
Step 3/4 : RUN sed -ri -e 's!/var/www/html!!g' /etc/apache2/sites-available/*.conf
 ---> Running in 5e138c604478
Removing intermediate container 5e138c604478
 ---> c1a5ab105e43
Step 4/4 : RUN sed -ri -e 's!/var/www/!!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
 ---> Running in 72bfc0204ee7
Removing intermediate container 72bfc0204ee7
 ---> b538709a75d8
Successfully built b538709a75d8
Successfully tagged php:test

$ mkdir test

$ docker run -d --rm --name apache -v "$PWD"/test:/var/www/html/subfolder php:test
0635fc3253f23b1fbb7e5c2a4b708bac332e1c3c02d6aaa2b98a97064bc38cbc

$ docker logs apache
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2
. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2
. Set the 'ServerName' directive globally to suppress this message
[Mon Nov 09 18:11:46.321689 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.1.33
 configured -- resuming normal operations
[Mon Nov 09 18:11:46.321755 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

$ docker exec -it apache bash

root@56d9c177280e:/var/www/html# echo $APACHE_DOCUMENT_ROOT
/var/www/html/subfolder

root@56d9c177280e:/var/www/html# grep APACHE_DOCUMENT_ROOT /etc/apache2/sites-available/*.conf
/etc/apache2/sites-available/000-default.conf:  DocumentRoot ${APACHE_DOCUMENT_ROOT}
/etc/apache2/sites-available/default-ssl.conf:          DocumentRoot ${APACHE_DOCUMENT_ROOT}

root@56d9c177280e:/var/www/html# grep APACHE_DOCUMENT_ROOT /etc/apache2/apache2.conf
<Directory ${APACHE_DOCUMENT_ROOT}>

root@56d9c177280e:/var/www/html# service apache2 status
[ ok ] apache2 is running.
```

**Comment by yosifkit** [comment]
`service apache2` isn't going to work for the container (to check the status, or control its running state); there is no `init` system in the image and `service` definitely won't read a local environment variable. You need to use the provided `ENTRYPOINT` + `CMD` scripts ([docker-php-entrypoint](https://github.com/docker-library/php/blob/16c3e237e0097325f22ec09e5b9fca557a4479d5/7.2/buster/apache/docker-php-entrypoint), [apache2-foreground](https://github.com/docker-library/php/blob/16c3e237e0097325f22ec09e5b9fca557a4479d5/7.2/buster/apache/apache2-foreground)) as defined in the Dockerfile:

https://github.com/docker-library/php/blob/16c3e237e0097325f22ec09e5b9fca557a4479d5/7.2/buster/apache/Dockerfile#L271-L279

**Comment by MagicLegend** [comment]
First off: thank you for both of your quick replies. @wglambert Except for your final statement I can reproduce what you have. Calling `service apache2 status` will still result in errors. However, this seems to be due to what @yosifkit points out.

@yosifkit Could you help me understand what pointers there were to `service` not working? Where could I have seen there is no `init` from the bash shell? I'd love to understand more of the inner workings of Linux.

> "`service` definitely won't read a local environment variable"

No, but `apache2` will; when it reads it's config files right?

---

Building on your answers, I have worked on the image I was using further, and it is all working now. When starting the container without a command the apache server will indeed be started, even though `service` reports a crashed service. However: The actual answer to my question seems to be the fact that **I started the container with an command, `/bin/bash`, meaning that the `apache2-foreground` script will not start; and thus apache will not start.** This should maybe be added to the documentation. It might save someone with not that much bash / docker knowledge searching time. The workaround I came up with is to mount a script into the container with the following:

```sh
#!/bin/sh

apache2-foreground & sleep 1 && ./vendor/bin/phpunit tests
```

This will start apache, and simultaneously wait one second and then start `phpunit`. In my use case, Bitbucket Pipelines, this made the container start apache and then run the (API integration) tests.

Again thank you for your time and answers. I'd like to hear back if what I ran into should be added to the documentation.

**Comment by yosifkit** [comment]
>  I started the container with an command, `/bin/bash`, meaning that the `apache2-foreground` script will not start; and thus apache will not start.

That is a just a general "how containers work"; the executable you run is all that is running inside the container (if `ps` is installed in the image, you can use that to see what is running).  There is no init system like `sysvinit` or `systemd`, so there is no central "controlling process" (unless the process you run is an init system).

> No, but `apache2` will; when it reads it's config files right?

If it is an environment variable, then it is not in a config file, but only lives as an attribute of a process. `service` strips away all environment variables before starting a service (since, for normal systems you don't want users' local shell variables interfering with how global services run). So `apache2` started via `service` never even has a chance to see them.

**Comment by TrueOsiris** [comment]
Old issue, but still encountered this issue when creating a container for php8.2-apache (release candidate at the moment).
imho bad usage of sed:

    `RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf`

should be

    `RUN sed -ri -e "s!/var/www/html!$APACHE_DOCUMENT_ROOT!g" /etc/apache2/sites-available/*.conf`

If you want to set the `ENV APACHE_DOCUMENT_ROOT /var/www/html/subfolder` up front, my guess is you want that as a litteral, replaced in your apache2 config files. The .conf files don't work with variables like that.

**Comment by tianon** [comment]
> The .conf files don't work with variables like that.

https://httpd.apache.org/docs/2.4/configuring.html#syntax

> The values of variables defined with the [`Define`](https://httpd.apache.org/docs/2.4/mod/core.html#define) of or shell environment variables can be used in configuration file lines using the syntax `${VAR}`. If "VAR" is the name of a valid variable, the value of that variable is substituted into that spot in the configuration file line, and processing continues as if that text were found directly in the configuration file.

**Comment by brunoggdev** [comment]
> Old issue, but still encountered this issue when creating a container for php8.2-apache (release candidate at the moment). imho bad usage of sed:
> 
> ```
> `RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf`
> ```
> 
> should be
> 
> ```
> `RUN sed -ri -e "s!/var/www/html!$APACHE_DOCUMENT_ROOT!g" /etc/apache2/sites-available/*.conf`
> ```
> 
> If you want to set the `ENV APACHE_DOCUMENT_ROOT /var/www/html/subfolder` up front, my guess is you want that as a litteral, replaced in your apache2 config files. The .conf files don't work with variables like that.
> 
> e.g. my functional php8.2-apache container https://github.com/TrueOsiris/docker-webserver with this variable.

Totally solved a problem I've been fighting with for an hour or even more already, thank you!
