### ISSUE TITLE
Images not available in docker hub for 7.4.13 and 8.0.0

### ISSUE THREAD

**Issue by adhocore** [docker-library/php#1094]
Is it just me? I could only see 8.0rc5 updated ~3~ 5 days ago and not 8.0.0 or even 7.4.13 in docker hub [tags](https://hub.docker.com/_/php?tab=tags&page=1&ordering=last_updated)

**Comment by TimurFlush** [comment]
+1

**Comment by JoelLinn** [comment]
#1090 just wait.

**Comment by adhocore** [comment]
not sure if 1090 also adds 7.4.13.

also curious is the php8 tag 8.0.0 or just 8.0? thanks

**Comment by iiQi** [comment]
+1

**Comment by sshnuke3** [comment]
> not sure if #1090 also adds 7.4.13.
> 
> also curious is the php8 tag prefix will be 8.0.0 or just 8.0? thanks

i think it's still php:8.0-rc available
8.0.0 image is not available yet

**Comment by nusphere** [comment]
there need to be a merge on #1090 - @tianon @yosifkit
