### ISSUE TITLE
Docker hub : Image 7.3.25 not available

### ISSUE THREAD

**Issue by even42** [docker-library/php#1095]
Hi,

Version 7.3.25 don't exist on docker hub => https://hub.docker.com/_/php?tab=tags&page=1&name=7.3.25

I tried "FROM php:7.3.25-fpm-stretch"  this version don't exist 

I tried also "FROM php:7.3-fpm-stretch" but I sitll stuck with the old version. In my case 7.3.16

Regards.

**Comment by wglambert** [comment]
The PR is still pending https://github.com/docker-library/official-images/pull/9176

https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/100728981-81421700-33c8-11eb-87ab-e74a033fd064.png)
amd64 is still missing

**Comment by tomcastleman** [comment]
Strange as [the build](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/315/console) looks like it was successful...

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/1098 and https://github.com/docker-library/php/pull/1090, especially https://github.com/docker-library/php/pull/1090#issuecomment-736639641:

> What happened here is that ARM managed to build and push faster than amd64 did, then we hit Docker's rate limits while trying to update the manifest lists for a while.
