### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by dungahk** [docker-library/php#1098]
I'm getting this error when trying to pull the latest images that were pushed yesterday.

`docker pull php:7.3.25-fpm-alpine3.12` throws `no matching manifest for linux/amd64 in the manifest list entries`

`docker pull amd64/php:7.3.25-fpm-alpine3.12` works.

I got the same for 8.0.0.

I'm not sure if this is the correct place to raise this issue so if it is not just let me know.

By the way, thank you all for the hard work on maintaining all of this!

**Comment by manuelgrabowski** [comment]
Same here, never had this before – am I just too early in trying to upgrade and things are still being built?

**Comment by dungahk** [comment]
As far as I can tell, it should be available already, see https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/

I've found similar issues on other repositories, see https://github.com/nginxinc/docker-nginx/issues/397

**Comment by fefas** [comment]
Same here

**Comment by shyim** [comment]
I will use in meanwhile `amd64/php:8.0-fpm-alpine` works for me. It was listed in the job

**Comment by zeriyoshi** [comment]
Isn't this the issue?
https://doi-janky.infosiftr.net/job/put-shared/job/light/job/php/

**Comment by rufinus** [comment]
> I will use in meanwhile `amd64/php:8.0-fpm-alpine` works for me. It was listed in the job

the same hickup was on the 7.4 release... name changed from `7.4.0RCx-alpine` to `7.4-alpine`

**Comment by rufinus** [comment]
> I will use in meanwhile `amd64/php:8.0-fpm-alpine` works for me. It was listed in the job

the i386 and amd64 builds still are missing. the 8.0-fpm-alpine is just a different tag for the same digest

**Comment by zyfran** [comment]
Also
```bash
$ docker pull php:7.4-fpm;docker pull php:7.4-cli;docker pull php:7.4.13-cli-alpine
7.4-fpm: Pulling from library/php
Digest: sha256:520410d6f38905bce2e8eae6fee38b66cedeed3ba9ac0a29d6c9ce98fa5c0580
Status: Image is up to date for php:7.4-fpm
docker.io/library/php:7.4-fpm
7.4-cli: Pulling from library/php
Digest: sha256:e4c725c007311b56405f9d7ee42fbe990d7c63b2e1d7a8de73585b3ee5576564
Status: Image is up to date for php:7.4-cli
docker.io/library/php:7.4-cli
7.4.13-cli-alpine: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```
```
php 7.4-fpm 876051031ecc 13 days ago 405MB
php 7.4-cli 639632eff06b 13 days ago 405MB
```

**Comment by webmaster777** [comment]
> Is it the cause of this?
> https://doi-janky.infosiftr.net/job/put-shared/job/light/job/php/

`429 -- Too Many Requests`

Well, that's something. Looks like Docker Hub's rate limiting is biting?

**Comment by zeriyoshi** [comment]
👍 
https://doi-janky.infosiftr.net/job/put-shared/job/light/job/php/135/execution/node/37/log/

**Comment by dungahk** [comment]
Thank you all.
