### ISSUE TITLE
Image Docker - php:7.4.13-alpine with Bitcoin Miner

### ISSUE THREAD

**Issue by eversdn1** [docker-library/php#1110]
After install a new clean server on aws e use this php:7.4.3-alpine image on my docker compose, after 30 minutes the cpu jump to 100%.
the synthoms and behavior is exact the same like this article.
https://www.linkedin.com/pulse/kinsing-malware-permanent-solution-amul-patel

Regards,
Everson Nunes

**Comment by JoelLinn** [comment]
Can you isolate this issue to one or at least a minimal set of components? How are you measuring the cpu usage (trying to rule out you misinterpret the steal time)

**Comment by eversdn1** [comment]
Unfortunately it´s difficult to believe, but it´s simple, a new clean installation of the official php image are infected by a miner.
![WhatsApp Image 2021-01-04 at 10 48 38](https://user-images.githubusercontent.com/76958568/103562658-30777f80-4e9a-11eb-92e6-449e2c728179.jpeg).

**Comment by JoelLinn** [comment]
what are you running inside the php container? just the plain image or some other php software?

**Comment by wglambert** [comment]
Looks like that `kdevtmpfsi` is on the host system and not the container, what options are you running the container with?

Issues with `kdevtmpfsi` 
https://github.com/docker-library/redis/issues/225
https://github.com/docker-library/redis/issues/217
https://github.com/docker-library/postgres/issues/798#issuecomment-747610025
>This is an unfortunate consequence of having a public-facing instance with a compromised (or simple) password

**Comment by eversdn1** [comment]
docker-compose file
version: '3.7'
services:
        nginx:
                container_name: nginx
                image: nginx:1.19.6-alpine
                restart: unless-stopped
                depends_on:
                     - php
                volumes:
                      - ./www:/www
                      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
                ports:
                      - "8000:8000"
                links:
                      - php
                networks:
                      - proxy

        php:
                container_name: php
                image: php:7.4.13-fpm-alpine
                restart: unless-stopped
                ports:
                      - "9000:9000"
                networks:
                      - proxy
networks:
  proxy:
     driver: bridge
                         

> what are you running inside the php container? just the plain image or some other php software?
I´m running just phpinfo.




> Looks like that `kdevtmpfsi` is on the host system and not the container, what options are you running the container with?
> 
> Issues with `kdevtmpfsi`
> [docker-library/redis#225](https://github.com/docker-library/redis/issues/225)
> [docker-library/redis#217](https://github.com/docker-library/redis/issues/217)
> [docker-library/postgres#798 (comment)](https://github.com/docker-library/postgres/issues/798#issuecomment-747610025)
> 
> > This is an unfortunate consequence of having a public-facing instance with a compromised (or simple) password
wglambert - When the container is stopped the kdevtmpfsi stopped to. Now i´m running 7.3.25 php image and the problem are solved.

**Comment by tianon** [comment]
You definitely don't want to expose PHP-FPM to the public internet -- you want it in the same Docker Network as NGINX so NGINX can access it, but nothing else (drop the `9000:9000` from the `php` service definition).

I'm certain there are all sorts of nasty things an attacker could do with a public FPM instance. :scream: :disappointed:

**Comment by eversdn1** [comment]
Thanks for all feedback.
I will close 9000 port of php-fpm and create a new server. Let´s wait and monitor to see.

Printscreen - top command on container php.
![image](https://user-images.githubusercontent.com/76958568/103581527-f4084b80-4eba-11eb-82a9-75c680873a02.png)

**Comment by JoelLinn** [comment]
Probably should be closed by now

**Comment by eversdn1** [comment]
Sure, solved after close PHP Port.

Regards,
Everson

Em qua, 10 de fev de 2021 04:55, Joel Linn <notifications@github.com>
escreveu:

**Comment by hakuno** [comment]
Is it enough? I'm unsure.

You can close the listening port (incoming). But it may have some outgoing connection.

ps. also known as  reverse connection.
