### ISSUE TITLE
Add FFI support for PHP 8 images

### ISSUE THREAD

**Issue by llaville** [docker-library/php#1112]
Hello,

Is it possible to add [FFI](https://www.php.net/manual/en/book.ffi.php) support in PHP 8 images ?

Thanks

**Comment by JoelLinn** [comment]
It’s marked as EXPERIMENTAL https://www.php.net/manual/en/intro.ffi.php

You can easily build your own PHP containers though. Fork the repo, edit the templates and run the `update.sh` script

Also I think it is dangerous. If it would ever be included, it should be deactivated by default.

**Comment by tianon** [comment]
It seems to work just fine via `docker-php-ext-install`? :confused:

```Dockerfile
FROM php:8.0-apache-buster
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends libffi-dev; \
	rm -rf /var/lib/apt/lists/*; \
	docker-php-ext-install ffi
```

```console
root@33e5b4950242:/# php -i | grep ffi
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini,
ffi.enable => preload => preload
ffi.preload => no value => no value
```

**Comment by llaville** [comment]
It's 👍 for me too ! @tianon solution is enough for me. Thanks and sorry to forgot to reply sooner :)
