### ISSUE TITLE
php 7.2 Dockerfile

### ISSUE THREAD

**Issue by clmoreno** [docker-library/php#1120]
Hi, i would like to inspect 7.2-fpm-alpine3.12 Dockerfile for debugging  purposes but the source code isn't available in this repo. 

Is the code in another repo? where i can find the code related to the 7.2-fpm-alpine3.12 variant?

Thanks for the help!

**Comment by tianon** [comment]
https://github.com/docker-library/php/commits/master/7.2/alpine3.12/fpm might be useful for you (https://github.com/docker-library/php/tree/20ebff40bb865416f3767540df06ad1df384337d/7.2/alpine3.12/fpm is the last supported instance of that version combination).
