### ISSUE TITLE
password_hash() and crypt() return incorrect values on Alpine

### ISSUE THREAD

**Issue by SJrX** [docker-library/php#1125]
The php manual page for [crypt()](https://www.php.net/manual/en/function.crypt.php) states that:

>  The two digit cost parameter is the base-2 logarithm of the iteration count for the underlying Blowfish-based hashing algorithm and must be in range 04-31, values outside this range will cause crypt() to fail

This is implicitly the same as [password_hash()](https://www.php.net/manual/en/function.password-hash.php) since the values are suppose to be compatible:

If I run the following:

```
$ time  echo -e "<?php \n \$hash=password_hash('hello', PASSWORD_BCRYPT, ['cost' => 20]); \n var_dump(\$hash);" | docker run -i  --entrypoint /usr/local/bin/php   php:7.4-cli-alpine
NULL
real    0m1.790s
user    0m0.021s
sys     0m0.051s
$ time  echo -e "<?php \n \$hash=password_hash('hello', PASSWORD_BCRYPT, ['cost' => 20]); \n var_dump(\$hash);" | docker run -i  --entrypoint /usr/local/bin/php   php:7.4-cli-buster
string(60) "$2y$20$5/ITHApxrJt.6/4vL9f30uyShXw1jKwSN3yOtESv.XzsGD3e/3rMO"
real    1m1.527s
user    0m0.050s
sys     0m0.016s
```

I tracked the issue down to the implementation of blowfish bcrypt in musl and [made this mailing list post](https://www.openwall.com/lists/musl/2021/01/28/2). Discussions on freenode suggested this is [by design](http://git.musl-libc.org/cgit/musl/commit/src/crypt/crypt_blowfish.c?id=aeaceb1fa89b865eb0bca739da9c450b5a054866), [additional background](https://www.openwall.com/lists/musl/2012/08/08/20). 

Other implementations such as libxcrypt have a work factor limit of 39 (https://github.com/besser82/libxcrypt/blob/develop/lib/crypt-bcrypt.c#L734)

**Comment by phy25** [comment]
If this is something that is also broken on native alpine, you might want to create a bug report with PHP rather than with this Docker image.

**Comment by tianon** [comment]
This is really interesting - thanks for being so thorough in digging through the layers!

Honestly though, if this is "working as designed" for the musl implementation, I doubt you're going to get much love from the PHP developers -- the documentation at https://www.php.net/manual/en/function.password-hash.php is pretty clear that `false` is defined to be an error, so any user code that isn't checking the return value is inherently buggy (and in looking at the implementation, they do appear to use `NULL` interchangeably with the documentation-defined `false` value, which is fair IMO).

At most I'd imagine a documentation change clarifying that the "cost" argument is dependent on the underlying implementation.

**Comment by tianon** [comment]
(https://www.php.net/manual/en/function.crypt.php is less specific on the error case, and simply says "a string that is shorter than 13 characters and is guaranteed to differ from the salt on failure", but the actual underlying implementation has several instances of `return NULL;` for obvious error cases)

**Comment by SJrX** [comment]
> If this is something that is also broken on native alpine, you might want to create a bug report with PHP rather than with this Docker image.

I created it here because I think this image is compiling PHP. My understanding and belief is that this image could fix this by linking to a different crypt implementation than musl. But I actually don't do much C/C++ compilation to know whether that is doable or even makes sense.

> Honestly though, if this is "working as designed" for the musl implementation

"Working as designed" is my paraphrasing of it. I don't know that I agree with their implementation decision, the crux of it is that they want to avoid DoS attacks caused by expensive work factors. 

> At most I'd imagine a documentation change clarifying that the "cost" argument is dependent on the underlying implementation.

My feeling was that it's also possible that they just said that linking to musl instead of glibc is not supported, if musl isn't going to maintain compatibility with libcrypt or libxcrypt or whatever. Truth be told I'm not sure that I understand exactly how PHP is calling the musl crypt call. 

I did notice a bunch of code in PHP source code (https://github.com/php/php-src/blob/master/ext/standard/crypt.c#L93) that handles different cases of libraries, so it's also possible that by flipping a few flags you could get it to use the built in version which it seems to suggest it can use on Windows.

**Comment by tianon** [comment]
I can still reproduce this issue with PHP 7, but not with PHP 8:

```console
$ time  echo -e "<?php \n \$hash=password_hash('hello', PASSWORD_BCRYPT, ['cost' => 20]); \n var_dump(\$hash);" | docker run -i  --entrypoint /usr/local/bin/php   php:8-cli-alpine
Unable to find image 'php:8-cli-alpine' locally
8-cli-alpine: Pulling from library/php
2408cc74d12b: Already exists 
fde5ea1cb188: Already exists 
3935ba60366a: Already exists 
4712e34f1d29: Already exists 
6a3b65d24407: Pull complete 
25e8a2ef4024: Pull complete 
e32b00625506: Pull complete 
794adbdcd14d: Pull complete 
e8a0e7382588: Pull complete 
Digest: sha256:8f2d187d987bb30dc674dce8f81d5fbe8a1db59bb041d774ac6abe6e7484d35b
Status: Downloaded newer image for php:8-cli-alpine
string(60) "$2y$20$EAH8nPWaQd.V2i70UHwuGOyQK9khM4XfSvkOq.9.Lzvk9OYH4E11C"

real	0m47.257s
user	0m0.009s
sys	0m0.044s

$ time  echo -e "<?php \n \$hash=password_hash('hello', PASSWORD_BCRYPT, ['cost' => 20]); \n var_dump(\$hash);" | docker run -i  --entrypoint /usr/local/bin/php   php:8-cli-bullseye
Unable to find image 'php:8-cli-bullseye' locally
8-cli-bullseye: Pulling from library/php
42c077c10790: Already exists 
8934009a9160: Pull complete 
5357ac116991: Pull complete 
54ae63894b5a: Pull complete 
b4112dfb6b21: Pull complete 
14ceebee7f2c: Pull complete 
e523cfe7c87a: Pull complete 
58849b79c1af: Pull complete 
7ac4b01fe432: Pull complete 
Digest: sha256:d44e655859654450ba4a75a67bcfb5e8bf05b069f5ce8182c195af9d2159a7f5
Status: Downloaded newer image for php:8-cli-bullseye
string(60) "$2y$20$a3TVXIP0hRIbWUONP1gV4u/nggziT508xmXKxxFuWd4QpEHuWOEUq"

real	0m48.173s
user	0m0.028s
sys	0m0.023s
```

:+1:
