### ISSUE TITLE
Can't enable Memcached on php:7.4-fpm-alpine

### ISSUE THREAD

**Issue by LucianoVandi** [docker-library/php#1132]
Hello, i'm trying to add memcached support to `php:7.4-fpm-alpine`, below my Dockerfile.

```docker
FROM php:7.4-fpm-alpine

RUN apk update && apk add --no-cache --allow-untrusted \
    apache2 apache2-ssl apache2-proxy \
    memcached php7-pecl-memcached

ENTRYPOINT [ "httpd", "-DFOREGROUND"]
```

The container build without any error, but if from within the container I do `php -m`can't see the memcached module loaded.

```
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]
``` 
I'm on Mac OS 10.11.6, Docker CE Version 18.06.1-ce-mac73 (26764).

**Comment by wglambert** [comment]
There's a docs entry for installing extensions https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions
```console
$ docker build -t php:test - << EOF
FROM php:7.4-fpm-alpine
RUN apk add libmemcached-dev libmemcached autoconf pkgconfig g++ zlib-dev make && pecl install memcached && \ 
docker-php-ext-enable memcached && apk del make g++ autoconf pkgconfig 
EOF

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.4-fpm-alpine
 ---> 597b78d02952
Step 2/2 : RUN apk add libmemcached-dev libmemcached autoconf pkgconfig g++ zlib-dev make && pecl install memcached && docker-php-ext-enable memcached && apk del make g++ autoconf pkgconfig
 ---> Using cache
 ---> 3408f876001f
Successfully built 3408f876001f
Successfully tagged php:test

$ docker run --rm php:test php -m | grep memcached
memcached
```

See also https://github.com/docker-library/php/issues/575#issuecomment-365097494
>I'd recommend instead running memcached in a separate container

And any reason why you're opting to install Apache in the [`fpm`](https://github.com/docker-library/docs/tree/master/php#phpversion-fpm) variant instead of using the default [`apache`](https://github.com/docker-library/docs/tree/master/php#phpversion-apache) variant?

**Comment by LucianoVandi** [comment]
@wglambert this solved my issue, thanks! Basically I can't install extensions with `apk add`?  I need to reproduce an environment with php-fpm and apache2 through mpm_event_module/proxy_pass, but the apache variant uses `mod_php`.

**Comment by tianon** [comment]
When you install via apk, you send up with two versions of PHP in the image
(ours and Alpine's), with a very low chance of compatible extensions.

You might be interested in the CLI variant (which is roughly the same as
FPM but without the FPM binary).

**Comment by LucianoVandi** [comment]
@tianon thanks for the explanation. What are the advantage of using CLI variant? I need fpm anyway...

**Comment by tianon** [comment]
Ah sorry, I misunderstood and thought FPM was just dead weight for your use
case; my apologies!
