### ISSUE TITLE
[php:7.3-fpm] pdo_mysql and mysqlnd are in 5.0.12 version (20150407)

### ISSUE THREAD

**Issue by Johnson66666** [docker-library/php#1133]
**Image version(s) affected**:

7.3-fpm

**Description**  

I need pdo_mysql, but I'm unable to install it properly using tools provided in docker image. By the way, mysqlnd comes by defaut on v5.0.12 even if I don't require pdo_mysql. However, mysqlnd seems to be maintained, see https://github.com/php/php-src/tree/master/ext/mysqlnd.

**How to reproduce** 

```shell
# Dockerfile used to build

# Get php 7.3-fpm image from Docker Hub
FROM php:7.3-fpm

# Install php Core & PECL extensions
RUN apt-get update && apt-get install -y \
        libmagickwand-dev \
        gnupg2 \
    && docker-php-ext-install -j$(nproc) \
        exif \
        opcache \
        pdo_mysql \
    && pecl install imagick-3.4.4 \
    && pecl install redis-5.3.3 \
    && pecl install xdebug-3.0.2 \
    && docker-php-ext-enable imagick redis xdebug
```

```shell
# Build image
docker-compose build --no-cache php
```

**Result** 

```shell
docker exec -ti php bash
php -i
```

> mysqlnd
> 
> mysqlnd => enabled
> Version => mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
> Compression => supported
> core SSL => supported
> extended SSL => supported
> Command buffer size => 4096
> Read buffer size => 32768
> Read timeout => 86400
> Collecting statistics => Yes
> Collecting memory statistics => Yes
> Tracing => n/a
> Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
> API Extensions => pdo_mysql
> 
> PDO
> 
> PDO support => enabled
> PDO drivers => sqlite, mysql
> 
> pdo_mysql
> 
> PDO Driver for MySQL => enabled
> Client API version => mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

**Comment by wglambert** [comment]
`pdo_mysql` is installed and listed under the available php modules using your Dockerfile
```console
$ docker build -t php:test - << EOF
FROM php:7.3-fpm
RUN apt-get update && apt-get install -y \
        libmagickwand-dev \
        gnupg2 \
    && docker-php-ext-install -j$(nproc) \
        exif \
        opcache \
        pdo_mysql \
    && pecl install imagick-3.4.4 \
    && pecl install redis-5.3.3 \
    && pecl install xdebug-3.0.2 \
    && docker-php-ext-enable imagick redis xdebug
EOF

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.3-fpm
 ---> 3e198790fbea
Step 2/2 : RUN apt-get update && apt-get install -y         libmagickwand-dev         gnupg2     && docker-php-ext-install -j8         exif         opcache         pdo_mysql     && pecl install imagick-3.4.4     && pecl install redis-5.3.3     && pecl install xdebug-3.0.2     && docker-php-ext-enable imagick redis xdebug
 ---> Using cache
 ---> 64f41a4d2070
Successfully built 64f41a4d2070
Successfully tagged php:test

$ docker run --rm php:test php -m | grep -i pdo
PDO
pdo_mysql
pdo_sqlite
```

**Comment by Johnson66666** [comment]
> `pdo_mysql` is installed and listed under the available php modules using your Dockerfile

Thanks, I know, and it's working well . My question is why `pdo_mysql` and `mysqlnd` are under a 2015 version, and how can I upgrade it to install latest extensions?

**Comment by wglambert** [comment]
Probably something to do with the versions of php it supports? Using the latest `php:8-fpm` gets you:

```console
pdo_mysql

PDO Driver for MySQL => enabled
Client API version => mysqlnd 8.0.2
```

I was looking for some sort of version matrix for it but can't seem to find much about `mysqlnd` or `pdo_mysql` versions and what's supported

**Comment by yosifkit** [comment]
`docker-php-ext-install` just uses the modules included with that release of PHP, so you need to use a newer major release of PHP to get a new bundled release of `pdo_mysql` (especially since the external pecl package is unmaintained: https://pecl.php.net/package/pdo_mysql)

And `mysqlnd` is also from the bundled extensions, but we enable it by default: https://github.com/docker-library/php/blob/57143cba9161c913cae8ba0a985bc30ba35130d2/Dockerfile-debian.template#L170-L171

`mysqlnd` version in PHP 7.3 branch: https://github.com/php/php-src/blob/729cd8bacd89be280eaf996b6b692068d99c7249/ext/mysqlnd/mysqlnd.h#L24
`mysqlnd` version in PHP 7.4 branch: https://github.com/php/php-src/blob/71297a254b8f0d97c028f3324cbaf95adf8de33c/ext/mysqlnd/mysqlnd.h#L24
`mysqlnd` version in PHP 8.0 branch: https://github.com/php/php-src/blob/957cb13a4959ed6a802508f14317253bf06f82cd/ext/mysqlnd/mysqlnd.h#L22
