### ISSUE TITLE
No linux/amd64 in 7.4.16-alpine?

### ISSUE THREAD

**Issue by xendk** [docker-library/php#1135]
We got a dependabot update that fails on:

```
7.4.16-alpine: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

Obviously there was one in 7.4.15-alpine, so what happened?

**Comment by kilburn** [comment]
There's no `linux/amd64` for `7.4.16-fpm-buster` either:
```
Step 1/10 : FROM php:7.4.16-fpm-buster
7.4.16-fpm-buster: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by Schwuuuuup** [comment]
➤  sudo docker pull docker.io/php:7.4.16-apache-buster
Trying to pull repository docker.io/library/php ... 
7.4.16-apache-buster: Pulling from docker.io/library/php
no supported platform found in manifest list

7.4-apache-buster seems to be ... wait for it ... "busted" (badum-tss)

**Comment by arnested** [comment]
This is the build job we are all waiting for, I guess:

https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/

**Comment by arnested** [comment]
> This is the build job we are all waiting for, I guess:
> 
> https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/

But the job seems stuck:

```
Still waiting to schedule task
‘multiarch-amd64’ is offline
```

**Comment by Schwuuuuup** [comment]
Right... still no progress on:
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/339/console

**Comment by tianon** [comment]
Indeed, unfortunately the official images amd64 build server stopped responding and we're still trying to investigate 😱

(Closing this in favor of https://github.com/docker-library/official-images/issues/9749 😬❤️)
