### ISSUE TITLE
8.0.3 build stuck for amd64 and i386?

### ISSUE THREAD

**Issue by Sarke** [docker-library/php#1136]
It's been going for over 24 hours now:

https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/lastBuild/

```
Still waiting to schedule task
‘multiarch-amd64’ is offline
```

https://doi-janky.infosiftr.net/job/multiarch/job/i386/job/php/lastBuild/

```
Still waiting to schedule task
‘multiarch-i386’ is offline
```

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/php/issues/1135
