### ISSUE TITLE
No sock file generating when running any FPM image

### ISSUE THREAD

**Issue by Drillan767** [docker-library/php#1138]
I need to run a PHP-FPM image so that I can connect the sock to an Nginx server. However, for an unknown reason, I can't manage to find any single sock file in the container.

I tried with an Ubuntu 20.10, a Macbook Pro 2016 and a Macbook Air M1, so both with ARM and AMD64 architectures.

I tried with the following images:

- php:8.0.3-fpm
- php:fpm
- php:7.4-fpm
- php:8.0.3-fpm-alpine3.13

To run the images, I used both a docker-compose file (where I realized the problem) and via the following command line:

```
docker run -it --rm  --name test-php-fpm php:<version>
```

Each of the versions used returned me the following log:

> NOTICE: fpm is running, pid 1
> NOTICE: ready to handle connections

When connecting to the different docker images, all I could find in `/var/run` or `/run` were an empty `lock` directory and an empty file, but no sock file whatsoever. For the alpine version, both the directories are empty.

I have no idea if I'm doing something obviously wrong or if there's a real problem, so in any case I'd really need some help to understand what's going on.

Thank you in advance

**Comment by wglambert** [comment]
You'll want to create any sockets that you'd need. 
Here's some things that might help with your usecase:
https://stackoverflow.com/questions/47056062/how-to-connect-nginx-to-php-fpm-using-unix-socket-in-docker
https://medium.com/@shrikeh/setting-up-nginx-and-php-fpm-in-docker-with-unix-sockets-6fdfbdc19f91
http://www.inanzzz.com/index.php/post/q31r/using-unix-socket-for-php-fpm-and-nginx-docker-setup

**Comment by yosifkit** [comment]
Rather than a socket file, you can alternatively have `nginx` connect to port 9000 of the fpm container (where it listens by default and will be the same FPM protocol).

**Comment by Drillan767** [comment]
Hello, thank you for your quick replies! I honestly don't know what I did wrong and what I did to make things work, but I magically managed to make my website run with PHP-FPM. I honestly don't know how. Thank you both for your suggestions and your links!

**Comment by Mek101** [comment]
> https://medium.com/@shrikeh/setting-up-nginx-and-php-fpm-in-docker-with-unix-sockets-6fdfbdc19f91
> When you run docker the php-fpm.sock will be created automatically.
