### ISSUE TITLE
Multiple vulnerables

### ISSUE THREAD

**Issue by markuman** [docker-library/php#1139]
```
php:7.4 (debian 10.8)
=====================
Total: 523 (UNKNOWN: 4, LOW: 396, MEDIUM: 39, HIGH: 83, CRITICAL: 1)
```

Scanned with https://github.com/aquasecurity/trivy  
Any ideas about it? Maybe switching to ubuntu:20.04 base instead of debian:buster?

**Comment by tianon** [comment]
I'm confused: :confused:

```console
$ docker pull php:7.4
7.4: Pulling from library/php
Digest: sha256:407a65316cb5e2a64eadf5d17ea6cb6292e9ed19fe703a5c534fd834bcbd3beb
Status: Image is up to date for php:7.4
docker.io/library/php:7.4

$ trivy image --ignore-unfixed php:7.4
2021-03-16T20:48:42.875Z	INFO	Detecting Debian vulnerabilities...

php:7.4 (debian 10.8)
=====================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

```

**Comment by tianon** [comment]
(see also https://github.com/aquasecurity/trivy/issues/323)

**Comment by markuman** [comment]
I'm confused too.  
The solution is just to hide vulnerable packages? Seriously?

**Comment by phy25** [comment]
See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves and your question might be a better fit for the scanning tool itself. If you have questions on specific vulnerabilities you should look up information in upstream OS packages which is usually well documented.
