### ISSUE TITLE
brotli encoding not available in bundled libcurl

### ISSUE THREAD

**Issue by GrahamCampbell** [docker-library/php#1140]
The docker images have ext-curl installed, but not support for brotli encoding enabled, despite the version of libcurl supporting it.

**Comment by GrahamCampbell** [comment]
The issue seems to be the curl shipped with Debian isn't compiled with that option enabled, so the PHP 7.3+ images should compile curl themselves to get this feature.

**Comment by GrahamCampbell** [comment]
It looks like Debian Bullseye's libcurl is compiled with brotli enabled, at least.

**Comment by GrahamCampbell** [comment]
Will there be bullseye based php images soon?

**Comment by yosifkit** [comment]
We should wait until sometime after Bullseye reaches "Full Freeze" (https://release.debian.org/bullseye/freeze_policy.html). See also https://github.com/docker-library/golang/issues/316#issuecomment-577420220.

**Comment by tianon** [comment]
Fixed via #1190 :+1:
