### ISSUE TITLE
[PHP-FPM] Impossible bind log file 👻

### ISSUE THREAD

**Issue by chiqui3d** [docker-library/php#1141]
I am using the php:7.4-fpm image and I have changed the configuration to have the log files in production mounted on the host, but something very strange happens, in the host they appear empty, when in the container if it have data.

Dockerfile

```
RUN rm /usr/local/etc/php-fpm.d/* \
&& touch /var/log/php-fpm.log \
&& chown -R www-data:www-data /var/log/php-fpm.log
COPY ./docker/php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf
```
Docker-compose

```
 volumes:
      - ./logs/php/:/var/log
```

PHP-FPM - www.conf

```
[global]
error_log = /var/log/php-fpm.log
daemonize = no
log_level = notice
log_limit = 8192
[www]
listen = 9000
user = www-data
group = www-data
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
```

`docker-compose exec php cat /var/log/php-fpm.log`

```
[23-Mar-2021 02:34:21] NOTICE: fpm is running, pid 8
[23-Mar-2021 02:34:21] NOTICE: ready to handle connections
[23-Mar-2021 02:39:03] NOTICE: fpm is running, pid 8
[23-Mar-2021 02:39:03] NOTICE: ready to handle connections
[23-Mar-2021 02:40:30] NOTICE: fpm is running, pid 8
[23-Mar-2021 02:40:30] NOTICE: ready to handle connections
[23-Mar-2021 02:41:49] NOTICE: fpm is running, pid 7
[23-Mar-2021 02:41:49] NOTICE: ready to handle connections
```

On the host it appears empty, plus I have log files that are working fine in the same directory.

**Comment by phy25** [comment]
This is how you can override PHP configuration: https://github.com/docker-library/docs/tree/master/php#configuration

Probably why your path does not work:

https://github.com/docker-library/php/blob/1ad18817e5de82df1a8855fe711de0b3c0c320b9/7.4/buster/fpm/Dockerfile#L42

**Comment by chiqui3d** [comment]
What I do in my image is to copy the configuration
`COPY /docker/php-fpm/app.ini $PHP_INI_DIR/conf.d/php.ini`
```
date.timezone = "Europe/Madrid"
expose_php = Off
apc.enable_cli = 1
session.auto_start = 0
memory_limit = -1
opcache.enable=1
opcache.use_cwd=0
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption=256
opcache.validate_timestamps=1
opcache.fast_shutdown=1
opcache.revalidate_freq=0
realpath_cache_size=4096K
realpath_cache_ttl=600
upload_max_filesize = 20M
post_max_size = 108M
default_socket_timeout=3600
request_terminate_timeout=600
```

I don't know what else I need to change? The truth is that with so many PHP configurations, I'm getting confused.

But the strange thing is what I said before, is that the logs are inside the container, but the host is not.

**Comment by chiqui3d** [comment]
It's a permissions error as far as I can see, I found a great explanation here => https://github.com/docker/compose/issues/5507
