### ISSUE TITLE
Configuring locale on php:7.4-fpm-alpine

### ISSUE THREAD

**Issue by LucianoVandi** [docker-library/php#1144]
I've added locale support on `php:7.4-fpm-alpine`, following this [guide](https://github.com/Auswaschbar/alpine-localized-docker/blob/master/Dockerfile)

It seems to works as expected if i run `date` on the command line:

```bash
$: locale
LANG=
LC_CTYPE=it_IT.UTF-8
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE=it_IT.UTF-8
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES=it_IT.UTF-8
LC_ALL=it_IT.UTF-8

$: date
Sab Mar 27 11:03:21 UTC 2021
```

But if I run thru php it shows dates in default locale:
```bash
$: php -r "setlocale(LC_ALL, 'it_IT.UTF-8'); echo date('r');"
Sat, 27 Mar 2021 11:04:56 +0000
```
Do I miss any steps from the setup?

**Comment by wglambert** [comment]
Alpine doesn't really have support for locales https://github.com/docker-library/php/issues/1041#issuecomment-664609975
