### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by drpain** [docker-library/php#115]
I have to look at the ext-configure scripts a bit more to know how to do this myself, but does anyone know how I would go about adding xdebug to the possible modules? 

This is more a development package, but it would help me greatly.

**Comment by drpain** [comment]
I see even though you normally install it via a package manager, it's actually a pecl library. I will rather do this when I prepare my image.

**Comment by drpain** [comment]
For those interested in adding xdebug for the current ```FROM php:5.6-fpm``` image, you can do so using the following Dockerfile section

```
# Install xdebug additionally
RUN curl -L -o /tmp/xdebug.tar.gz http://xdebug.org/files/xdebug-2.3.3.tgz \
&& tar xfz /tmp/xdebug.tar.gz \
&& rm -r /tmp/xdebug.tar.gz \
&& mv xdebug-2.3.3 /usr/src/php/ext/xdebug \
&& docker-php-ext-install xdebug
```

My full Dockerfile is below if you want to see it in context. It would still need you to sed / echo more configuration into the php config files. And for you to expose the xdebug port. I will update it once I have gotten this to work. Please note I use redis for sessions, hence the configuration for it. 

```
FROM php:5.6-fpm

# Copy dev php.ini
COPY config/php.ini /usr/local/etc/php/

# Enable Reporting
RUN echo "php_flag[display_errors] = On">>/usr/local/etc/php-fpm.conf
RUN echo "php_admin_flag[log_errors] = On">>/usr/local/etc/php-fpm.conf
RUN echo "php_admin_value[display_errors] = 'stderr'">>/usr/local/etc/php-fpm.conf
RUN echo "php_value[session.save_handler] = redis">>/usr/local/etc/php-fpm.conf
RUN echo "php_value[session.save_path] = 'tcp://redis:6379/'">>/usr/local/etc/php-fpm.conf

# Setting SAST Time
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
RUN "date"

# Install modules
RUN apt-get update && apt-get install -y \
libfreetype6-dev \
libjpeg62-turbo-dev \
libmcrypt-dev \
libpng12-dev \
imagemagick \
php5-imagick \
&& curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/2.2.7.tar.gz \
&& tar xfz /tmp/redis.tar.gz \
&& rm -r /tmp/redis.tar.gz \
&& mv phpredis-2.2.7 /usr/src/php/ext/redis \
&& docker-php-ext-install redis mysql mysqli iconv exif pdo pdo_mysql opcache bcmath mbstring zip \
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
&& docker-php-ext-install gd

# Install xdebug additionally
RUN curl -L -o /tmp/xdebug.tar.gz http://xdebug.org/files/xdebug-2.3.3.tgz \
&& tar xfz /tmp/xdebug.tar.gz \
&& rm -r /tmp/xdebug.tar.gz \
&& mv xdebug-2.3.3 /usr/src/php/ext/xdebug \
&& docker-php-ext-install xdebug

# Use composer to install dependencies
RUN mkdir -p /usr/share/nginx/html
WORKDIR "/usr/share/nginx/html"
RUN curl -sS https://getcomposer.org/installer|php

CMD ["php-fpm"]
```

**Comment by helderco** [comment]
There's a simpler way to install xdebug, or any PECL extensions for that matter:

```
pecl install xdebug
```

Although, I prefer using `docker-php-ext-install`, so I built a script that does exactly what you're doing by hand: [docker-php-pecl-install](https://github.com/helderco/docker-php/blob/master/template/bin/docker-php-pecl-install).

You use it like this:

```Dockerfile
FROM php:5.6-fpm
RUN docker-php-pecl-install xdebug-2.3.3 uploadprogress-1.0.3.1
```

So, as you can see, you can install multiple extensions on the same line.

**Comment by drpain** [comment]
Sweet thank you Helder! I will give it a try

**Comment by drpain** [comment]
@helderco You are a legend thank you!
