### ISSUE TITLE
PHP 7.4.18 bug ID 81002 is effecting php:7.4-apache images 

### ISSUE THREAD

**Issue by markdegroat** [docker-library/php#1155]
This bug is blocking seeders from running in my case but this code shouldn't have made it into the official docker image for php 7.4 - is there a way to alleviate this issue before they release 7.4.19 as I could not find an ETA online anywhere?

https://bugs.php.net/bug.php?id=81002

The latest comment in this thread is also relevant:
https://bugs.php.net/bug.php?id=80892

**Comment by yosifkit** [comment]
> is there a way to alleviate this issue before they release 7.4.19

We strive to follow upstream releases as closely as possible and so don't really backport patches. Once there is a release available, we'll publish a new image

**Comment by markdegroat** [comment]
Thank you for the prompt response - your edit solution I attempted before and it appeared from reading docs I read that I wasn't able to specify `7.4.X` but instead only `7.X`

I was viewing the supported tags from this page:
https://hub.docker.com/_/php
and it didn't have a variant listed for 7.4.17, but I did attempt to just follow that format.  Will attempt again if that should work.

**Comment by chapterjason** [comment]
PHP 8.0.5 is also affected.

**Comment by edudobay** [comment]
PHP 7.4.19 and 8.0.6 have been released with this issue fixed. Should we wait for an automatic build by @docker-library-bot or can we open a PR ourselves?

**Comment by yosifkit** [comment]
Until the releases are in the API (like https://www.php.net/releases/index.php?json&max=100&version=8.0), the bot would undo any merged PR.

**Comment by Schwuuuuup** [comment]
It looks to me, like 7.4.19 is released (https://www.php.net/releases/index.php?json&max=100&version=7.4) but the Docker file still contains 7.4.18... or am I mistaken?

**Comment by NiklasBr** [comment]
Built a few minutes ago with `FROM php:7.4-fpm` and got 7.4.18 unfortunately. How often is the bot refreshing?

**Comment by chapterjason** [comment]
@NiklasBr https://github.com/docker-library/php/blob/47e681a74116da5a99e804bef5a7808df40d831f/.github/workflows/ci.yml#L7

https://crontab.guru/#0_0_*_*_0

**Comment by tianon** [comment]
That action is only a build test -- it isn't responsible for the automated bumps done by @docker-library-bot.

What you're looking for is https://doi-janky.infosiftr.net/job/update.sh/job/php/, which is powered by https://github.com/docker-library/oi-janky-groovy/tree/master/update.sh, which triggers each image's update job to check for (and then test build) changes every ~6 hours.

In the case of PHP 7.4.19, the test builds done by @docker-library-bot were in-progress at https://doi-janky.infosiftr.net/job/update.sh/job/php/6844/, and resulted in https://github.com/docker-library/php/commit/47e681a74116da5a99e804bef5a7808df40d831f.

From there we get into https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet and https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what, thus https://github.com/docker-library/official-images/pull/10127 which is now merged and the official builds are in-queue and/or in-progress (with a couple of them already complete): https://doi-janky.infosiftr.net/job/multiarch/view/images/view/php/
