### ISSUE TITLE
Problem running wget https://get.docker.com/ | sh

### ISSUE THREAD

**Issue by cts-prog3** [docker-library/php#117]
I am following https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md and am at the step where it says run 
wget -qO- https://get.docker.com/ | sh

![dockererror](https://cloud.githubusercontent.com/assets/7528702/8696618/3112e82c-2b31-11e5-87af-c4389cd0f6cc.PNG)
 I tried running apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9 but that didn't seem to help.

**Comment by jjelev** [comment]
I am quite sure that you have addressed the wrong repository.
Please refer to official installation docs. Pay attention to section 3 from the installation process.
http://docs.docker.com/installation/ubuntulinux/#installation

try `wget -qO- https://get.docker.com/gpg | sudo apt-key add -` first and then `wget -qO- https://get.docker.com/ | sh`

lastly add your user to docker group to be able to run docker without sudo (optional)
`sudo usermod -aG docker your_user_name`
