### ISSUE TITLE
PHP 8.1 not updated

### ISSUE THREAD

**Issue by mvorisek** [docker-library/php#1170]
PHP 8.1 alpha 2 is released but PHP 8.1 did not update.

Judging from https://github.com/docker-library/php/commits/master/versions.json , is `docker-library-bot` bot configured correctly to update PHP 8.1 when a new release is made or what action is needed to trigger it?

**Comment by yosifkit** [comment]
We use the APIs to check for new releases, so it won't be updated until it is listed in one of the APIs.

Regular releases:
https://github.com/docker-library/php/blob/6da00646d52e29c26491ee25d1ab2e3dcb4cc940/versions.sh#L51

Pre-releases:
https://github.com/docker-library/php/blob/6da00646d52e29c26491ee25d1ab2e3dcb4cc940/versions.sh#L64

**Comment by ramsey** [comment]
This is expected. We have not yet officially released Alpha 2. Once we announce it on the mailing lists and post to the website, it will be official.

**Comment by ramsey** [comment]
The 8.1.0alpha2 release is now officially announced. 😁

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/123423967-7ea34b00-d5c0-11eb-856d-d8d1812e7a6a.png)

not sure if related, but the PHP 8.1 RC build job have issues - is this the reason why alpha2 was not comitted yet by the bot?

**Comment by agustingomes** [comment]
@mvorisek is possitble it's failing the build bacause qa.php.net no longer has the alpha1 version, and from what I can see in the error in Jenkins, it's still referencing it, hence the failure.

**Comment by heddn** [comment]
Seems to be failing on libsodium:

> ext/sodium/libsodium.dep -MT ext/sodium/libsodium.lo
make: /bin/sh: Operation not permitted
make: *** [Makefile:1366: ext/sodium/libsodium.lo] Error 127

**Comment by yosifkit** [comment]
> not sure if related, but the PHP 8.1 RC build job have issues - is this the reason why alpha2 was not comitted yet by the bot?

Yes, this is why it is not committed yet. The failure is related to our build servers needing a `runc` update to get https://github.com/opencontainers/runc/pull/2750 and so the Alpine 3.14 based builds currently fail which causes the `update.sh` job to not commit the update for that version yet.   We're working on a fix to get an updated docker for all our architectures (docker does not publish builds for all of them).

**Comment by tianon** [comment]
Builders are updated and update test build is in progress -- sorry for the delay!

**Comment by heddn** [comment]
Am I being impatient? Is alpha2 supposed to be released now the builders are running? Is there a delay between the build running and new releases on docker hub?  https://hub.docker.com/_/php?tab=tags&page=1&ordering=last_updated&name=8.1.0alpha2

**Comment by mvorisek** [comment]
@yosifkit @tianon what is the build/tag process and when it should happen? The sources was updated in https://github.com/docker-library/php/commit/541ab0e70f98cc3efce08ead9548285c984d6d33 2 days ago, but the image is still not available. The Jenkins jobs run several times per day, but nothing is pushed to the registry yet. Can this delay be decreased in general so the images are available as soon as the new php release is available?

**Comment by tianon** [comment]
Commit went up in https://github.com/docker-library/php/commit/541ab0e70f98cc3efce08ead9548285c984d6d33, PR is up at https://github.com/docker-library/official-images/pull/10437; see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what for the full process.
