### ISSUE TITLE
How to generate apache access log in php image: 7.4-apache

### ISSUE THREAD

**Issue by samuelgeek** [docker-library/php#1174]
Dear, I would like to clear a doubt with the community.

I am deploying a staging environment and would like to implement observability to collect application logs and would like to collect apache access logs but I noticed that the php:7.4-apache image does not generate access log when I use tail -f /var/ log/apache2/access.log has no output, I would like to know how to activate this feature in the image, could you help me?

**Comment by wglambert** [comment]
https://github.com/docker-library/php/blob/541ab0e70f98cc3efce08ead9548285c984d6d33/8.0/buster/apache/Dockerfile#L84-L88

Because docker logs are read from `/dev/stderr` and `/dev/stdout` these get redirected https://github.com/docker-library/php/issues/863#issuecomment-510694726

**Comment by samuelgeek** [comment]
> https://github.com/docker-library/php/blob/541ab0e70f98cc3efce08ead9548285c984d6d33/8.0/buster/apache/Dockerfile#L84-L88
> 
> Because docker logs are read from `/dev/stderr` and `/dev/stdout` these get redirected [#863 (comment)](https://github.com/docker-library/php/issues/863#issuecomment-510694726)

Thank you very much for the reply, in that case do I run the commands in the Dockerfile?

**Comment by yosifkit** [comment]
Since it is already logging access to stdout, you can just get it with `docker logs` (or wherever you configure [`log-driver`](https://docs.docker.com/config/containers/logging/configure/) to point to).

**Comment by samuelgeek** [comment]
I managed to solve the problem as follows:

docker run -v /var/log/lumen:/var/www/html/storage/logs --log-driver gelf --log-opt gelf-address=udp://:12201 -d -p "8080:80 " --name ms-products --network devnet <DOCKER IMAGE>

As I'm running an application in lumen in this container I chose to use logstash using the input file to capture error logs and gelf to capture apache's access log.

My logstash configuration file to read log files generated by lumen is:

`input {
    file {
        path => "/var/log/applog/*.log"
        start_position => "beginning"
        ignore_older => 0
        codec => multiline { pattern => "\[[\d]{4}" negate => "true" what => "previous" }
    }
}

filter {
  grok {
    match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{DATA:env}\.%{DATA:severity}: %{DATA:message}" }
  }
}

## Add your filters / logstash plugins configuration here

output {
  elasticsearch {
    hosts => ["http://${ELASTIC_HOST:elasticsearch}:9200"]
    index => "${ELASTIC_LOG_INDEX:logs-services}"
    user => "${ELASTIC_USER:elastic}"
    password => "${ELASTIC_PASS:changeme}"
  }
  stdout { }
}`

My configuration file for apache access log listening:

`input {
    gelf {
      port => 12201
    }
}

filter {
  grok {
    match => { "message" => "%{COMMONAPACHELOG} %{QS:referrer} %{QS:agent}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://${ELASTIC_HOST:elasticsearch}:9200"]
    index => "${ELASTIC_LOG_INDEX:access-logs-services}"
    user => "${ELASTIC_USER:elastic}"
    password => "${ELASTIC_PASS:changeme}"
  }
  stdout { }
}`
