### ISSUE TITLE
Why dockerfile is not based on Centos.

### ISSUE THREAD

**Issue by clh021** [docker-library/php#118]
Excuse me,
I found here dockerfile is based on Debian to create the mirror of, and most of our real application in the real server is use CentOS to deployment environment, so I want to ask is, for whatever reason, there is no production based on CentOS mirror, because most of the time I hope my container environment and server environment unified.

**Comment by Moghedrin** [comment]
The whole point of Docker itself is that you don't *need* container environment and server environment unified in this way. Furthermore, maintaining a variation of every official image for every conceivable base that people may *want*, especially if the desire for that alternate base is only for environment unification, would be completely untenable in the long run.
