### ISSUE TITLE
gnu-libiconv-1.16 doesn't work with php8

### ISSUE THREAD

**Issue by joepagan** [docker-library/php#1180]
As I highlighted in [this comment on the issue](https://github.com/docker-library/php/issues/240#issuecomment-876464325): `gnu-libiconv-1.16` does not work with `php:8.0-fpm-alpine`. 
It installs ok and appears in the php info, though the errors I get are as if it is not installed.

The highly up voted answers in the linked issue specifically reference the `edge` CDN: `http://dl-cdn.alpinelinux.org/alpine/edge/community` where only libiconv-1.16 is available. Instead, for php8 we have to use the CDN for alpine `v3.13` (despite being on `alpine` which is currently `v3.14`) to get access to `gnu-libiconv=1.15-r3` which does load successfully and work with php8.

On another point, I do feel that the original issue should be re-opened as this seems like the work around in the original issue is a hack which we shouldn't need to do, though I appreciate that issue requires changes further up the chain at the alpine level to resolve.

**Comment by samuelkarp** [comment]
> I appreciate that issue requires changes further up the chain at the alpine level to resolve.

Hey @joepagan! I'm not sure what the official image project can do if there's a problem upstream with Alpine.  Can you close this and reopen it when there's something actionable?

**Comment by wglambert** [comment]
Closing given what was said in https://github.com/docker-library/php/issues/240#issuecomment-353678474

There isn't really anything actionable we could do at the Dockerfile level to alleviate this

**Comment by joepagan** [comment]
Yes that's fair to close, sorry for the noise and for inactivity had some stuff going on. Now coming back to it I think it's more of an bug for php themselves to look at.
