### ISSUE TITLE
unclean shutdown with apache can prevent subsequent start

### ISSUE THREAD

**Issue by ybizeul** [docker-library/php#1185]
When using an apache container, like `php:5.6-apache` base image and adding `a2enmod rewrite auth_digest` to our own build.

If the container crashes, it will never start again with an error :

```
web_1    | [Sun Aug 01 08:45:26.633525 2021] [auth_digest:error] [pid 1] (17)File exists: AH01762: Failed to create shared memory segment on file /var/run/apache2/authdigest_shm.1
web_1    | [Sun Aug 01 08:45:26.636090 2021] [auth_digest:error] [pid 1] (17)File exists: AH01760: failed to initialize shm - all nonce-count checking and one-time noncesdisabled
```

The issue seems to be with the overlay filesystem preserved if a container unexpectedly stops, and docker didn't clean the overlay filesystem.

A fix would be to make sure  `/run/apache2` is empty when starting, but not sure how practical this is.

**Comment by tianon** [comment]
Given that the module was enabled by your image (not something enabled in the base image), I'd suggest adding an entrypoint script to your image as well that performs the necessary cleanup -- it would be a bit complicated for us to add something generic to the image to do this safely.

**Comment by tianon** [comment]
Another option would be to use `--tmpfs` for `/run/apache2`, but I think that might still persist between container runs sometimes.

**Comment by ybizeul** [comment]
Thanks for answering. Yes I guess it makes sense, though having a fresh /run directory at start might not be a bad idea and avoid situations like this one. Could be a disruptive change though. I'll close this now thanks again !
