### ISSUE TITLE
7.4.22-fpm: permission errors during configuration

### ISSUE THREAD

**Issue by robbieaverill** [docker-library/php#1191]
Hi team, I have a Dockerfile using `7.4-fpm`, which as of recently pulls in 7.4.22. It looks like this:

```
FROM php:7.4-fpm
WORKDIR "/public"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install nano vim iputils-ping \
		sqlite3 libsqlite3-dev libpq-dev cron supervisor && \
	docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
	docker-php-ext-install bcmath mysqli pdo pdo_mysql opcache pgsql pdo_pgsql
```

The `RUN` here now fails with the following error:

```
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
enable igbinary serializer support? [no] : enable lzf compression support? [no] : enable zstd compression support? [no] : building in /tmp/pear/temp/pear-build-defaultuserrbqX62/redis-5.3.4
running: /tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
ERROR: `/tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no' failed
```

Everything continues to work correctly if I switch back to `7.4.21-fpm` instead of `7.4.22-fpm`.

This is running in a CircleCI container, for context.

**Comment by tianon** [comment]
You probably need a newer version of Docker, runc, and/or libseccomp (you can verify by switching to `FROM php:7.4-fpm-buster`, which will probably work).

**Comment by robbieaverill** [comment]
Hi @tianon, thanks for the reply. I can confirm that `7.4-fpm-buster` works. If you don't think this is an issue please feel free to close it, just thought I'd raise it in case something changed unintentionally.

**Comment by tianon** [comment]
It's related to #1190 but was intentional (unfortunate, but IMO the fixes are worth updating for).
