### ISSUE TITLE
[BUG] 8.1.0RC1 alpine images have broken networking/gethostbyaddr behaviour

### ISSUE THREAD

**Issue by sbuerk** [docker-library/php#1201]
We wanted to add php 8.1.0RC1 to our testing chain to start early mitigate issues in our projec(s).

As we uses the alpine images as base (size etc) we added the 8.1.0RC1 one and detected weired behaviors. We narrowed it down and can reproduce it with a simple test script.

Background: We have tests resolving '::1' ipv6 and should resolved to "localhost" or at least something other then ::1. What was weired is, that id did not worked. We moved it to the start of phpunit, from where we stripped down the test-file.

But it is 8.1.0RC1 not per se, local install works and even the other (as far as tested) seems to work, only the alpine onces are broken

To make sure we do not intrude the issue through our Dockerfile which installs further packages, we tested it against the original images build/released from here:

Create "test-folder/test.php" with following code:
```php
<?php
echo "CHECK ::1 hostname before/after version compare" . PHP_EOL;

// duplicationg this line bevore other code lines, would work until something
// like version_compare is used.
// EXPECTED: localhost
echo "#1 IPv6(::1): " . (string)gethostbyaddr('::1') . PHP_EOL;

// this line chanes the return in 8.1.0RC1-alpine - but why ?
// but even other codelines changed it
if (!version_compare(PHP_VERSION, PHP_VERSION, '=')) {}

// EXPECTED: localhost => alpine ::1, others localhost as expected
echo "#2 IPv6(::1): " . (string)gethostbyaddr('::1') . PHP_EOL;
```

Test commands with outputs (in folder where test.php was created):
Note: not all, just some as cross checks

```
// not working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-alpine php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): ::1
```

```
// not working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-alpine3.13 php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): ::1
```

```
// not working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-alpine3.14 php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): ::1
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.0-alpine php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.0-alpine3.13 php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.0-alpine3.13 php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-cli php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1 php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-cli-buster php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```

```
// working
$ docker run -it --rm --name blub -v "$PWD":/myapp -w /myapp php:8.1.0RC1-buster php test.php

CHECK ::1 hostname before/after version compare
#1 IPv6(::1): localhost
#2 IPv6(::1): localhost
```
Basicly for 8.0 the sambe base images are used for alpine, and I did not found (yet) a different betwenn the 8.1.0RC1 builds
from 8.0 which would explain this.

Anyone a clue how to "stabalize" it ?

Note: Checked /etc/hosts in the container, it has the right entries.

Thanks for any hints, how we can fix it on our sides - or where this behavour comes from.

**Comment by tianon** [comment]
This is strange -- I know there used to be a lot of bugs around `gethostbyaddr` and Alpine's behavior, but I can't seem to find a good reference for the previous issues now that I need it.  I don't see anything interesting in 8.1's changelog that would lead to this, either. :confused:

**Comment by sbuerk** [comment]
Only things I can found are for other languages, not regarding ::1 but DNS resolving at all - and consens is through google to switch do another base image :/

**Comment by sbuerk** [comment]
Create php bug report for now:

https://bugs.php.net/bug.php?id=81441

**Comment by tianon** [comment]
It looks like there are PHP 8.1 packages in Alpine's Edge distribution too that are probably worth trying to see if they suffer from the same issue (as additional useful input for your bug): https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php81

In this case, I don't think there's anything we can change/fix in the image itself to correct this, so I'm going to close this in favor of https://bugs.php.net/bug.php?id=81441. :grimacing:

**Comment by sbuerk** [comment]
Tested the alpine 3.14 image with php81* packages from edge testing => working.
Tested also this repo alpine 8.1.0RC1 images with "musl" from edge/testing => working.

What also worked was to install musl from edge/testing in the 3.14 alpine image.
Would provide a PR for it to use musl from testing for the alpine images (at least for 3.14) with musl from testing, if this is wanted. 

From our side this would be nice, because using the install-php-extensions helper script would work, which do not work for the the direkt alpine image.

**Comment by nikic** [comment]
PHP 8.1 switched to using `getnameinfo()` instead of the deprecated `gethostbyaddr()` (https://github.com/php/php-src/blob/a22f9fc104fee7466ad715d4e024b7ef9ede4e4e/ext/standard/dns.c#L183). Not seeing anything obvious wrong with that code. Is there something special about getnameinfo() on musl?

**Comment by nikic** [comment]
Hm, possibly this is because we're not initializing sin_port? Looking at the getnameinfo() man page, that might be required.

**Comment by sbuerk** [comment]
Just to note - 8.1.0RC6 contains bugfix for this issue.
