### ISSUE TITLE
Can access root file system, even as root user

### ISSUE THREAD

**Issue by BillyMorgan** [docker-library/php#1202]
As of 7.3.29-fpm I don't seem to be able to access the root file system.

```
docker run --rm -it php:7.3.29-fpm bash
root@07d226875503:/var/www/html# ls /
ls: cannot access '/': Operation not permitted
```

I can't see any existing issue tickets logged and 7.3.29-fpm was released ~1 month ago, so I imagine it's just me doing something stoopid. I'm just not sure what. As you can see the steps to reproduce are fairly simple 🤷

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/issues/465
>you'll need to update Docker, runc, and likely libseccomp on your host.

**Comment by tianon** [comment]
See also #1192.
