### ISSUE TITLE
Option to enable caching in docker-php-ext-install

### ISSUE THREAD

**Issue by wedi** [docker-library/php#1203]
WIth the advent of moby's buildx and its cool [caching features](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache) I have started to replace instructions to avoid caching / remove caches with matching cache mounts. The results are some pretty significant reductions in build times.

I wonder what you think about an option to leverage these caching mechanisms in the `docker-php-ext-*` utility set?

**Comment by yosifkit** [comment]
I am unsure what sort of changes you are alluding to. The current scripts are as simple as possible to pre-configure a specific php extension (`phpize`), build it (`make`), and then enable it (drop a single line in a file in `$PHP_INI_DIR/conf.d/`). They work very well with `docker build` cache. I am very hesitant to increase their complexity.
