### ISSUE TITLE
Unable to load dynamic library 'mysqli'

### ISSUE THREAD

**Issue by RT-Tap** [docker-library/php#1205]
I have been trying to get phpmyadmin working and every time I try to access it I get the following error: 
```
Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: mysqli
```
However I have `extension=mysqli` uncommented so it should load, right? 

Whenever I enter the container and try to run any php command I get the following error:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/mysqli (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mysqli: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/mysqli.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mysqli.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

I also tried to manually install using
```
apt-get install php-mysqli
apt-get install php-mysql
apt-get install php7.3-mysql
```
All returned with `E: unable to locate package`
Or am I supposed to manually download and compile and place it into respective directory?

`phpinfo();` output:

![phpinfo](https://user-images.githubusercontent.com/71105781/133919829-1895b570-0b3e-4650-a18e-88c624f9ad2e.png)

**Comment by phy25** [comment]
https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions

**Comment by RT-Tap** [comment]
Thank you very much ....  how I haven't come across that page I have no idea,  but thank you for pointing me in the right direction.
