### ISSUE TITLE
Building 5.6-fpm from Dokerfile

### ISSUE THREAD

**Issue by maxttor** [docker-library/php#121]
trying build image from Dokerfile 5.6-fpm got error on 10 Step:  
`
Step 10 : COPY docker-php-ext-* /usr/local/bin/ 
No source files were specified
`

**Comment by hairmare** [comment]
@maxttor Are you running ``docker build`` in the ``2.6/`` subdirectory? It looks like you are working with just the Dockerfile and not the accompanying files in the dir.

**Comment by maxttor** [comment]
@hairmare, yes, thx.

**Comment by tianon** [comment]
I'm definitely really curious why you're building from source instead of
just using the pre-built images?

More specifically, we're going to need more information about how you got
the "Dockerfile" you're working with and how you're building (especially if
there are steps we can use to reproduce and figure out the issue).

**Comment by mlalbuquerque** [comment]
I'm using your php:5.6-fpm image, but when installing extensions, I had some troubles. First, the ZLIB ext: I had to change the file "config0.m4" name to "config.m4" to install correctly.

And now I'm having problems with spl. It's printing this error:

```
cp: cannot stat 'modules/*': No such file or directory
Makefile:86: recipe for target 'install-modules' failed
make: *** [install-modules] Error 1
```
What it could be?

**Comment by tianon** [comment]
Sorry for the late reply!  Turns out ZLIB is one of the special snowflakes that has to be compiled in to work, so it's added now (https://github.com/docker-library/php/blob/85447ff6a554f05b1cb893e5edf2a2cbba848332/7.0/Dockerfile#L56; added in https://github.com/docker-library/php/pull/31).
