### ISSUE TITLE
Install specific php extension version using docker-php-ext-configure / or docker-php-ext-install

### ISSUE THREAD

**Issue by vz-spr** [docker-library/php#1215]
Hello.

Can you tell, please, how to install specific version of php extension using `docker-php-ext-configure` or `docker-php-ext-install` ?

Or if one use such way of installing php extensions packages no need to worries about versions compatibilities of those packages at all ? If yes, can you, please, update description in readme ?

**Comment by phy25** [comment]
There's a general description at https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions
