### ISSUE TITLE
Question regarding docker hub php container image tags

### ISSUE THREAD

**Issue by mfn** [docker-library/php#1220]
Hello 👋🏼 ,

my understanding is that docker hub does not have/use immutable tags for the PHP releases.

I've been using the following format to reference the base images in my docker image:
```
# https://hub.docker.com/layers/php/library/php/7.4.25-bullseye/images/sha256-f68f244566e4f195152b7e81f73426e46fbd53ad206d79dbcb09255198cb7c1e?context=explore
FROM php@sha256:f68f244566e4f195152b7e81f73426e46fbd53ad206d79dbcb09255198cb7c1e
```
(this is the reference for the amd64 architecture)

After a few weeks I checked this URL and it does not exist anymore:
![image](https://user-images.githubusercontent.com/87493/142610589-928958e4-d691-4523-9c67-e8f2aeaa5974.png)

Today it is this https://hub.docker.com/layers/php/library/php/7.4.25-bullseye/images/sha256-0a9aa59f89b055c13f9c3faa840e7b3390c5367fb31e830e09cf7e2c3473032c?context=explore
![image](https://user-images.githubusercontent.com/87493/142610717-bd59e7f6-690f-4cca-84f7-e05bf133fec5.png)

The screenshot says "last pushed: a day ago" but I can't follow where does came from, at least not in this repo:
![image](https://user-images.githubusercontent.com/87493/142610897-22952259-ca30-438c-8d25-b6cde95721b4.png)

Thing is: although the web url does not work anymore, the hash reference _does_ work.

Can someone shed light on this what is happening here (or: why)?

Thank you 🙏🏼

**Comment by tianon** [comment]
I can't speak to what's going on with Docker Hub's interface, but official images maintains https://github.com/docker-library/repo-info which should be helpful here.

Specifically, https://github.com/docker-library/repo-info/commits/master/repos/php/remote/7.4.25-bullseye.md is going to be your money shot, where you can see that the changes before the PHP (security-related) version bump which deprecated 7.4.25 changed all the layers all the way down, which is a clue that this was likely a Debian base image rebuild (which happens roughly every thirty days to pick up security updates in all the packages in all dependent images).  Looking at https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fdebian, that tracks: https://github.com/docker-library/official-images/pull/11308 :grinning:

**Comment by mfn** [comment]
@tianon thanks a lot, that very much explains it! I tried to figure out some things but I could not find the track you did from docker-library/php to docker-library/repo-info to docker-library/official-images ; that's a bit hard to digest for the uninitiated 😅 Again, thank you 🙏🏼
