### ISSUE TITLE
Any chance packaged tar is not compatible with armv7 architecture?

### ISSUE THREAD

**Issue by quentincaffeino** [docker-library/php#1221]
I'm trying to build an image which basically looks like this:

```Dockerfile
FROM php:7.4-alpine

RUN ash -x /usr/local/bin/docker-php-source extract
```

I'm on x86_64 but I need an image for armv7 so I'm using buildx.

```sh
$ docker buildx create --use
$ docker buildx build --platform=linux/arm/v7 --tag app:php74 --progress plain --file ./Dockerfile .
```

And I get this error:

```log
#9 13.73 + set -e
#9 13.73 + dir=/usr/src/php
#9 13.74 + mkdir -p /usr/src/php
#9 13.77 + '[' '!' -f /usr/src/php/.docker-extracted ]
#9 13.78 + tar -Jxf /usr/src/php.tar.xz -C /usr/src/php '--strip-components=1'
#9 13.85 tar: Child returned status 1
#9 13.86 tar: Error is not recoverable: exiting now
```

I checked and /usr/src/php.tar.xz exists. Also tried redownloading image - no luck.

**Comment by quentincaffeino** [comment]
I found that buildx inittialized only with `linux/amd64, linux/386`. To add I ran:

```sh
$ docker buildx create --use --platform linux/amd64,linux/386,linux/arm/v7
```

But that didn't help, build still fails with the same error

**Comment by tianon** [comment]
That's extremely unlikely -- can you test on a native system?  That would help you rule out whether it's caused by the QEMU emulation.

If it turns out that it's the packaged `tar` being incompatible, this should be filed with the Alpine project; otherwise, it should be filed in Docker's QEMU repo: https://github.com/moby/qemu

**Comment by quentincaffeino** [comment]
In the mean time can we apply the fix I found for this which works by first extracting xz and then tar?

```sh
			xz -d /usr/src/php.tar.xz
			tar -xf /usr/src/php.tar -C "$dir" --strip-components=1
```

**Comment by tianon** [comment]
Unfortunately, we won't be adding a workaround for this to our image, but
you're welcome to do so in your own image that's "FROM" this one.
