### ISSUE TITLE
docker-php-ext-configure ldap should fail when libldap-common is not available

### ISSUE THREAD

**Issue by thinkl33t** [docker-library/php#1228]
Since the change reported in https://github.com/docker-library/php/issues/1194, and tracked down in https://github.com/docker-library/php/issues/1194#issuecomment-904954896 , we have encountered [multiple](https://github.com/roundcube/roundcubemail-docker/issues/160) [pieces](https://github.com/nextcloud/docker/issues/1572) of containerized PHP software that have been failing to connect to LDAP, and they have all led back to this common issue.

Since it is non-obvious to developers that installing the ldap module will require this dependency, i suggest either:
1) install it by default in the php debian-based containers
2) install it on demand when `docker-php-ext-configure ldap` is run
3) cause installation to fail if it is not installed when `docker-php-ext-configure ldap` is run

I think (1) would be the easiest, but obviously adds a dependency that would be unwanted in a lot of installations.

**Comment by thinkl33t** [comment]
Note: this effects LDAP with TLS - I believe insecure LDAP still works OK, but shouldn't be used for obvious reasons.

**Comment by yosifkit** [comment]
>1. install it by default in the php debian-based containers

While the package is very small (https://packages.debian.org/buster/libldap-common), we do not install extra packages for extensions that aren't enabled by default.

>2. install it on demand when docker-php-ext-configure ldap is run

We do not want to maintain the extension to required packages mapping; that is the goal of https://github.com/mlocati/docker-php-extension-installer. (it looks like they have not updated to ensure `libldap-common`, so maybe an issue or PR there would help others)

>3. cause installation to fail if it is not installed when docker-php-ext-configure ldap is run

Detecting if it is installed would be maintaining the same map as auto-installing it; see previous answer.

**Comment by thinkl33t** [comment]
I have opened an issue upstream with docker-php-extension-installer

**Comment by thinkl33t** [comment]
I have added libldap-common to ldap on docker-php-extension-installer, but I can't find any way in which the php container specifications here actually consume that script?  Am i missing something or is it completely unrelated?

**Comment by phy25** [comment]
https://github.com/mlocati/docker-php-extension-installer#usage

"php" does not consume "docker-php-extension-installer".

**Comment by tianon** [comment]
> We do not want to maintain the extension to required packages mapping; that is the goal of https://github.com/mlocati/docker-php-extension-installer.

:see_no_evil: :heart:
