### ISSUE TITLE
PHP 8.1 docker image only for arm platform

### ISSUE THREAD

**Issue by misaon** [docker-library/php#1229]
Please add/build PHP 8.1 images for amd64 platform too.

**Comment by webmaster777** [comment]
![image](https://user-images.githubusercontent.com/2650744/144015255-c0fc7e2a-9dec-4a2f-9ce5-a5c4f859416b.png)

Have some patience.

**Comment by ruudk** [comment]
To monitor the status, see https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/

**Comment by jelrikvh** [comment]
Ah, today I learned that the image is already seen as available before all manifests are published. Thanks :-)!
