### ISSUE TITLE
Unable to use private key in tag fpm-alpine3.15 and tag fpm-alpine

### ISSUE THREAD

**Issue by albertvveld** [docker-library/php#1237]
After I build a new php (7.4 and 8.1) Image with tags fpm-alpine3.15 and tag fpm-alpine, I wasn't able to use my private key anymore to pull from Gitlab in a running container. When I build the exact same Image with alpine 3.14 it does work again.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue
