### ISSUE TITLE
How are the *.conf files "summarized" in the php-fpm (alpine) images?

### ISSUE THREAD

**Issue by solventt** [docker-library/php#1242]
In the alpine images:

The '/usr/local/etc/' directory has the php-fpm.conf file that contains a directive `include=etc/php-fpm.d/*.conf`. in turn 'etc/php-fpm.d/' does not exist.

/usr/local/etc/php-fpm.d/ has: 

docker.conf
www.conf
www.conf.default
zz-docker.conf

Do the above files summarize somehow to each other, as well as to the global file (php-fpm.conf)? How the configuration is formed from many files here? Why are there so many files?

**Comment by wglambert** [comment]
Files in the config directory are loaded in alphabetical order so `zz-docker` would be loaded last over additional user-created files placed there
https://github.com/docker-library/php/blob/c3ee24b4280eff1b55b7a22e527532617e56bcf0/8.1/alpine3.15/fpm/Dockerfile#L205-L241

Their configuration changes are shown in `php -i` where you'll also see `Loaded Configuration File => (none)` by default if the user doesn't supply one
