### ISSUE TITLE
[feature]php is release 8.0.15 today now..

### ISSUE THREAD

**Issue by jt9ge** [docker-library/php#1244]
please build php-fpm 8.0.15.

**Comment by tianon** [comment]
https://github.com/docker-library/php/commit/b09fd3beb1bf3e9942dcc8d94262e08e157c9c1e -> https://github.com/docker-library/official-images/pull/11711
(https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)
