### ISSUE TITLE
Github CI action failed fo Update PHP8.1 to 8.1.2

### ISSUE THREAD

**Issue by sbuerk** [docker-library/php#1246]
Github CI action failed fo Update PHP8.1 to 8.1.2

The github pipeline action has an error ? Was this regonaized ?

https://github.com/docker-library/php/actions/runs/1726984212

**Comment by yosifkit** [comment]
The GitHub action does not perform the update, that's just the regular build tests for the new commit that contained the update (https://github.com/docker-library/php/commit/b4b4093acd612a1b489c6442585379275e9e4df6) that the `update.sh` job did.
