### ISSUE TITLE
Provide a docker tag for the latest RCs

### ISSUE THREAD

**Issue by EtienneBruines** [docker-library/php#1248]
At https://github.com/php/php-src/issues/7978#issuecomment-1019561378 it is mentioned, that the maintainers of PHP would love some community help in trying out and verifying PHP RC versions to prevent issues like https://github.com/docker-library/php/issues/1245 from appearing in stable releases.

Would it be possible to have a docker tag always pointing to that latest RC version? That way more people can contribute in trying out releases before they land.

**Comment by ramsey** [comment]
As mentioned here: https://github.com/php/php-src/issues/7978#issuecomment-1022346926

> the PHP project does release RCs of its patch releases. These are not pushed through normal distribution channels, but it's possible to detect their releases through the feed located here: https://qa.php.net/api.php?type=qa-releases&format=json
>
> In that feed, there are currently no RCs for any supported versions (`"active": true`) of PHP, so they list `number` as `0` in the `release` property for each.

**Comment by tianon** [comment]
Given there aren't any right now, we can't really publish anything, but I've opened https://github.com/docker-library/php/pull/1249 which should make them show up/go away automatically over time (via @docker-library-bot). :smile:

**Comment by ramsey** [comment]
We should have two RCs announced next week for 8.0.x and 8.1.x.

**Comment by tianon** [comment]
Huge success: https://github.com/docker-library/php/commit/0869d23 :smile:
