### ISSUE TITLE
Sample of Ubuntu dockerfile

### ISSUE THREAD

**Issue by ttodua** [docker-library/php#1252]
I've gone through the previous issues, mentioning Ubuntu images/dockerfiles will not be included in this repo. However, for the sake of some help, can you give us an example ('in-house' version)  of dockerfile (apache variation) which will be based on Ubuntu (focal-fossa) and will be a good start point?

thanks

**Comment by yosifkit** [comment]
I think the easiest starting point would be to change the `FROM` line in any of our Dockerfiles, like [`8.0-apache`](https://github.com/docker-library/php/blob/a013f410ff05ec348b34a85f6c9c2ae460c30086/8.0/bullseye/apache/Dockerfile). I honestly think there will be minimal changes after that (maybe a couple package name differences).

**Comment by ttodua** [comment]
thanks for reply. unfotunately no, I've tried `FROM phusion/baseimage:focal-1.1.0` but then there comes other issues (mbstring dependent `libonig` is not being installed and throws error).
that's why it would have been a help from you if you provided sample for ubuntu folks.
