### ISSUE TITLE
Alpine 3.15 make: /bin/sh: Operation not permitted

### ISSUE THREAD

**Issue by Hello-Linux** [docker-library/php#1253]
Please see the picture
![2022-02-09 11-01-38 的屏幕截图](https://user-images.githubusercontent.com/17851645/153113913-4e63084d-65ae-42b3-92ad-421c1ec1d00e.png)

**Comment by yosifkit** [comment]
This sounds very much like https://github.com/docker-library/php/issues/1177#issuecomment-920260435
