### ISSUE TITLE
Enable readline in phpdbg

### ISSUE THREAD

**Issue by computator** [docker-library/php#1257]
phpdbg and readline are already both enabled by default, however the `--enable-phpdbg-readline` flag is not set to enable readline in phpdbg. If this could be enabled it would make using phpdbg much more convenient!

**Comment by tianon** [comment]
If `phpdbg` is enabled, it's definitely not on purpose. :grimacing: :see_no_evil:

**Comment by computator** [comment]
Well it's definitely useful, so don't disable it or anything, or at the least leave it enabled in the CLI variants please :)

**Comment by tianon** [comment]
Apparently we were excited to have it implicitly (looking through old issue comments), so I've codified the explicit stance (and included `readline`) in #1259. :+1:
