### ISSUE TITLE
Composer reports incorrect PHP version in php:7.4.*-fpm-alpine3.15

### ISSUE THREAD

**Issue by josefsabl** [docker-library/php#1263]
Now this is very strange. Although php -v reports correct php version (7.4.28) when trying to use composer to install dependencies it tells me I have PHP 8.0.16.

Steps to reproduce:

1. Run the container

```
docker run -it php:7.4.28-fpm-alpine3.15 /bin/sh
```

2. Run this script

```
apk add composer
echo '{
  "name": "test/test",
  "version": "0.0",
  "authors": [],
  "require": {
    "php": "^7.4.0"
  }
}' > composer.json
composer install
```

3. Result:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.4.0 but your php version (8.0.16) does not satisfy that requirement.
```

The problem seems to be with the latest version of alpine and not the php version. I tried for two last versions of both:

```
php:7.4.28-fpm-alpine3.15 bug
php:7.4.27-fpm-alpine3.15 bug
php:7.4.28-fpm-alpine3.14 ok
php:7.4.27-fpm-alpine3.14 ok
```

**Comment by GreyXor** [comment]
Hello,
when you `apk add composer`, apk add `php8` dependency (https://pkgs.alpinelinux.org/package/edge/community/x86_64/composer)
Then when you run `composer` it uses in fact the php that you have just installed via the command apk add (the php8 dependency of `composer`. and not the one that is installed in the image.

I want to say that the best practice is to use composer via a multilayer dockerfile. The [composer image](https://hub.docker.com/_/composer) is perfect for that.

however if you still want to use the PHP version of the docker image. then you can simply add the path to the binary before calling composer
``

**Comment by josefsabl** [comment]
Well, I am speechless. This makes the composer package in the alpine completely useless as it breaks its usage. They better remove it completely to at least prevent confusion of users. We are thinking about walking away from alpine. This lunacy is one more reason to speed up the decision.

I am installing the composer like this now (in case somebody stumbles upon this):

```
COPY --from=composer:2.2.7 /usr/bin/composer /usr/bin/composer
```

Thank you for your explanation.

**Comment by tianon** [comment]
Indeed -- see https://github.com/docker-library/php/pull/542; when you `apk add composer` (or any other PHP package) in the `php` base image, you're installing a second version of PHP (as explained).

I'm not sure whether Alpine has similar pinning behavior such that we could block installation of Alpine's PHP packages in the image as we did for Debian in https://github.com/docker-library/php/pull/542, but I'd be +1 on doing so if such a feature exists.

**Comment by GreyXor** [comment]
You can also install composer in that way
`RUN sh -c "$(curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions)" -c @composer`
