### ISSUE TITLE
`strip --strip-all` must be conditional when php was (re)compiled with `--enable-debug`

### ISSUE THREAD

**Issue by mvorisek** [docker-library/php#1268]
This is a feature request.

https://github.com/docker-library/php/blob/b3e617367771db15eeafabc6a52209c0b24ea823/8.1/bullseye/cli/docker-php-ext-install#L108-L113 should be wrapped in a condition to check if php was configured /wo debug mode

for debug mode, no symbols should be stripped

as a temporary solution `sed -zE 's~[^\n]+find modules[^\n]+\n[^\n]+-maxdepth[^\n]+\n[^\n]+-name[^\n]+\n[^\n]+-exec[^\n]+\n[^\n]+strip --strip-all[^\n]+\n[^\n]+\{\}[^\n]+\n~~'` can be used, but native support/condition is highly appreciated

**Comment by tianon** [comment]
I think I'm a little confused -- all our PHP builds are without debug symbols / stripped?

https://github.com/docker-library/php/blob/399ed12afc9d939f5da704d667a57e5678a699b1/Dockerfile-linux.template#L399-L406

(This block of code in the template doesn't have any `if` around it -- it is included in all variants.)

**Comment by mvorisek** [comment]
That is correct - debug build is never enabled, but if php is recompiled manually with debug enabled, the `docker-php-ext-install` script should honor that and do NOT strip any symbols

**Comment by tianon** [comment]
Hmm, is there a clean way we can reliably detect that?  That's not really a configuration we officially support, so I hesitate to make our already somewhat complex script even more complex unless the implementation is really clean/straightforward. :sweat_smile:

Is there maybe a way we can query it from PHP itself?  I don't really like the idea of just "guessing" based on whether something like `/usr/local/bin/php` still has any debugging symbols. :see_no_evil:

**Comment by mvorisek** [comment]
> Hmm, is there a clean way we can reliably detect that? Is there maybe a way we can query it from PHP itself?

Yes, there is php constant for it, together with `-n` option for `php` binary to skip any ini configuration, we can query it reliably with the following command:

```
php -n -r 'echo ZEND_DEBUG_BUILD;'
```

**Comment by tianon** [comment]
Oh, nice!  I'll get around to it eventually if you don't, but if you have a debug build already handy, can you share the output of that on it? :innocent:

**Comment by mvorisek** [comment]
https://github.com/mvorisek/image-php/runs/5680159626?check_suite_focus=true#step:5:65

for php compiled with `--enable-debug`, the value is `1`

**Comment by tianon** [comment]
Very nice, thank you!  PR filed at https://github.com/docker-library/php/pull/1278 :+1:

**Comment by mvorisek** [comment]
Thank you as well! PR tested, it works fabulously 👌
