### ISSUE TITLE
Is it possible to update FD_SETSIZE without recompiling PHP?

### ISSUE THREAD

**Issue by bkuhl** [docker-library/php#1275]
I'm trying to use `phpdbg` to generate code coverage in a decently sized project.  One error I'm running into is this:

```
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 7228.
 --enable-fd-setsize=8192 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
```

The output of `ulimit -n` within my container is over 1 million, so I'm inclined to believe PHP is just not picking up on this value.  **Is there any way to set this value within a Dockerfile or at runtime, without having to recompile php from scratch?**

**Comment by yosifkit** [comment]
As far as I can tell, this comes from `/usr/include/x86_64-linux-gnu/bits/typesizes.h` (which is part of the `libc6-dev` package).
```console
$ docker run -it --rm debian:bullseye
root@bf3e9cfbb012:/# apt update
root@bf3e9cfbb012:/# apt install libc6-dev
root@bf3e9cfbb012:/# grep FD_SETSIZE /usr/include/x86_64-linux-gnu/bits/typesizes.h 
#define __FD_SETSIZE		1024
```

So, I don't think there is a way to change it without recompiling. I think `--enable-fd-setsize=####` added to the configure arguments would work, but I don't think it is something we can generally add without a recommendation from PHP upstream.

Out of curiosity, do you get the same problem using Debian's packages? (`php-phpdbg` installed from a `debian:bullseye` image)

**Comment by bkuhl** [comment]
🤔  I was afraid recompiling might become an issue here.  I really don't want to go down that path.

> Out of curiosity, do you get the same problem using Debian's packages? (php-phpdbg installed from a debian:bullseye image)

My application is still running PHP 7.0 (I know, we're working on upgrading) so we're stuck with stretch linux at the moment and I don't think I can test on bullseye (php 7.0 looks [only to be available for stretch](https://packages.debian.org/search?keywords=php7.0-fpm)).
