### ISSUE TITLE
RISC-V image is important

### ISSUE THREAD

**Issue by xlmnxp** [docker-library/php#1279]
when I search for a lot of docker images I found it not support `risc-v` for example `wordpress` (I successfully install it manually in ubuntu image) then I go to contribute to support risc-v for official `wordpress` image then I found they based on this image and it not support `risc-v` yet

**Comment by tianon** [comment]
Conceptually, I agree, but with the PHP image based on Debian, we'll unfortunately need to wait for RISC-V to become a fully supported architecture there (which IMO is prudent anyhow -- the things they require for that such as access to decent hardware for running on, a stable ISA standard, etc are all good things that users of this image would want as well :see_no_evil:). :heart:

**Comment by xlmnxp** [comment]
@tianon RISC-V is officially supported by debian and ubuntu and ISA is stable and frozen 
and you can use any cheap SBC support RISC-V like `VisionFive` or `Nezha`

**Comment by tianon** [comment]
It's not supported by Debian yet: https://wiki.debian.org/Ports/riscv64, https://wiki.debian.org/ArchiveQualification/riscv64

It's a "ports" architecture -- there's work being done to get enough hardware to make it a real official port and be supported beyond Debian Unstable/Experimental, but it's not there yet.

(I have an Unmatched that's used by https://github.com/docker-library/official-images and builds the `riscv64` builds of https://hub.docker.com/_/debian -- I'm pretty familiar here :sweat_smile:)

See also the links on https://github.com/docker-library/official-images/pull/10502 for ways to get involved in Debian to push that forward.

(I believe Alpine is in a similar place -- `riscv64` is supported in Alpine Edge, but not a release yet: https://gitlab.alpinelinux.org/alpine/aports/-/issues/13269)

**Comment by danog** [comment]
Until both debian and alpine get stable support for riscv64, I've created riscv64 images of php here: https://hub.docker.com/r/danog/php
