### ISSUE TITLE
Php dockerfile for ppc64le platform

### ISSUE THREAD

**Issue by dhoblem** [docker-library/php#128]
I have installed and tested PHP(5.6.8) on ppc64le architecture.
 
I have also created a Dockerfile for this for ubuntutu 14.10 &15.04 as well and wish to contribute it to the community.
Please let me know how to go about it.

**Comment by yosifkit** [comment]
It would be awesome to have multiple architectures for the official images. Unfortunately docker, the Docker Hub, and the Official Images program only officially support amd64 images, but hopefully this will change in the future.

**Comment by tianon** [comment]
As in https://github.com/docker-library/wordpress/issues/81#issuecomment-241161933, see https://hub.docker.com/r/ppc64le/php/ :+1:
