### ISSUE TITLE
Not able to configure DAV directory

### ISSUE THREAD

**Issue by carlosjfcasero** [docker-library/php#1288]
Hi. I'm not able to configure a DAV directory.
This is the part of my `.conf` file where I configure it:

```
DavLockDB /var/www/html/DavLock
<VirtualHost *:443>
	...
	<Directory /var/www/html>
		AllowOverride All
	</Directory>

	Alias /webdav /var/www/html/webdav

        <Directory /var/www/html/webdav>
            DAV On
        </Directory>

</VirtualHost>
```

I can put my server up and running but the file `/var/www/html/DavLock` is no created and I can access my DAV folder from multiple clients at the same time.

Could somebody please give me a hand?
Thanks!

**Comment by wglambert** [comment]
Hmm, not sure what is missing for it to create that directory

What do you get in your `docker logs`? 
Using your config file I run into the same thing, I'm guessing it's just a configuration issue with something
```console
$ docker run -d -p 8080:80 --name php -v "$PWD"/httpd.conf:/etc/apache2/sites-available/000-default.conf php:apache sh -c 'a2enmod dav dav_fs && exec docker-php-entrypoint apache2-foreground'
8ec73325bb1107eea1e0fda0cb0adcd4188e2c5e20308073c281c418ec93d3ce

$ docker logs php
Enabling module dav.
Considering dependency dav for dav_fs:
Module dav already enabled
Enabling module dav_fs.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 05 22:33:13.606453 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.1.4 configured -- resuming normal operations
[Tue Apr 05 22:33:13.606534 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

$ docker exec php ls -al /var/www/html
total 8
drwxrwxrwx 1 www-data www-data 4096 Mar 29 01:20 .
drwxr-xr-x 1 root     root     4096 Mar 29 01:16 ..
```

**Comment by carlosjfcasero** [comment]
My logs look exactly like yours. After seeing this message in logs (`To activate the new configuration, you need to run: service apache2 restart`), I restarted apache inside container (`apache2 -k graceful`). However, I got the same result, no /var/www/html/DavLock is created

**Comment by carlosjfcasero** [comment]
Ok, after trial and error, and examining logs, I figured out dav db was actually being created, but not in my /html directory. So adding this line `DavLockDB /var/www/html/DavLock` in `.conf` file and correct permissions to my html folder outside docker `chown -R www-data:www-data html`was enough to make it work.
Thanks for your help!
