### ISSUE TITLE
Our pipeline crashed because an existing tag got a new OS...

### ISSUE THREAD

**Issue by renepardon** [docker-library/php#1293]
We use the **php:7.4-apache** tag to build our image for one application. So far so good, but the underlying debian changed from buster to bullseye. Why this happened? Why an OS change in an existing tag? This broke our pipeline and I had to be even more specific in choosing **php:7.4-apache-buster** now which makes it work again. 

Was this done by intention or by mistake?

**Comment by wglambert** [comment]
The image's OS can change according to Debian's release schedule https://wiki.debian.org/DebianReleases#Production_Releases

`php:7.4-apache` is a broad tag that essentially matches the latest of `7.4-apache`. You can get more specific such as `php:7.4-apache-buster` or even `php:7.4.29-apache-buster`

These are the tags it currently matches
![image](https://user-images.githubusercontent.com/26428991/165131473-2ac4e7f1-22e8-426f-a25a-02ba3abae302.png)

You can also get the md5 digest which is immutable and will always pull that exact image https://github.com/docker-library/repo-info/blob/master/repos/php/remote/7.4.29-apache-buster.md

**Comment by renepardon** [comment]
Ok, thank you for clarification! :)
