### ISSUE TITLE
Is that ok if I change the template file to generate a fpm with zts version dockerfile?

### ISSUE THREAD

**Issue by RandalTeng** [docker-library/php#1317]
I'd like submit a pr of that,
I want install parallel extension in docker contianer, and find out that the php version of fpm is nts
Also for pthread extension
I can't find any discuss of zts in issues.
If there is no, I will close this issue.

**Comment by tianon** [comment]
I think this is a duplicate of #249 which has some useful discussion/links.

**Comment by RandalTeng** [comment]
Actually I had read this issue, my boss let me use go rpc call or pcntl_fork instead of it.
I'll close it. the issue is ture, it really not make scence.

> I think this is a duplicate of #249 which has some useful discussion/links.
