### ISSUE TITLE
SSLCertificateKeyFile: file does not exist or is empty

### ISSUE THREAD

**Issue by adriangabura** [docker-library/php#1318]
Hello,
I have an issue that is unremitting. If you could have please a look.
Using php:7.4.30-apache-buster

```
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost
		DocumentRoot ${LaravelProject}/public

		<Directory />
			Options FollowSymLinks
			AllowOverride All
			Require all granted
		</Directory>

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		SSLEngine on

		SSLCertificateFile /etc/ssl/certs/cert.crt
		SSLCertificateKeyFile /etc/ssl/private/cert.key

		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

	</VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

```

I pasted the damnable files and checked, they exist. This is Debian there's no SELinux stuff SO talks about. Yet it doesn't work for some reason. It works on Fedora using exactly same code.

Is this something Docker related or smth I am missing?
Thanks

**Comment by wglambert** [comment]
It could be permissions related, anything in the `docker logs`?

**Comment by adriangabura** [comment]
Ehh, nothing really... The private key is 600, I made sure of that. Is SELinux used in this dockerized debian version?

**Comment by tianon** [comment]
Unfortunately, this sounds like it's "just" a quirk of how Apache works and there's not really much we can do about it. :sweat_smile:

(I definitely do my own TLS termination via something like NGINX, but it's never the most _straightforward_ thing no matter how it's done except maybe Traefik where it can happen 100% automatically :see_no_evil:)
