### ISSUE TITLE
Remove some unused packages

### ISSUE THREAD

**Issue by hydrargyrum** [docker-library/php#1324]
(This is a follow-up of https://github.com/monicahq/docker/issues/109)

I see in a [Dockerfile](https://github.com/docker-library/php/blob/master/8.1/bullseye/fpm/Dockerfile) some effort is made to remove unused packages. But inspecting the resulting image, some packages seem questionable for a production image, for example autoconf, make, curl (command-line tool), dpkg-dev, gcc.
Those would be acceptable for an [build-stage image](https://docs.docker.com/develop/develop-images/multistage-build/) where only required stuff would be installed/copied in the production-stage image. Furthermore, cleaning unused packages from a build-stage image would be pointless, so the apt-mark part would not even be needed.

```
% docker run --rm --entrypoint /bin/sh -it php:8.1-fpm -c "apt-mark showmanual"
autoconf
ca-certificates
curl
dpkg-dev
file
g++
gcc
libargon2-1
libbrotli1
libc6
libc6-dev
libcom-err2
libcurl4
libffi7
libgcc-s1
libgcrypt20
libgmp10
libgnutls30
libgpg-error0
libgssapi-krb5-2
libhogweed6
libicu67
libidn2-0
libk5crypto3
libkeyutils1
libkrb5-3
libkrb5support0
libldap-2.4-2
liblzma5
libnettle8
libnghttp2-14
libonig5
libp11-kit0
libpsl5
libreadline8
librtmp1
libsasl2-2
libsodium23
libsqlite3-0
libssh2-1
libssl1.1
libstdc++6
libtasn1-6
libtinfo6
libunistring2
libxml2
make
pkg-config
re2c
xz-utils
zlib1g
```

**Comment by yosifkit** [comment]
Those are all left on purpose so that extra extensions can be easily installed via `docker-php-ext-install`.

https://github.com/docker-library/php/blob/6598612e4d37cf1e3775581a6a8b08f1fd378d17/8.1/bullseye/fpm/Dockerfile#L20-L39

**Comment by tianon** [comment]
See also https://github.com/docker-library/php/pull/438, especially https://github.com/docker-library/php/pull/438#issuecomment-353695749.

**Comment by hydrargyrum** [comment]
If I understood it correctly, the pointed comment is about debian's apt-get purge not being good enough. I don't disagree with that. But if we want to avoid needless packages (@yosifkit implied they were actually needed for derived images), we could take the multi-stage approach:
- build/install whatever in a first image
- install only what's needed for production in a second image
- copy what was built in image 1 to image 2
- only publish image 2
- all of the above using a single Dockerfile!

**Comment by tianon** [comment]
The difficulty is not in what _we_ build/include in the images (we can mange that), but rather that there are explicitly parts of PHP itself that we do _not_ build in the images, but _do_ support `docker-ext-*` for assisting users in installing in simple ways.
