### ISSUE TITLE
sendmail works incorrectly in PHP8 alpine builds

### ISSUE THREAD

**Issue by speller** [docker-library/php#1327]
I'm using latest PHP 8.1 alpine image with the following sendmail version:

```
/magento # sendmail --help
BusyBox v1.34.1 (2022-07-19 20:11:24 UTC) multi-call binary.
```
The mail function sends headers and body with \r\n line delimiters according to standards and passes this data to sendmail. But sendmail converts all line-endings to \r\r\n making the whole mail broken.

A related issue in the PHP repo: https://github.com/php/php-src/issues/8086 (closed as PHP does everything correctly).

**Comment by wglambert** [comment]
I'm guessing it's busybox-specific, have you tried the non-alpine version?

**Comment by speller** [comment]
@wglambert @tianon I suppose you as the maintainers should be aware of the issue because one of the basic PHP features is non-functional in Alpine images. This is not a bug of PHP, this may be a bug of Busybox, but why users of the image should apply workarounds and not maintainers? Of course, I will do something because I need it, but I think the way when core PHP functionality doesn't work because maintainers don't care is not the best way.

**Comment by speller** [comment]
@wglambert 
> have you tried the non-alpine version?

How can I do that?

**Comment by speller** [comment]
@tianon 
> includes a few alternative options you should probably consider installing in your image
I just tried ssmtp but the result is the same.
