### ISSUE TITLE
Apache + CGI variant?

### ISSUE THREAD

**Issue by C-Duv** [docker-library/php#1329]
I want my container to run Apache and process PHP scripts using FastCGI / `mod_fcgid` (not `mod_php`).

I can start from a `debian` Docker image and *apt-install* all the thing (`apache2`, `libapache2-mod-fcgid`, `php-cgi`) but the `php:<version>-apache` variant has all the integrated tooling to run Apache in a Docker container so it would be a shame not to use it :)

Basically I need `php:<version>-apache` image with the cgi-fcgi binary (`php-cgi` Debian package).

So I tried staring from `php:<version>-apache` with `a2enmod fcgid && a2dismod php7` but I can't get the `php-cgi` binary (only tried using the `php-cgi` Debian package).

Removing the `/etc/apt/preferences.d/no-debian-php` file [as documented](https://github.com/docker-library/docs/blob/master/php/README.md#e-package-php-xxx-has-no-installation-candidate) allows the install of `php-cgi` package but also brings the other `php-*` Debian packages, even the one already installed with `install-php-extensions` which I am pretty sure is not recommended…

Is there a solution in the `php:<version>-apache` Docker image or should I go for:

* `php:<version>-cli` variant, *apt-install* Apache and get a copy of the `/usr/local/bin/docker-php-entrypoint`?
* or even from `httpd` Docker image and `apt-get install` the PHP stuff?

**Comment by wglambert** [comment]
Installing php packages from repos won't work as the one in the image is compiled so the package won't recognize any existing php https://github.com/docker-library/php/issues/976

Similar threads about cgi 
https://github.com/docker-library/php/issues/280
https://github.com/docker-library/php/issues/668#issuecomment-403640949
>We definitely don't enable running of CGI scripts in Apache (and indeed don't see a reason to -- if folks want PHP, they should use mod_php as configured in the -apache variants or PHP-FPM via the FastCGI protocol)

**Comment by C-Duv** [comment]
I know installation of Debian package is explicitent disabled and I understand why.

My use case is to replicate an existing non-Docker setup that runs Apache AND FastCGI. By the tone of the quote (which is quite definitive) it looks like it's not an acceptable scenario/setup by the PHP Docker team.

At least, not as a single Docker container… because one other solution is to use 2 containers:

* an `httpd` based with FastCGI module
* and a `php:<version>-cli` which has `php-cgi`

and share a Docker volume/bind between the two.

**Comment by tianon** [comment]
Yes, our opinion is that if you have two processes that need to be managed, you're going to have the best time managing those (especially in cases of a process failing/dying) if you run them as separate containers so that the process manager (Docker, in this case) can appropriately manage/monitor both.

(If you want FastCGI, you probably want the `fpm` variants though, not the `cli` variants.)
