### ISSUE TITLE
How to override PHP_URL to create from a custom src

### ISSUE THREAD

**Issue by alexander-schranz** [docker-library/php#1332]
I see that there are 3 ENV configured "PHP_URL", "PHP_ASC_URL" and "PHP_SHA256".

So I thought I can create an image and override the ENVs this way:

```Dockerfile
FROM php:8.2.0RC4-zts-bullseye AS php-base

ENV PHP_URL="https://github.com/dunglas/php-src/archive/refs/heads/frankenphp-8.2.tar.gz"
ENV PHP_ASC_URL=""
ENV PHP_SHA256=""
```

But `ENV` are only available in the runtime and the Build does not use the `ENV` I'm defining. So what is the purpose of this `ENV`s if I can not overwrite the in the build process? Should maybe this kind of ENVs be converted to `ARG`. As I think ARG are possible to overwrite the build process?

**Comment by yosifkit** [comment]
I guess the `ENV` values are there for users that want to re-verify the downloaded `php.tar.xz`. I think they were an artifact of previous templates, and so could maybe removed from the images.

If you want to override the build, then you'll need to copy the full Dockerfile and its context (the scripts in the same directory) and add your changes. A `FROM` in a Dockerfile can't change previous image layers.

**Comment by alexander-schranz** [comment]
@yosifkit thx for the clarification. sad docker does not support this kind of things. I must say I'm the not understanding the diff between ARG and ENV 🤔
