### ISSUE TITLE
Apache2 are not using ENVVARS

### ISSUE THREAD

**Issue by nskartem** [docker-library/php#1334]
Hello!

I have a customized Docker image, based on php:7.4.27-apache2-buster image.
I've added apache2-mpm-itk module to limit apache2 users by directories.
There is no separate site user in container, apache2 is operating with numeric UIDs instead of usernames (so main apache2 process is owned by root, and newly created apache2 child process is owned by site user).
Problem is that when I've tried to set default umask variable in /etc/apache2/envvars to 0002 to grant apache2 child processes in that container access to another directory with 770 permissions (mounted as volume to that container), it is not working. I've added layer, that edits /etc/apache2/envvars to Dockerfile:
`RUN echo "umask 0002" >> /etc/apache2/envvars`
 it was correctly added, I see it in a container:
`root@site-name-backend:/var/www# tail -n 1 /etc/apache2/envvars
umask 0002`
But it's not applying.
As I see, apache2 in a container not using ENVVARS, or maybe I'm doing something wrong.

**Comment by edgreenberg-mri** [comment]
There's a bunch of discussion about envvars (not specifically docker image) at https://askubuntu.com/questions/146688/why-doesnt-apache2-respect-my-envvars-file    Might help.  Good luck.

**Comment by tianon** [comment]
If you're using our `apache2-foreground` wrapper, you can see that it _does_ source the `envvars` file here:

https://github.com/docker-library/php/blob/0680c8567819e2a53a8064d2a881a576ff9b9edf/apache2-foreground#L7-L11

**Comment by nskartem** [comment]
Many thanks for your help!
Sorry for inconvenience, I've found, that envvars and umask in the container are working properly, problem was in misconfiguration of the CMS.
