### ISSUE TITLE
Provide support for historic point releases.

### ISSUE THREAD

**Issue by ryanaslett** [docker-library/php#134]
We would like to use the official docker images for php to feed into our CI system, but since our application (drupal) sets it's minimum required version based upon whats typically installed in hosting environments, our tests have to work with our minimum required version (5.5.9 in this case).

Is there any possibility that we could have support for whatever minor version we'd like to use? Or would there be too much container bloat on dockerhub to allow for that?

**Comment by yosifkit** [comment]
There is already quite a back fill: https://hub.docker.com/r/library/php/tags/.  It only shows the first 100 tags available, so you have to manually look through the [json "pages"](https://hub.docker.com/v2/repositories/library/php/tags/?page_size=100&page=2) to see more.  None of the previously built images are deleted, but it doesn't look like we ever built one that old.  It might be possible to do a one-off build; what so you think @tianon?

**Comment by tianon** [comment]
I think tools like phpenv (https://github.com/phpenv/phpenv) are probably better suited to the task of creating older PHP images than the official images process is, unfortunately. :disappointed:

**Comment by ryanaslett** [comment]
Heh. Thats what we're using now, but sometimes our CI system runs into issues using phpenv (primarily due to the fact that phpenv runs php as a bash shell), and as such the signal handling can sometimes get awry from what we expect in error situations. We've been using hand built php containers for drupalCI for a while, but it would be nice to have something 'official' to base our containers off of. 

In any case, thanks for looking at this. We totally understand if this isn't something y'all want to step backwards into and create - its definitely an edge case.

**Comment by tianon** [comment]
This is definitely an edge case that we don't feel comfortable supporting (especially considering that upstream doesn't really support these older versions anymore), but I think this issue might serve as a source of information for folks looking to create such a thing for themselves. :+1:
