### ISSUE TITLE
Suggestion: Provide an initial HTML or PHP page

### ISSUE THREAD

**Issue by edgreenberg** [docker-library/php#1346]
When a container FROM php:8.0-apache is created and hit on port 80 (out of the box) the first result is a 403, probably because there is no default document and DirectoryIndex is prohibited.  It would be nice for the developer if there was some sort of default index.html or index.php in /var/www/html so that the out-of-box-experience is a better one, and the developer doesn't have to figure out whether the image is broken or not. 

I haven't tried any of the other variants other than the one mentioned above.  

I note that building the default nginx image (another provider, I'm sure) comes with a "Welcome to nginx!" page. 

Again, just a suggestion, and thanks to the team for all the hard work putting out the image and all it's variants.

**Comment by tianon** [comment]
In the case of NGINX, the provided page is a standard part of a default NGINX install, whereas PHP doesn't have any such thing (that I'm aware of), so I'd be very hesitant to create one. :sweat_smile:
