### ISSUE TITLE
 For php:5.5-apache I get error when I run apt-get update

### ISSUE THREAD

**Issue by tkumark** [docker-library/php#1347]
In the docker container **php:5.5-apache** when I run **apt-get update** I get the following error
`W: GPG error: http://security.debian.org/ jessie/updates InRelease: The following signatures were invalid: KEYEXPIRED 1668892417 The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AA8E81B4331F7F50`

How do I fix this issue?

**Comment by wglambert** [comment]
php 5.5 was deprecated in 2016 https://github.com/docker-library/php/pull/289

https://unix.stackexchange.com/a/508728
>if you want to continue fetching Jessie backports, you need to use archive.debian.org instead

Here's the Dockerfile of it https://github.com/docker-library/php/blob/882b9c25f14e782e45a978a68d48843b7ac54042/5.5/apache/Dockerfile
