### ISSUE TITLE
Alpine 3.17 php-fpm can't install php8-pecl-imagick

### ISSUE THREAD

**Issue by Loic-Hakisa** [docker-library/php#1352]
Using docker image : php:8.1-fpm-alpine 
I can't build anymore, it doesn't found php8-pecl-imagick package.

Using "php:8.1.13-fpm-alpine3.16" it's working fine.

**Comment by jnoordsij** [comment]
The variant you mention is the PHP 8.0 variant and was dropped from the latest Alpine version. It has been replaced by the  `php81-pecl-imagick` package.

*Important note*: installing PHP extensions with apk is something you probably do want to avoid, as it has all sorts of possibly nasty consequences, apart from bloating the resulting image. You probably want to read the docs about [installing extensions](https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions) in the image, or in this case the part about [PECL extensions](https://github.com/docker-library/docs/tree/master/php#pecl-extensions).

**Comment by Loic-Hakisa** [comment]
Thank you, I will check this in details !
