### ISSUE TITLE
Get PHP images updated out of schedule

### ISSUE THREAD

**Issue by carusogabriel** [docker-library/php#1370]
Hello there!

Today we release a few PHP updates containing Security fixes that we are strongly advising users to upgrade to.

Is there a way to trigger your scripts, so we can get the images up to date?

Thanks!

**Comment by yosifkit** [comment]
Job triggered; should have updates here in the Dockerfiles after a successful build test.

**Comment by WyriHaximus** [comment]
Great, thank you @yosifkit :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/14090 :+1:
