### ISSUE TITLE
Add phpdbg to zts images

### ISSUE THREAD

**Issue by dercoder** [docker-library/php#1377]
Regarding to the issue https://github.com/docker-library/php/issues/1260 I would suggest to add the phpdbg again to ZTS images.
It would be better to add it for all images again but ZTS is at least no FPM image 

The workarround 
```
COPY --from=php-cli /usr/local/bin/phpdbg /usr/local/bin/
```
will also not help in this case

**Comment by tianon** [comment]
Sorry for the delay!  This is an interesting point -- the ZTS images are spiritually the same as the CLI images, but with ZTS enabled, so I think it probably does make sense to re-enable `phpdbg` there.
