### ISSUE TITLE
Switch to secure downloads

### ISSUE THREAD

**Issue by ericandrewlewis** [docker-library/php#138]
I noticed [some curls issuing insecure HTTP requests](https://github.com/docker-library/php/blob/master/5.6/Dockerfile#L37-L38). We should audit these, see whether secure HTTPS versions of the assets exist, and switch them.

**Comment by sherter** [comment]
Downloads are verified with GPG (see [next line](https://github.com/docker-library/php/blob/master/5.6/Dockerfile#L39)). I don't think using HTTPS on top improves security in any way, does it?

**Comment by tianon** [comment]
Yeah, since we're verifying both PGP signatures _and_ SHA256 (which is embedded directly in the `Dockerfile` itself), I think this is kind of overkill unless it's readily available and upstream recommends it.

**Comment by tianon** [comment]
It's readily available, and certainly not _discouraged_ by upstream, so I've filed https://github.com/docker-library/php/pull/293. :+1:
