### ISSUE TITLE
curl and libcurl versions do not match on alpine images

### ISSUE THREAD

**Issue by j3j5** [docker-library/php#1399]
PHP images using alpine (3.16 and 3.17) have a version mismatch on their curl and libcurl version. curl is on version 7.88 while libcurl is on 8.0. This occurs both on 8.1 and 8.2 versions. [Looking](https://hub.docker.com/layers/library/php/8.1-alpine3.16/images/sha256-a7608ce2f3d7afbde217898e3c6cf0e69fd9e739378dacbed262f8cc3d0d40f2?context=explore) [at](https://hub.docker.com/layers/library/php/8.1-alpine3.17/images/sha256-1fe6adc8c9c35dfd6f7cd3e1a838201df2f3d2aecc94841e9a064931420c3d47?context=explore) [Docker](https://hub.docker.com/layers/library/php/8.2-alpine3.16/images/sha256-8a68231a27ed75b0f476e046d7e25dff6e1bbb19292c1f555c36ef96c0331ff2?context=explore
) [Hub](https://hub.docker.com/layers/library/php/8.2-alpine3.17/images/sha256-5026c54310b19d10f3fc3fc4d24e21e928cc1b2847e9202f52e73a97d2c8aebd?context=explore) apparently curl 8.0 is also installed but running a terminal into the image the version installed is 7.8.
![Screenshot_20230419_140225](https://user-images.githubusercontent.com/1239921/233148050-c8b89f00-e56f-48a6-ac7a-49dd1939fb43.jpg)

**Comment by tianon** [comment]
Is there a specific problem this is causing?  The underlying issue here is that Alpine has done a major version bump of curl in their stable release, but has not done a rebuild of the base image, so the layer which installs the `curl` package is cached but the layer which installs `libcurl`'s dev package for linking against in PHP has been updated. :disappointed:

**Comment by MirakuSan** [comment]
I think there is a specific problem, I've just opened an issue : https://github.com/docker-library/php/issues/1401 because the images have almost all a vulnerability with version of curl < 8.0.0

**Comment by valthebald** [comment]
Here's specific problem: on Debian, curl does not resolve any host, i.e. inside the container 
```
docker exec -it 99f1313c6eb1 /bin/sh
# curl https://www.google.com/
curl: (6) getaddrinfo() thread failed to start
```

**Comment by tianon** [comment]
All supported images have since been rebuilt. :+1:
