### ISSUE TITLE
How to change the UID of the Apache process?

### ISSUE THREAD

**Issue by jpetazzo** [docker-library/php#14]
On `php:apache`, we are trying to change the UID of the Apache process, so that it can access files owned by another uid than `33/www-data` (because we're sharing some files with another container).

I tried:
- setting `ENV APACHE_RUN_USER 1000`
- editing `/etc/apache2/envvars`
- running Apache with `-D APACHE_RUN_USER=1000`

Noworkie :(

@tianon told me:

```irc
15:57 <tianon> you want -u SOME-UID and probably have to sed the conf file
15:57 <tianon> can you file an issue?
15:57 <tianon> and say I sent you?
```

**Comment by md5** [comment]
I was just looking at this issue in the context of https://github.com/docker-library/wordpress/issues/52

It turns out that Apache will interpolate environment variables in the form `${ENVVAR}`, so I changed the `apache2.conf` file used for the `php:apache` image to get its user and group from `APACHE_RUN_USER` and `APACHE_RUN_GROUP` respectively. After doing this, I was able to set the user that Apache runs as with `-e APACHE_RUN_USER=myuser`.

One caveat is that the `User` directive in Apache's config file only accepts usernames, not uids, so in some cases you may need to create a dummy user with the same uid as your mounted volume. The other caveat is that the `Dockerfile` is currently chowning `/var/lock/apache2` and `/var/run/apache2` to `www-data:www-data`. These would also need to be owned by the same dummy user instead of by `www-data`.

```diff
diff --git a/5.6/apache/Dockerfile b/5.6/apache/Dockerfile
index f584653..abad2c3 100644
--- a/5.6/apache/Dockerfile
+++ b/5.6/apache/Dockerfile
@@ -70,6 +70,8 @@ COPY docker-php-ext-* /usr/local/bin/
 COPY apache2-foreground /usr/local/bin/
 WORKDIR /var/www/html
 
+ENV APACHE_RUN_USER www-data
+ENV APACHE_RUN_GROUP www-data
 EXPOSE 80
 CMD ["apache2-foreground"]
 ##</autogenerated>##
diff --git a/5.6/apache/apache2.conf b/5.6/apache/apache2.conf
index 0a22836..0fb411e 100644
--- a/5.6/apache/apache2.conf
+++ b/5.6/apache/apache2.conf
@@ -6,8 +6,8 @@ Timeout 300
 KeepAlive On
 MaxKeepAliveRequests 100
 KeepAliveTimeout 5
-User www-data
-Group www-data
+User ${APACHE_RUN_USER}
+Group ${APACHE_RUN_GROUP}
 HostnameLookups Off
 ErrorLog /proc/self/fd/2
 LogLevel warn
```

**Comment by yosifkit** [comment]
@md5, that seems to be a valid solution.  What are the problems involved?

**Comment by tianon** [comment]
I really wish we could just get a fix to https://github.com/docker/docker/issues/8460, since that'd fix this in the ideal way. :cry:

**Comment by md5** [comment]
@yosifkit I think it would just be a matter of documentation.

For example, I think a `Dockerfile` like this could work for the boot2docker case of uid `1000`:

```Dockerfile
FROM php:5.6-apache
RUN adduser --uid 1000 --gecos 'My Apache User' --disabled-password myuser \
             && chown -R myuser: /var/lock/apache2 /var/run/apache2
ENV APACHE_RUN_USER myuser
```

This is assuming [the changes](https://github.com/docker-library/php/issues/14#issuecomment-72997403) I posted above, plus probably a change in the entrypoint to use `$APACHE_RUN_USER` in the `chown`.

**Comment by md5** [comment]
Actually, I'm thinking of the `wordpress` repo with the `chown`. There is no `entrypoint` here.

**Comment by AdilHoumadi** [comment]
Any news about this issue ?

**Comment by ip2k** [comment]
Just came across this looking for an unrelated issue, but could you use this, assuming the UID and GID are 1000?

```
User #1000
Group #1000
```

Ref: http://httpd.apache.org/docs/current/mod/mod_unixd.html#user
and http://httpd.apache.org/docs/current/mod/mod_unixd.html#group

**Comment by md5** [comment]
@ip2k I looks like I was simply unaware of the `#NNN` notation for numeric ids.

**Comment by Vampouille** [comment]
What about using `usermod` to change numeric uid of `www-data` user :
```bash
usermod --non-unique --uid 999 www-data
```
This way we don't need to change apache configuration (no need to sed apache2.conf file).
We just need to :

* run `usermod` before starting apache process (with something like run-parts docker-entrypoint.d/ see http://www.camptocamp.com/en/actualite/flexible-docker-entrypoints-scripts/)
* change owner of some directory: `/var/lock/apache2`

**Comment by Vampouille** [comment]
Proposal with usermod : https://github.com/docker-library/php/pull/286
