### ISSUE TITLE
Can't send PHP errors to container log using PHP-FPM image

### ISSUE THREAD

**Issue by ericandrewlewis** [docker-library/php#140]
I've created [a small repo that uses nginx and PHP-FPM](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log) to explain this issue.

I create a PHP-FPM image from Docker hub that specifies a custom [php.ini](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/Dockerfile#L2) which [sends errors to `/proc/self/fd/2`](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/config/php.ini#L2), which is where I've noticed the [PHP-FPM image sends logs](https://github.com/docker-library/php/blob/master/5.6/fpm/php-fpm.conf#L6). Then I call an [undefined function in `index.php`](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/src/index.php#L2), and still only see access logs from both nginx and php-fpm in the container log.

![screen shot 2015-10-01 at 2 31 19 pm](https://cloud.githubusercontent.com/assets/1087646/10230042/25e6683e-6849-11e5-8df4-c0aef326f988.png)

**Comment by ericandrewlewis** [comment]
This is happening because `catch_workers_output` is unset in the `php-fpm.conf`. Perhaps we could set `catch_workers_output` to `yes` there?

**Comment by yosifkit** [comment]
Sounds reasonable to me.
