### ISSUE TITLE
apk update for persistent deps

### ISSUE THREAD

**Issue by mostafa-rz** [docker-library/php#1404]
Hi, 
Can you please explain why the repo is not updated(apk update) before [adding the persistence deps](https://github.com/docker-library/php/blob/9d896ba1fb230ba7e2a0c903ed9db1a8e48176c9/8.1/alpine3.17/fpm/Dockerfile#L23)?
In the Alpine packages repo, OpenSSL is now updated and there are no vulnerabilities anymore, but I will get a vulnerability because php fpm is not adding the latest OpenSSL version.

**Comment by tianon** [comment]
We don't do an explicit `apk update` there because `apk add --no-cache` implies it (but with the added behavior that it then prunes the updated package lists afterwards so that they don't end up in the final image).
