### ISSUE TITLE
Disable daylight saving time for Asia/Tehran

### ISSUE THREAD

**Issue by imeysam** [docker-library/php#1407]
In this year in Iran, based on the government's decision, daylight saving time is not affected. But the php:7.4-fpm image is not supported.
I set 'date_default_timezone_set("Asia/Tehran");' and it represents +04:30, when it should represent +03:30.

**Comment by phy25** [comment]
PHP 7.4 is end-of-life so I assume the Docker image itself will never receive new updates.

See https://serverfault.com/questions/1123233/why-doesnt-the-timezonedb-extension-have-the-latest-data#comment1466567_1123233

**Comment by imeysam** [comment]
I upgraded php v8.1.
