### ISSUE TITLE
Memcached installation error in php:8.1-apache

### ISSUE THREAD

**Issue by andriuhatm** [docker-library/php#1418]
**Description**
From yesterday we started getting an error when building docker containers, specifically when installing **memcached** with the command `RUN install-php-extensions memcached` but the same happens with `pecl install memcached`.
> configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR>

The suggested attribute `--with-libmemcached-dir=<DIR>` doesn't fix it and throws an error as if the file didn't existed in the provided location.
> unable to locate header file memcached.h**

**Steps to replicate**
- Install memcached in Dockerfile using pecl or install-php-extensions

**Workaround**
The workaround for now is to use `php:8.1.9-apache` instead of `php:8.1-apache`

**Comment by TimWolla** [comment]
ref https://github.com/php/php-src/issues/11452

**Comment by AdamKatzDev** [comment]
I've also encountered the same issue in `7.4`.

That is probably somehow related to the recent Debian PR.
https://github.com/docker-library/php/pull/1416
As a workaround use `8.1-fpm-bullseye`, `8.1-bullseye`, `7.4-bullseye`, etc.

**Comment by yosifkit** [comment]
Yup, it seems there is a bug with the [`libmemcached`](https://packages.debian.org/bookworm/libmemcached-dev) package in bookworm. The pkg-config file has this content:

```
root@e3b27f5cf8f8:/# cat /usr/lib/x86_64-linux-gnu/pkgconfig/libmemcached.pc
...
Requires:  libsasl2
Requires.private:  libcrypto
```

So it is missing the dependency on `libssl-dev` that provides `libcrypto`. Adding `libssl-dev` to the `apt-get install` will fix the error.

**Comment by digilopment** [comment]
Hi, I have the same issue, unfortunately yesterday I reported here (with description and reported versions) https://github.com/php/php-src/issues/11452 Thank you.

**Comment by tianon** [comment]
I filed the bug against the Debian package appropriately: https://bugs.debian.org/1038149
