### ISSUE TITLE
List of available ENV for php-apache image

### ISSUE THREAD

**Issue by huyhoang8398** [docker-library/php#1419]
Is there a way to see all the available ENV for php-apache image that I could use?
For example:
PHP_MEMORY_LIMIT
...

**Comment by tianon** [comment]
We don't support any environment variables for `php.ini` settings in this image (however, `php.ini` _does_ support interpolation of environment variables, so you should be able to supply your own `php.ini` file which _does_ respond to variables like the one you've descrbied).
