### ISSUE TITLE
Add User 1000 to www-data with php-apache image

### ISSUE THREAD

**Issue by huyhoang8398** [docker-library/php#1420]
Im using php-apache image.
Do I still need to add user 1000 to www-data and chown all the /var/www/html to www-data

```Dockerfile
RUN usermod -u 1000 www-data
...
RUN chown -R www-data:www-data /var/www/html
```

Or maybe in docker compose with this ENV:
```Dockerfile
environment:
   - APACHE_RUN_USER="#1000"
   - APACHE_RUN_GROUP="#1000"
```
Or just leave it as default? but i chroot to the container and see all files is own by root:root

**Comment by tianon** [comment]
Honestly, you're probably even be better off running with `--user 1000:1000` (or `user: '1000:1000'` in `docker-compose.yml`), if you've got a new enough kernel/Docker to support Apache running unprivileged and binding to port 80 (but barring that, what you've described _should_ work).
