### ISSUE TITLE
how to generate dockerfile？

### ISSUE THREAD

**Issue by overMiracle** [docker-library/php#1422]
### I cloned your project to local, I need the latest version of php8.2.7, alpine3.16 (because I need openssl1.1), I modified the configuration file, how to generate php:8.2.7-alpine3.16 dockerfile

**Comment by yosifkit** [comment]
One way is to manually update `versions.json` and then run `./apply-templates.sh 8.2`. Another is to edit the `FROM` in a Dockerfile in one of the `8.2/alpine*/*` folders.

Alternatively, you can edit `versions.sh` to not skip the combination that you need and then run it (`./versions.sh 8.2`) to update `versions.json` for you (and then run the apply templates to update/add the Dockerfiles).

Likely somewhere here:
https://github.com/docker-library/php/blob/0bae31aa4aa0afffdc394072bda779fa652f74fc/versions.sh#L87-L110
