### ISSUE TITLE
A lot of Warning info

### ISSUE THREAD

**Issue by vndroid** [docker-library/php#1427]
Such as:

```
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
```

Based Alpine 3.18, how to fix it?

**Comment by tianon** [comment]
I'm not sure I understand completely what you're asking -- what are you trying to do, what have you tried, what are you expecting, what are you getting instead?  Are the warnings causing a problem, or are they just not nice to look at?
