### ISSUE TITLE
How to enable curl extension other features?

### ISSUE THREAD

**Issue by vndroid** [docker-library/php#1428]
The docker image `php:8.2.8-fpm-alpine3.18` already has the curl extension, but some feature is disabled.

![1691475589100](https://github.com/docker-library/php/assets/15273693/e6d6f250-b780-4560-b8c4-e650c54b613e)

If I want to enable the `CharConv ` and `http3`, 

I try the command:

```bash
docker-php-ext-configure curl --with-http3
# or
docker-php-ext-configure curl --enable-http3
```

but they are both unrecognized. what should I do it?

**Comment by tianon** [comment]
https://hub.docker.com/_/php#:~:text=How%20to%20install%20more%20PHP%20extensions

> ## How to install more PHP extensions
> 
> Many extensions are already compiled into the image, so it's worth checking the output of `php -m` or `php -i` before going through the effort of compiling more.
> 
> We provide the helper scripts `docker-php-ext-configure`, `docker-php-ext-install`, and `docker-php-ext-enable` to more easily install PHP extensions.
> 
> In order to keep the images smaller, PHP's source is kept in a compressed tar file. To facilitate linking of PHP's source with any extension, we also provide the helper script `docker-php-source` to easily extract the tar or delete the extracted source. Note: if you do use `docker-php-source` to extract the source, be sure to delete it in the same layer of the docker image.
> 
> ```Dockerfile
> FROM php:8.2-cli
> RUN docker-php-source extract \
> 	# do important things \
> 	&& docker-php-source delete
> ```
> 
> ### PHP Core Extensions
> 
> For example, if you want to have a PHP-FPM image with the `gd` extension, you can inherit the base image that you like, and write your own `Dockerfile` like this:
> 
> ```dockerfile
> FROM php:8.2-fpm
> RUN apt-get update && apt-get install -y \
> 		libfreetype-dev \
> 		libjpeg62-turbo-dev \
> 		libpng-dev \
> 	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
> 	&& docker-php-ext-install -j$(nproc) gd
> ```
> 
> Remember, you must install dependencies for your extensions manually. If an extension needs custom `configure` arguments, you can use the `docker-php-ext-configure` script like this example. There is no need to run `docker-php-source` manually in this case, since that is handled by the `configure` and `install` scripts.
> 
> If you are having difficulty figuring out which Debian or Alpine packages need to be installed before `docker-php-ext-install`, then have a look at [the `install-php-extensions` project](https://github.com/mlocati/docker-php-extension-installer). This script builds upon the `docker-php-ext-*` scripts and simplifies the installation of PHP extensions by automatically adding and removing Debian (apt) and Alpine (apk) packages. For example, to install the GD extension you simply have to run `install-php-extensions gd`. This tool is contributed by community members and is not included in the images, please refer to their Git repository for installation, usage, and issues.
> 
> See also ["Dockerizing Compiled Software"](https://tianon.xyz/post/2017/12/26/dockerize-compiled-software.html) for a description of the technique Tianon uses for determining the necessary build-time dependencies for any bit of software (which applies directly to compiling PHP extensions).
> 
> ### Default extensions
> 
> Some extensions are compiled by default. This depends on the PHP version you are using. Run `php -m` in the container to get a list for your specific version.
