### ISSUE TITLE
/8.1/alpine3.18/zts/Dockerfile

### ISSUE THREAD

**Issue by arcanisgk** [docker-library/php#1438]
https://github.com/docker-library/php/blob/83461ac6dbfa05acb3d743e10404983ce89334f5/8.1/alpine3.18/zts/Dockerfile

this is broken at startup still restarting ...

**Comment by tianon** [comment]
If you want help, you're going to have to be a lot more specific about your problem. :sweat_smile:

What are you trying to do?  What have you tried?  What did you experience instead?  (A minimal reproducer would be helpful.)
