### ISSUE TITLE
Port 80 doesn't expose in Windows 10 with php:5.6-apache images

### ISSUE THREAD

**Issue by saggafarsyad** [docker-library/php#145]
Hello

I am new to Docker and I'm very excited when I know there is an official docker images for php. I try the `php:5.6-apache` image, I follow the instruction but I can't access the localhost. I get this message with curl

    curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused

I solved it by adding `-p 80:80`, so it would be

    docker run -it --rm -p 80:80 --name my-running-app my-php-app  

It would be helpful if you add some note in the docs about this for Windows users

Thank you

**Comment by Moghedrin** [comment]
This isn't a windows issue or an issue with the image: this is a matter of how Docker works. See the documentation for this behavior [here](https://docs.docker.com/reference/builder/#expose).
