### ISSUE TITLE
PHP 8.3.0 RC 6 not available

### ISSUE THREAD

**Issue by xvilo** [docker-library/php#1461]
I'm writing because it appears the PHP 8.3.0 RC6 tag is not available on Docker Hub when searching through the tags on the website. Also, pulling the tag does not work, unfortunately. 

I noticed the Dockerfiles have been updated accordingly https://github.com/docker-library/php/commit/bde3d5c08a72f61ed5af7592b1910faed1e4a3f2 

Did something go wrong with publishing the updated image, how can we publish this version to Docker Hub.

**Comment by LaurentGoderre** [comment]
https://github.com/docker-library/official-images/pull/15704

**Comment by damien-louis** [comment]
@xvilo I guess you can close this issue

**Comment by xvilo** [comment]
Has indeed been fixed, thanks! 👍
