### ISSUE TITLE
unable to find php image with webserver

### ISSUE THREAD

**Issue by bathivinod** [docker-library/php#1462]
I am able to find image contains (php8.1+apache+debian) in php:8.1-apache

Is there an image consists of php+<anyweb>+apline eg (php8.1+httpd+alpine) ?

**Comment by LaurentGoderre** [comment]
Having both the php and apache in the same Alpine image defeats the purpose of using Alpine. You could use the PHP fpm variant with a proxy in front.

**Comment by bathivinod** [comment]
Thank you @LaurentGoderre for clarification.
