### ISSUE TITLE
required composer with php:8.1-apache

### ISSUE THREAD

**Issue by bathivinod** [docker-library/php#1465]
is there any version like php:8.1-apache with includes composer also or similar

**Comment by damien-louis** [comment]
I guess all Docker tags don't include Composer.

You can use it simply with a Dockerfile like this:

```
FROM php:8.1-apache

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && chmod +x /usr/local/bin/composer
```

**Comment by bathivinod** [comment]
Hi @damien-louis 
Thanks for providing input.

**Comment by tianon** [comment]
You can also copy it from the `composer` image: https://github.com/docker-library/drupal/blob/96f915e1503663db2bc6f7cff28774e62aeac4ca/10.1/php8.2/apache-bookworm/Dockerfile#L66
