### ISSUE TITLE
When will the php8.3 image be released?

### ISSUE THREAD

**Issue by xgbnl** [docker-library/php#1466]
I'm looking forward to it😜

**Comment by jnoordsij** [comment]
It won't arrive at least until the official release announcement (which will appear probably today or tomorrow), after which it requires some more action + time.

See also https://github.com/docker-library/php/pull/1464 (and then https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what).

**Comment by damien-louis** [comment]
8.3.0 is official:
https://www.php.net/archive/2023.php#2023-11-23-2

**Comment by xvilo** [comment]
Releated MR that can be merged https://github.com/docker-library/php/pull/1464/

**Comment by pereorga** [comment]
8.2.13 is not available, either. I understand there may be complexities in maintaining these images, but I'm wondering if there’s a particular reason for the delay in updates following PHP releases. Having these images updated in sync with PHP releases would be beneficial. Could this be fully automated?

Anyway, thank you. Your ongoing efforts in managing the official PHP Docker images significantly contributes to the PHP community, and I, along with many others, greatly benefit from your dedication.

**Comment by kilvn** [comment]
php 8.3 is released, now you can build docker image: php:8.3-fpm
https://www.php.net/releases/8.3/zh.php

**Comment by yosifkit** [comment]
Closed by https://github.com/docker-library/php/pull/1464 (and https://github.com/docker-library/official-images/pull/15776)

**Comment by zerkms** [comment]
```
➜ docker pull php:8.3-fpm
8.3-fpm: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

and the tag shows no layers: https://hub.docker.com/layers/library/php/8.3-fpm/images/sha256-eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb?context=explore
