### ISSUE TITLE
8.1-fpm-alpine3.18 can no longer connect to pecl

### ISSUE THREAD

**Issue by afilina** [docker-library/php#1469]
Hi,

I am no longer able to ping `pecl.php.net` from the container. This started 2 days ago. Npthing changed in our environment, except that I see a new push to `8.1-fpm-alpine3.18` 3 days ago. What changed that could have led to this problem, and how can we fix it?

Thanks.

**Comment by afilina** [comment]
Yes, it looks like a similar issue, except that it's a more recent PHP version and the issue started happening overnight, while it was working for many years until then.

**Comment by LaurentGoderre** [comment]
@afilina I wonder if it's more a change in Alpine rather than anything to do with a specific PHP version.

**Comment by tianon** [comment]
Can you provide a specific command that replicates the error you're seeing?  (as noted above, I wasn't able to reproduce a failure)

**Comment by afilina** [comment]
@LaurentGoderre Yes, this is very likely. However, I would expect a pinned Docker image to remain unaffected, but it was updated a few days before the error started showing up. This means that there's no reasonable way for me to have a reproducible local env. At least if I understand the underlying issue correctly.

**Comment by afilina** [comment]
> Can you provide a specific command that replicates the error you're seeing? (as noted above, I wasn't able to reproduce a failure)

Just `ping pecl.php.net` as I said in the original post. It was working and then it stopped, coinciding with an upstream update that was pushed to this legacy image (based on what I see on Docker Hub).

**Comment by LaurentGoderre** [comment]
@afilina pinning to a tag doesn't guarantee immutability because we are constantly updating the base OS to address vulnerabilties. If you want immutability you pin to a specific SHA but then you wouldn't be getting the vulnerability updates.

**Comment by LaurentGoderre** [comment]
@afilina here is what I get locally

```
docker run --rm --entrypoint ping php:8.1-fpm-alpine3.18 pecl.php.net
PING pecl.php.net (104.236.228.160): 56 data bytes
64 bytes from 104.236.228.160: seq=0 ttl=63 time=33.530 ms
64 bytes from 104.236.228.160: seq=1 ttl=63 time=54.114 ms
64 bytes from 104.236.228.160: seq=2 ttl=63 time=56.521 ms
64 bytes from 104.236.228.160: seq=3 ttl=63 time=42.443 ms
64 bytes from 104.236.228.160: seq=4 ttl=63 time=30.746 ms
64 bytes from 104.236.228.160: seq=5 ttl=63 time=31.024 ms
64 bytes from 104.236.228.160: seq=6 ttl=63 time=37.091 ms
64 bytes from 104.236.228.160: seq=7 ttl=63 time=54.873 ms
64 bytes from 104.236.228.160: seq=8 ttl=63 time=34.396 ms
64 bytes from 104.236.228.160: seq=9 ttl=63 time=31.808 ms
64 bytes from 104.236.228.160: seq=10 ttl=63 time=34.674 ms
64 bytes from 104.236.228.160: seq=11 ttl=63 time=35.424 ms
64 bytes from 104.236.228.160: seq=12 ttl=63 time=37.498 ms
64 bytes from 104.236.228.160: seq=13 ttl=63 time=40.624 ms
64 bytes from 104.236.228.160: seq=14 ttl=63 time=52.140 ms
64 bytes from 104.236.228.160: seq=15 ttl=63 time=49.530 ms
64 bytes from 104.236.228.160: seq=16 ttl=63 time=30.407 ms
64 bytes from 104.236.228.160: seq=17 ttl=63 time=42.466 ms
64 bytes from 104.236.228.160: seq=18 ttl=63 time=47.633 ms
64 bytes from 104.236.228.160: seq=19 ttl=63 time=32.901 ms
64 bytes from 104.236.228.160: seq=20 ttl=63 time=44.471 ms
64 bytes from 104.236.228.160: seq=21 ttl=63 time=38.838 ms
64 bytes from 104.236.228.160: seq=22 ttl=63 time=51.927 ms
64 bytes from 104.236.228.160: seq=23 ttl=63 time=52.865 ms
64 bytes from 104.236.228.160: seq=24 ttl=63 time=75.173 ms
64 bytes from 104.236.228.160: seq=25 ttl=63 time=109.770 ms
64 bytes from 104.236.228.160: seq=26 ttl=63 time=45.096 ms
64 bytes from 104.236.228.160: seq=27 ttl=63 time=31.420 ms
64 bytes from 104.236.228.160: seq=28 ttl=63 time=164.128 ms
64 bytes from 104.236.228.160: seq=29 ttl=63 time=32.608 ms
64 bytes from 104.236.228.160: seq=30 ttl=63 time=57.331 ms
64 bytes from 104.236.228.160: seq=31 ttl=63 time=33.720 ms
64 bytes from 104.236.228.160: seq=32 ttl=63 time=41.266 ms
64 bytes from 104.236.228.160: seq=33 ttl=63 time=38.645 ms
64 bytes from 104.236.228.160: seq=34 ttl=63 time=91.905 ms
64 bytes from 104.236.228.160: seq=35 ttl=63 time=156.221 ms
64 bytes from 104.236.228.160: seq=36 ttl=63 time=32.764 ms
^C
--- pecl.php.net ping statistics ---
37 packets transmitted, 37 packets received, 0% packet loss
round-trip min/avg/max = 30.407/51.567/164.128 ms
```

**Comment by afilina** [comment]
@LaurentGoderre Ok, so maybe something else changed in my environment that's causing this. I will investigate on our end with a specific SHA to better isolate the cause. I don't think I'll pin it to a SHA, since the vulnerability patches are definitely important.

Since it clearly works for multiple people, I will close this issue.
