### ISSUE TITLE
witam serdecznie pana kleksa

### ISSUE THREAD

**Issue by Polci4k** [docker-library/php#1477]
1. Atrybuty formularza do wysyłania pliku: Aby umożliwić wysyłanie plików, formularz musi posiadać atrybut `enctype="multipart/form-data"`.

2. Typy kontrolki input:
   - `text`
   - `password`
   - `checkbox`
   - `radio`
   - `submit`
   - `file`
   - `hidden`
   - `reset`
   - `button`

3. Nazwa tablicy w PHP przechowującej dane z GET: Ta tablica nosi nazwę `$_GET`.

4. Sposób wysyłania danych przy użyciu metody GET: Dane są przesyłane poprzez dołączenie ich do URL-a w formie parametrów zapytania. Na przykład: `www.strona.pl?parametr1=wartość1&parametr2=wartość2`.

5. Formularz HTML z polem input, polem radio i przyciskiem:
<form method="POST">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username"><br><br>
    
    <label for="option1">Option 1:</label>
    <input type="radio" id="option1" name="options" value="option1">
    
    <label for="option2">Option 2:</label>
    <input type="radio" id="option2" name="options" value="option2"><br><br>
    
    <button type="submit">Wyślij</button>
</form>

6. Formularz HTML z polem select wielokrotnego wyboru:
<form method="POST">
    <label for="cars">Select multiple cars:</label><br>
    <select id="cars" name="cars[]" multiple>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="opel">Opel</option>
        <option value="audi">Audi</option>
    </select><br><br>
    <button type="submit">Wyślij</button>
</form>

7. Kod PHP wyświetlający przesłane dane z URL-a:
<?php
if(isset($_GET['email']) && isset($_GET['role'])){
    echo "Email: " . $_GET['email'] . "<br>";
    echo "Rola: " . $_GET['role'];
}
?>

8. Skrypt wyświetlający dane z formularza:
<form method="GET">
  <label for="surname">Nazwisko:</label>
  <input type="text" name="surname"><br><br>
  
  <label for="is_active">Czy aktywny:</label>
  <input type="checkbox" name="is_active"><br><br>
  
  <button type="submit">Wyślij</button>
</form>

**Comment by Polci4k** [comment]
<?php

// Tworzenie formularza metodą POST
echo "<form method=post>";

// Pole tekstowe dla kosztu benzyny
echo "<label>Koszt benzyny</label>";
echo "<br>";
echo "<input type='number' name='kosztbenzyny'>";
echo "<br>";

// Pole tekstowe dla ilości kilometrów
echo "<label>Ilość kilometrów</label>";
echo "<br>";
echo "<input type='number' name='ilosckilometrow'>";
echo "<br>";

// Pole tekstowe dla średniego spalania
echo "<label>Średnie spalanie</label>";
echo "<br>";
echo "<input type='number' name='sredniespalanie'>";
echo "<br>";

// Przycisk do wysłania formularza
echo "<button type='submit'>Wyślij</button>";
echo "<br>";
echo "<br>";

// Wyświetlanie informacji przesłanych przez formularz
echo "<label>Informacje</label>";
echo "<br>";
echo "<br>";

// Wyświetlanie kosztu benzyny
echo "<label>Koszt benzyny: </label>";
if(isset($_POST["kosztbenzyny"])){
    echo $_POST['kosztbenzyny'];
};
echo "<br>";

// Wyświetlanie ilości kilometrów
echo "<label>Ilość kilometrów: </label>";
if(isset($_POST["ilosckilometrow"])){
    echo $_POST['ilosckilometrow'];
};
echo "<br>";

// Wyświetlanie średniego spalania
echo "<label>Średnie spalanie:</label>";
if(isset($_POST["sredniespalanie"])){
    echo $_POST['sredniespalanie'];
};
echo "<br>";
echo "<br>";

// Obliczanie i wyświetlanie wyniku
echo "<label>Wynik: </label>";
if(isset($_POST["kosztbenzyny"])){
    echo $_POST['kosztbenzyny'] * $_POST['ilosckilometrow'] * $_POST['sredniespalanie'] / 100;
}; 
?>

**Comment by LaurentGoderre** [comment]
You would have better luck asking this in a forum for PHP development. This area is for issues with the PHP Docker image.

**Comment by Thentomint** [comment]
> 1. Atrybuty formularza do wysyłania pliku: Aby umożliwić wysyłanie plików, formularz musi posiadać atrybut `enctype="multipart/form-data"`.
> 
>     2. Typy kontrolki input:
>        
>        * `text`
>        * `password`
>        * `checkbox`
>        * `radio`
>        * `submit`
>        * `file`
>        * `hidden`
>        * `reset`
>        * `button`
> 
>     3. Nazwa tablicy w PHP przechowującej dane z GET: Ta tablica nosi nazwę `$_GET`.
> 
>     4. Sposób wysyłania danych przy użyciu metody GET: Dane są przesyłane poprzez dołączenie ich do URL-a w formie parametrów zapytania. Na przykład: `www.strona.pl?parametr1=wartość1&parametr2=wartość2`.
> 
>     5. Formularz HTML z polem input, polem radio i przyciskiem:
> 
> 
> Username:
> 
> ```
> <label for="option1">Option 1:</label>
> <input type="radio" id="option1" name="options" value="option1">
> 
> <label for="option2">Option 2:</label>
> <input type="radio" id="option2" name="options" value="option2"><br><br>
> 
> <button type="submit">Wyślij</button>
> ```
> 
>     6. Formularz HTML z polem select wielokrotnego wyboru:
> 
> 
> Select multiple cars:
> Volvo Saab Opel Audi
> 
> Wyślij
> 
>     7. Kod PHP wyświetlający przesłane dane z URL-a:
> 
> 
> "; echo "Rola: " . $_GET['role']; } ?>
> 
>     8. Skrypt wyświetlający dane z formularza:
> 
> W wolnym czasie lubię grać na [https://mostbet.net.pl/promo/bonus/](https://mostbet.net.pl/promo/bonus/) to świetna zabawa
>
> Nazwisko:
> 
> Czy aktywny:
> 
> Wyślij

Dziękuję za zebranie tych informacji. Kilka rzeczy trzeba wyjaśnić - na przykład, formularz przycisku radiowego nie ma faktycznego pola tekstowego dla „Nazwa użytkownika”, a przykład wielokrotnego wyboru nie ma znaczników select i option, więc nie zadziała. Skrypt PHP może mieć również pełną składnię, ponieważ nie zadziała bez otwarcia <?php. Warto go trochę zmodyfikować, aby przykłady były w pełni funkcjonalne
