### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kasteckis** [docker-library/php#1478]
.

**Comment by LaurentGoderre** [comment]
Normally you don't need to worry about SSL when. it's handled by a proxy. What kind of issue are you getting?

**Comment by kasteckis** [comment]
> Normally you don't need to worry about SSL when. it's handled by a proxy. What kind of issue are you getting?

An application from the inside generates HTTP url's intead of HTTPS urls, because from the inside it thinks it is being accessed from HTTP instead of HTTPS.

**Comment by tianon** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto and/or https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded are designed for that problem :eyes:

That being said, our installation is a pretty standard apache2 installed from Debian, so you should be able to munge the configuration in the same way.  I haven't tested it in a while, but https://github.com/docker-library/php/issues/506#issuecomment-335929742 is an example of where I've done this successfully in the past.
