### ISSUE TITLE
PHP 8.3.1 not available

### ISSUE THREAD

**Issue by rogerdz** [docker-library/php#1479]
PHP 8.3.1, 8.2.14, 8.1.27 not available in Docker Hub. Did something go wrong with publishing the updated image ?

**Comment by tianon** [comment]
https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

(mostly just that it's a major holiday weekend and we're all on PTO -- the update PR is open now at https://github.com/docker-library/official-images/pull/15974)
