### ISSUE TITLE
Accessing apache files

### ISSUE THREAD

**Issue by WojakGra** [docker-library/php#1481]
Is it possible to connect Apache files to a volume so that they are automatically added there when creating a container, or do they have to be copied manually?

**Comment by kphunter** [comment]
- using `docker compose`: yes - you can specify a volume mount to a specific file using either the [short or long syntax](https://docs.docker.com/compose/compose-file/05-services/#volumes)
- using Kubernetes: yes - you can specify a `configMap` as a volume and bind it to a container using a [volume mount](https://kubernetes.io/docs/concepts/storage/volumes/#configmap)
- if you copy Apache files using the `COPY` command in a `Dockerfile`, you lose the benefit of being able to update the configuration independently from the image
