### ISSUE TITLE
curl error on php:8.2-apache (bookworm)

### ISSUE THREAD

**Issue by irulvam** [docker-library/php#1485]
when i use curl with vendor guzzelhttp always fail

this is error output

```
root@3bfcc3d6852c:/var/www/html# curl google.com
curl: (6) getaddrinfo() thread failed to start
```

how to fix this?

**Comment by yosifkit** [comment]
I guess that this is likely due to seccomp -- so, need to update Docker, runc, and libseccomp on your host.

https://github.com/docker-library/python/issues/837#issuecomment-1599640563

**Comment by Read2uk** [comment]
Hi @irulvam have you figured out the problem?

I have the same issue with 8.3-apache bookworm

**Comment by tianon** [comment]
> I guess that this is likely due to seccomp -- so, need to update Docker, runc, and libseccomp on your host.
> 
> [docker-library/python#837 (comment)](https://github.com/docker-library/python/issues/837#issuecomment-1599640563)
