### ISSUE TITLE
Add Support for shmop

### ISSUE THREAD

**Issue by Breee** [docker-library/php#1486]
We need support for shmop [https://www.php.net/manual/en/book.shmop.php](https://www.php.net/manual/en/book.shmop.php)

Would it be possible to build the container images with `--enable-shmop`  ?

**Comment by tianon** [comment]
See https://hub.docker.com/_/php#:~:text=How%20to%20install%20more%20PHP%20extensions (I've just tested, and `docker-php-ext-install shmop` works as-is without any extra packages installed :sweat_smile:)
