### ISSUE TITLE
Can't install php7.4-sybase package on php:7.4-apache-bullseye

### ISSUE THREAD

**Issue by alb3ric** [docker-library/php#1494]
Hello,

I can't manage to install php7.4-sybase package on php:7.4-apache-bullseye container.

``` 
apt-get install php7.4-sybase

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php7.4-sybase is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php7.4-sybase' has no installation candidate
```
Off course, I did a apt-get update before that :)

I tried the same with a debian:bullseye image and a debian:slim-bullseye and it is working on both.
I checked the sources.list and can't see any difference.

Thanks in advance for your help.

Best regards,

**Comment by sbuerk** [comment]
The official images does not provide prebuild packages, `php7.4-*` sounds more like a debian or ondrej php pre-build package install. For that, the official images are the wrong. You better need to base on a ubuntu based image, add the onrej-php repository (or use a image already have that) and than simply install that package.

If you want to use these images, have a look here https://hub.docker.com/_/php/ in the section how to install other core extenions or pecl packages properly.

**Comment by yosifkit** [comment]
Also note that the `php:7.*` docker images have not received any updates since https://github.com/docker-library/php/pull/1349 (i.e., since the version reached end of life). So, they are unsupported and have very outdated packages installed in them.

**Comment by alb3ric** [comment]
Thanks for your answers, it's helping a lot.

Regards
