### ISSUE TITLE
Add mlocati/docker-php-extension-installer to base image

### ISSUE THREAD

**Issue by carnage** [docker-library/php#1498]
https://github.com/mlocati/docker-php-extension-installer

The script here is a very mature implementation which will install a huge number of different php extensions and their dependencies into both alpine and debian based images it seems like it would be a really useful tool to add to the base images.

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/621 -- it was created specifically _because_ we have no plans to integrate this functionality.
