### ISSUE TITLE
Update libxml in php:7.3-apache to version 2.9.14

### ISSUE THREAD

**Issue by SnowRunescape** [docker-library/php#1509]
The current version of libxml bundled with the php:7.3-apache Docker image is outdated. We propose updating it to version 2.9.14 to ensure compatibility with the latest features and security patches.

**Details:**
The php:7.3-apache image is widely used in various development environments and projects. However, the included libxml library, used for XML parsing, is currently not up to date. Updating to libxml version 2.9.14 will provide users with access to the latest improvements and bug fixes, enhancing both functionality and security.

**Expected Outcome:**
By updating the libxml library to version 2.9.14 in the php:7.3-apache Docker image, users will benefit from improved XML parsing capabilities and strengthened security measures. This update ensures that developers can confidently rely on the php:7.3-apache image for their projects without concerns about outdated dependencies.

**Additional Information:**

Link to the Docker Hub page for php:7.3-apache: Docker Hub - php:7.3-apache
Link to the libxml GitHub repository: [GitHub - GNOME/libxml2](https://github.com/GNOME/libxml2)
Documentation for libxml version 2.9.14: [libxml2 - Version 2.9.14 Documentation](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.9.14)

**Note:**
This issue is opened with the intention of improving the php:7.3-apache Docker image by updating its dependencies to the latest versions. We welcome any feedback, contributions, or discussions regarding this proposed update.

**Comment by phy25** [comment]
PHP 7.3 is not a supported version listed here: https://github.com/docker-library/docs/tree/master/php#supported-tags-and-respective-dockerfile-link

In fact, its support has already ended at the end of 2021: https://www.php.net/supported-versions.php
