### ISSUE TITLE
Upgrade historical manifests

### ISSUE THREAD

**Issue by mvorisek** [docker-library/php#1522]
CI log:
```
/usr/bin/docker pull php:5.4
  5.4: Pulling from library/php
  [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled
by default and will be removed in an upcoming release. Suggest the author of docker.io/library/php:5.4 to upgrade
the image to the OCI Format or Docker Image manifest v2, schema 2. More information at
https://docs.docker.com/go/deprecated-image-specs/
```

please repush historical images to use the newest manifest in order to make them working with the latest Docker - see https://docker-docs.uclv.cu/registry/spec/deprecated-schema-v1/#update-to-image-manifest-version-2-schema-2

**Comment by tianon** [comment]
Unfortunately, this is a little complicated.  I think https://github.com/docker/roadmap/issues/173 is the roadmap issue for Docker at large, but some of the complexities for DOI are that we don't want to just "pull, convert, push" all these old images and have them show up as "updated", so ideally a solution here needs to happen without updating timestamps and that isn't something we can accomplish on our own. :bow:

Thank you for raising this though (and the user interest in it). :heart:

**Comment by tianon** [comment]
In hindsight, I probably should've transferred this issue last week, but now we've got https://github.com/docker-library/official-images/issues/16997 which I'm going to close this in favor of (to track this at the broader/more applicable level). :bow: :heart:
