### ISSUE TITLE
Security updates on older php version images

### ISSUE THREAD

**Issue by SC7639** [docker-library/php#1523]
My company is still using php 7.2 with apache for their legacy website. We are looking to move from ansible to docker. I've noticed the vulnerability. Is this something that gets updated when the patches are released or something I'll need to deal with myself? Buster is going to be out of LTS starting Jun 30th, will the base image be updated to the next LTS bullseye

**Comment by tianon** [comment]
Cross-linking the updated https://github.com/docker-library/php/issues/1524
