### ISSUE TITLE
Debian Buster based images - Updrage?

### ISSUE THREAD

**Issue by SC7639** [docker-library/php#1524]
I'm currently using php:7.2-apache image that has debian buster as its base image. Buster's LTS is ending on the 30th of Jun 20204, is there any plan to update these images to bullseye or will I need to create my own image from scratch. If I did so can I submit it here? I noticed you have no directories for images before php 8.1.

**Comment by phy25** [comment]
PHP 7.2 is already end of life https://www.php.net/supported-versions.php and thus you should not expect updates here. You can maintain your own images at your own risk

**Comment by yosifkit** [comment]
Thanks @phy25!

Yeah, we don't maintain Dockerfiles or build images for end-of-life PHP versions. As a starting point, you can find the Dockerfiles for the old PHP versions in the git history of this repo, but they may no longer build or even work with a newer `FROM`.
