### ISSUE TITLE
`PHP_EOL` is set to `CR LF` line endings

### ISSUE THREAD

**Issue by smrqdt** [docker-library/php#1537]
For some reason PHP CLI uses Windows/DOS line endings (`\r\n`) instead of Linux/POSIX line ending (`\n`), when run from the container:

```
% podman run --rm -it docker.io/library/php:8.3-cli -r 'echo PHP_EOL;' | xxd
00000000: 0d0a
% podman run --rm -it docker.io/library/php:8.3-bullseye -r 'echo PHP_EOL;' | xxd
00000000: 0d0a
% podman run --rm -it docker.io/library/php:8.3-alpine -r 'echo PHP_EOL;' | xxd  
00000000: 0d0a
```

(No difference when using docker instead of podman.)

Instead of `CR LF` (`\r\n` or `0x0D 0x0A`) PHP should use only `LF` (`\n` or `0x0A`), like when installed on Fedora via package manager:

```
php -r 'echo PHP_EOL;' | xxd
00000000: 0a           
```

I’m not a php developer, but I suspect this is caused by some mishap at compile time?

The wrong line endings result in mayhem with bash completion functions generated by php inside the container (e.g. nextcloud’s `occ`) and probably in other situations.

**Comment by LaurentGoderre** [comment]
I believe it is working as intended

```bash
% docker run --rm -it php:8.3-alpine -r 'echo "\r\n";' | xxd
00000000: 0d0d 0a                                  ...
% docker run --rm -it php:8.3-alpine -r 'echo "\n";' | xxd  
00000000: 0d0a                                     ..
% docker run --rm -it php:8.3-alpine -r 'echo PHP_EOL;' | xxd
00000000: 0d0a 
```

**Comment by LaurentGoderre** [comment]
It seems the confusion stems from the communication from the container to the host. Running the command entirely in the container yields the expected output

```bash
% docker run --rm -it php:8.3-cli bash
root@c4203615df4f:/# apt update 2>&1 > /dev/null && apt install xxd 2>&1 > /dev/null 
root@c4203615df4f:/# php -r "PHP_EOL;" | xxd
root@c4203615df4f:/# php -r "echo PHP_EOL;" | xxd
00000000: 0a
```

**Comment by tianon** [comment]
This is due to the `-t`/`--tty` flag and the way TTYs on Linux work :eyes:

```console
$ docker run --rm php -r 'echo PHP_EOL;' | xxd
00000000: 0a     
```

**Comment by smrqdt** [comment]
Well, thinking about it, I should have expected that podman would behave like a teletype from the early 20th century, after I explicitly asked it to do so with the `--tty` flag. 😄

Thank you for the enlightenment, and sorry for opening an issue.
