### ISSUE TITLE
missing signature key on php:5.4-apache

### ISSUE THREAD

**Issue by CyberPoison** [docker-library/php#1546]
Hi, i'm facing a weird issues with my CI-CD recently, when i do a FROM or a git pull of the image:

docker pull php:5.4-apache

I got:
```sh
Error response from daemon: missing signature key
```

I also tryed to disable trust with
```
export DOCKER_CONTENT_TRUST=0
```

But i didn't get away from the issue and i wasn't able to bypass this.

**Comment by LaurentGoderre** [comment]
Try pulling again. The `missing signature key` has a fix in place now.

**Comment by tianon** [comment]
As noted by Laurent, there's now a fix in place in Docker Hub for the original pulling issue (schema1 images should pull successfully again in tools which support them).

If you have a tool which does not support them and you still need to work with them, I have written https://github.com/tianon/oci-schema1 to help perform the conversion without any runtime support (`bash` + `jq` + a little `crane`).
