### ISSUE TITLE
Call to undefined function grapheme_strlen()

### ISSUE THREAD

**Issue by ludovicKiefer** [docker-library/php#1551]
I have a project that uses the php:8.2-fpm image. My projects works fine on my PC that's running under Debian 12 but it throws an error on a Mac running macOS 15.1 Sequoia with an Apple M1 chip.

My program uses the grapheme_strlen function, the error says "Call to undefined function grapheme_strlen()". The error is thrown with PHP 8.2.15 and PHP 8.3.13, but only on the Mac: no problem on the Debian PC running PHP 8.2.15 (x86_64) and in production (Debian too).

To be more precise, my project uses the php image in a Dockerfile:

```
FROM php:8.2-fpm
RUN docker-php-ext-install -j$(nproc) pdo_mysql
RUN apt-get update; \
    apt-get install -y libmagickwand-dev libzip4 libzip-dev; \
    pecl install imagick; \
    docker-php-ext-enable imagick;
RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl
RUN docker-php-ext-configure exif \
    && docker-php-ext-install exif
RUN docker-php-ext-configure zip \
    && docker-php-ext-install zip
```

**Comment by joshtrichards** [comment]
Unless you're saying that the same Dockerfile generates a different result only on M1, I think you're looking at your situation the wrong way.

For one, `intl` depends on `icu` (which you don't appear to be installing).

You can take a look at how we install `intl` and `icu` in our image here:

https://github.com/nextcloud/docker/blob/d8b6fe8239304d792327fe86eed2f3216107854e/Dockerfile-debian.template#L23

Refs:

https://www.php.net/manual/en/intl.requirements.php

https://stackoverflow.com/questions/48674297/php-intl-extension-in-docker-container

https://github.com/docker-library/docs/blob/master/php/README.md#php-core-extensions

**Comment by ludovicKiefer** [comment]
End of the story: the bug was related to a lack of space available for the images. In Docker Desktop the Virtual disk limit was set to only 40Go, and then there was not enough space in the images to install the PHP dependencies. Increasing it to 128Go was the solution.

The sad part is that Docker Desktop don't notifies when the virtual disk limit is reached.
