### ISSUE TITLE
use apache base image

### ISSUE THREAD

**Issue by sopitz** [docker-library/php#158]
Why does this Dockerfile install the whole apache again instead of using the apache2 image (https://github.com/docker-library/httpd/blob/01b9f786daeace767c57c82d7289f4a8490d1035/2.4/Dockerfile) as baseimage?

**Comment by yosifkit** [comment]
The `httpd` image is as close to how upstream recommends as possible, so it is built directly from source. But the php image uses httpd from the Debian apt repos under `apache2` because that is the build that most people are used to having (`a2enmod`, `sites-available`, etc).

**Comment by urzds** [comment]
Doesn't this contradict https://github.com/docker-library/php/issues/218#issuecomment-207552863?

**Comment by yosifkit** [comment]
Nope, this image is packaging PHP, not Apache httpd.  We can use `httpd` from Debian repos while still following upstream by compiling PHP from source.

**Comment by tianon** [comment]
Closing since this is answered. :+1:
