### ISSUE TITLE
Add note about pecl install on docker hub

### ISSUE THREAD

**Issue by Grummfy** [docker-library/php#160]
Hello,
a lot of issue here and comment in docker hub are related to pecl extension.

Adding a simple sentence like:

    To install geoip, memcached, etc or any other pecl extension just use the following command: 
     pecl install memcached

With this, a lot of issue and command will not appends.

If you explain to me where I can find the text written on https://hub.docker.com/_/php/ I can make a PR

Thanks

**Comment by yosifkit** [comment]
The description is generated from this file: [docker-library/docs/php/content.md](https://github.com/docker-library/docs/blob/master/php/content.md).  Thanks for your help!

**Comment by Grummfy** [comment]
thanks => https://github.com/docker-library/docs/pull/418

I will close this issue
