### ISSUE TITLE
tag php 7.0.1 on dockerhub

### ISSUE THREAD

**Issue by agiuliano** [docker-library/php#165]

**Comment by netroby** [comment]
PHP 7.0.1 released several days, but still not found on dockerhub

**Comment by thaJeztah** [comment]
Looks like the pull request for that is up, but not merged yet: https://github.com/docker-library/official-images/pull/1290

**Comment by yosifkit** [comment]
The build server is currently building them and will then push.

**Comment by mbn18** [comment]
The 7.0.1 tag was added but its not accessible:

    $ docker pull php:7.0.1-fpm
    Trying to pull repository docker.io/library/php ... not found
    Tag 7.0.1-fpm not found in repository docker.io/library/php

**Comment by tianon** [comment]
Apologies for the delay, there was an error in the push -- it should be up
now.
