### ISSUE TITLE
mbstring

### ISSUE THREAD

**Issue by bufface** [docker-library/php#166]
I'm new in docker, i 'm using 5.6-apache image and I need **"mbstring"** extension but I don't know how enable it or install. Can you help me with this?

Sorry for my poor English.

**Comment by tianon** [comment]
Check out the "How to install more PHP extensions" section on
https://hub.docker.com/_/php/ -- you probably just need to do something
like "RUN docker-php-ext-install mbstring" in a new Dockerfile that's "FROM
php:5.6-apache" and you should be good to go.

**Comment by bufface** [comment]
I will try what you say. Thanks

**Comment by pollardino** [comment]
IT' s work... Awesome. Thanks
