### ISSUE TITLE
PHP 7 mysqlnd - cannot find config.m4

### ISSUE THREAD

**Issue by piotrantosik** [docker-library/php#167]
Hi!

Currently is not possible to install mysqlnd extension on php7
I get a error:
```Cannot find config.m4.```

In this extension config is named as ```config9.m4```:
https://github.com/php/php-src/blob/PHP-7.0.1/ext/mysqlnd/config9.m4

It is similar to https://github.com/docker-library/php/pull/89 ?

**Comment by tianon** [comment]
mysqlnd is actually one that doesn't work properly unless it's compiled
directly into PHP, hence
https://github.com/docker-library/php/blob/a5c680f5dc7e7e0e431f979283ef596f25e03fbc/7.0/Dockerfile#L51
(ie, it's already compiled in)

**Comment by piotrantosik** [comment]
Sorry is a my mistake.
Thanks for fast reply!
