### ISSUE TITLE
docker-php-ext-enable: Ordering

### ISSUE THREAD

**Issue by strarsis** [docker-library/php#173]
Related to this issue: https://github.com/krakjoe/apcu-bc/issues/9#issuecomment-168378224

I want to order the apc/apcu ini files, so that apcu loads before apc.
I use docker-php-ext-enable to enable also customly build extensions.

docker-php-ext-enable should also accept an order number,
or an extra command like docker-php-ext-order be provided.

Thank you and
with best regards

**Comment by tianon** [comment]
I think the best way to handle this is probably by adding a new flag to be able to specify a custom filename, which is what really controls the order that PHP loads the files/extensions AFAIK.  Something like `--ini-name` would be my preference for the flag name, with usage like `docker-php-ext-enable --ini-name=0-first-load.ini some-extension`.  I'll start working on a PR. :smile:
