### ISSUE TITLE
Can't create log file

### ISSUE THREAD

**Issue by ir-fuel** [docker-library/php#175]
I added a custom php ini file containing:

```
error_log = /var/log/php_errors.log
log_errors = On
log_errors_max_len = 1024

```

I checked with phpinfo() and it picks up my ini file and the values shown correspond to those I have configured, however when opening bash in my docker container I don't see a `php_errors.log` file being created. I put some `error_log` statements in my php code but no file to be seen.
When I do `sudo docker logs my_container` I can see the `error_log` output being printed there, so the code gets executed.

What is missing in my configuration?

**Comment by ir-fuel** [comment]
FYI I am building the Dockerfile from:
`FROM php:5.6-apache`

**Comment by ir-fuel** [comment]
Nobody?
How do you guys handle error logging?

**Comment by yosifkit** [comment]
I think the "docker way" is to log to stdout and stderr but the current `docker logs` command does not give them back as stderr and stdout :disappointed:.  It will work fine if you use a different `--log-driver` though! (https://docs.docker.com/engine/reference/logging/overview/)

That could be permissions; the process runs as `www-data` in the container and that folder `/var/log/` is only writable by `root`.  You should be able to put it in `/var/log/apache2/` which does have the correct permissions and a file called `error.log` too.

**Comment by ir-fuel** [comment]
Thanks man! Will try moving the log file.

**Comment by ir-fuel** [comment]
Thank you sir :+1: 
It works!
