### ISSUE TITLE
[Proposal/question] install composer by default

### ISSUE THREAD

**Issue by schmunk42** [docker-library/php#177]
I'd like to propose or discuss to install `composer` from https://getcomposer.org by default.

I know that this requires additional extensions installed by default (see also https://github.com/docker-library/php/issues/17). And that it's not a 100% minimal solution, but it would greatly simplify dockerized testing of PHP projects, like described here: https://github.com/stage1/docker-php/pull/144. 

An alternative would be to setup a new automated-build repository which does the job, but I'd say that `composer` is used by almost all PHP projects nowadays.

Working examples for package managers from other Docker images:

```
docker run ruby gem
docker run nodejs npm
docker run python pip
```

**Comment by hairmare** [comment]
:+1: this as it make life way easier for folks that did not grow up on php.

FWIW the (non-php) package managers you mention all get bundled with their upstream languages, whereas composer does not get this treatment by PHP/Zend.

The lack of regular [releases](https://github.com/composer/composer/releases) from composer makes this harder than it should be.

If you're just after a `php:5.6-cli` based composer, there are some [automated dockerhub images](https://hub.docker.com/r/composer/composer/) at https://github.com/RobLoach/docker-composer that might fit the bill.

**Comment by schmunk42** [comment]
I saw the images you mentioned, but they are only built for 5.6 and I think handling releases could be made simpler.

We could install the latest release of composer with 

    curl -sS https://getcomposer.org/installer | php -- --version=$(curl -s https://api.github.com/repos/composer/composer/releases/latest | grep -oP '"tag_name": "\K[^"]+')

Related:

 - https://github.com/composer/composer/issues/2803

**Comment by mathroc** [comment]
it would probably useful to install git at the same time

**Comment by yosifkit** [comment]
The part that makes me hesitant is that composer isn't maintained or recommended by upstream and we try to stay as close to their recommendations as possible (unless someone can point me to such a recommendation).

**Comment by Seldaek** [comment]
Composer maintainer here. I fully hear you on the frequent releases issue, and I'm working hard lately to reach a 1.0 stable which would already be easier to manage for distributions.

Do note that some distros already provide composer packages though, debian testing has it https://packages.debian.org/stretch/composer and rpms are available via http://rpms.famillecollet.com/rpmphp/zoom.php?rpm=composer who is maintaining php for redhat AFAIK, so relatively official.

Tagging https://github.com/composer/composer/issues/2803 as well so I won't forget to ping you here when a stable version is out.

**Comment by drpain** [comment]
:+1:  Yes please!

**Comment by urzds** [comment]
Related to #100?

**Comment by xabbuh** [comment]
By the way, Composer did get its first stable release in the meantime.

**Comment by mathroc** [comment]
what do you think about adding a `docker-php-composer-install` script ? ( see #260 )

**Comment by sylus** [comment]
We already have a base composer docker image @ https://github.com/RobLoach/docker-composer that is based on the php image.

Isn't this duplicating this work?

**Comment by sylus** [comment]
Just adding @Robloach if has any comments. I think the additional dependencies are to fulfill potential requirements of composer? Didn't think about the `apache` or `fpm` variants, thx ^_^

**Comment by mathroc** [comment]
https://github.com/RobLoach/docker-composer is indeed useful but I think a simple way to have composer right into library/php is best. the PR I made provides an easy way to have a basic composer installed and needed package & deps can be added as required (eg: git, ext-zip, etc.) It makes it easy to build a light image with composer installed. 

It can also be used to install composer just for build time:

```
FROM php

RUN docker-php-composer install && composer install --no-dev && rm $(which composer)
```

**Comment by schmunk42** [comment]
One thing which would be also nice, is a possibility to set an GitHub API token by an ENV variable, like so:

- https://github.com/dmstr/docker-php-yii2/blob/master/7.0/image-files/usr/local/bin/composer
- https://github.com/codemix/yii2-dockerbase/blob/master/2.0/apache/composer

(* both not perfect solutions IMHO, but composer is not really usable without GitHub tokens)

**Comment by mathroc** [comment]
@schmunk42 I'm usually mounting a volume on ~/.composer/ to deal with this, it lets composer save its token (and cache!) in a persistent location
to work with a ENV variable we would have to either add an entrypoint wrapper to the image or a wrapper to composer. I'm not sure what's the best here

**Comment by RobLoach** [comment]
Would be great to have Composer be available directly in the PHP container. It has become the defacto method for installing PHP dependencies.

> it looks like there is a bit more to those images than just installing composer

Correct, and these additions probably don't need to be brought into the PHP container. Even just bringing it in as `/usr/bin/composer` or similar would be a great benefit.

**Comment by mathroc** [comment]
running `docker-php-composer-install` brings the image from 59.55 MB to 61.19 MB. I guess that's small enough. I can add it into #260 if everyone feels the same (and the script can still be used to customize the composer installation)

**Comment by mathroc** [comment]
fwiw, there a [recent discussion](http://news.php.net/php.internals/95586) in php internals about an rfc to [Deprecate PEAR/PECL & Replace with composer/pickle](https://wiki.php.net/rfc/deprecate-pear-include-composer)
it's not yet (and maybe won't be) an official recommendation but maybe that and the [stable releases of composer](https://github.com/composer/composer/releases) will be enough to consider moving this forward ?

**Comment by sandrokeil** [comment]
It's not a good idea to install Composer, because Composer has [additional system deps](https://github.com/prooph/docker-files/blob/master/composer/7.0-cli#L16) and it exists already an [official Composer Docker image](https://hub.docker.com/r/composer/composer/).

**Comment by schmunk42** [comment]
@sandrokeil Is this really an official image from **composer**? I couldn't find anything about it in the docs.

**Comment by mathroc** [comment]
it's not an official image (but it's the most popular) and as said before, it bundles [more than just composer](https://github.com/RobLoach/docker-composer/blob/master/base/Dockerfile#L7-L40). 
another point for having composer in the same image than php: packages can add extensions in there dependencies if the extensions installed in your php image and composer image aren't the same you might have unexpected errors and/or have to install extensions in both images

**Comment by mathroc** [comment]
a reminder: the PR #260 does not install composer by default (don't know if it should), at the moment it provides a scripts to [add composer inside the image similarly to how extensions are added](https://github.com/docker-library/docs/pull/640/files?short_path=1454aff#diff-1454affb7559ca5c76c0592e68f7d54f)

**Comment by sandrokeil** [comment]
I'm not sure if it's worth it. Maybe for testing or development. Normally you would create an own base PHP Docker image for your application, where other PHP Docker images like Composer depends on (like in my example above). 

You need git and bz2 for Composer to work properly and this should not be in the PHP image, if only needed for Composer.

**Comment by mathroc** [comment]
@sandrokeil I'm not sure what you mean

I do have separate image for php-fpm and composer in development in some projects, in some other I don't (`docker-composer exec php composer` works well too) 
What makes it "normal", one of the popular image for a language I know (nodejs) and the main other I'm using (schickling/rust) also includes their package manager
@schmunk42 also mention that ruby and python are doing the same

anyway, I don't get why it would be a problem to either have a script to install it easily (or even install it by default)

> You need git and bz2 for Composer to work properly and this should not be in the PHP image, if only needed for Composer.

composer is certainly more useful with git and bz2, but they don't need to be installed by default (in #260 even composer is not installed by default). tbh I don't get why it would be a problem to install them in a php image. 
If you care about the image size and/or security issues it might bring, you can remove them just after using composer in your production images, eg:

```
FROM php:7.0-alpine

ADD src/ /app/

RUN apk add --no-cache --virtual .composer-deps git bz2 && \
    docker-php-composer-install && \
    cd /app/ && composer install --optimize-autoloader--no-dev && \
    apk del .composer-deps && \
    rm $(which composer)
```

**Comment by schmunk42** [comment]
For me, one of the most important things is, that I can `docker build` my whole application - that's what Docker is about.
With a separate container/image, I need volumes_from or on the host, which makes things much more  error prone.

**Comment by alcohol** [comment]
I would prefer to see Composer as part of the base image. I started on [composer/docker](/composer/docker), but it just seems excessive for a simple binary file.

Also, the fact that most people need a lot of extensions and what not for their plugins/etc, which they also require for their application container (which is usually derived from one of the official php images), it just makes it more convenient. No need to mess with volumes etc.

**Comment by bweston92** [comment]
That means people who don't want or need composer in there have to have it?

@schmunk42 Would you really want to build a production image with Composer inside, after building it is never going to be used again?

I agree with @sandrokeil just use your own base image and keep `php` vanilla.

**Comment by schmunk42** [comment]
> @schmunk42 Would you really want to build a production image with Composer inside, after building it is never going to be used again?

We use composer inside the `Dockerfile` to build the image, copying vendor from the host is too error-prone IMO.

**Comment by alcohol** [comment]
> We use composer inside the Dockerfile to build the image, copying vendor from the host is too error-prone IMO.

Just, but their argument (which is valid) is that you can install composer before doing so, and then remove it, all in the same Dockerfile, thus leaving no trace of its presence in the final image.

**Comment by schmunk42** [comment]
> thus leaving no trace of its presence in the final image.

Not to be picky here, but that's not correct (unless I've missed something ;)). `docker history` will show you all `CMD`s etc... ran in the build process. You should be able to create a container from a specific layer and you don't reduce your image size, when removing it in a separate setup. (Although, you could install composer and your app in one `RUN` and remove composer afterwards, but that seems a bit overoptimized to me.)

We also use composer i.e. to run `composer show` in the image for debugging, and I'd also like to use `composer` from the image as the standard way for installing/copying vendor files locally, if we would not suffer from https://github.com/docker/for-mac/issues/77

**Comment by bweston92** [comment]
@schmunk42 but not everyone needs composer especially in production.

In fact our CI runs `composer info -i` as a build step so we know what is inside that container.

We are just forwarding the application code with the artefacts gathered using composer and create an image using just the files. I just don't see why force composer in a base image.

**Comment by mathroc** [comment]
> That means people who don't want or need composer in there have to have it?
> I agree with @sandrokeil just use your own base image and keep php vanilla.

@bweston92 my proposal (see #260) composer is not installed by default, it only add [a script](https://github.com/docker-library/php/pull/260/commits/59a7bf9cd268c96362d953e867090551ff0ec126) to install it as easily as a php extension and a few tweaks (an additional env var and updated $PATH) to make working with it nicer

**Comment by schmunk42** [comment]
> I just don't see why force composer in a base image.

I'd be absolutely fine with a `php-composer-install` script, like `php-ext-install`

Another important thing would be correct API token handling.

**Comment by mathroc** [comment]
for those interested, here is a follow up on this issue being closed and _/composer added to hub.docker.com : #344
