### ISSUE TITLE
PHP7 enable sockets

### ISSUE THREAD

**Issue by DarkRide** [docker-library/php#181]
Hi , 

I would like to enable sockets on PHP to use mongofill with Yii2

https://github.com/mongofill/mongofill

But there's no documentation and no easy way to do it :(

Can you help me plz ? 

Thx

**Comment by tianon** [comment]
Something simple like this should do the trick:
```Dockerfile
FROM php:7
RUN docker-php-ext-install sockets
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with the `sockets` extension installed.

**Comment by DarkRide** [comment]
It works like a charm !

Thx

**Comment by ve3** [comment]
`docker-php-ext-install sockets` give me errors.

> /usr/src/php/ext/sockets/sendrecvmsg.c: In function 'init_ancillary_registry':
> /usr/src/php/ext/sockets/sendrecvmsg.c:128:19: error: invalid application of 'sizeof' to incomplete type 'struct cmsgcred'
>   128 |  PUT_ENTRY(sizeof(struct cmsgcred), 0, 0, from_zval_write_ucred,
>       |                   ^~~~~~
> /usr/src/php/ext/sockets/sendrecvmsg.c:99:17: note: in definition of macro 'PUT_ENTRY'
>    99 |  entry.size   = sizev; \
>       |                 ^~~~~
> /usr/src/php/ext/sockets/sendrecvmsg.c:129:36: error: 'SCM_CREDS' undeclared (first use in this function)
>   129 |    to_zval_read_ucred, SOL_SOCKET, SCM_CREDS);
>       |                                    ^~~~~~~~~
> /usr/src/php/ext/sockets/sendrecvmsg.c:105:19: note: in definition of macro 'PUT_ENTRY'
>   105 |  key.cmsg_type  = type; \
>       |                   ^~~~
> /usr/src/php/ext/sockets/sendrecvmsg.c:129:36: note: each undeclared identifier is reported only once for each function it appears in
>   129 |    to_zval_read_ucred, SOL_SOCKET, SCM_CREDS);
>       |                                    ^~~~~~~~~
> /usr/src/php/ext/sockets/sendrecvmsg.c:105:19: note: in definition of macro 'PUT_ENTRY'
>   105 |  key.cmsg_type  = type; \
>       |                   ^~~~
> make: *** [Makefile:213: sendrecvmsg.lo] Error 1

**Comment by nataaliam** [comment]
> `docker-php-ext-install sockets` give me errors.
> 
> > /usr/src/php/ext/sockets/sendrecvmsg.c: In function 'init_ancillary_registry':
> > /usr/src/php/ext/sockets/sendrecvmsg.c:128:19: error: invalid application of 'sizeof' to incomplete type 'struct cmsgcred'
> > 128 |  PUT_ENTRY(sizeof(struct cmsgcred), 0, 0, from_zval_write_ucred,
> > |                   ^~~~~~
> > /usr/src/php/ext/sockets/sendrecvmsg.c:99:17: note: in definition of macro 'PUT_ENTRY'
> > 99 |  entry.size   = sizev; 
> > |                 ^~~~~
> > /usr/src/php/ext/sockets/sendrecvmsg.c:129:36: error: 'SCM_CREDS' undeclared (first use in this function)
> > 129 |    to_zval_read_ucred, SOL_SOCKET, SCM_CREDS);
> > |                                    ^~~~~~~~~
> > /usr/src/php/ext/sockets/sendrecvmsg.c:105:19: note: in definition of macro 'PUT_ENTRY'
> > 105 |  key.cmsg_type  = type; 
> > |                   ^~~~
> > /usr/src/php/ext/sockets/sendrecvmsg.c:129:36: note: each undeclared identifier is reported only once for each function it appears in
> > 129 |    to_zval_read_ucred, SOL_SOCKET, SCM_CREDS);
> > |                                    ^~~~~~~~~
> > /usr/src/php/ext/sockets/sendrecvmsg.c:105:19: note: in definition of macro 'PUT_ENTRY'
> > 105 |  key.cmsg_type  = type; 
> > |                   ^~~~
> > make: *** [Makefile:213: sendrecvmsg.lo] Error 1
> 
> PHP 8.1.2 x64

Same here

**Comment by matriphe** [comment]
I also got exactly same issue. PHP 8.1.2 as well.

**Comment by matriphe** [comment]
installing on `php:8.1.1-cli-alpine` works.

**Comment by carestad** [comment]
Yep. This started happening in the 8.1.2 images
