### ISSUE TITLE
Error installing mailcatcher

### ISSUE THREAD

**Issue by Magarusu** [docker-library/php#185]
Hello,

I am trying to install mailcatcher under my php 5.4 dockerfile by using

RUN apt-get update && apt-get install -y ruby ruby-dev build-essential sqlite3 libsqlite3-dev

RUN gem install mailcatcher --no-ri --no-rdoc

but I receive the following error:
ERROR:  Error installing mailcatcher:
	activesupport requires Ruby version >= 2.2.2.

Is there any way I can install mailcatcher in this docker?

Thanks.

**Comment by kbemelmans** [comment]
The proper way to do that would be making a new container for mailcatcher and then linking it to the PHP container. Remember the docker principe: 1 process for 1 container.

**Comment by tianon** [comment]
If you absolutely must have `mailcatcher` inside the PHP image, you'll need to find a way to get a newer version of Ruby (or possibly an older version of `mailcatcher` -- I don't know much about it and am simply guessing based on the error message you received while trying to install it).
