### ISSUE TITLE
Container won't start twice: "httpd (pid 13) already running"

### ISSUE THREAD

**Issue by conradkleinespel** [docker-library/php#187]
Hello,

Thanks for setting up this image. It's saving me a ton of time :+1: 

It seems like if you run `php:5.6-apache` through Docker Compose, it will run fine the first time, but not the second time, because it seems to be keeping a reference to the previous process ID.

This have discussed here previously (in 2014): https://groups.google.com/forum/#!topic/docker-user/2dP09wrq5Qk

Is there any specific reason for this? Would you be OK with a PR that removes the left over PID before exiting, as shown in the link above.

Best regards,
Conrad

**Comment by tianon** [comment]
https://github.com/docker-library/php/blob/bdfd0fc1d19102cd6f951614072a51eabf7191bf/5.6/apache/apache2-foreground
should already be doing this -- have you done a "docker-compose pull" to
make sure you've got the latest image?

**Comment by chrissound** [comment]
I'm running into this issue on the `5.6.3-apache` tag.

**Comment by tianon** [comment]
Can you please try again with `5.6-apache`? (`5.6.30` is the latest, but intermediate or old point releases are not supported -- only the latest is)

**Comment by chrissound** [comment]
If they're not supported can we mention this on the readme / docker page?

**Comment by yosifkit** [comment]
@chrissound, something other than this?

# Supported tags and respective `Dockerfile` links

-	[`7.1.5-cli`, `7.1-cli`, `7-cli`, `cli`, `7.1.5`, `7.1`, `7`, `latest` (*7.1/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/Dockerfile)
-	[`7.1.5-alpine`, `7.1-alpine`, `7-alpine`, `alpine` (*7.1/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/alpine/Dockerfile)
-	[`7.1.5-apache`, `7.1-apache`, `7-apache`, `apache` (*7.1/apache/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/apache/Dockerfile)
-	[`7.1.5-fpm`, `7.1-fpm`, `7-fpm`, `fpm` (*7.1/fpm/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/fpm/Dockerfile)
-	[`7.1.5-fpm-alpine`, `7.1-fpm-alpine`, `7-fpm-alpine`, `fpm-alpine` (*7.1/fpm/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/fpm/alpine/Dockerfile)
-	[`7.1.5-zts`, `7.1-zts`, `7-zts`, `zts` (*7.1/zts/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/zts/Dockerfile)
-	[`7.1.5-zts-alpine`, `7.1-zts-alpine`, `7-zts-alpine`, `zts-alpine` (*7.1/zts/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/7.1/zts/alpine/Dockerfile)
-	[`7.0.20-cli`, `7.0-cli`, `7.0.20`, `7.0` (*7.0/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/Dockerfile)
-	[`7.0.20-alpine`, `7.0-alpine` (*7.0/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/alpine/Dockerfile)
-	[`7.0.20-apache`, `7.0-apache` (*7.0/apache/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/apache/Dockerfile)
-	[`7.0.20-fpm`, `7.0-fpm` (*7.0/fpm/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/fpm/Dockerfile)
-	[`7.0.20-fpm-alpine`, `7.0-fpm-alpine` (*7.0/fpm/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/fpm/alpine/Dockerfile)
-	[`7.0.20-zts`, `7.0-zts` (*7.0/zts/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/zts/Dockerfile)
-	[`7.0.20-zts-alpine`, `7.0-zts-alpine` (*7.0/zts/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/66a746410bf607ce9b41046e2b42a619fc71d272/7.0/zts/alpine/Dockerfile)
-	[`5.6.30-cli`, `5.6-cli`, `5-cli`, `5.6.30`, `5.6`, `5` (*5.6/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/Dockerfile)
-	[`5.6.30-alpine`, `5.6-alpine`, `5-alpine` (*5.6/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/alpine/Dockerfile)
-	[`5.6.30-apache`, `5.6-apache`, `5-apache` (*5.6/apache/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/apache/Dockerfile)
-	[`5.6.30-fpm`, `5.6-fpm`, `5-fpm` (*5.6/fpm/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/fpm/Dockerfile)
-	[`5.6.30-fpm-alpine`, `5.6-fpm-alpine`, `5-fpm-alpine` (*5.6/fpm/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/fpm/alpine/Dockerfile)
-	[`5.6.30-zts`, `5.6-zts`, `5-zts` (*5.6/zts/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/zts/Dockerfile)
-	[`5.6.30-zts-alpine`, `5.6-zts-alpine`, `5-zts-alpine` (*5.6/zts/alpine/Dockerfile*)](https://github.com/docker-library/php/blob/c48c629568bc166b58b271114d0b44ea6d5cfa09/5.6/zts/alpine/Dockerfile)

**Comment by tianon** [comment]
The description includes a section of "Supported tags" right at the top. 😉

**Comment by chrissound** [comment]
Oh I see, it's `5.6.30-apache` and not `5.6.3-apache`, right?

**Comment by tianon** [comment]
Correct, but "5.6-apache" will track the latest PHP 5.6 release without you
having to update at each point release to stay supported (until the EOL of
PHP 5.6).

**Comment by anjarasoa** [comment]
docker
