### ISSUE TITLE
phpdbg

### ISSUE THREAD

**Issue by dmp1ce** [docker-library/php#191]
It would be great if a PHP image with phpdbg was available. I use fpm locally to develop websites but time to time it would be nice to be able to build with phpdbg enabled and installed so that a request could be ran through a debugger.

The only way I know of using this image to debug with phpdbg is to fork the project or reinstall PHP in my Dockerfile.

**Comment by hairmare** [comment]
According to https://github.com/docker-library/php/pull/151#issuecomment-170241618 it should be installed by default on php 7. I'm not sure if it's in the fpm image though it seems to be in the cli image.

**Comment by dmp1ce** [comment]
@hairmare I didn't know that. Thank you.
