### ISSUE TITLE
pecl/pear requires mbstring

### ISSUE THREAD

**Issue by billiam13s** [docker-library/php#195]
I installed mbstring in docker `docker-php-ext-install mbstring` and then trying to install mailparse `pecl install mailparse-2.1.6`. pecl result in `pecl/mailparse requires PHP extension "mbstring"`. After grep mbstring from php -i, it does display mbstring result. Anyone know how to enable pecl or pear to load mbstring?

Thanks

**Comment by booyaa** [comment]
if you've got a custom dockerfile you could add `RUN docker-php-ext-install mbstring`, quick and dirty way is to do an `docker exec -it name_of_your_container docker-php-ext-install mbstring`

**Comment by billiam13s** [comment]
mbstring is installed, but pear or pecl think mbstring is missing when installing mailparse.

**Comment by booyaa** [comment]
when do you call pecl? can you share your dockerfile or docker commands?

**Comment by billiam13s** [comment]
```
FROM php:5.6

RUN docker-php-ext-install mbstring

RUN pecl install mailparse-2.1.6

```
will result

```
Step 3 : RUN pecl install mailparse-2.1.6
 ---> Running in ff88e4f6e582
pecl/mailparse requires PHP extension "mbstring"
No valid packages found
install failed
```

I tried on PHP7, 5.6, 5.5. All of their version of `pecl` does NOT have mbstring extension enable, while grep from  php -i `php -i | grep mbstring` do exists.

**Comment by tianon** [comment]
Ouch, I found a clue in http://www.cerberusweb.com/forums/thread-25.html:

> use
> 
> pear install pecl/mailparse
> 
> The difference between the "pear" and "pecl" commands is that "pecl" disables php.ini so that you can overwrite extension .so or .dll files that would otherwise be in use and locked for write. So, unless mbstring is built into PHP (not a loaded module in php.ini), you won't be able to install mailparse.

Now, I can't get that first command to work, but it does seem plausible that `mbstring` has to be built into PHP for this to work, so this might be a decent justification for doing so.

**Comment by tianon** [comment]
(which would also relate to / close #34)

**Comment by billiam13s** [comment]
I read about issue #34. It would be nice to have mbstring enable by default. 

I tried `pear install pecl/mailparse-2.1.6` and `pecl install mailparse-2.1.6`. pear will run for try to install then will fail due to mbstring is missing. pecl will fail right away. I hope #34 will solve this problem, meanwhile are there any workaround solution can be use?

This is just the beginning of my setup, without mailparse I can't run composer install.

Thanks,

**Comment by lubobill1990** [comment]
+1

**Comment by L0rD59** [comment]
Hi i've same problem as describe here : https://bugs.php.net/bug.php?id=71181

**Comment by bizmate** [comment]
mbstring is also not enabled on php:5-fpm for some reason and since this can only be enabled at install time there is not way to add it unless you build your own container from scratch.

**Comment by tianon** [comment]
It can be enabled _generally_ post-install, but `pecl` explicitly ignores the configuration which allows for that.  I'll make a PR shortly to include support for it by default.

**Comment by L0rD59** [comment]
Containeur are already rebuild in dockerhub repository ? Because the probleme are still present : 

```
docker pull php:5.6-cli

docker run --rm -it php:5.6-cli bash

pecl install mailparse-2.1.6
pecl/mailparse requires PHP extension "mbstring"
No valid packages found
install failed

```

**Comment by billiam13s** [comment]
I guess they haven't have time to publish the tags at dockerhub yet. Last push was 13 days ago. https://hub.docker.com/r/library/php/tags/

**Comment by tianon** [comment]
https://github.com/docker-library/php/blob/master/README.md has a little blurb about what the process is from here:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/php" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/php), especially [PRs with the "library/php" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fphp). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We'll likely make the bump PR over there later today unless someone wants to clone and run `./generate-stackbrew-library.sh` and beat us to it before then. :+1:
