### ISSUE TITLE
Issues with 5.6

### ISSUE THREAD

**Issue by mgan59** [docker-library/php#197]
When trying to build the image

`php/5.6$ docker build .`

```
Sending build context to Docker daemon 43.01 kB
Step 1 : FROM debian:jessie
 ---> 256adf7015ca
Step 2 : RUN apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*
 ---> Running in 56e0bf3cae2b
Err http://security.debian.org jessie/updates InRelease

Err http://httpredir.debian.org jessie InRelease

Err http://httpredir.debian.org jessie-updates InRelease

Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Reading package lists...
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package libxml2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package ca-certificates
E: Unable to locate package curl
E: Unable to locate package librecode0
E: Unable to locate package libsqlite3-0
E: Package 'libxml2' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by tianon** [comment]
`Could not resolve 'security.debian.org'` sounds like an issue with your local DNS -- does DNS work outside containers on the host in question?  If so, have you restarted the Docker daemon recently so that it'll pick up any updates to `resolv.conf`?

On top of that, I'm curious why you're attempting to build from the `Dockerfile` instead of just using `FROM php:5.6` -- any particular use case we're not covering already?

**Comment by mgan59** [comment]
:+1: yeah ran `docker-machine restart` on the virtual machine did the trick.

So was trying to build a wordpress container that enables a few php compilation flags.  I was having a problem with `FROM php:5.6` which I'd try and call `docker-php-ext-enable json` and get errors saying `docker-php-ext-enable` couldn't be found.  I was looking at this `Dockerfile` and saw the `COPY` command.  So I attached to my built container and could find those commands... so my thought was just to use this dockerfile's php compile step and add in my additional logic.  :|  Maybe I did something wrong though, spent quite abit of time banging my head on Docker and it all is starting to blend together.  

Thanks @tianon  for the heads up about restarting my `docker-machine` in the event the network connection gets messed up.  Feel free to close as fixed.  Cheers!

**Comment by tianon** [comment]
Hmm, are the flags you want available as modules that could be added via our `docker-php-ext-install` script like we do for `gd` and friends in the `Dockerfile` for `wordpress` itself?

**Comment by mgan59** [comment]
So based on the docs I've read `enable json` is bundled with PHP so it is a matter of just enabling it.

I added

```
RUN docker-php-ext-enable json
```

**ERROR when I build**

```
Step 4 : RUN docker-php-ext-enable json
 ---> Running in b64358153725
error: /usr/local/lib/php/extensions/no-debug-non-zts-20131226/json does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
opcache.so
```

For now, I edited the php/5.6 and added 

```
--enable-json \ 
```

inside of the `php config` to compile.  This did fix my json issue, but now my wordpress installation is complaining about MySQL :|

**Comment by tianon** [comment]
Hmm JSON should already be built-in and enabled:
```console
$ docker run -it --rm php:5.6 bash
root@1979a4b377b3:/# php -i | grep json
json
json support => enabled
json version => 1.2.1
proto_binary_fetched_json => 0
```

**Comment by mgan59** [comment]
@tianon Kept at it.  So in the end, had some confusion around my `docker-compose.yml` in the way I set the build so my changes weren't propagating.  Which solved part of my mystery.  In the end, I learned quite abit about building/tagging images and workflows with docker.  Regardless, I have everything working now using

```
FROM php:5-fpm
RUN apt-get update && apt-get install -y \
        php5-mysql \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install mysql
```

Thanks for all your help!  :star:

**Comment by Stephen-daughter-in-law** [comment]
@tianon https://stackdev.space/questions/what-is-the-best-method-to-extract-data-from-a-curl-request-in-a-wordpress-website
