### ISSUE TITLE
Building with a new cURL version?

### ISSUE THREAD

**Issue by marklocker** [docker-library/php#198]
Does anyone know the best way to get this image working with an upgraded version of cURL? As per [this question on ServerFault](http://serverfault.com/questions/757553/updated-curl-not-taking-effect-in-php).

I have a requirement to make HTTP/2 requests from within a PHP 7 app, something which isn't supported out of the box with this image because of the older version of cURL it's compiled with.

Any help from those with knowledge in this area would be massively appreciated!

**Comment by urzds** [comment]
Have you tried the Alpine variant of the image? They currently package 7.48.0 [^1], which is not even a month old.

[^1]: https://pkgs.alpinelinux.org/package/main/x86_64/curl

**Comment by joserobleda** [comment]
Same issue here, I'm trying to build the image the latest cURL.

Would you accept a PR installing it?

**Comment by geerlingguy** [comment]
I tried getting a newer version of curl on any of the PHP 5.6, 7.0, or 7.1 images, but since they all build off of Debian Jessie, and the curl version there is locked in at 7.38, it seems you have to recompile PHP to get the newer curl version supported.

Here's how I was building it (didn't work):

```
FROM php:5.6-apache

# Install custom/newer version of curl from source.
RUN apt-get update \
    && apt-get install -y libssl-dev wget \
    && apt-get purge --auto-remove -y curl libcurl3 \
    && wget https://curl.haxx.se/download/curl-7.49.1.tar.gz \
    && tar -xzf curl-7.49.1.tar.gz \
    && cd curl-7.49.1 \
    && ./configure --with-ssl --prefix=/usr \
    && make && make install \
    && ldconfig \
    && cd .. && rm -rf curl-7.49.1 \
    && rm -rf /var/lib/apt/lists/*
```

`docker-php-ext-install curl` didn't help either. Since curl is one of the extensions compiled in, I couldn't get it to work without some cryptic error messages :(

**Comment by geerlingguy** [comment]
@marklocker - Also note that it looks like the 7.2 branch of this image builds off of Debian Stretch (the others all build on Jessie); so 7.2+ should have a more modern version of cURL.

**Comment by geerlingguy** [comment]
If you want to maintain a forked copy of this repo and build the base containers yourself, you can update the `curl` version like so:

https://github.com/geerlingguy/docker-library-php/pull/1/files

It would be nice if there were an easier way to do this building _on top of_ the PHP library container. Maybe one way would be to drop all the `curl` configuration from the base image entirely... I mean, opcache isn't installed by default either :)

**Comment by tianon** [comment]
I think Stretch (and thus https://github.com/docker-library/php/issues/504) is the appropriate solution to this issue, so I'm going to close in favor of https://github.com/docker-library/php/issues/504. :+1: :heart:
