### ISSUE TITLE
Alpine image is huge

### ISSUE THREAD

**Issue by mbrevda** [docker-library/php#208]
The alpine based image, merged in #176, is about 28% smaller than the original, which is good. An image built using the alpine package manager is **96% smaller** than the original! Accordingly, and as per @ncopa (who wrote the pr for alpine), [there is still some work to be done](https://github.com/docker-library/php/pull/176#issuecomment-199242813) that can bring the image size down.

```
php                   alpine              e40e7aabdb36        17 hours ago        376.5 MB
php                   latest              8c8eb06f7c64        17 hours ago        483.8 MB
frolvlad/alpine-php   latest              9eda42b8cf2e        2 weeks ago         18.22 MB
```

**Comment by ncopa** [comment]
see #206

**Comment by mbrevda** [comment]
Tracked in #206, thanks!
