### ISSUE TITLE
Include a docker-php-ext-disable

### ISSUE THREAD

**Issue by kmfk** [docker-library/php#220]
I saw that there is no disable script here - ideally, it'd be great to replicate both `php5enmod` and `php5dismod` functionality.

I created a disable script based on `docker-php-ext-enable` and am copying it in my build.  The script just looks for the existence of the extension ini file and removes it - but not sure if there is a more ideal way to handle this?  Willing to PR it, if there's any interest.

The use case for me was to be able to enable or disable xdebug on the fly when running PHPUnit:

`docker exec -ti php sh -c "docker-php-ext-disable xdebug && vendor/bin/phpunit`

**Comment by isp0000** [comment]
@kmfk why not add your script as pull request?

**Comment by tianon** [comment]
I'm honestly a little -1 on adding this.  Enabling an extension in a generic way is simple (requires getting `extension=xxx.so` into the PHP configuration somewhere).  Disabling in a fully generic way is not nearly as simple, so I would actually recommend using `--ini-name` (from https://github.com/docker-library/php/pull/178) to accomplish this more easily.

**Comment by shouze** [comment]
Yes, furthermore there's no good reason to disable an extension in fact. If you use the same container for tests/dev & production (which is pretty cool), you can imagine running php differently depending on your environment.

It's easier for example to run php `php -d 'extension=xdebug.so' myscript.php` when developing your app then running just `php myscript.php` in production.

**Comment by kodeart** [comment]
+1 It is useful if you create your own images for dev/prod. If dev extends the production image, it's great to disable something from production, i.e.

```
# in dev Dockerfile
FROM my-production-image
RUN docker-php-ext-disable opcache
```

**Comment by shouze** [comment]
@kodeart yes... but why not producing a dedicated image for dev and another one for prod? Very easy with automated builds & tags.

**Comment by pproenca** [comment]
@kmfk @tianon  I've opened a pull request which introduces `docker-php-ext-disable` in #270

**Comment by tianon** [comment]
Given that https://github.com/docker-library/php/pull/178 added `--ini-name` for explicitly controlling the exact filename `docker-php-ext-enable` creates (and that the filenames it uses are already trivially deterministic), I'm going to close this with the recommendation that users who need to disable extensions after previously enabling them simply use `rm` on the appropriate file (or `sed`, if they've added additional configuration to the file since enabling the extension).  Thanks!

**Comment by ponthilagan** [comment]
HI,

Use the following line to disable the ext opcahce
`    docker-php-ext-configure opcache --disable-opcache; 
`

**Comment by timnolte** [comment]
Something of note where people may want to specifically disabled xdebug you can set the environment variable `XDEBUG_MODE=off` and that will turn off xdebug on-the-fly. This was my primary purposed for investigating a `docker-php-ext-disable` method.

**Comment by LaurentGoderre** [comment]
Thanks for sharing this!

**Comment by jonpontet** [comment]
> Something of note where people may want to specifically disabled xdebug you can set the environment variable `XDEBUG_MODE=off` and that will turn off xdebug on-the-fly. This was my primary purposed for investigating a `docker-php-ext-disable` method.

Or `xdebug.mode=off` 
[Reference](https://xdebug.org/docs/all_settings#mode)

**Comment by fruitl00p** [comment]
Just to chime in here on an old comment...  @tianon 

I'm looking for a way to enable / disable an extension after it was already configured / installed etc. It's common to enable/disable xdebug quickly for an image and we currently handle this by utilizing docker-php-ext-enable xdebug vs rm "/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"; but this feels clunky having to download the APK everytime. I'd like to keep the actual module after installation but add / delete the .ini only. That would allow far easier on/offline working and keep the xdebug (enabled / disabled) features.

I know i'm almost there, but having the docker-php-ext-enable xdebug conditionally check if the .SO is already there before downloading would suffice for my usecase. Any chance this might be something you'd consider?

**Comment by tianon** [comment]
I think instead of using `docker-php-ext-enable` for the "toggling" use case, you might instead rename the file with a `.disabled` suffix (ie, rename back and forth instead of deleting and recreating).

**Comment by cha0s** [comment]
10 years later and the solution is...?

Why not "close" what you "open"? Your API is broken and this is a bug.
