### ISSUE TITLE
Is the php alpine image's size correct?

### ISSUE THREAD

**Issue by SydOps** [docker-library/php#223]
php                      7.0.5-alpine        37c5280b6fc1        2 weeks ago         382.7 MB
    php                      7.0.5               c47a0064b207        2 weeks ago         489.6 MB

**Comment by SydOps** [comment]
seems install the tools, such as `gcc` in different layers, and can't delete them to reduce the image size.

**Comment by yosifkit** [comment]
Yeah, we kept them around so that `docker-php-ext-install` would work.  Now there is a PR to remove them: #206.

**Comment by andypost** [comment]
Already fixed
```
php                 7-alpine            b68317823092        2 weeks ago         56.39 MB
```

**Comment by dzubchik** [comment]
@SydOps , maybe this issue should be closed now?

**Comment by SydOps** [comment]
Yes, thanks
