### ISSUE TITLE
Cannot use ftp_ssl_connect() with this docker image

### ISSUE THREAD

**Issue by hobbysoldat** [docker-library/php#236]
Hi! In my project we need FTP client support, so I added the ftp extension: 

`RUN docker-php-ext-install ftp` 

This adds the basic FTP Constants and some of the functions.

The problem is that to use some ftp functions (e.g. ftp_ssl_connect() ), the ftp extension needs to be [statically build into php](http://php.net/manual/en/function.ftp-ssl-connect.php). Can I still use this Image or do I have to create my own Docker Image with --enable-ftp activated? http://php.net/manual/en/ftp.installation.php

**Comment by yosifkit** [comment]
I guess this means we need to add `enable-ftp` to the configure like `mysqlnd` and `mbstring`. :cry:

> `ftp_ssl_connect()` is only available if both the ftp module and the OpenSSL support is built statically into php

**Comment by hobbysoldat** [comment]
Yep, I just tried adding this to my setup manually and adding the --enable-ftp configure flag solves the issue. Seems like I have to use my own image for now until you guys can get this fixed. I could do a pull request if that is helpful.

**Comment by patrickomeara** [comment]
I'm hitting this issue as well.

I tried adding `--enable-ftp` to the configure but still didn't get `ftp_ssl_connect()` @hobbysoldat can you create a PR or share what changes you made to get it working?
