### ISSUE TITLE
PHP5.6-FPM - php.ini

### ISSUE THREAD

**Issue by synolog75** [docker-library/php#238]
Hi,

How can i change value in php.ini on docker 5.6.22-fpm ?
I would like change default charset value but I do not find that file in docker (only php-fpm.conf or www.conf)
Have you an idea to set this ?

Thanks.
Charlie

**Comment by yosifkit** [comment]
If it is a configuration within a `php.ini` file you could add or edit one of the files within `/usr/local/etc/php-fpm.d/` and it would be applied.

**Comment by synolog75** [comment]
Hi,

Thanks for your help.
I added that in Dockerfile : `RUN     echo "default_charset = \"\";" > /usr/local/etc/php/conf.d/php.ini`
So right now new charset is available.

:-)
