### ISSUE TITLE
Can't install any extension on Windows

### ISSUE THREAD

**Issue by KravetsAndriy** [docker-library/php#252]
Hey guys.I stucked with problem, when I'm copy-pasting whole original Dockerfile of 5.5.37-apache to my Dockerfile and just adding one line:
_docker-php-ext-install mysql_ (for example)
and getting error the follow error:
_/bin/sh: 1: docker-php-ext-install: Permission denied_
I want to clarify that I need custom fields during the compiling of PHP. When I'm using already builded container it works fine. I have already took permissions for this file, tried to check if its correct, moved to differend groups,etc.The interest thing that it works fine on my Docker for Mac, but the same project doesn't work on Docker for Windows. Maybe it could be related to the file permissions on Windows, etc. So I think that its my problem 100%, but I can't find out where is a problem. If someone stucked with this kind of problem, I will be glad for any help. Cheers!

**Comment by christianbundy** [comment]
Try adding this to your Dockerfile:

```
RUN chmod +x /usr/local/bin/docker-php-ext-*
```

I'm guessing the file permissions are being lost on the Windows filesystem, so you'll most likely need to set them in the container itself.

**Comment by tianon** [comment]
If the repository is cloned locally, Git will appropriately track and apply `+x` to the local copies of these scripts.  For building on Windows, you should be getting https://github.com/moby/moby/pull/11148, which will automatically apply `+x` to all `COPY`'d files anyhow.

Regardless, I'd recommend instead simply consuming the pre-built images as-is, and adding your additional bits separately, ala:
```dockerfile
FROM php:5-apache
RUN docker-php-ext-install mysql
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with your additional extensions installed.
