### ISSUE TITLE
apache2.conf AllowOverride config change

### ISSUE THREAD

**Issue by misterbisson** [docker-library/php#254]
https://github.com/docker-library/php/pull/251 removed the `apache2.conf` file for the 5.5-apache and 5.6-apache. This changed the following Directory stanza from the following...

```xml
<Directory /var/www/>
        AllowOverride All
        Require all granted
</Directory>
```

To...

```xml
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```

This led to some surprises in behavior, and a lot of 404s.

**Comment by tianon** [comment]
Thanks for filing the issue! :+1:

Working on a fix now!
