### ISSUE TITLE
Any way to install extensions after the container is running?

### ISSUE THREAD

**Issue by anatoniewski** [docker-library/php#257]
I am trying to use php:fpm image on AWS Beanstalk in parallel with nginx, and I need to load more extensions, and I would like to do so after the container is running. Is this possible? Hoping I am missing something as I've been toying with this for about 6 or so hours...

**Comment by yosifkit** [comment]
You can do things like `docker exec` but then you would have to restart the container for it to read any updated `php.ini` files and load the modules.  You should also be able to make a simple Dockerfile:
```dockerfile
FROM php:7-fpm
RUN docker-php-ext-install [modules] ...
COPY custom-php.ini /usr/local/etc/php/conf.d/
```

**Comment by anatoniewski** [comment]
I was able to convince it to reload the newly installed extensions with the following command:
docker kill --signal="USR2" {Container ID}
