### ISSUE TITLE
Add redis to installable extensions

### ISSUE THREAD

**Issue by wernight** [docker-library/php#263]
Related to #262, I often want to install the very popular Redis client for PHP. This isn't trivial on Alpine Linux. If you could please support it, it'd help greatly.

**Comment by wernight** [comment]
Steps:

    $ apk add --update --no-cache autoconf g++
    $ pecl install redis
    $ docker-php-ext-enable redis

**Comment by shouze** [comment]
Hi @wernight redis is not shipped within php source code so, you should just follow explained steps in https://github.com/docker-library/php/issues/262#issuecomment-233108680.

**Comment by wernight** [comment]
Could there be a place for people to include ways to install common extensions, or some `docker-php-ext-install` run a script that does the install?

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/75#issuecomment-353673374, which describes how I determine what's necessary to install extensions (and really compiled software in general).

Given that `redis` is not a built-in extension (as noted above), there's nothing for us to do here.  Installing `redis` from PECL _is_ the appropriate solution. :+1:

**Comment by vladkras** [comment]
`apk add --update --no-cache autoconf g++ make`
adds extra 200Mb to 179Mb alpine package so I prefere to use
```
ENV REDIS_VERSION 4.0.2

RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$REDIS_VERSION.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-* /usr/src/php/ext/redis

RUN docker-php-ext-install redis
```
inspired by #77

**Comment by kilvn** [comment]
it's ok.
```
printf "\n" | curl 'http://pecl.php.net/get/redis-4.3.0.tgz' -o redis-4.3.0.tgz \
      && pecl install redis-4.3.0.tgz \
      && rm -rf -- redis-4.3.0.tgz \
      && rm -rf /tmp/pear \
      && docker-php-ext-enable redis
```
