### ISSUE TITLE
How to update pdo-mysql on php56-apache ?

### ISSUE THREAD

**Issue by SiberianCMS** [docker-library/php#267]
Hello,

It looks like it is build with php.

The version of php-mysql is 5.0 but I need at least version 5.5. How it is possible ?

Thanks

**Comment by madalinignisca** [comment]
I would recommend you to use php-mysqlnd as you won't depend on mysql dev libraries and you can use some extra nice things that some of us use.

**Comment by SiberianCMS** [comment]
Looks like Zend Framework 1.12 has no Mysqlnd adapter :(

**Comment by madalinignisca** [comment]
You said above for php-mysql. Php-mysqlnd is a dropon replacemwnt for that. With it you'll have pdo-mysql as well.

Based on your last comment I guess yoi have not even tried.

I guarantee it's working, with zf-1.12

**Comment by tianon** [comment]
This appears to be both about an older version of the PHP image and solved, so I'm going to close. :+1: :heart:
