### ISSUE TITLE
PHP 7.0.9 is not available on dockerhub

### ISSUE THREAD

**Issue by pravindahal** [docker-library/php#273]
Is it because of the travis build failing?

The build is failing because [PHP did not publish PGP signature files for PHP 5.5.38](https://bugs.php.net/bug.php?id=72690).

This is potentially also related to [this bug](https://github.com/docker-library/php/issues/242).

**Comment by yosifkit** [comment]
Yeah, we are still waiting on the asc file for 5.5: https://github.com/docker-library/official-images/pull/1974.

**Comment by pravindahal** [comment]
The asc is available now.
