### ISSUE TITLE
Zend Opcache not available (--enable-opcache)

### ISSUE THREAD

**Issue by n0v3xx** [docker-library/php#276]
Hi,

why is the Zend Opcache not available in the PHP 7 containers?!

Please enable it per default "--enable-opcache"
http://php.net/manual/en/opcache.installation.php

best regards

**Comment by yosifkit** [comment]
I think that one can just be installed with the handy `docker-php-ext-install` script:
```
FROM php:7
RUN docker-php-ext-install opcache
```

**Comment by n0v3xx** [comment]
Thanks it works :)
