### ISSUE TITLE
Add README and CONTRIBUTING

### ISSUE THREAD

**Issue by thaJeztah** [docker-library/php#30]
When working on a PR for #28, I notice that the README that is used on the registry (https://registry.hub.docker.com/_/php/) is not included in the repository.

Reading the [Guidelines for Creating and Documenting Official Repositories](https://docs.docker.com/docker-hub/official_repos/) the following files are missing;

- `README-short.txt`
- `logo.png`
- `README.md`

And while at it, perhaps a `CONTRIBUTING.md`

On a final note, the current description of the repository only refers to the php.net website ("Docker Official Image packaging for PHP https://php.net").

Perhaps a link to the registry could be added for convenience?

**Comment by yosifkit** [comment]
@thaJeztah, think we can close this?  There is a README now and info about contributing is on the linked docs.  Do we still need a `contributing.md` in all the repos?

**Comment by thaJeztah** [comment]
Yes, let's close this: a contributing.md is only cherry on the cake :-)
