### ISSUE TITLE
Cronjob is not working ?

### ISSUE THREAD

**Issue by windsdeng** [docker-library/php#301]

**Comment by yosifkit** [comment]
You added something to `/etc/cron` in the image?  Containers only run a single process; in this case `php` or `apache`, so there is no cron daemon running.  You will need to setup your own daemon to get cron working. You could start a second container that runs cron and shares any folders from the `php` container that it needs. Or you could share the cron to the docker host and have it's cron take care of it.  Or make a cron task on the host that does a docker exec into the php container and runs what you need.

**Comment by windsdeng** [comment]
Thank you!

**Comment by svinohod** [comment]
Docker Containers can run multiple services in a container, see https://docs.docker.com/config/containers/multi-service_container/
