### ISSUE TITLE
Use dumb-init to fix PHP-FPM PID 1 issues

### ISSUE THREAD

**Issue by wernight** [docker-library/php#303]
PHP-FPM probably spawns processes. Unless it reaps processes in all cases, it'd be useful to use [dumb-init](https://github.com/Yelp/dumb-init) to fix those issues. It's meant for Docker and works also on Alpine.

Just need 2 lines to add it, then change entrypoint from:

    ENTRYPOINT ["/entrypoint.sh"]

to:

    ENTRYPOINT ["dumb-init", "/entrypoint.sh"]

**Comment by yosifkit** [comment]
This is unneeded; PHP fpm is designed to properly reap its children: [php source fpm_children.c](https://github.com/php/php-src/blob/1c295d4a9ac78fcc2f77d6695987598bb7abcb83/sapi/fpm/fpm/fpm_children.c#L177).

**Comment by wernight** [comment]
Thanks 👍
