### ISSUE TITLE
docker-php-ext-enable gd - cannot create directory

### ISSUE THREAD

**Issue by itshaadi** [docker-library/php#304]
when i tried to install GD extension using  `docker-php-ext-install gd` command
the process stopped because `docker-php-ext-enable gd` couldn't create ini file in the following directory
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini
so after a while i used docker exec command to log into the running container and make that directory.
after that everything was fine.

here is my dockerfile

```
FROM php:5.6.25-apache
RUN apt-get update && \
    apt-get install -y libfreetype6-dev libjpeg62-turbo-dev && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/  &&  \
    docker-php-ext-install gd
```

so is it a bug or i did something wrong ? should i run `docker-compose build` as root ?

**Comment by yosifkit** [comment]
I am unable to replicate here on `php:5.6.26`, though I see no difference in the two versions that would cause this issue.

You shouldn't need to run as root to do docker commands as long as you are in the docker group.

Have you tried deleting you images and pulling again?

**Comment by iazami** [comment]
i just got this image and i didn't make any changes. so i don't think pulling again would be helpful.

**Comment by hamdrew** [comment]
I ran into this once on a container that had been around for awhile. I restarted the container and it worked again. Docker is an incredible piece of software, but sometimes I think it can get into "weird" states, especially after several cycles of sleep/wake/network changes/etc.

**Comment by tianon** [comment]
Indeed, I've seen many reports of images getting corrupted, and a remove / re-pull (or re-build) being required to fix them.

Since we are unable to reproduce (and the `wordpress` official image, among others, successfully includes and compiles `gd` on all supported PHP versions), I'm going to close.  Thanks!

**Comment by lifetoss** [comment]
> This work fine: https://github.com/dynamic/silverstripe-docker/blob/master/Dockerfile

Thank you bro
