### ISSUE TITLE
Get the latest ICU version (got libicu 52.1 instead of 57.1)

### ISSUE THREAD

**Issue by romqin** [docker-library/php#307]
My Dockerfile:
```
FROM php:7.0-fpm

RUN apt-get update && \
    apt-get install -y libicu-dev && \
    docker-php-ext-install intl
```

When I run the [symfony requirements](https://github.com/symfony/symfony-standard/blob/master/bin/symfony_requirements) binary, I got this message:
```
 * intl ICU version installed on your system is outdated (52.1) and
   does not match the ICU data bundled with Symfony (57.1)
   > To get the latest internationalization data upgrade the ICU
   > system package and the intl PHP extension.
```

Do you know how can I get the latest ICU version ?
Thanks

**Comment by yosifkit** [comment]
That is the latest available in Debian Jessie: https://packages.debian.org/jessie/libicu-dev.

**Comment by deguif** [comment]
Hello @romqin 

Here a workaround to your problem. Compile yourself the icu library with the version you want:
```
RUN curl -sS -o /tmp/icu.tar.gz -L http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz && tar -zxf /tmp/icu.tar.gz -C /tmp && cd /tmp/icu/source && ./configure --prefix=/usr/local && make && make install

RUN docker-php-ext-configure intl --with-icu-dir=/usr/local && \
    docker-php-ext-install intl
```

**Comment by fadykstas** [comment]
my solution with OS X was:
run
`curl -sS -o /tmp/icu.tar.gz -L http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz && tar -zxf /tmp/icu.tar.gz -C /tmp && cd /tmp/icu/source && ./configure --prefix=/usr/local && make && sudo make install`

than run
`sudo pecl install intl` 

and than 
`Specify where ICU libraries and headers can be found [DEFAULT] : /usr/local`

**Comment by schmunk42** [comment]
Btw: This rather large test suite https://github.com/yiisoft/yii2/issues/13750 fails with ICU 57.1 but not with ICU 52.1

**Comment by SilverFire** [comment]
@schmunk42 ICU rules get changed time-to-time, so assertions may become outdated.
Generally it's not a problem.

**Comment by aissasell** [comment]
and how to upgrade in Windows

**Comment by 0911315** [comment]
and how to upgrade in Windows

**Comment by yosifkit** [comment]
updated "get the latest icu" here: https://github.com/docker-library/php/issues/455#issuecomment-309921509

**Comment by nbao** [comment]
i got error on my mac with Mamp Pro
In file included from /private/tmp/pear/temp/intl/php_intl.c:25:
/private/tmp/pear/temp/intl/php_intl.h:23:10: fatal error: 'php.h' file not found
#include <php.h>
         ^
1 error generated.
make: *** [php_intl.lo] Error 1
ERROR: `make' failed

How can i fix it?

**Comment by chucoyos** [comment]
intl ICU version installed on your system is outdated (52.1) and does not match the ICU data bundled with Symfony (59.1)
To get the latest internationalization data upgrade the ICU system package and the intl PHP extension.
![2017-07-31](https://user-images.githubusercontent.com/30364462/28802515-6c7a0c96-761c-11e7-9e8d-cc6afbe9510f.png)
