### ISSUE TITLE
Documentation is lacking a LOT

### ISSUE THREAD

**Issue by sxpert** [docker-library/php#310]
I am trying to instanciate a php:7-fpm instance
so far, I tried a LOT of things, but can't seem to get the thing to find my index.php file
also, it seems that despite log_level being present (commented) in the sample config filt, it is NOT supported, and prevent the php-fpm executable from starting, so there's no way to get detailed error information about which file it is trying to open/look for
all I get is : 
172.17.0.1 -  10/Oct/2016:15:00:18 +0000 "GET /index.php" 404

**Comment by tyranron** [comment]
@sxpert It would be nice if you provide more information about what you are trying to do:
- `docker-compose.yml` or `docker run` commands that you are using
- `Dockerfile` if you are using one
- configuration files which you mount into containers
- nginx configuration of virtual host that passes requests to php-fpm container

This will help us to understand your problem.
