### ISSUE TITLE
how to add php.ini

### ISSUE THREAD

**Issue by enricopuglia** [docker-library/php#311]
How can I add custom php.ini file to my docker container? 
which is the path where I should copy a custom php.ini file?
is there a way to modify the php.ini values from env variables defined in Dockerfile?

**Comment by tylkomat** [comment]
create your own `Dockerfile` and `ADD php.ini /usr/local/etc/php`

**Comment by westy92** [comment]
You could also mount a volume with your php.ini at `/usr/local/etc/php`.

**Comment by tianon** [comment]
In addition to the solutions documented here, this is also documented in the official image description on the Docker Hub since https://github.com/docker-library/docs/pull/87. :+1:

**Comment by konohanaruto** [comment]
Thanks.

**Comment by waellkh** [comment]
> create your own `Dockerfile` and `ADD php.ini /usr/local/etc/php`

where i get my php.ini ??

**Comment by rhzs** [comment]
@waellkh you need to create your `php.ini` file and save it in your root project, example from Google App Engine with PHP runtime https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-base/php.ini

**Comment by midoo1992** [comment]
> create your own `Dockerfile` and `ADD php.ini /usr/local/etc/php`

I have this error 
Service 'phpt3' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder311520649/php.ini: no such file or directory
