### ISSUE TITLE
how to use php-mysql

### ISSUE THREAD

**Issue by alicance** [docker-library/php#312]
I want to use lnmp env，but lack of mysqli .haven`t php_mysql packge?

**Comment by yosifkit** [comment]
It just needs to be installed from the extra modules that come with php as described on the docs https://github.com/docker-library/docs/tree/584a5d777ae8b09acb251237392abe8a1022e86f/php#how-to-install-more-php-extensions.  So this will work:

```dockerfile
FROM php:7
RUN docker-php-ext-install mysqli

# docker build -t my-new-php-image .
# docker run -it --rm my-new-php-image bash -c 'php --info | grep mysql'
```

**Comment by alicance** [comment]
o~o,I know,THX!
