### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by bscheshirwork** [docker-library/php#313]
excellent! updating 7.0.11->7.0.12 just now!
https://github.com/docker-library/php/blob/9f010251157b45dab7c59b657736d97f2b29c0b5/7.0/zts/Dockerfile

FROM php:7.0.12-zts

But... After build it (with --no-cache) I can see...

phpinfo()
PHP Version => 7.0.11

don't push on the server a new version?

**Comment by yosifkit** [comment]
That is strange I just pulled `php:7.0.12-zts` and it contains the correct version, but the image was pushed 3 days ago so I am not sure why your image still contained `7.0.11`.

**Comment by bscheshirwork** [comment]
I can't repeat this situation now. Issue close.
Sorry, this is my fail (may be wrong tag in a docker-compose.yml or something else)
