### ISSUE TITLE
update.sh file is not working

### ISSUE THREAD

**Issue by killtheclock** [docker-library/php#316]
whe i type ./update.sh

i get this error

`./update.sh: line 76: jq: command not found
curl: (23) Failed writing body (0 != 7813)`

as a result it dosent update the dockerfiles and my Os is Ubuntu 16.04.1 LTS xenial

**Comment by killtheclock** [comment]
oups my mistake i did `sudo apt-get install jq` 
and now i can run the update.sh

**Comment by yosifkit** [comment]
Yeah, we added jq to make scraping json output not so hacky.
