### ISSUE TITLE
`docker-php-ext-install` should be quiet unless there are errors / warnings

### ISSUE THREAD

**Issue by k0pernikus** [docker-library/php#319]
Given the dockerfile:

```
FROM php:7-apache
RUN apt-get -qq update && apt-get -qq install libxml++2.6-dev > /dev/null
RUN docker-php-ext-install soap
COPY ./ /var/www/html
```

Running `docker-php-ext-install soap` [spams the console](https://gist.github.com/k0pernikus/f3b3598bf5580915a173a579ff2d6f56). I want it to be as quite as possible and only to show errors and warnings.

Hence, I directed the output to `/dev/null`

```
RUN docker-php-ext-install soap > /dev/null
```

yet this also dumps debug information:

```
Step 3 : RUN docker-php-ext-install soap > /dev/null
 ---> Running in 5a05f4e3576d
+ cd /usr/src/php/ext/soap
+ phpize
+ ./configure
 ---> f506393f0161
```

I do want to keep the error and warning messages if they occure, yet those are none.

It would be nice to have `quiet` flag for  which does that out of the box, or that the all messages that are not representing at least a warning should be written to stdout.

**Comment by yosifkit** [comment]
Oh, yeah a silent mode would be nice or preferably a verbose mode that turns it on.  Or we could just remove the [`set -x`](https://github.com/docker-library/php/blob/1c798c1d1775be867bbbaad43c7c82d94dd60340/docker-php-ext-configure#L48) in the configure script

**Comment by mathroc** [comment]
with bash we could set `BASH_XTRACEFD=1` to make the trace output on stdout but I couldn't find the equivalent (if it exists) for sh

**Comment by Rubinum** [comment]
this feature would be very nice.

**Comment by tianon** [comment]
Sorry for the delay!

I'd be +1 on removing the `set -x` from `docker-php-ext-configure`. :+1:

**Comment by J0WI** [comment]
It seems not to be that simple. I just created #555 but I still get a huge output. I also tried to remove the `RUN set -x;` in the Dockerfiles with no effect.

**Comment by tianon** [comment]
Yes, removing `set -x` doesn't make these scripts quiet, but it prevents us from adding additional output, so for many extensions, doing something like `RUN docker-php-ext-install foobar > /dev/null` will be completely silent (maybe a few compiler warnings) unless there's an actual build failure (and then it'll include the error).

**Comment by cjaoude** [comment]
Thanks guys. Way too chatty.

```
# add silently...
RUN set -x;
RUN docker-php-ext-install foo > /dev/null
```
