### ISSUE TITLE
Is there a way to add the suhosin patch to a child image (without forking)?

### ISSUE THREAD

**Issue by dsnopek** [docker-library/php#325]
I'm assuming the answer to this is "no" because I didn't see any way, but I figured I'd ask folks who know Docker images better than first before falling back on forking. Thanks!

**Comment by tianon** [comment]
Yeesh, sorry for the hyper-long delay.  I think that given the responses here (really, the lack thereof), I believe you're right.  As far as I understand, Suhosin is a set of patches to PHP itself, and thus would require recompiling PHP to include.  Sorry!
