### ISSUE TITLE
Why is 'mkdir -p /usr/src/php' deleted in one commit 

### ISSUE THREAD

**Issue by dangyuluo** [docker-library/php#327]
I'm upgrading my php version from 7.0.6 to the latest version, but found that redis extension cannot be correctly installed. And the reason is that the direction `/usr/src/php/ext` does not exist. 
But it did existed in earlier version of PHP docker, and the action of creating `/usr/src/php` was deleted in commit f016f5dc420e7d360f7381eb014ac6697e247e11.

I just don't know why it is deleted. Is it moved to somewhere, or what should I do to install Redis?

**Comment by daohoangson** [comment]
Would love to know why it was removed too. My workaround for this is to `mkdir -p /usr/src/php/ext` in  Dockerfile RUN.

**Comment by dangyuluo** [comment]
Now I see that the directory `/usr/src/php` is created in `docker-php-source extract`.
But it seems that even if I run an empty content `php:7.0.12-apache` container, the directory `/usr/src/php` doesn't exist. There's only `php.tar.xz` and `php.tar.xz.asc` under `/usr/src`

**Comment by tianon** [comment]
See https://github.com/docker-library/php/pull/256 (and the linked issues from that one) for more details on that particular change.

Which Redis are you trying to install?

If it's the one from PECL, I've had success with the following:
```dockerfile
FROM php:7.0-fpm

RUN pecl install redis-3.0.0 \
    && docker-php-ext-enable redis
```

**Comment by dangyuluo** [comment]
@tianon 
I'm using this method to install Redis extension. 
```yaml
#Redis
RUN mkdir -p /usr/src/php/ext && curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
    && docker-php-ext-install redis
```

Am I doing it in a wrong way?

**Comment by tianon** [comment]
Sorry for the delay!  I'd still recommend installing via PECL instead (as I referenced above), but the usage you described should be working again as of https://github.com/docker-library/php/pull/288. :+1:
