### ISSUE TITLE
a error when i use docker-php-ext-install 

### ISSUE THREAD

**Issue by swumao** [docker-library/php#329]
error: /usr/src/php/ext/1 does not exist

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    $$ docker-php-ext-install pdo_mysql

**Comment by tianon** [comment]
I think instead of `$$`, you want `&&` on that last line :smile:

**Comment by swumao** [comment]
yes...

and when I use pecl to install stomp extension, another error occured...
