### ISSUE TITLE
php-fpm: How to clean OPCache?

### ISSUE THREAD

**Issue by JarJak** [docker-library/php#332]
How can I restart php-fpm to clean OP Cache and/or APC Cache? In other Debian instances I could simply run 
`service php-fpm restart`
 but here php is not a service..
```
service --status-all
 [ - ]  bootlogs
 [ - ]  bootmisc.sh
 [ - ]  checkfs.sh
 [ - ]  checkroot-bootclean.sh
 [ - ]  checkroot.sh
 [ - ]  cron
 [ - ]  exim4
 [ - ]  hostname.sh
 [ ? ]  hwclock.sh
 [ - ]  killprocs
 [ - ]  motd
 [ - ]  mountall-bootclean.sh
 [ - ]  mountall.sh
 [ - ]  mountdevsubfs.sh
 [ - ]  mountkernfs.sh
 [ - ]  mountnfs-bootclean.sh
 [ - ]  mountnfs.sh
 [ - ]  procps
 [ - ]  rc.local
 [ - ]  rmnologin
 [ - ]  rsync
 [ - ]  sendsigs
 [ + ]  udev
 [ ? ]  udev-finish
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ - ]  urandom
```

**Comment by ihor-sviziev** [comment]
you can send USR2 signal:
http://serverfault.com/questions/444673/php-fpm-signals-for-pool-error-log-rotation

**Comment by yosifkit** [comment]
Think of the container as the service; the only thing running in the container is php-fpm, so `docker restart my-fpm-container` would work.  (assuming that your nginx or other front end can properly route to the new container)

**Comment by JarJak** [comment]
I dont want to restart whole virtual machine, the website must be working
24/7

2016-11-23 20:13 GMT+01:00 yosifkit <notifications@github.com>:

**Comment by bweston92** [comment]
@JarJak what stops you adding a new container forwarding the traffic to that and removing the old contain? Containers should be immutable anyway.

Never the less something like this might be ok:
```
docker run my-container systemctl restart php-fpm
```

**Comment by estahn** [comment]
See #399 ... Issue should be closed.
