### ISSUE TITLE
memcache install fails 

### ISSUE THREAD

**Issue by RoosterKelly** [docker-library/php#333]
Using the example directly from the [docs](https://hub.docker.com/_/php/)

`FROM php:5.6-apache
RUN apt-get update && apt-get install -y libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached`

I get the following error:

`checking for ZLIB... yes, shared
checking for pkg-config... /usr/bin/pkg-config
checking for zlib location... configure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located
ERROR: `/tmp/pear/temp/memcached/configure --with-php-config=/usr/local/bin/php-config --with-libmemcached-dir=no' failed
error: /usr/local/lib/php/extensions/no-debug-non-zts-20131226/memcached does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
opcache.so
The command '/bin/sh -c apt-get update && apt-get install -y libmemcached-dev     && pecl install memcached     && docker-php-ext-enable memcached' returned a non-zero code: 1
`

**Comment by strarsis** [comment]
libmemcached has to be installed for pecl extension install of memcached to be successful:
````
[...]
checking for libmemcached location... configure: error: memcached support requires libmemcached.
[...]
````
Without memcached.so available, the extension cannot be enabled.

**Comment by strarsis** [comment]
Follow up: Official Docker `php` images had a change in tagging/architecture (`-bookworm` for Debian `bookworm` distribution).
The `memcached` PHP extension build failed again, but this time the `libssl-dev` package also has to be installed 
(see https://serverfault.com/a/1136017).
