### ISSUE TITLE
[php-fpm] Config file naming/ordering

### ISSUE THREAD

**Issue by strarsis** [docker-library/php#338]
The config files in /usr/local/etc/php-fpm.d/ override each other for some options.
Usually, the config files would be applied by descending order of their file names.
It would be more obvious and easier to re-order if a prefix (01_; 02_; ...) could be added to their file names.

/usr/local/etc/php-fpm.d/:
`docker.conf; www.conf; (www.conf.default); zz-docker.conf`

Is the filename of 'zz-docker.conf' prefixed with 'zz' so that its options are applied lastly?
Why is there also a 'docker.conf'? Should it be applied first? Or only not as last one?

**Comment by tianon** [comment]
The `zz-` prefix is included so that those flags get applied last, yes -- the other is named simply `docker.conf` because the order of those does not really matter.

**Comment by tianon** [comment]
See also https://github.com/docker-library/php/issues/241 for a discussion about documenting this!
