### ISSUE TITLE
php 7.1 was released yesterday!!

### ISSUE THREAD

**Issue by swumao** [docker-library/php#341]
https://php.net/archive/2016.php#id2016-12-01-3

when php:7.1-fpm update?

**Comment by shouze** [comment]
@swumao I've made a PR ;) https://github.com/docker-library/php/pull/342

**Comment by shouze** [comment]
@swumao you can close this one #342 has been merged and the container will probably be available during next week or so.

**Comment by swumao** [comment]
@shouze But the [OFFICIAL REPOSITORY](https://hub.docker.com/r/library/php/) does not updated...

**Comment by shouze** [comment]
It's a matter of time, don't worry ;)

**Comment by swumao** [comment]
Ok, thank you very much!
