### ISSUE TITLE
( wait on line ) how to move httpd.conf to image  with Apache ( laravel )

### ISSUE THREAD

**Issue by iehong** [docker-library/php#345]
now my dockerfile is like

FROM php:5.6.28-apache
COPY . .
EXPOSE 80

i want the root Directory point to ./public with httpd.conf (may be)

how can i config

thank you

**Comment by tianon** [comment]
This is dictated by `DocumentRoot` in `/etc/apache2/sites-available/000-default.conf`:
```
/etc/apache2/sites-available/000-default.conf:12:	DocumentRoot /var/www/html
```

Modifying that value should do what you're looking for:
```dockerfile
RUN sed -ri 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
```

**Comment by iehong** [comment]
i see ,thank you
