### ISSUE TITLE
adding php7.0-pgsql

### ISSUE THREAD

**Issue by pir1981** [docker-library/php#348]
I want to extend the image with php7.0-pgsql and constantly get error messages about pg_connect(). Anyone knows what to do? I can make it work outside docker, when running all with apt-get.

The issue is: 
_WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function pg_connect() in /usr/share/nginx/html/passwords.php:9"_

I also get it when I set 
`extension_dir="/usr/local/lib/php/extensions/no-debug-non-zts-20151012:/usr/lib/php/20151012"`

and when I set  on top (with or wihtout full path)
`extension=pgsql.so`

Docker states on startup

_NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012:/usr/lib/php/20151012/pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012:/usr/lib/php/20151012/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0_

and the error is still undefinde function pg_connect()

This is my code in Docker. 
```
ENV PHP_PGSQL_VERSION 7.0.13-2
RUN set -xe\
        && echo "deb http://ftp.de.debian.org/debian stretch main" >> /etc/apt/sources.list \
        && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y php7.0-pgsql=$PHP_PGSQL_VERSION
```

What am I missing? Thanks a ton!

**Comment by yosifkit** [comment]
Packages from the apt repos will not necessarily work with the php in the image, since they may have been created for a different version of php.  This is similar to https://github.com/docker-library/php/pull/210. 
```
FROM php:7.0-fpm

RUN apt-get update \
    && apt-get install -y --no-install-recommends  libpq-dev libpq5 \
    && docker-php-ext-install pgsql \
    && apt-get purge -y --auto-remove libpq-dev \
    && rm -rf /var/lib/apt/lists/*
````

**Comment by pir1981** [comment]
@yosifkit thanks. 

For my understanding:
1.) why do they not work together. What is the difference between this image and apt repos (besides the way it is coded)
2.) you are suggesting to install the whole pgsql . I just want php-pgsql. I am running the pgsql outside Docker and just want to be able to talk PHP-pgsql through Docker.
3.) if I carry over your idea of not putting in the versioning, is that what you are suggesting is the issue? so php7.0-pgsql should be installed without a version? - I will check that and report back

**Comment by tianon** [comment]
The package in Debian's APT repos is compiled from/for the `php` package in Debian itself -- the ABI _might_ be compatible, but very likely isn't (so if we configured our PHP to use it, it'll still likely either not work at all, or will have hard-to-debug errors).

The code @yosifkit provided only installs the `pgsql` extension for PHP (specifically in `docker-php-ext-install pgsql`, the `apt-get` bit before it only installs the `libpq` library which is required by the PHP `pgsql` extension).

If your `Dockerfile` is already `FROM php:7.0-xxx` (where `xxx` is any of the Debian-based variants of PHP such as `fpm`, `apache`, or `cli`), the `RUN` line @yosifkit provided should work as-is. :+1:

**Comment by pir1981** [comment]
Computer says no :(

I did exactly as you write and tested even more. My standalone nginx image works, my nginx image and this php image work together as well. Then I add just @yosifkit code and build FROM the php image that is working: and I still get the pg_connect  error. 

There are also no .so files hinting on pgsql and neither does phpinfo() show any pgsql tabel (on my non-docker version I see a separate table with pgsql info).

**Comment by pir1981** [comment]
I rebuild everything step by step again and now it works.....
