### ISSUE TITLE
How to configure the open apache .htaccess

### ISSUE THREAD

**Issue by wl496928838** [docker-library/php#355]
How to configure the open apache .htaccess

**Comment by tianon** [comment]
Can you please be a little more specific about what you've tried to do and what's not working for you?

**Comment by nsteinmetz** [comment]
In your dockerfile, Just add :

```
a2enmod rewrite
```

So that htaccess is read.

**Comment by wl496928838** [comment]
Thank you for the success.

**Comment by MetaiR** [comment]
@nsteinmetz I am sorry, I am a beginner.
where should I add this line?

**Comment by nsteinmetz** [comment]
@MetaiR 

You would have something like below in your `Dockerfile` :

```
FROM php:apache
RUN a2enmod rewrite
```

**Comment by doodhout** [comment]
Question: can you use a2enmod rewrite without a dockerfile? I.e. when using the Docker UI in Synology, the possibilities are rather constrained, but I'd like to have it working without leaving the UI.

**Comment by strarsis** [comment]
@doodhout: When you can use `docker-compose` you can specify a build-step with Dockerfile.
You can also build your own image + push it onto Dockerhub or similar, so the Synology Docker can pull it.

**Comment by doodhout** [comment]
I'd rather not mess around but just use prebuilt images from upstream.

The trick I used to have this working without having to edit the docker file and build the image myself, is to SSH into the (running) container and enable a2enmod from there. Works fine.

**Comment by JoelLinn** [comment]
If you insist to not have your own dockerfile you can change the run command to something like 
`sh -c "a2enmod rewrite && exec apache2-foreground"`
if that is possible inside the Synology UI

**Comment by doodhout** [comment]
That's very much possible, since we have shell access to each running container from the web UI.
