### ISSUE TITLE
Logs (access.log, error.log) to stdErr

### ISSUE THREAD

**Issue by tchiotludo** [docker-library/php#358]
This configuration seems normal to everyone :  
```
[global]
error_log = /proc/self/fd/2 

; if we send this to /proc/self/fd/1, it never appears
access.log = /proc/self/fd/2
```

But this really sucks, the access log is merged with the error log.
The fpm config doesn't allow us to catch true error (error output on catch error), the fpm log info & the access log.

I can see that the the comment is true, if you try anything else that is docker supported (/dev/stdout, ...) doesn't seems to work.
But I really wonder what is the reason since other docker image works well. I really want to report the bug to the right repositories. 

I've the impression that is fpm related bug but I can't find any issue reported about this.
Any help will be really appreciate.

**Comment by gajus** [comment]
I am not even getting this far... I am not able to get logs in the console at all.

I can see that [`php-fpm.d/docker.conf` is being created](https://github.com/docker-library/php/blob/master/5.6/fpm/Dockerfile#L151-L163), and this is my [`php.ini` configuration](https://gist.github.com/gajus/2d6586c052f80a741bfe1761bbe1ce6c#file-php-ini-L37-L52).

However, unless I add [`echo "php_admin_flag[log_errors] = On">>/usr/local/etc/php-fpm.conf` to my Dockerfile](https://gist.github.com/gajus/d48203c931059bc2df9c5154160de1e6#file-dockerfile-L13), I am not getting any logs.

Is there something I am overlooking?

**Comment by coding-master-** [comment]
@ssssaaa111

**Comment by tchiotludo** [comment]
@gajus : try to replace 
`error_log = /var/log/php-errors.log` by `error_log = /dev/stderr` and it must be working

logging to docker must be to files like /dev/stderr, /dev/stdout, /proc/self/fd/2, /proc/self/fd/1 in by capture by docker daemon

**Comment by tianon** [comment]
Yeah, I'd love to have a decent fix for this, but we haven't found one yet -- I'm guessing that the reason `/proc/self/fd/1` (and `/dev/stdout`, which is a symlink to `/proc/self/fd/1`) doesn't work is that `php-fpm` likely closes STDOUT as part of its own startup routines. :disappointed:

**Comment by tchiotludo** [comment]
created a bug report on php : https://bugs.php.net/bug.php?id=73886, wait and see

**Comment by tchiotludo** [comment]
for information : https://github.com/php/php-src/pull/2310
It's being discussed internally with a patch available.
@tianon you have right, the patch show that the STDOUT is closed, and the patch don't close it anymore.
Hope this will be accepted :crossed_fingers:

**Comment by tianon** [comment]
Closing since this is a bug in upstream's handling of stdout, not something we can reasonably fix in the image.

I'd love to see a PR which adds https://bugs.php.net/bug.php?id=73886 and https://github.com/php/php-src/pull/2310 as context to our existing comment for future reference (and so we have an obvious place to go look for when this can be adjusted), though! :heart:

ala:
```conf
; if we send this to /proc/self/fd/1, it never appears
; see https://bugs.php.net/bug.php?id=73886
; and https://github.com/php/php-src/pull/2310
access.log = /proc/self/fd/2
```

**Comment by josuealcalde** [comment]
Hi

I have been struggling with this bug to have access_log in stdout and I think I have found a good solution. I don't know if it is enough to go upstream.


The idea is put access.log to /proc/self/fd/3 and redirect /proc/self/fd/3 to sdout.

So, I have this in my php-fpm-conf

`access.log=/proc/self/fd/3
`
And i have added this to the docker-php-entrypoint:

`exec 3> /dev/stdout
`

I already have a custom www.conf file for my php-fpm configuration, so it has not been a big deal to change the access.log.

For the docker-php-entrypoint I have used sed in my dockerfile:

RUN sed -i s/exec\ \"\$@\"\/exec\ 3\>\ \\/dev\\/stdout\\nexec\ \"\$@\"/  /usr/local/bin/docker-php-entrypoint


Maybe this is a bit tricky to go upstream, but it can help people to solve this problem by their own.
