### ISSUE TITLE
how to add lua modules in apache

### ISSUE THREAD

**Issue by dennsliu** [docker-library/php#368]
We want to run lua in apache,  so i need to add lua mocules.

LoadModule lua_module modules/mod_lua.so

How to add? I have tried to add in /etc/apache2/apache2.conf, but it don't work.

**Comment by yosifkit** [comment]
Since we are just using the Debian package of Apache2/httpd you should be able to enable it just like normal.
```Dockerfile
RUN a2enmod lua
# not sure if you also need to install liblua
RUN apt-get update && apt-get install -y liblua5.2-0 && a2enmod lua && rm -rf /var/lib/apt/lists/*
```
