### ISSUE TITLE
Errors cause white screen of death 

### ISSUE THREAD

**Issue by mwpastore** [docker-library/php#370]
With the default configuration of php:7.0-fpm-alpine (i.e. no main php.ini file), any errors generated by the PHP application cause some FastCGI clients ([Caddy](https://caddyserver.com) with the [caddy-filter](https://github.com/echocat/caddy-filter) plugin, in my case) to fail to handle the response body and return a "white screen of death" (i.e. no body, Content-Length: 0). Watching some FastCGI traffic through tcpdump, it appears as though the errors are appearing inline above the headers in the response. Is there some configuration to prevent this from happening that we can include in the Dockerfile by default (or at least document somewhere)?

**Comment by tianon** [comment]
Do you or your application add any custom configuration?  I don't think we modify the default PHP configuration any, but I'm not sure what FPM's default behavior is (especially around `display_errors` and/or `error_reporting`).

The fact that it's dumping errors before the headers is extremely bizarre, and I can't think of any reason why it'd be doing that except a bug in FPM or PHP. :disappointed:

**Comment by mwpastore** [comment]
It could very well be a bug in Caddy too. I'm trying to distill a small test case, but I'm struggling to come up with a simple and straightforward FastCGI client for testing purposes. Any suggestions?

**Comment by tianon** [comment]
We've got a couple tests that use `fcgi-client` (https://github.com/docker-library/official-images/blob/080d965cf44e4fbee47b3c4479ab1898ae15547d/test/tests/php-fpm-hello-web/run.sh), although I wouldn't say it's great -- probably enough to help debug. :+1:

Usually, I've found that FPM is annoying enough that the simplest way to test is to simply hook it up in NGINX, but that doesn't help debugging issues like this. :disappointed:

**Comment by mwpastore** [comment]
It looks like this is an issue with Caddy, specifically the caddy-filter plugin. I'll close this issue for now and continue pursuing it with those folks. Thank you!
