### ISSUE TITLE
Alpine: Use readline instead of libedit?

### ISSUE THREAD

**Issue by teohhanhui** [docker-library/php#375]
Unicode input does not work in interactive mode (`php -a`)

**Comment by tianon** [comment]
This was changed to use `libedit` consistently in both Alpine _and_ Debian in https://github.com/docker-library/php/pull/202, but I can't seem to find the rationale for why we did so (nor can I remember the exact logic). :disappointed:

@ncopa perhaps you recall the reasoning behind this choice? :pray:

**Comment by tianon** [comment]
I went to go switch this back to `readline` and figured I should probably do some testing before I opened the PR, and found that if I set `LANG` to a UTF-8 enabled locale such as `C.UTF-8`, this actually works just fine:

```console
$ docker pull php:7.2-cli
7.2-cli: Pulling from library/php
802b00ed6f79: Already exists 
59f5a5a895f8: Already exists 
6898b2dbcfeb: Already exists 
8e0903aaa47e: Already exists 
d43aa0efb0b7: Pull complete 
9219be93e21e: Pull complete 
79637da64359: Pull complete 
eb02498a33f1: Pull complete 
25380f748c5d: Pull complete 
Digest: sha256:37fb2422bc2fd375e1c63e887a1643e3009e23a9b937d5200a192b03079398d7
Status: Downloaded newer image for php:7.2-cli

$ docker run -it --rm -e LANG=C.UTF-8 php:7.2-cli
Interactive shell

php > echo '💩';
💩
php > 
```

Same with Alpine: (but here, without `LANG` since Alpine doesn't have locales)

```console
$ docker run -it --rm php:7.2-cli-alpine3.8
Unable to find image 'php:7.2-cli-alpine3.8' locally
7.2-cli-alpine3.8: Pulling from library/php
4fe2ade4980c: Already exists 
5cf60c0c0763: Pull complete 
468219aa4689: Pull complete 
4a8b1a3b9e51: Pull complete 
36c6d354250a: Pull complete 
47f8bedd0ad9: Pull complete 
bbfd59530507: Pull complete 
bf393a4d6f2a: Pull complete 
36a92a815a92: Pull complete 
Digest: sha256:b7470c2adc0163b91a27d0fd1e107b5fb57bacc28c682acd2514e8289e8fa50b
Status: Downloaded newer image for php:7.2-cli-alpine3.8
Interactive shell

php > echo '💩';
💩
php > 
```

So I'm going to close this since it appears to be working. :+1:

**Comment by Cojad** [comment]
@tianon your test works in php7.2 but fail with php8

```docker run -it --rm -e LANG=C.UTF-8 php:8-cli php -a```
This will not accept any non-ascii characters. 

```docker run -it --rm php:8-cli-alpine php -a```
This will result 💩 displayed as `\U+DFF0\U+DF9F\U+DF92\U+DFA9`

Any idea why utf-8 doesn't work in docker php8?

My temporary solution is to install libreadline then execute php8 using
`LD_PRELOAD=/lib/x86_64-linux-gnu/libreadline.so.7 php -a`

But I prefer better solution...

**Comment by tianon** [comment]
Can confirm that this is broken again. :disappointed:

However, I don't get escape sequences no matter what I set (or don't set) `LANG` to -- it won't accept `💩` for me at all (it appears to ignore the input entirely). :confused:

**Comment by tianon** [comment]
PR up at #1187
