### ISSUE TITLE
Error "Could not gather sufficient random data" with PHP 7.0-alpine 

### ISSUE THREAD

**Issue by jderusse** [docker-library/php#376]
When using the `php:7.0-alpine`
```
$ docker run --rm php:7.0-alpine php -r "random_int(0, 1);"

Fatal error: Uncaught Exception: Could not gather sufficient random data in Command line code:1
Stack trace:
#0 Command line code(1): random_int(0, 1)
#1 {main}
  thrown in Command line code on line 1
```

Whereas the same call to other version (like php `7.1-alpine` or `7.0`) works
`$ docker run --rm php:7.1-alpine php -r "random_int(0, 1);"`
`$ docker run --rm php:7.0 php -r "random_int(0, 1);"`

**Comment by jderusse** [comment]
I think this commit from @nikic may be related: https://github.com/php/php-src/commit/14c72cc5824d5fa472b79b7216a01be0918ccc5d

**Comment by pravindahal** [comment]
Same issue in 7.1 alpine variant too.

**Comment by yosifkit** [comment]
It looks like the fix is merged in https://github.com/php/php-src/pull/2385, so it should be fixed on the next php release.

**Comment by StalkAlex** [comment]
Is there any other options than wait till next release? I guess it's not fast solution.

**Comment by herloct** [comment]
> Now the same issue has been introduced in 7.1 alpine variant too.

Me too, on `7.1.2-fpm-alpine`.

It works fine on my laptop (ubuntu 16.04), but it throws `Could not gather sufficient random data` on my server (debian jessie).

**Comment by jderusse** [comment]
I just upgraded the kernel of my CI server. It solves the issue

**Comment by StalkAlex** [comment]
@jderusse you mean docker host machine?

**Comment by jderusse** [comment]
yep

**Comment by herloct** [comment]
@jderusse 
> I just upgraded the kernel of my CI server. It solves the issue

Upgrading kernel from v3 to v4?

**Comment by francislavoie** [comment]
@StalkAlex I fixed it by specifying version the tag `php:7.0.15-alpine` to downgrade to `7.0.15` until `7.0.17` releases.

**Comment by StalkAlex** [comment]
@francislavoie  I did the same but for php 7.1.2, downgraded to 7.1.1. Thanks!

**Comment by palmtale** [comment]
Found the same issue in 7.1.2-fpm-alpine,
It worked OK while hosted on my laptop mac os x, 
but "Could not gather sufficient random data" hosted on server CentOS7.2.1511(Some Cloud VM).
my calling function is random_bytes

**Comment by pravindahal** [comment]
Seems to be fixed in 7.1.3.

**Comment by hvanderheide** [comment]
Just confirmed the issue is fixed with the latest release. Was having this issue with Nextcloud and the Debian stable kernel (3.16.0). After pulling the latest 7-fpm-alpine everything works.

**Comment by yosifkit** [comment]
@pravindahal and @hvanderheide, thanks for confirming fix!

Closing as it seems to be resolved in the latest release.  Feel free to comment if you run into this again on the latest images.

**Comment by chinassx** [comment]
How to solve it?
