### ISSUE TITLE
Please enable mod_rewrite

### ISSUE THREAD

**Issue by babatundebusari** [docker-library/php#377]
mod_rewrite is like a very popular module and mostly needed with apache
most people will be using nginx anyways if not mostly because of mod_rewrite with apache

will be GREAT to OFFICIALLY enable mod_rewrite by default to the official image
Yes we can create own own custom image but would be BETTER if its added to official by default

Thanks

**Comment by hairmare** [comment]
I haven't use mod_rewrite since [`FallbackResource `](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#fallbackresource) from mod_dir made it really easy to just use `FallbackResource /index.php` and not have any complex mod_rewrite configs.

While most projects still describe how to get set up with mod_rewrite, I have yet to find one where replacing mod_rewrite with FallbackResource does not work. It looks like most developers have just been using mod_rewrite to fallback to a php script and not for any serious rewriting.

**Comment by sveneh** [comment]
Just in case you need mod rewrite, create a simple Dockerfile with this content

```
FROM php:apache
RUN a2enmod rewrite
```

**Comment by babatundebusari** [comment]
@sveneh 

i know how to do that
my request is to **OFFICIALLY** support it

**Comment by yosifkit** [comment]
We don't support any non-default mods being on by default. We'd rather not turn on extra mods that might not be used. We swap `mpm_event` for `mpm_prefork` for performance ([dockerfile](https://github.com/docker-library/php/blob/738fcd0bdaed0b27e56b4975be94abe2dbe0b0b4/7.1/apache/Dockerfile#L61-L62)).  The supported way is to run `a2enmod` on the mods you want turned on.  If you are opposed to making a Dockerfile with those enabled, you can just run some shell on start that will enable them:
```console
$ docker run -d --name apache-rewrite php:7-apache sh -c 'a2enmod rewrite && exec docker-php-entrypoint apache2-foreground'
$ docker exec -it apache-rewrite bash
root@5f9d9d912c6a:/var/www/html# ls /etc/apache2/mods-enabled/ | grep rewrite
rewrite.load
```

**Comment by hairmare** [comment]
Like this? https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions 😞

**Comment by bittner** [comment]
I'm really trying to address common questions that pop up again and again, hence literally a FAQ section.

**Comment by babatundebusari** [comment]
after deliberating for a while, i think it is true to only leave default stuffs on and any additional stuffs should be bundled with a custom image

So i agree with that logic

**Comment by bittner** [comment]
@babatundebusari As you write yourself, mod_rewrite is very popular and widespread use is common (Wordpress, Joomla!, et al.). Therefore, it's likely that this very question will pop up again. I think it would make sense to address this problem to avoid the question being asked again and again.

**Comment by neohunter** [comment]
lets add this to the README ? :)

**Comment by axelf** [comment]
Adding `RUN a2enmod rewrite` does not working for me. Do i have to do another step i forgot?

Thats my Dockerfile:
```
FROM php:7.1-apache

RUN a2enmod rewrite
RUN docker-php-ext-install mysqli pdo pdo_mysql
```

**Comment by stufently** [comment]
Pidarasi

**Comment by Hubbitus** [comment]
Why not just provide environment variable, read modules and enable them in entrypoint script?
