### ISSUE TITLE
php:7-fpm-alpine not based on alpine:3.5

### ISSUE THREAD

**Issue by MelwinKfr** [docker-library/php#382]
Hi,

I have an issue with this because I would like to use PHP 7 and install the following extensions:
- opcache
- pdo_mysql

But I need to install those packages before:
- php7-opcache
- php7-pdo_mysql

Which are only available on Alpine branch `edge` and `3.5` (see the following links)
- [php7-opcache](https://pkgs.alpinelinux.org/packages?name=php7-opcache&branch=&repo=&arch=&maintainer=)
- [php7-pdo_mysql](https://pkgs.alpinelinux.org/packages?name=php7-pdo_mysql&branch=&repo=&arch=&maintainer=)

**Comment by hairmare** [comment]
The image installs php from source and has a [helper to install extensions](https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions). To get opcache and pdo_mysql installed you might use the following Dockerfile:

```Dockerfile
FROM php:7-fpm-alpine

RUN docker-php-ext-install opcache
RUN docker-php-ext-install pdo_mysql
```

**Comment by MelwinKfr** [comment]
Thank you ! 

I thought I had to install the right Alpine packages before installing extensions.

**Comment by dimaip** [comment]
Regardless, are there any plans to switch to 3.5?
3.4 has bugs like this one: https://bugs.alpinelinux.org/issues/6651
