### ISSUE TITLE
Apache image does not support APACHE_ARGUMENTS

### ISSUE THREAD

**Issue by xakraz** [docker-library/php#389]
The file `5.6/apache/apache2-foreground` does not support the environment variable `APACHE_ARGUMENTS` which can be set by the `envvars` file ...

If can be useful for such usage:
- http://httpd.apache.org/docs/2.4/mod/core.html#ifdefine
- http://jennyandlih.com/using-apaches-ifdefine-dev-and-production-environments

**Comment by tianon** [comment]
Closing for the same reason as the PR: (https://github.com/docker-library/php/pull/390#issuecomment-286894904)

> There isn't need of an env for this.  You can just supply the args via the command to the container:
> ```console
> $ docker run -d php:apache --apache-arg1 --apache-arg2
> ```
