### ISSUE TITLE
Base the fpm tag from cli

### ISSUE THREAD

**Issue by amq** [docker-library/php#395]
I find myself constantly having to pull two images: `fpm` and `cli`, which contain a lot of redundancy and use more bandwidth than they would if `fpm` was based from `cli`.

To avoid this, I sometimes do `docker run -it --rm php:fpm php -v`, but this is counterintuitive.

Similar can be applied to other tags.

**Comment by tianon** [comment]
All the images include the php cli -- I'm not sure what the actual benefit
of this change would be?  We don't keep the PHP source, and if we recompile
PHP to include FPM, it's going to recompile the cli bits from the base
image anyhow, so there wouldn't actually be a space savings (due to the way
Docker handles layers).

**Comment by amq** [comment]
Maybe build cli with fpm then (probably under 2 MB of overhead), and the fpm Dockerfile would only contain a different CMD?

**Comment by tianon** [comment]
Closing, since that's exactly what we do (see https://github.com/docker-library/docs/pull/1066 for the recent documentation clarification that _all_ variants include the PHP cli, and FPM and Apache simply have different default commands). :+1:

(Sorry for the delay!)

**Comment by tianon** [comment]
For a more exact size comparison between the two: (so yes, it's probably overkill to have both variants now, but we're a bit late to backtrack on that)
```console
$ docker images php
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
php                 7.2-fpm             b842e819f48f        3 days ago          367MB
php                 7.2-apache          c6965aaf628c        3 days ago          377MB
php                 7.2-cli             66de0fd8677a        3 days ago          352MB
```
