### ISSUE TITLE
Include path for pool definitions in php-fpm.conf is wrong

### ISSUE THREAD

**Issue by runemoennike** [docker-library/php#397]
After pulling the latest docker image with FPM (`php:7.1-fpm-alpine`), the path to include pool definitions in php-fpm.conf is missing a forward slash at the beginning. This results in pool definitions not being included at all. It's being set to:

`include=etc/php-fpm.d/*.conf`

But it should be:

`include=/etc/php-fpm.d/*.conf`

**Comment by bolanos** [comment]
I believe its correct:
```
; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /usr/local otherwise
include=etc/php-fpm.d/*.conf
```
`/etc/php-fpm.d/*.conf` wont exist.

if anything it would be `/usr/local/etc/php-fpm.d/*.conf`

**Comment by runemoennike** [comment]
I was mistaken. The path is relative to the PHP include path, so the right place to put pool configurations would be, for example, in `/usr/local/etc/php-fpm.d/`.
