### ISSUE TITLE
Docker Hub updates?

### ISSUE THREAD

**Issue by ellisio** [docker-library/php#411]
What is the typical lag time between pushing a version update to this repository, and having Docker Hub updated? Looks like you pushed `7.1.4` updates 4 days ago on GitHub. The last push, for `7.1.3` on Docker Hub was 25 days ago.

Cheers

**Comment by SmoshySmosh** [comment]
👍 Would be great to see 7.1.4 in dockerhub.

**Comment by hairmare** [comment]
The actual version needs to be updated in https://github.com/docker-library/official-images/blob/master/library/php for it to get pushed to the hub. If this hasn't happened yet it might have gone forgotten or there is a blocking issue that I'm not aware of.

**Comment by visualfanatic** [comment]
I think @hairmare is right, they need to run [this script](https://github.com/docker-library/php/blob/master/generate-stackbrew-library.sh), so Docker Hub is able to pick it up. The typical lag is about 24 hours (I think) for non-security updates. It would be awesome if they would use post-commit hooks from that main repo and automatically build new images.

**Comment by hallabro** [comment]
For the record docker hub now seems to contain 7.1.4 (https://hub.docker.com/_/php/).

**Comment by tianon** [comment]
Closing, since this is long since solved. :+1:
