### ISSUE TITLE
pecl does not work under alpine versions

### ISSUE THREAD

**Issue by mikk150** [docker-library/php#412]
I am trying to convert my PHP image from php:7.0-zts to php:7.0-zts-alpine, but I havent yet found how to make pecl work

phpize is missing

**Comment by tianon** [comment]
`phpize` should be available, but the dependencies it requires are not; I've had success just now building the following on my machine:
```dockerfile
FROM php:7.0-fpm-alpine

RUN apk add --no-cache \
		$PHPIZE_DEPS \
		openssl-dev

RUN pecl install mongodb-1.2.5
RUN docker-php-ext-enable mongodb
```

**Comment by mikk150** [comment]
oh phpize is not installed when `$PHPIZE_DEPS` is not installed

```Dockerfile
FROM php:7.0-zts-alpine

RUN apk add --no-cache \
        $PHPIZE_DEPS \
    && pecl install pthreads \
    && docker-php-ext-enable pthreads
```

actually works...

**Comment by MatTheCat** [comment]
I find it a bit sad to have to reinstall all of `$PHPIZE_DEPS`. Couldn't this be handled trough a `package.xml`?
