### ISSUE TITLE
php cli process not responding to ctrl+c

### ISSUE THREAD

**Issue by fieg** [docker-library/php#415]
We have a symfony console command which consumes messages from rabbitmq. When we start the script with docker-compose:

```
docker-compose run --rm dev php bin/console consume -vvv
```

We can't stop script execution with ctrl+c. We have to manually do a `docker kill` to stop it, which is pretty annoying. Other contrainers/images don't seem to have this problem.

We are using the `php:7.1.4-cli` image.

**Comment by arout** [comment]
Does sigquit work for you?   **CTRL + \**

**Comment by fieg** [comment]
Never mind, the library we are using to consume messages from rabbitmq was blocking signals. Sorry for you time.

**Comment by arout** [comment]
No worries, glad you have it sorted
