### ISSUE TITLE
Why are you still installing Apache 2.2?

### ISSUE THREAD

**Issue by eric-tucker** [docker-library/php#425]
Just wondering why this setup isn't installing apache 2.4.

**Comment by tianon** [comment]
It is, but the package is `apache2.2-common` for legacy reasons (if you look at https://packages.debian.org/jessie/apache2.2-common, you'll see it's a transitional package that actually installs 2.4) -- we should likely update that to use `apache2-bin` instead.

**Comment by tianon** [comment]
Or perhaps simply `apache2` which is what that package actually pulls in, so that we don't inadvertently cause a regression?

**Comment by eric-tucker** [comment]
Ahh. Makes sense.  Sorry for not understanding this.

**Comment by tianon** [comment]
No worries -- filed https://github.com/docker-library/php/pull/427 to make this more clear/direct. :+1:
