### ISSUE TITLE
Installation of sybase_ct fails with  configure: error: ctpublic.h missing!

### ISSUE THREAD

**Issue by bizmate** [docker-library/php#434]
$ docker -v
Docker version 17.03.1-ce, build c6d412e

$ docker-compose -v
docker-compose version 1.13.0, build 1719ceb

```
FROM php:5-fpm

# https://dunglas.fr/2014/01/connection-to-a-ms-sql-server-from-symfony-doctrine-on-mac-or-linux/
# Add Free tds
# http://stackoverflow.com/questions/4976971/compiling-php-with-curl-where-is-curl-installed
RUN apt-get update && apt-get install -y  apt-transport-https freetds-bin libcurl4-gnutls-dev 

#Add DBLIB PDO driver
RUN docker-php-ext-install -j$(nproc) curl sybase_ct
```
Error 

checking for unistd.h... yes
checking size of long int... 8
checking checking if we're on a 64-bit platform... yes
checking Checking for ctpublic.h... **configure: error: ctpublic.h missing!**
ERROR: Service 'php5' failed to build: The command '/bin/sh -c docker-php-ext-install -j$(nproc) curl sybase_ct' returned a non-zero code: 1

**Comment by tianon** [comment]
According to https://packages.debian.org/file:ctpublic.h, `ctpublic.h` is in the `freetds-dev` package -- once that's installed, you should be able to get past this `configure` error.

**Comment by bizmate** [comment]
@tianon thanks for the comment but it does not seam to make any difference. I added freetds-dev on the first run but still see 
`checking Checking for ctpublic.h... configure: error: ctpublic.h missing!`

To make sure it installs I use just apt-get install on the package. Like this
`#RUN apt-get install -y php5-sybase`
It seams strange as docker-php-ext-install lists it as a possible extension to install

**Comment by yosifkit** [comment]
It seems the default place it looks for sybase files is `/home/sybase`.  This works:

```console
RUN docker-php-ext-configure sybase_ct --with-sybase-ct=/usr \
	docker-php-ext-install sybase_ct
```

**Comment by bizmate** [comment]
@yosifkit thank you for the reply but I do not get a successful build from this command

```
checking host system type... Invalid configuration `docker-php-ext-install': machine `docker-php-ext' not recognized
configure: error: /bin/bash ./config.sub docker-php-ext-install failed
ERROR: Service 'php5' failed to build: The command '/bin/sh -c docker-php-ext-configure sybase_ct --with-sybase-ct=/usr         docker-php-ext-install sybase_ct' returned a non-zero code: 1
Makefile:5: recipe for target 'build' failed
```
Just to confirm I have added freetsd-dev as suggested before and running this Dockerfile
```
FROM php:5-fpm
# https://dunglas.fr/2014/01/connection-to-a-ms-sql-server-from-symfony-doctrine-on-mac-or-linux/
# Add Free tds
# http://stackoverflow.com/questions/4976971/compiling-php-with-curl-where-is-curl-installed
RUN apt-get update && apt-get install -y  apt-transport-https freetds-bin freetds-dev libcurl4-gnutls-dev \
	libfreetype6-dev libmcrypt-dev libicu-dev

#Add DBLIB PDO driver
RUN docker-php-ext-configure sybase_ct --with-sybase-ct=/usr \
	docker-php-ext-install sybase_ct
#RUN apt-get install -y php5-sybase
```

**Comment by yosifkit** [comment]
Whoops, I missed an `&&` at the beginning of my second line :disappointed: 

```dockerfile
RUN docker-php-ext-configure sybase_ct --with-sybase-ct=/usr \
	&& docker-php-ext-install sybase_ct
```

**Comment by tianon** [comment]
Closing, since this is solved. :+1:

See https://github.com/docker-library/php/issues/75#issuecomment-353673374 for a more long-form explanation of how I normally determine the necessary packages for installing random compiled software in Docker (including and especially PHP extensions).
