### ISSUE TITLE
A bug have to fix

### ISSUE THREAD

**Issue by jkluzhao** [docker-library/php#436]
image php:fpm-alpine dockerfile like below
```
apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
                ...
apk del .build-deps
```
cause unable to extension ,because delete $PHPIZE_DEPS
https://github.com/docker-library/php/blob/76a1c5ca161f1ed6aafb2c2d26f83ec17360bc68/7.1/fpm/alpine/Dockerfile

**Comment by yosifkit** [comment]
Correct, we delete the dependencies to keep the alpine-based images size minimal. If you are installing one of the extensions included with php source, you can use the helper scripts: [see docs](https://github.com/docker-library/docs/tree/0fbef0e8b8c403f581b794030f9180a68935af9d/php#how-to-install-more-php-extensions).  In the alpine based images, the `docker-php-ext-*` scripts [install the `PHPIZE_DEPS` as needed](https://github.com/docker-library/php/blob/fba839b7dfbde029db36e834570a6b546189ee9e/docker-php-ext-install#L92).

You can even use the scripts for [extensions from pecl](https://github.com/docker-library/docs/tree/0fbef0e8b8c403f581b794030f9180a68935af9d/php#pecl-extensions).

```dockerfile
FROM php:7.0-alpine
RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
	&& pecl install redis \
	&& pecl install xdebug \
	&& docker-php-ext-enable redis xdebug \
	&& apk del .phpize-deps
```
