### ISSUE TITLE
Pecl issue since PCRE changes

### ISSUE THREAD

**Issue by baptiste-ls** [docker-library/php#440]
Hi all,

Installing apcu with pecl broke since the update on alpine 7.1 fpm ~11days ago. this seems related to PCRE changes.

I've seen the issue https://github.com/docker-library/php/issues/432, but opcache installation works now without a problem.

Here is the stacktrace:

```running: make
/bin/sh /tmp/pear/temp/pear-build-defaultuserGplcjD/apcu-5.1.8/libtool --mode=compile cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/apcu -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserGplcjD/apcu-5.1.8/include -I/tmp/pear/temp/pear-build-defaultuserGplcjD/apcu-5.1.8/main -I/tmp/pear/temp/apcu -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/apcu/apc.c -o apc.lo
mkdir .libs
 cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/apcu -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserGplcjD/apcu-5.1.8/include -I/tmp/pear/temp/pear-build-defaultuserGplcjD/apcu-5.1.8/main -I/tmp/pear/temp/apcu -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/apcu/apc.c  -fPIC -DPIC -o .libs/apc.o
In file included from /tmp/pear/temp/apcu/apc.c:40:0:
/usr/local/include/php/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
compilation terminated.
Makefile:196: recipe for target 'apc.lo' failed
make: *** [apc.lo] Error 1
ERROR: `make' failed```

**Comment by tianon** [comment]
Can you please provide a more complete `Dockerfile` to replicate the issue?

**Comment by baptiste-ls** [comment]
Thanks for the answer! Here is the Dockerfile:

```
FROM php:7.1-fpm-alpine

RUN set -ex ; \

    apk --no-cache --virtual .setup_dependencies add \
        build-base \
        autoconf \
        openssl; \

    # APCu
    yes "" | pecl install apcu-5.1.8; \
```

**Comment by baptiste-ls** [comment]
I fixed it by installing pcre-dev. In PR https://github.com/docker-library/php/pull/433 pcre-dev was added at build-deps level in php/7.0/fpm/alpine/Dockerfile and not persistent-deps. Maybe that's something that needs to be changed to keep compatibility with previous versions of the tag.

**Comment by yosifkit** [comment]
> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile
>
> \- [Docker Hub readme](https://github.com/docker-library/docs/tree/21fbcc746575cef5105f1377dea2861728ff3954/php#phpalpine)

It was purposely added to `PHPIZE_DEPS` so that it would be removed and the resulting image will be kept as small as possible.  If you are installing extensions then you probably want to use this variable to add the dependencies that other extensions might need when they are compiled (is it used in our `docker-php-ext-*` scripts).

```dockerfile
RUN apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		other-packages \
	&& download-and-install-my-extension \
	&& apk del .build-deps
```

Something similar to these [lines](https://github.com/docker-library/php/blob/fba839b7dfbde029db36e834570a6b546189ee9e/7.1/alpine/Dockerfile#L137-L144) might also be useful to ensure that you don't remove any shared libraries that might be necessary.

**Comment by teohhanhui** [comment]
> Something similar to these lines might also be useful to ensure that you don't remove any shared libraries that might be necessary.

Doesn't running `apk del` after `apk add` risk removing necessary packages if they are present in both `.php-rundeps` and `.build-deps`?

**Comment by yosifkit** [comment]
@teohhanhui, no, they are part of the virtual package `.php-rundeps` so they will not be removed when the other virtual `.build-deps` is deleted.
