### ISSUE TITLE
php-fpm restart service

### ISSUE THREAD

**Issue by wesleyvicthor** [docker-library/php#444]
Why I cannot find the php-fpm service to restart inside the container ?
I cannot run out of the 502 Bad Gateway error as for some reason my nginx container does not find the php-fpm socket, even changing the listen mode.
I am on OSX my docker-compose as follows:
```md
version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./../app:/home/app
      - ./backend.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.1-fpm
    volumes:
      - ./../app:/home/app
    ports:
      - "9000:9000"

**Comment by hairmare** [comment]
Your config looks OK. Is backend.point pointing to `php:9000`? How are you checking for the service? The php container should have a single master process running multiple sub-processes. To reload it you can

```
docker-compose restart php
```

If you need to override parts of the php container you can either do something similar to what you are doing with `backend.conf`. You can also create your own image derived `FROM php:7.1-fpm` with overridden configs. See [the docs](https://docs.docker.com/compose/compose-file/#build) for more info on how to build your own images using docker-compose.

**Comment by wesleyvicthor** [comment]
yes, its pointing to php:9000. what is pissing me off now is that the nginx service is going up and down does not matter what I do. every docker stack deploy it keeps going up and down. and they cannot communicate still.

thanks for your comment @hairmare but I have tried many ways with the ready to go images from official distribution and it seems not work, I will have a try with my own Dockerfile and stack them.

**Comment by wesleyvicthor** [comment]
yay, got it! my ```fastcgi_pass``` from nginx was pointing to a different service name, + I added the networks. thanks to ```docker logs```!

**Comment by NominationP** [comment]
could you tell me detail >.< I'm stuck here
