### ISSUE TITLE
alpine /bin/sh: dpkg-architecture: not found

### ISSUE THREAD

**Issue by ruolinn** [docker-library/php#449]
dpkg-architecture --query DEB_BUILD_GNU_TYPE
/bin/sh: dpkg-architecture: not found

**Comment by yosifkit** [comment]
What version and line are you talking about? `dpkg-architecture` is installed using the  `PHPIZE_DEPS` variable ([line 12](https://github.com/docker-library/php/blob/a403050c0060c6f0664b1c2f30314970e178847e/7.1/alpine/Dockerfile#L12) and [line 93](https://github.com/docker-library/php/blob/a403050c0060c6f0664b1c2f30314970e178847e/7.1/alpine/Dockerfile#L93)).

**Comment by ruolinn** [comment]
sorry my english is poor.
I try alpine 3.4 Dockerfile use PHP7.1 
line gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"  is not found

**Comment by ruolinn** [comment]
+ export CFLAGS=-fstack-protector-strong -fpic -fpie -O2 CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
+ docker-php-source extract
+ cd /usr/src/php
+ dpkg-architecture --query DEB_BUILD_GNU_TYPE
/bin/sh: dpkg-architecture: not found
+ gnuArch=
The command '/bin/sh -c set -xe 	&& apk add --no-cache --virtual .build-deps 		$PHPIZE_DEPS 		coreutils 		curl-dev 		libedit-dev 		libxml2-dev 		openssl-dev 		sqlite-dev 		&& export CFLAGS="$PHP_CFLAGS" 		CPPFLAGS="$PHP_CPPFLAGS" 		LDFLAGS="$PHP_LDFLAGS" 	&& docker-php-source extract 	&& cd /usr/src/php  	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" 	&& ./configure 		--build="$gnuArch" 		--with-config-file-path="$PHP_INI_DIR" 		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" 				--disable-cgi 				--enable-ftp 		--enable-mbstring 		--enable-mysqlnd 				--with-curl 		--with-libedit 		--with-openssl 		--with-zlib 				--with-pcre-regex=/usr 				$PHP_EXTRA_CONFIGURE_ARGS 	&& make -j "$(nproc)" 	&& make install 	&& { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } 	&& make clean 	&& cd / 	&& docker-php-source delete 		&& runDeps="$( 		scanelf --needed --nobanner --recursive /usr/local 			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' 			| sort -u 		| xargs -r apk info --installed 			| sort -u 	)" 	&& apk add --no-cache --virtual .php-rundeps $runDeps 		&& apk del .build-deps 		&& pecl update-channels 	&& rm -rf /tmp/pear ~/.pearrc' returned a non-zero code: 127

**Comment by tianon** [comment]
You're definitely going to need to be more specific about what you're doing: https://travis-ci.org/docker-library/php/jobs/242154086#L444 (it is working for our builds)

**Comment by ruolinn** [comment]
i use chinese alpine /etc/apk/repositories http://mirrors.ustc.edu.cn/alpine/edge/main i change offcial it work
