### ISSUE TITLE
Request to add 7.0-zts-apache image

### ISSUE THREAD

**Issue by evgpisarchik** [docker-library/php#450]
current image [7.0-apache](https://github.com/docker-library/php/blob/master/7.0/apache/Dockerfile)
produces an error on attempt to run Apache in [worker MPM mode](https://httpd.apache.org/docs/2.4/mod/worker.html)

`
php7:crit] [pid 108:tid 140028858967936] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed
Action 'configtest' failed.
The Apache error log may have more information.
`

Do you think it makes sense to implement **7.0-zts-apache image** ?
Would you accept a pull request?

**Comment by yosifkit** [comment]
I really don't want to add even more variations of php compile-time flags. Was it wrong to have the plain zts image from https://github.com/docker-library/php/pull/171?  Would it be fine to just turn it on all the time for the apache image?

**Comment by evgpisarchik** [comment]
The **plain zts image** will work with apache2  in mpm-worker mode but only when **mod_fastcgi** is used (not **mod_php** as it's done for [7.0-apache](https://github.com/docker-library/php/blob/master/7.0/apache/Dockerfile).

**Comment by evgpisarchik** [comment]
Actually I'm fine with the image you've mentioned above.
Thank you.

**Comment by yosifkit** [comment]
So are you saying that we should enable zts always in the apache variant of the php image?  And maybe even remove the zts variant?

Or is this issue resolved?

**Comment by evgpisarchik** [comment]
Sorry for the confusion,

I just wanted to ask if we can add 7.0-zts-apache to allow to configure apache in worker/event mpm mode ( they require thread safe php) 
with usage of mod_php (php/apache should be in the same container as it's done to 7.0-apache, but php isn't thread safe here).

If we use zts image then mod_fastcgi (php/apache are in saparate containers) should be used  instead of mod_php

I didn't mean to change 7.0-apache which allows only prefork mpm mode because it's has non thread safe version of php.

For me this issue solved becase I'm ok to use zts image + a separate container with apache with mod_fastcgi

**Comment by tianon** [comment]
Excellent, thanks for clarifying @evgpisarchik! (and glad you got your use case solved :+1:)
