### ISSUE TITLE
debian stretch update

### ISSUE THREAD

**Issue by Nemo64** [docker-library/php#457]
This is probably huge but I ask anyways.
Is there any plan to update to debian 9 (stretch)?

I have to work with typo3 which now requires libpcre3 in version 8.38 (the old version actually creates segment faults).
Quick search reveals: yep, jessie has only 8.35.

I have tried it with the alpine image and that one works but i feel more comfortable with debian so I'd prefer that.

**Comment by Nemo64** [comment]
If someone has the same problem with libpcre3, i have a workaround using package pinning:

create a `source.list` file:
```
deb http://deb.debian.org/debian stretch main
```
and a `source.preference` file:
```
Package: *
Pin: release a=jessie
Pin-Priority: 600

Package: *
Pin: release a=stretch
Pin-Priority: 500

Package: libpcre3*
Pin: release a=stretch
Pin-Priority: 900
```
And add this to your Dockerfile
```
COPY source.list /etc/apt/sources.list.d/
COPY source.preference /etc/apt/preferences.d/
```
So now, if you try to install libpcre3, it will be downloaded from the stretch release. So now you just need to install the newer libpcre (preferably in your existing apt-get install command)
`apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y libpcre3 libpcre3-dev`

I haven't found something breaking yet but package pinning (especially with libraries) is a bit of an adventure so be careful.

**Comment by tianon** [comment]
See https://github.com/docker-library/php/pull/448.

I think https://github.com/docker-library/php/pull/360 and https://github.com/docker-library/golang/pull/131#issuecomment-270677556 are also relevant (since a Debian version bump is going to be a similar situation). :disappointed:

**Comment by yosifkit** [comment]
Closing in favor of discussion to create base distro update process https://github.com/docker-library/php/issues/504.
