### ISSUE TITLE
Desbian strech with PHP7

### ISSUE THREAD

**Issue by piclemx** [docker-library/php#461]
I don't find any image with both.... how could a create or have this image?

**Comment by tianon** [comment]
See https://github.com/docker-library/php/pull/448.

I think https://github.com/docker-library/php/pull/360 and https://github.com/docker-library/golang/pull/131#issuecomment-270677556 are also relevant (since a Debian version bump is going to be a similar situation).

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/php/issues/504. :+1:
