### ISSUE TITLE
intl_ext is not enabled

### ISSUE THREAD

**Issue by xpr0ger** [docker-library/php#462]
I have a problem related to intl_ext, it seems not enabled.  PHP -m does not contain it. What I've missed? What should I do to enable this extension? And yes, every time build is completed without any errors.

```
FROM php:7.1.2-fpm

RUN apt-get update && apt-get install -y \
        libicu-dev \
        && docker-php-ext-configure intl \
        && docker-php-ext-install intl
```

**Comment by hairmare** [comment]
`docker-php-ext-enable intl` should help

**Comment by xpr0ger** [comment]
Nope, I've already tried it. I got messege that intl.so already loaded. But
thank you for your suggestion.

5 июля 2017 г. 12:05 AM пользователь "Lucas Bickel" <
notifications@github.com> написал:

**Comment by hairmare** [comment]
I tried to reproduce your issue and wasn't able to do so. When I build an image using your Dockerfile `php -m` contains `intl` as expected.

Is you local `php:7.1.2-fpm` image up to date? Maybe running `docker pull php:7.1.2-fpm` before buildig helps?

**Comment by xpr0ger** [comment]
Yes, that was the reason. Thanks a lot.
