### ISSUE TITLE
Installation of curl fails -  easy.h should be in <curl-dir>/include/curl/

### ISSUE THREAD

**Issue by laurin1** [docker-library/php#467]
dockerfile:

FROM php:7.1.7-apache
RUN apt-get update \
	&& docker-php-ext-install curl fileinfo imap ldap mbstring mysqli openssl pdo_mysql soap odbc ftp 

Produces this:

checking for cURL support... yes, shared
checking for cURL in default path... not found
configure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/

Well, just found the same issue in PHPBrew:

https://github.com/phpbrew/phpbrew/issues/861

And a bug has been filed with PHP itself:

https://bugs.php.net/bug.php?id=74125

**Comment by tianon** [comment]
Isn't `curl` already enabled in the image by default?
```console
$ docker pull php:7.1-apache
7.1-apache: Pulling from library/php
Digest: sha256:bf65d92b08473d628c6af87b4b9da1dec434e2bb2dce1c98192470547b314d10
Status: Downloaded newer image for php:7.1-apache

$ docker run --rm php:7.1-apache php -i | grep curl
Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--disable-cgi' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pcre-regex=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-apxs2' 'build_alias=x86_64-linux-gnu'
curl
```

**Comment by laurin1** [comment]
Ah, yes, you are correct. I'm on Windows and I assumed from the docs that anything enabled by extension= was not enabled in this repo, thanks.

**Comment by tianon** [comment]
:+1:
