### ISSUE TITLE
docker exec error 7-fpm-alpine

### ISSUE THREAD

**Issue by crashbtz** [docker-library/php#469]
Hi, 
I'm trying to run 7-fpm-alpine docker image and when the container is running and i'm trying  docker exec

    docker exec -ti <my_conaitner> bash

I have this error:

    rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH"

I don't have this issue with 7-fpm image

Thanks

**Comment by tianon** [comment]
Indeed, the Alpine images do not include "bash" by default -- you'll need
to either install it, or use "sh" instead.

**Comment by crashbtz** [comment]
Ok thanks both of you for the answer
