### ISSUE TITLE
Missing dependency for bz2 ext

### ISSUE THREAD

**Issue by denisura** [docker-library/php#47]
Installation of bz2 extension in inherited dockerfile throws error

```
RUN docker-php-ext-install bz2
```

```
configure: error: Please reinstall the BZip2 distribution
```

In order to fix it the following dependency needs to be installed

```
RUN apt-get update && apt-get install -y libbz2-dev
```

**Comment by pboethig** [comment]
RUN apt-get update && apt-get install -y libbz2-dev
RUN docker-php-ext-install bz2

Works for me

**Comment by bumbummen99** [comment]
Put that somewhere or below the last installed extension in your Workspace Dockerfile:

```
###########################################################################
# BZ2:
###########################################################################

USER root

ARG INSTALL_BZ2=false

RUN if [ ${INSTALL_BZ2} = true ]; then \
    apt-get update && \
    apt-get install -y libbz2-dev && \
    apt-get install -y php${LARADOCK_PHP_VERSION}-bz2 \
;fi
```

Don't forget to add the env var in your .env and map it in your .yml (or remove the if...)
