### ISSUE TITLE
How to change built-in database sqlite3 ?

### ISSUE THREAD

**Issue by Heer0** [docker-library/php#470]
I need to activate **SQLITE_ENABLE_UPDATE_DELETE_LIMIT** option in SqLite, but i have no idea how to do that :/.

thank you in advance.

**Comment by yosifkit** [comment]
As far as I can tell you have to download and compile your own sqlite or just use a subselect:

- https://stackoverflow.com/questions/1824490/how-do-you-enable-limit-for-delete-in-sqlite
- https://stackoverflow.com/questions/8516627/php5-sqlite3-recompile-for-update-delete-limit
