### ISSUE TITLE
php5.6-fpm on windows 10 home work not stable

### ISSUE THREAD

**Issue by apapacy** [docker-library/php#476]
php5.6-fpm on windows 10 home work not stable
some request return 500 http status
pm.max_children = 1 in configuration file fix it

**Comment by tianon** [comment]
We use the default values provided by upstream.  See https://github.com/docker-library/php/issues/162 for some additional discussion of this topic. :+1:

**Comment by apapacy** [comment]
I'm switch to another tools. Close this issuses.
