### ISSUE TITLE
Apache envvars not being loaded

### ISSUE THREAD

**Issue by evertramos** [docker-library/php#481]
Hello there!

It seems for some reason that this merge did not correct the **envvar** for php-7.1.8-apache as of https://github.com/docker-library/php/pull/251/files

Same point of https://github.com/docker-library/php/issues/97

**Comment by yosifkit** [comment]
7.1-rc1 was added in #296 and has the same changes as #251.

https://github.com/docker-library/php/blob/c8a1150f4b3cf8afe862084da8a40c7cfcf75b4e/7.1/apache/apache2-foreground#L4-L16
