### ISSUE TITLE
7.1.8-fpm-alpine does not build

### ISSUE THREAD

**Issue by DanielMack** [docker-library/php#490]
Currently, the aforementioned Dockerfile is not buildable - neither with a local Docker instance nor the [official, automated build-system](https://docs.docker.com/docker-hub/builds/).

Error on Dockerhub : 

> [91m+ export CFLAGS=-fstack-protector-strong -fpic -fpie -O2 CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
>\+ docker-php-source extract
>/bin/sh: docker-php-source: Permission denied
>[0m
>Removing intermediate container 90f5950ae10f

Error on a local docker instance (17.06.1-ce): 

>\+ export CFLAGS=-fstack-protector-strong -fpic -fpie -O2 CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
>\+ docker-php-source extract
>/bin/sh: docker-php-source: not found

**Comment by DanielMack** [comment]
error on a pretty clean debian system (Kernel 3.16.0-0.bpo.4-amd64) : 

> /bin/sh: docker-php-source: Permission denied

**Comment by yosifkit** [comment]
Perhaps the same as: https://github.com/docker-library/ghost/pull/83#issuecomment-324768379.  In other words, are the files executable (`chmod +x`) before being committed to whatever git repo they are in?

**Comment by DanielMack** [comment]
sorry, no - just did a chmod +x on all of the files and re-tried it on all three docker instances ... same result

**Comment by tianon** [comment]
I cannot reproduce (and neither can the official images build server, as can be seen by the image tags being pushed) -- do you have an example Git repository which exhibits the issue in a way that can help us reproduce?

**Comment by DanielMack** [comment]
https://github.com/DanielMack/php-fpm-alpine

**Comment by tianon** [comment]
Ah, newlines are bad on your shell scripts -- you've got `\r\n` (which is common on Windows), but need simply `\n`.  There's a tool called `dos2unix` which you might have, or there's a setting in Git for Windows which can help (see https://help.github.com/articles/dealing-with-line-endings/).

```console
/ # hexdump -C docker-php-source | head -n1
00000000  23 21 2f 62 69 6e 2f 73  68 0d 0a 73 65 74 20 2d  |#!/bin/sh..set -|
```
(note the `0d 0a`, which should simply be `0a`)

**Comment by DanielMack** [comment]
ERMAGERD - THANK YOU

Its now building unter linux ... Windows Docker still crashes, though

**Comment by helloMJW** [comment]
如果是在windows编辑, 然后再Linux 执行build. 也会导致 docker-php-source: not found 
因为在windows编辑的文件到Linux上会出现 ^M 字符.
