### ISSUE TITLE
php 7.2rc stretch with argon2 password hashing?

### ISSUE THREAD

**Issue by morloderex** [docker-library/php#515]
Hello with php 7.2 argon password hashing was added with an addional configuration flag `--with-password-argon2` how can i add this configuration flag during compiliation without recompiling the image all over again? 

I know that stretch has the library `libargon2-dev`.

**Comment by tianon** [comment]
Looks like the library is `libargon2-0-dev` in Debian -- it's in Alpine also (`argon2-dev`), but only in `edge`.

It's technically part of the `standard` extension, but I tried for a while to recompile just that without rebuilding PHP itself to no avail. :disappointed:

I think we'll probably need to consider including this flag directly in our build if it's something recommended by PHP.

Looks like once Debian gets 7.2, they'll have it enabled: https://gitlab.com/deb.sury.org/php/commit/a91992745b62690ef5257cd6597ad0a8d7afe9ff (which is a positive sign for us)

I'll work a bit on a patch and see what I can come up with.

**Comment by tianon** [comment]
https://github.com/docker-library/php/pull/521 :metal:
