### ISSUE TITLE
PCRE is to old (at least for 7.1-fpm tag)

### ISSUE THREAD

**Issue by josefglatz** [docker-library/php#516]
Hi,

the PHP 7.1 image `php:7.1-fpm` has an too old PCRE Library Version which may triggers PHP segmentantion faults.

At least PCRE Library Version 8.38 is needed afaik

**Comment by tianon** [comment]
This sounds related to some of the issues being alluded to in https://github.com/docker-library/php/issues/495.

**Comment by josefglatz** [comment]
indeed. We can close it therefore?

**Comment by tianon** [comment]
Agreed, thanks @josefglatz :+1:
