### ISSUE TITLE
GD lib support for jpg/freetype/freetype2 is missing (php:7.1-fpm)

### ISSUE THREAD

**Issue by josefglatz** [docker-library/php#517]
The mentioned supports are missing. Are there any reasons for that?

**Comment by tianon** [comment]
See https://hub.docker.com/_/php/ under "How to install more PHP extensions", specifically "PHP Core Extensions" (https://github.com/docker-library/docs/blob/40230cffa9ede247bd2212e1ca5ace407efb90df/php/README.md#how-to-install-more-php-extensions), of which the first real example is installing `gd`.

It would be very complex (and large) for us to pre-compile every possible PHP core extension into the image, so we instead opted for an approach which allows our users to install them after the fact which keeps the core image smaller and simpler.
