### ISSUE TITLE
arm32v7 images are built on armel, not armhf

### ISSUE THREAD

**Issue by xobs** [docker-library/php#518]
Docker images built for arm32v7 are built using armel debian, and not armhf.  This means that binaries that may normally be run on armhf linux cannot be run inside php images.

````
novena@novena-k8s-3:~$ dpkg --print-architecture
armhf
novena@novena-k8s-3:~$ docker run -it --rm php:7.2-rc-apache dpkg --print-architecture
armel
novena@novena-k8s-3:~$ 
````

**Comment by xobs** [comment]
The node package gets the correct architecture, for example:

````
novena@novena-k8s-3:~$ docker run -it --rm node:9.0.0 dpkg --print-architecture
armhf
novena@novena-k8s-3:~$
````

**Comment by tianon** [comment]
What you're seeing is actually https://github.com/moby/moby/issues/34875 -- Docker doesn't consider `variant` when picking an image to pull/run.

If you use `arm32v7/php:7.2-rc-apache` explicitly, it will always provide the image you expect (and in fact, the official image build servers do exactly that -- `docker pull arm32v7/php:7.2-rc-apache && docker tag arm32v7/php:7.2-rc-apache php:7.2-rc-apache` when building something which is `FROM php:7.2-rc-apache` on `arm32v7` to ensure the correct bits are pulled/used).

**Comment by xobs** [comment]
I see.  What is it that the Node package does differently that allows it to work?  When a fix is made (to moby?), will I need to update Docker, or just re-pull php:7.2-rc-apache?

**Comment by tianon** [comment]
Node doesn't support `arm32v5` -- only `arm32v7` (so `v7` is the only `variant` available with `arch: arm` on Node, which also means it won't work on the RPi 1 or zero as-is).

Once a fix is made in Moby, it'll need to make its way into a Docker release, then yeah, you'll update and re-pulling `php:xxx` should DTRT. :+1:
