### ISSUE TITLE
PHP Zip Archive Enabled Fail

### ISSUE THREAD

**Issue by trungtv** [docker-library/php#52]
I have wordpress with this php docker and runing into this issue: 
PHP Version [5.6.3] Pass 
Zip Archive Enabled Fail

Could anyone please show me how to enable zip support in this php container? docker-php-ext-install zip saying that I need to install zlib1g-dev but that package is not found within this debian build (apt-get install zlib1g-dev).
 Thanks

**Comment by blachawk** [comment]
Is there anyway we can process these same commands through a docker-compose yml file?

**Comment by blachawk** [comment]
Then how do we install, mysql, wordpress and zipArchive, all in a single file???
