### ISSUE TITLE
Old PID not allow container to restart

### ISSUE THREAD

**Issue by gdvyas** [docker-library/php#53]
I am using docker image php:5.3.29-apache on Ubuntu 14.04.1 ( docker 1.3.2)

The Docker Container created from this image is not able to start when it is not exited cleanly.

So, I have to remove the below file manually.

sudo rm /var/lib/docker/aufs/diff/"CONTAINER ID"/run/apache2/apache2.pid

Similar problem was observed when created my own image for  Nagios Monitor. I tried to clean up using command 
"/usr/sbin/apache2 -D FOREGROUND -k restart" 
in supervised

**Comment by kotowick** [comment]
Was this issue resolved? I am getting the same error when I reboot OSX, and start my last container -- Apache fails due to the PID issue.

**Comment by tianon** [comment]
Yes, if you update your `php:*apache` base image (and rebuild anything dependent), you should have the fix that was merged in https://github.com/docker-library/php/pull/59.

**Comment by tianon** [comment]
Fixed in #59.
