### ISSUE TITLE
Proposal: add -debug image variants

### ISSUE THREAD

**Issue by csandanov** [docker-library/php#530]
In images tagged as `-debug` compile PHP with `--enable-debug` flag and do not strip bins. 

I know you don't want to increase already long build time but I've decided it worth to leave a formal request. Meanwhile, I'm using my own fork https://github.com/wodby/base-php

**Comment by tianon** [comment]
> I know you don't want to increase already long build time

Indeed, we're already way overblown as it is. :disappointed:

```console
$ bashbrew list --uniq php | wc -l
31
```

(Yes, to build the official supported set of images for the `php` image, we currently have to build all of PHP no less than 31 times. :white_flag: :scream:)

Additionally, https://github.com/docker-library/php/issues/504 is going to complicate this further.

On top of all that, EOL dates for the currently supported versions are not terribly encouraging:

5.6: 31 Dec 2018
7.0:  3 Dec 2018
7.1:  1 Dec 2019
7.2: 30 Nov 2020

(from https://secure.php.net/supported-versions.php)

Not sure what to do here. :disappointed: :cry:

**Comment by csandanov** [comment]
Ok, thank you for clarifying :)

**Comment by csandanov** [comment]
In case someone needs `--enable-debug` images, we maintain a fork of this repo with alpine only images and `-debug` variants https://github.com/wodby/base-php
