### ISSUE TITLE
Use multi stages builds 

### ISSUE THREAD

**Issue by sylr** [docker-library/php#538]
Hi,

Current images ship with the building environment it required to build the binaries.

With [Docker multi stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) the result of the build can be copied to a new clean image that does not have the build env with is not required anymore, e.g. :

```
FROM golang:1.7.3 as builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go    .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]  
```

With this images will be lighter.

Regards.

**Comment by yosifkit** [comment]
The alpine-based php images are made for this exact reason; they are small and [remove build dependencies](https://github.com/docker-library/php/blob/e1dd0a7e1f0201f63da2050f4c165cbc6dc78d1c/7.2/alpine3.7/cli/Dockerfile#L146) in the layer that they are added to save space.  No need to have a multi stage build for that.

For more information on why official-images do not use multi stage builds, see https://github.com/docker-library/official-images/issues/3383.
