### ISSUE TITLE
PHP 7.2-apache on Debian 8

### ISSUE THREAD

**Issue by AndryBray** [docker-library/php#545]
Please, could you add support to php 7.2 on Debian 8 jessie?
Thank you

**Comment by tianon** [comment]
As seen in https://github.com/docker-library/php/issues/504, the plan is actually to eventually transition everything _off_ Jessie.  What's the use case that warrants sticking with Jessie variants?

**Comment by AndryBray** [comment]
The main reason is about third party components/libs which are not supported on debian stretch

**Comment by scottconnerly** [comment]
For example, coreutils recognizing overlayfs (https://www.gnu.org/software/coreutils/filesystems.html). overlayfs is available in stretch but not jessie.

This is specifically important for tailing log files (https://lists.gnu.org/archive/html/bug-coreutils/2016-03/msg00067.html).
