### ISSUE TITLE
Can't run php:7.2-fpm-alpine

### ISSUE THREAD

**Issue by cacahouwete** [docker-library/php#559]
```sh
$ uname -a
Linux pcAlexandreVinet 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker run --rm -ti php:7.2-fpm-alpine sh
Unable to find image 'php:7.2-fpm-alpine' locally
7.2-fpm-alpine: Pulling from library/php
docker: no matching manifest for linux/amd64 in the manifest list entries.
```

I can't run the image, do you have any idea why ?

**Comment by ottaviano** [comment]
nop, but it works for me with `7.2-fpm-alpine3.7`

**Comment by frankdejonge** [comment]
Seems this problem was the effect of something that happened in the last 24 hours. It worked yesterday but today it's missing the manifest.

**Comment by mykiwi** [comment]
@ottaviano Yes, because it's not the same image. Here it's `php:7.2-fpm-alpine3.6`

**Comment by frankdejonge** [comment]
@mykiwi that's correct, but how does that relate to this issue?

**Comment by adamquaile** [comment]
Just to clarify, I'm getting the same error running `docker run --rm -ti php:7.2-fpm-alpine3.6 sh` but `docker run --rm -ti php:7.2-fpm-alpine3.7 sh` is working.

So it doesn't seem to be just that the image has gone, but now something's missing. I'm guessing recent changes have broken something but it'll probably start working again soon. Fingers crossed!

**Comment by tianon** [comment]
Looks like the build failed: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/14/console

I've kicked it off again.  See https://github.com/docker-library/official-images/issues/3835 for more details about this problem.
