### ISSUE TITLE
arm64v8/php:7.2.1-apache-stretch exits in 2 seconds

### ISSUE THREAD

**Issue by meteortech** [docker-library/php#573]
I have just installed a new raspberry pi and have the latest raspbian os.  After setting up docker and trying to use this container for a web server for quite some time, I cannot get it to stay active.  

Here is my simplest attempt:
$ sudo docker run -d -p 80:80 --name my-apache-php-app -v "$PWD":/var/www/html arm64v8/php:7.2.1-apache-stretch

response is:
4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa

So it appears the container built correctly and started.

Next check status:
$ sudo docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                     PORTS               NAMES
4d11182d2538        arm64v8/php:7.2.1-apache-stretch   "docker-php-entrypoi…"   7 seconds ago       Exited (1) 5 seconds ago                       my-apache-php-app

So it appears to have run for 2 seconds.

Next inspect the container:
$ sudo docker inspect my-apache-php-app
[
    {
        "Id": "4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa",
        "Created": "2018-01-28T04:14:59.79770593Z",
        "Path": "docker-php-entrypoint",
        "Args": [
            "apache2-foreground"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2018-01-28T04:15:01.220937597Z",
            "FinishedAt": "2018-01-28T04:15:01.183940176Z"
        },
        "Image": "sha256:23850003068fb436aa9cd09d79119e8850c393404086d0aa6de543fac4cf6372",
        "ResolvConfPath": "/var/lib/docker/containers/4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa/hostname",
        "HostsPath": "/var/lib/docker/containers/4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa/hosts",
        "LogPath": "/var/lib/docker/containers/4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa/4d11182d2538cdfee7731afb444bd6514636f1bd4213b190670c7f00240304aa-json.log",
        "Name": "/my-apache-php-app",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/pi/Docker/webserver:/var/www/html"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/f48ecd5b17a83e69a4a03bdbb54cb94e2f94137a8f556e27c2209131e3325c26-init/diff:/var/lib/docker/overlay2/de2c0bc83b085b132f072f8de6b10ae78cb855dbb3c119cd1c24285a16a94ed8/diff:/var/lib/docker/overlay2/f1167c647a809261262c1744edbb1776637fb50109e99fa87a7c31d2901adf3e/diff:/var/lib/docker/overlay2/0932dbd3868c3cb6798437069b28cd0f10063c5b5571d5fd57b5a85492d62148/diff:/var/lib/docker/overlay2/1c65bb3eb6ea6f996733e4a64496fb24e382acecfcc6e7af9657dbe2d193f209/diff:/var/lib/docker/overlay2/ee5649c0f42a1792b69c4b5371b79a1a2d31f0b2cb91038e5756920f93d96ef6/diff:/var/lib/docker/overlay2/f1ca14c023a216edef0f014c616773252525771e36b4371c45b8b3a3060066a2/diff:/var/lib/docker/overlay2/708f955f928955d7bb46323d24b49b5a78c4f5d337736a231e21ae2cb6284569/diff:/var/lib/docker/overlay2/01e4680935421d57d107c951319082fc1da502966fcc98c4281a9f6933e12b5c/diff:/var/lib/docker/overlay2/d4c4d1a094b2c067aa3962668cfda3f4b683ad777cfda677942029597c9b9ce7/diff:/var/lib/docker/overlay2/17518ce73e2f50125c048451584010e506947b7f8a25137207fda3949273fa29/diff:/var/lib/docker/overlay2/66c07a2ac18219d4335c91d48186f8765b7153f66f9f425a6386a2669960e641/diff:/var/lib/docker/overlay2/42c1a8630b2833c75c4fb17290cec48332b974d0ccf27b51c046ebef06a48a87/diff:/var/lib/docker/overlay2/c4167678150f3b8376c815bdcaaf95e178ac53f6ea8aaeae16bff56c4561c744/diff:/var/lib/docker/overlay2/5fcf0fea7c7f79b8dfa9e2d195cd7783443e732fbabdb74f819383e73fe93a3e/diff",
                "MergedDir": "/var/lib/docker/overlay2/f48ecd5b17a83e69a4a03bdbb54cb94e2f94137a8f556e27c2209131e3325c26/merged",
                "UpperDir": "/var/lib/docker/overlay2/f48ecd5b17a83e69a4a03bdbb54cb94e2f94137a8f556e27c2209131e3325c26/diff",
                "WorkDir": "/var/lib/docker/overlay2/f48ecd5b17a83e69a4a03bdbb54cb94e2f94137a8f556e27c2209131e3325c26/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/pi/Docker/webserver",
                "Destination": "/var/www/html",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "4d11182d2538",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "APACHE_CONFDIR=/etc/apache2",
                "APACHE_ENVVARS=/etc/apache2/envvars",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie",
                "GPG_KEYS=1729F83938DA44E27BA0F4D3DBDB397470D12172 B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F",
                "PHP_VERSION=7.2.1",
                "PHP_URL=https://secure.php.net/get/php-7.2.1.tar.xz/from/this/mirror",
                "PHP_ASC_URL=https://secure.php.net/get/php-7.2.1.tar.xz.asc/from/this/mirror",
                "PHP_SHA256=6c6cf82fda6660ed963821eb0525214bb3547e8e29f447b9c15b2d8e6efd8822",
                "PHP_MD5="
            ],
            "Cmd": [
                "apache2-foreground"
            ],
            "ArgsEscaped": true,
            "Image": "arm64v8/php:7.2.1-apache-stretch",
            "Volumes": null,
            "WorkingDir": "/var/www/html",
            "Entrypoint": [
                "docker-php-entrypoint"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "bd884092a1afe9a71a7485e149aa33bc3d467366c22867c0484fcf8010189843",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/bd884092a1af",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f1d1a972a52b62508ceeffb901b280a7d6d8cf870dba81954e8ec6b5d6470db3",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

Any ideas as to the cause and how to fix?

**Comment by meteortech** [comment]
Additional info...
$ sudo docker logs my-apache-php-app
standard_init_linux.go:195: exec user process caused "exec format error"

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

**Comment by meteortech** [comment]
I tried running the apache2 without php and got the same result...

$ sudo docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ arm64v8/httpd:2.4
Unable to find image 'arm64v8/httpd:2.4' locally
2.4: Pulling from arm64v8/httpd
7e6d91e96b32: Pull complete 
f8ceb7a19a3d: Pull complete 
06475130e788: Pull complete 
0b3f571e1cfd: Pull complete 
17affcb06d02: Pull complete 
aeb4b7d984fa: Pull complete 
aa28af7804e5: Pull complete 
Digest: sha256:80e70512b7e65966905b86e6f374479ac216124e0e6a7f5b952b6b43d6ba79c6
Status: Downloaded newer image for arm64v8/httpd:2.4
0d27d857bb577fdd1fa6d77eafc5c5c52eeac7ff1d748f88bc92191af99ed64e

$ sudo docker logs my-apache-app
standard_init_linux.go:195: exec user process caused "exec format error"

**Comment by yosifkit** [comment]
Since you are running Raspbian, you cannot run arm64 based images. This is the reason for the exec format error. Raspbian (even on a Raspberry Pi 3) is only 32-bit (arm32v6).

You can use `httpd:2.4-alpine` and Docker will pull the right [architecture](https://hub.docker.com/r/arm32v6/httpd/), if you pull `php:7.2.1-apache-stretch`  it would be [arm32v5](https://hub.docker.com/r/arm32v5/php/) since there is no [arm32v6](https://hub.docker.com/r/arm32v6/php/) version.  This is because Debian does not support arm32v6.
