### ISSUE TITLE
7.2.2 , 7.1.14 not published docker hub

### ISSUE THREAD

**Issue by Meabed** [docker-library/php#580]
Hey guys
7.2.2 , 7.1.14 not published docker hub. travis failed as well.

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/php" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/php), especially [PRs with the "library/php" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fphp). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).


I'm sure we'll be making a PR to update images later today.
