### ISSUE TITLE
Alpine Images with Argon2 support

### ISSUE THREAD

**Issue by krenor** [docker-library/php#585]
https://github.com/docker-library/php/pull/521
Would be awesome if it'd be pre-compiled for alpine images, too. 👍

**Comment by tianon** [comment]
The primary blocker here is that Alpine doesn't yet contain the necessary library in a released version:

- https://pkgs.alpinelinux.org/packages?name=*argon2*&branch=v3.7
- https://pkgs.alpinelinux.org/packages?name=*argon2*&branch=edge

**Comment by tianon** [comment]
(So there's not much we can do until that's resolved.)
