### ISSUE TITLE
Try multiple gpg keyservers

### ISSUE THREAD

**Issue by csandanov** [docker-library/php#586]
I often get an error `gpg: keyserver receive failed: No keyserver available`. I suggest to try multiple key servers if one fails:
```
ha.pool.sks-keyservers.net
hkp://keyserver.ubuntu.com:80
hkp://p80.pool.sks-keyservers.net:80
pgp.mit.edu
```

It's really hard to understand sometimes why a key server isn't available, for example, it may be available from travisci but not available from a local machine. It could be caused by proxy services (.e.g. cloudflare) IPs being blocked by a government regulator (hello to abhorrent Roskomnadzor) which used by a key server. Besides, sometimes it just randomly happens even on travisci, so it can improve the build time.

Example script: https://github.com/wodby/alpine/blob/master/bin/gpg-verify.sh

**Comment by yosifkit** [comment]
My current opinion of this is expressed in https://github.com/docker-library/cassandra/pull/131#issuecomment-358444537.

Related issues: https://github.com/docker-library/tomcat/issues/87, https://github.com/docker-library/tomcat/pull/108, https://github.com/docker-library/mysql/issues/263#issuecomment-354025886 and https://github.com/docker-library/httpd/issues/66#issuecomment-316832441

**Comment by tianon** [comment]
Indeed, this is a rampant issue with the public PGP infrastructure in general.

> We've gone back and forth on adding a similar loop but don't want to yet open the flood gates to repeat this loop in all of the images maintained in http://github.com/docker-library.  We recommend just pulling the images from Docker Hub rather than building them yourself, but if you must build it, then editing the file to choose a gpg server that is better for your location is the solution (a quick `sed` or `awk` before `docker build`).
