### ISSUE TITLE
Client for connect to MySQL 8.0.4

### ISSUE THREAD

**Issue by bscheshirwork** [docker-library/php#590]
I try to use fresh mysql. I have errors:
```
Next PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /var/www/html/framework/db/Connection.php:686
...
PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /var/www/html/framework/db/Connection.php:686
```

I can see 

https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/ 

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-4.html chapter Security Notes

> Further, it is always possible to change ––default-authentication-plugin to a non-default value of your choice (At present, options other than caching_sha2_password are: mysql_native_password and sha256_password). For example, if ––default-authentication-plugin is set to mysql_native_password, the behavior of the MySQL 8.0.4 server is similar to MySQL 8.0.3 and prior. Correspondingly, libmysqlclient supports the MYSQL_DEFAULT_AUTH options for mysql_options() C API function. (For libmysqlclient based client tools available in MySQL packages, the ––default-auth command-line options achieves the same purpose.) The client-side option is a performance tool and saves an extra round-trip when used in tandem with ––default-authentication-plugin option on server side.

> We also recommend updating libmysqlclient to MySQL 8.0.4 or later so that new default authentication plugin is supported by clients that use it.

how to configure `mysqlnd`? 
https://github.com/docker-library/php/blob/be08d2067c6c6b4b9b061a0b082bf8630117a217/7.2/alpine3.7/fpm/Dockerfile#L120

or /may be/ update it (I can't find new version)?

just join link https://github.com/yiisoft/yii2/issues/15741

**Comment by bscheshirwork** [comment]
https://github.com/docker-library/mysql/issues/380

**Comment by yosifkit** [comment]
Going to close here as it seems to be an issue with mysql:8.0.4 and not specifically with php. 

Reminder that MySQL 8 series is still a "Development Release" and not a "Gernerally Available" release (https://dev.mysql.com/downloads/mysql/).
