### ISSUE TITLE
error! pls help me

### ISSUE THREAD

**Issue by irondevelopers** [docker-library/php#593]
Hello there,
My server debian 9.3
I want to install php 7.2 zts.
But I do not know how to do it!
When I run update.sh I get the following error: error: unable to determine release 5.6

**Comment by bweston92** [comment]
Hi @irondevelopers you do not need to run `update.sh` this repository contains Dockerfiles which build Docker images that are hosted on Docker Hub.

So with Docker [installed](https://docs.docker.com/install/) you can run the following `docker pull php:7.2` check out the Hub page for all the available tags/versions.

https://hub.docker.com/r/_/php/

**Comment by irondevelopers** [comment]
Hello there,
thanks for the answer!
I used this command: docker pull php: 7.2.2-zts-stretch
php was not installed. What else do I have to do

![aaa](https://user-images.githubusercontent.com/36849861/36721196-4476a5c0-1bbb-11e8-8835-086bd41fa188.PNG)

**Comment by ItsReddi** [comment]
@irondevelopers you're wrong here. This repository is not for installing php on you machine.
Its supposed to launch a php container.

**Comment by tianon** [comment]
Indeed -- this is not the repository you're looking for.  You're probably looking for https://secure.php.net/manual/en/install.php. :+1:
