### ISSUE TITLE
Outdated sodium extension + library in PHP 7.2 images / Cant update sodium library in child image

### ISSUE THREAD

**Issue by ReDev1L** [docker-library/php#598]
https://github.com/docker-library/php/blob/35aedb29009b46af6ea1009c9405d01d3f66968e/7.2/stretch/fpm/Dockerfile#L108
https://github.com/docker-library/php/blob/35aedb29009b46af6ea1009c9405d01d3f66968e/7.2/stretch/fpm/Dockerfile#L146

Remove this two lines please, i cant update sodium library in my child image cuz of those.

warning: sodium (sodium.so) is already loaded!

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/540#issuecomment-362784125 and following discussion for why this was enabled by default.

I wonder if we could convince PHP to compile it as a shared library so it can be more easily replaced afterwards if necessary.

**Comment by ReDev1L** [comment]
Thats really strange decision...

**Comment by ReDev1L** [comment]
Any thoughts on workaround?

**Comment by tianon** [comment]
https://github.com/docker-library/php/pull/605 :+1:
