### ISSUE TITLE
[feature request] docker-php-ext-install-and-enable script

### ISSUE THREAD

**Issue by lakano** [docker-library/php#603]
Hi,
After some hours to search for each of our ~20 extensions how to install, configure, enable them, I suggest to have a small all-in-one script, one call, to install required apk/deb packages, execute docker-php-ext-install / docker-php-ext-configure with the default arguments (but ideally where we can adjust them in extra parameters), call docker-php-ext-enable to enable them and clean all unused files on the disk.

Something like that:
docker-php-ext-install-and-enable redis geoip imagick igbinary gd --with-freetype-dir=/override/default/path/ 

This could be really useful :)

**Comment by tianon** [comment]
`docker-php-ext-install` does already imply `-enable`:

https://github.com/docker-library/php/blob/35aedb29009b46af6ea1009c9405d01d3f66968e/docker-php-ext-install#L107-L111

There's a _lot_ of discussion over in https://github.com/docker-library/php/issues/75 about automatically installing the required packages, especially why it's not really feasible to do for the maintainers of this project, but would definitely be a worthy project for someone external to take on as something that builds upon this image (but will likely require a fair amount of bandwidth to get started and keep up to date; see https://github.com/docker-library/php/issues/75#issuecomment-353673374 for more on that).
