### ISSUE TITLE
docker-php-ext-install zip fails

### ISSUE THREAD

**Issue by schmunk42** [docker-library/php#61]
It requires the zlib system package, a workaround is to add this to your `Dockerfile`

```
RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev
```

**Comment by yosifkit** [comment]
See docs forthcoming: https://github.com/docker-library/docs/pull/130

**Comment by tianon** [comment]
Fixed via documentation in docker-library/docs#130.

**Comment by jonbaldie** [comment]
If it helps anyone using the Alpine image, I succeeded with `zlib-dev`.

**Comment by qiangli** [comment]
for php:7.3-apache/debian
```
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --fix-missing \
    apt-utils \
    gnupg

RUN echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list
RUN echo "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list
RUN curl -sS --insecure https://www.dotdeb.org/dotdeb.gpg | apt-key add -

RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev
RUN docker-php-ext-install zip
```

**Comment by baldasso** [comment]
> If it helps anyone using the Alpine image, I succeeded with `zlib-dev`.

In Alpine I have to install libzip-dev too: `apk add libzip-dev`

**Comment by Glendog** [comment]
Did anyone get this working? 

```
FROM php:7.4-fpm-alpine

WORKDIR /var/www/html

RUN docker-php-ext-install pdo pdo_mysql zip
```

I get the zlib needed error. I added the code above but it says apk-get is not found.
