### ISSUE TITLE
PHP versions at end-of-life

### ISSUE THREAD

**Issue by mlocati** [docker-library/php#610]
First of all, let me explain our situation: we have a server with PHP 5.5 running a huge project. It has been developed during 5 years by 6 people.
Since it's so huge, even if it's full of tests, we can't cover all the possible cases. Furthermore, it's not exposed to the web (it in one of our LANs). So refreshing it's code it's not feasible (I already asked...).

So, removing Docker images for PHP versions that reached end-of-life (PHP 5.3, 5.4, 5.5, and 5.6 at the end of 2018) leads to problems for us.
I fully understand that you can't maintain tons of images, so I agree that these images shouldn't/can't be maintained forever in https://github.com/docker-library/php.

BTW, instead of *deleting* them from this repository (and from https://hub.docker.com/_/php ), what about *moving* them to a *legacy* unmaintained system (for instance https://github.com/docker-library/php-legacy and https://hub.docker.com/_/php-legacy)?

**Comment by ThomasNegeli** [comment]
I would suggest that you build your own images and maintain them in your own docker registry.
That's best for your usecase.
Relying on external systems and repositories not maintained by you will always bring you into trouble.

**Comment by mlocati** [comment]
Thanks for the tips: we already do that (obviusly, since there's isn't an official image for PHP 5.3 anymore).
I simply don't like this situation, since I don't think we are the only one having this problem (see for instance [how many PHP 5.3 projects exist on GitHub](https://github.com/search?q=docker+php+5.3)).
If you could create this legacy and unmaintained system, that wouldn't cost you much time, but it would save a lot of time for many people.

**Comment by yosifkit** [comment]
The images are not deleted from Docker Hub. We leave all old tags as they are. They just no longer receive rebuilds when a base image updates. As for continuing to keep them up-to-date in another Docker repo, that is not something we have resources for.

```console
$ docker pull php:5.3
5.3: Pulling from library/php
a3ed95caeb02: Pull complete 
e31c7da51bce: Pull complete 
614879c30ef3: Pull complete 
cad84e43249c: Pull complete 
c025cfddd505: Pull complete 
a10575de529c: Pull complete 
4f591d797078: Pull complete 
Digest: sha256:ba952a8970f2fc35e3703b2650495c64d6e015eb52a4ee03f750c69e863b3237
Status: Downloaded newer image for php:5.3
```

**Comment by mlocati** [comment]
> The images are not deleted from Docker Hub.

Thank you for your response, @yosifkit 
It's great to see that those images still exist. But IMHO if they are not listed on dockerhub, it's like if they don't exist...

> As for continuing to keep them up-to-date in another Docker repo, that is not something we have resources for.

I'm not asking to keep EOL versions up-to-date, I'm just asking to not remove them from dockerhub lists: in my mind, those *php-legacy* images shouldn't be maintained at all.

**Comment by yosifkit** [comment]
It is unfortunate that the Hub interface does not show all available tags. They should show up in the [tags page](https://hub.docker.com/r/library/php/tags/), but the Hub does not implement paging like their [api supports](https://hub.docker.com/v2/repositories/library/php/tags/?page=1&page_size=250). It is similarly not paged on the [store interface](https://store.docker.com/images/php?tab=description) even though it uses an almost [identical datasource](https://store.docker.com/api/content/v1/repositories/public/library/php/tags?page_size=250&page=1).
