### ISSUE TITLE
php 7.2 build failed for 7.2.4

### ISSUE THREAD

**Issue by DracoBlue** [docker-library/php#611]
https://travis-ci.org/docker-library/php/builds/360691986

Can you retrigger the build?

**Comment by anmolnagpal** [comment]
@tianon  Any idea when you are going to retrigger it.

**Comment by tianon** [comment]
Wasn't planning to -- Travis is not what pushes the images, it's simply a smoke test to ensure the build is good.

The real image build/push job is at https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/.

Is there some particular reason you want Travis re-triggered?

**Comment by DracoBlue** [comment]
Nope. I thought travis also publishes the images.

So I will wait until the new versions are available. Thanks for the fast response!
