### ISSUE TITLE
install xsl on php:7.1-fpm-alpine

### ISSUE THREAD

**Issue by lotarbo** [docker-library/php#613]
Hello, i need xsl ext on php, and make this dockerfile

```
FROM php:7.1-fpm-alpine

RUN apk upgrade --update && apk add --no-cache \
    freetype libpng libjpeg-turbo \
    && apk add --virtual build-deps freetype-dev libpng-dev libjpeg-turbo-dev libxslt-dev libxml2-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && export NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && docker-php-ext-install -j${NPROC} mysqli opcache xsl gd \
    && apk del build-deps
```

after that i have error
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xsl.so' - Error loading shared library libexslt.so.0: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20160303/xsl.so) in Unknown on line 0`

Can u help me?)

**Comment by yosifkit** [comment]
You need to add `libxslt` to your non-build-deps list so that `libexslt.so.0` will still be there after building the extension.
