### ISSUE TITLE
Enable log_errors by default

### ISSUE THREAD

**Issue by csandanov** [docker-library/php#614]
[`log_errors`](http://php.net/manual/en/errorfunc.configuration.php#ini.log-errors) is not defined in the configs, therefore set to `Off` by default, as a result, you can't see PHP errors in stdout. The default php.ini (both development and production versions) have it `On` and the official php manual recommends to have it enabled. Also, you can find [numerous related issues](https://github.com/docker-library/php/search?q=log_errors&type=Issues). I know there's a plenty of settings like that in PHP when the default value differs from the recommended value for dev/prod but this one is pretty important.

**Comment by tianon** [comment]
We don't adjust the PHP configuration from the defaults provided with the PHP source distribution -- can you provide a reference to the default `php.ini` that you're referring to which has this enabled?

**Comment by csandanov** [comment]
e.g. for PHP 7.2 from sources:

https://github.com/php/php-src/blob/php-7.2.4/php.ini-development#L493
https://github.com/php/php-src/blob/php-7.2.4/php.ini-production#L498

**Comment by yosifkit** [comment]
`php.ini-development` and `php.ini-production` are now included in the images and can be used as desired (https://github.com/docker-library/docs/pull/1290). See the [docs](https://github.com/docker-library/docs/tree/fb12582b4065f886e2aaef0b2dc835dc6fe05cfe/php#configuration) for an example of using one.
