### ISSUE TITLE
Error enabling pdo_pgsql with php:7.0 image

### ISSUE THREAD

**Issue by konetchy** [docker-library/php#618]
Hi there,

I'm having a little trouble enabling the `pdo_pgsql` extension in docker. I would appreciate any insight or help.

First part of my Dockerfile.
```
FROM php:7.0

RUN echo 'deb http://ftp.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/backports.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    libpq-dev \
    libxml2-dev \
    unzip \
 && apt-get -t jessie-backports install -y --no-install-recommends \
    libav-tools \
 && rm -rf /var/lib/apt/lists/* \
 && docker-php-ext-install \
    pcntl \
    pdo \
    pdo_pgsql \
    pgsql \
```

Fails with 
```re2c: error: cannot open ext/pdo/pdo_sql_parser.re
Makefile:201: recipe for target '/usr/src/php/ext/pdo/pdo_sql_parser.c' failed
make: *** [/usr/src/php/ext/pdo/pdo_sql_parser.c] Error 1
```

This just started happening today. I believe after an upgrade from php 7.0.28 to php 7.0.29 in the image. 

I was able to get it to successfully build by using the `php:7.1` image instead of `php:7.0`. After lots of googling, I can't find any dependencies it's missing. How do I enable the `pdo_pgsql` extensions for this build?

Thanks!

**Comment by tianon** [comment]
@yosifkit pointed out to me that this isn't actually necessary -- PDO is included in the images already, so you should be able to simply do `pdo_pgsql` (without `pdo`) and it should work properly. :+1:

**Comment by tianon** [comment]
(I've also filed https://github.com/php/php-src/pull/3211 to see about adjusting the line of code in `ext/pdo/Makefile.frag` to be more forgiving of differing methods of compilation.)

**Comment by konetchy** [comment]
Thank you!

**Comment by jelhaouchi** [comment]
Thanks :+1:
