### ISSUE TITLE
[Announcement] Install PHP extensions with just one command

### ISSUE THREAD

**Issue by mlocati** [docker-library/php#621]
I'm sorry to spam, but I think that this may be useful for many people...

I created a script that install PHP extensions (and all the required system libraries) with just one line.

It currently supports 55 extensions, but contributors are welcome.

You can find this script here: https://github.com/mlocati/docker-php-extension-installer

**Comment by tianon** [comment]
Neat!

I'm going to close (since this is a notice not an actionable issue), but I'm also going to drop a link over in #75 (where someone building something exactly like this has been discussed). :+1:
