### ISSUE TITLE
Send logs to stderr and stdout

### ISSUE THREAD

**Issue by spyrospph** [docker-library/php#63]
Hi I am using the below to redirect logs to stderr and stdout but with no success.

RUN ln -sf /dev/stdout /var/log/fpm-access.log && \
	ln -sf /dev/stdout /var/log/php5-fpm.log 

Are you aware of the change that needs to be done in order to do this and benefit from docker logs command?

**Comment by thaJeztah** [comment]
Isn't it already doing so?

https://github.com/docker-library/php/blob/master/5.6/fpm/php-fpm.conf

```
error_log = /proc/self/fd/2
daemonize = no

[www]

; if we send this to /proc/self/fd/1, it never appears
access.log = /proc/self/fd/2

```

**Comment by spyrospph** [comment]
thx for the help @thaJeztah. You were absolutely right

**Comment by thaJeztah** [comment]
You're welcome, I overlooked the `/proc/self/fd/2` myself the first time I saw it :D

**Comment by thaJeztah** [comment]
Think this is answered and can be closed
