### ISSUE TITLE
Patches to address MS-ISAC 2018-046

### ISSUE THREAD

**Issue by bobbyhubbard** [docker-library/php#634]
Request to build and deploy the latest php 5.6, 7.0,7/1 and 7.2 patches to address https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution_2018-046/

**Comment by phy25** [comment]
Sorry, but it seems that the latest versions on Docker Hub (7.2.5, 7.1.16, 7.0.30, 5.6.35) has already been latest. No need to trigger that.

**Comment by bobbyhubbard** [comment]
no, those are not the latest. http://us1.php.net/archive/2018.php#id2018-04-26-4

**Comment by phy25** [comment]
@bobbyhubbard You can follow up at docker-library/official-images#4297.

**Comment by bobbyhubbard** [comment]
@phy25 I think I understand now... so the versions are managed by that repo? My bad.
