### ISSUE TITLE
Publish 5.6.36 and 7.1.17 image tags request

### ISSUE THREAD

**Issue by hossam-fares** [docker-library/php#635]
Hello, 
    I can see you already have PHP 5.6.36 and 7.1.17 versions on the master branch but the image tag is not published to docker hub yet.

That new versions [solve multiple vulnerabilities in PHP Could allow for arbitrary code execution](https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution_2018-046/) and It would be great to have them soon

**Comment by phy25** [comment]
You can follow up at docker-library/official-images#4297.

**Comment by hossam-fares** [comment]
thanks @phy25

**Comment by yosifkit** [comment]
We are working to clear up our current build queue so that can be merged asap.
