### ISSUE TITLE
Alpine containers have insecure/outdated curl 7.57.0 version

### ISSUE THREAD

**Issue by chrisatomix** [docker-library/php#636]
Apologies if I'm posting this in the wrong place, but it looks like the Alpine PHP containers on Docker Hub are still running curl `7.57.0`, which contains multiple security vulnerabilities.

The APK package directory has the latest version (`7.59.0`, released in March).
When I build the first few lines of the Alpine PHP container manually it definitely installs curl `7.59.0`:

```Dockerfile
FROM alpine:3.7

RUN apk add --no-cache --virtual .persistent-deps \
		ca-certificates curl tar xz libressl
```

```
Sending build context to Docker daemon   31.2MB
Step 1/2 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 2/2 : RUN apk add --no-cache --virtual .persistent-deps 		ca-certificates curl tar xz libressl
 ---> Running in 700a16618c1a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/10) Installing ca-certificates (20171114-r0)
(2/10) Installing libssh2 (1.8.0-r2)
(3/10) Installing libcurl (7.59.0-r0)
(4/10) Installing curl (7.59.0-r0)
```

But if I build a container based on the published version Docker Hub, I get the insecure version:
```Dockerfile
FROM php:7-alpine
```
```
Sending build context to Docker daemon   31.2MB
Step 1/1 : FROM php:7-alpine
7-alpine: Pulling from library/php
Digest: sha256:fdd3e366067dce0da8e8f9beb48dce7d8e0215cc188db459fbeea9d5ce0406f2
Status: Downloaded newer image for php:7-alpine
 ---> 4f91f5a89b07
Successfully built 4f91f5a89b07

(interactive terminal into container)
# /usr/bin/curl --version
curl 7.57.0 (x86_64-alpine-linux-musl) libcurl/7.59.0 LibreSSL/2.5.5 zlib/1.2.11 libssh2/1.8.0
Release-Date: 2017-11-29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy 
```

From what I can see the Docker Hub version is pushed by a bot every day, so in theory it should have the latest version of curl. Am I correct that it should be up to date, or is this intentional?
Is there some kind of accidental APK caching going on in the CI/build pipeline?

Happy to provide more info if needed, this came up when I was testing out Google Container Registry's new vulnerability scanner:
![image](https://user-images.githubusercontent.com/1768449/39517212-5fcd3284-4e3e-11e8-99bf-1500a768971c.png)

Thanks!

**Comment by hairmare** [comment]
This seems to have been fixed since you opened the issue. The following command reports curl 7.60.0.

```bash
docker run --rm -ti --entrypoint curl php:7-alpine --version
```
```
curl 7.60.0 (x86_64-alpine-linux-musl) libcurl/7.60.0 LibreSSL/2.6.3 zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy 

```

**Comment by wglambert** [comment]
Issue seems resolved, going to close
