### ISSUE TITLE
SIGWINCH issue

### ISSUE THREAD

**Issue by injcristianrojas** [docker-library/php#64]
When making a [derived image](https://github.com/injcristianrojas/simple-xss-example/blob/master/Dockerfile) from php:5.6-apache, when the server starts, at the slightest movement it stops, and gives me this message:

```[Wed Jan 21 20:24:05.736731 2015] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully```

It happens when I resize the window, or on ```docker attach```, rendering it inaccessible.

**Comment by tianon** [comment]
Can you try running without "-t" and see if the problem persists?

**Comment by injcristianrojas** [comment]
The command issued is ```apache2 -D FOREGROUND```. No ```-t``` argument.

**Comment by tianon** [comment]
I mean on your `docker run`.

**Comment by injcristianrojas** [comment]
Nope. The original command issued is:
```Shell
docker run -it --rm --name test_server -p 8181:80 test-example
```

And now I replaced it with: 
```Shell
docker run -i --rm --name test_server -p 8181:80 test-example
```

Looks like more of an Apache issue.

**Comment by josericardo** [comment]
I received the same error on my first run, but things went fine in the second run.

**Comment by cwarden** [comment]
Apache is working as-designed according to [a bug report](https://bz.apache.org/bugzilla/show_bug.cgi?id=50669).

Running `docker run` with `--sig-proxy=false` prevents `SIGWINCH` (and all other signals) from being sent to apache.

**Comment by vbence** [comment]
Please at least change the recommended command line options on Docker Hub.

**Comment by chpio** [comment]
If is start it with `--sig-proxy=false` then `ctrl + c` is ignored, `--detach` is also a non-solution 1. `--rm` doesn't work with `-d` 2. i want it to run attached
