### ISSUE TITLE
ini_set('session.use_cookies', '0') fails

### ISSUE THREAD

**Issue by Allemanda** [docker-library/php#640]
I am using php docker from the official repository.
I tried to set session.use_cookies to 0 with the code:
$ret = ini_set('session.use_cookies', '0');
but it fails: $ret == false
Anyone know why?

**Comment by wglambert** [comment]
Since this issue doesn't seem to denote any errors with the image I'm going to close, if there is something reproducible to show an issue with the image then I'll re-open.
