### ISSUE TITLE
ARM Alpine 32 bit

### ISSUE THREAD

**Issue by JackGruber** [docker-library/php#648]
the creation of alpine images has failed for months :(
Is there a solution for this problem?

https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/php/

  - php:7.2.5-cli-alpine3.7
  - php:7.2.5-fpm-alpine3.7
  - php:7.2.5-zts-alpine3.7
  - php:7.2.5-cli-alpine3.6
  - php:7.2.5-fpm-alpine3.6
  - php:7.2.5-zts-alpine3.6

**Comment by yosifkit** [comment]
```
configure: error: C compiler cannot create executables
```

This looks similar to https://github.com/docker-library/golang/issues/196, https://github.com/docker-library/memcached/issues/25, https://github.com/docker-library/postgres/issues/420, and https://github.com/docker-library/redis/issues/137.

cc @tianon, @vielmetti

**Comment by tianon** [comment]
Ouch -- for the others, I've adjusted them to build on an emulated `arm32v7` device running via QEMU on my local desktop, but I think PHP's compilation is a bit too heavy for that to be a reasonable solution here. :disappointed:

**Comment by khs1994** [comment]
now support arm32v6 and arm32v7 alpine,close it. @tianon

**Comment by tianon** [comment]
Sounds good, thanks!
