### ISSUE TITLE
PHP 5.5.21, 5.4.36, 5.6.4 (CVE fixes)

### ISSUE THREAD

**Issue by thaJeztah** [docker-library/php#65]
Were released, some CVE's fixed

@tianon, standing at a concert right now, so can't make you a PR :smile:

**Comment by thaJeztah** [comment]
Oh, seems only 5.5 was updated

**Comment by thaJeztah** [comment]
Which is weird, I see mentions of other updates here as well;

https://github.com/CHH/php-build/pull/253

Maybe not yet released?

**Comment by GrahamCampbell** [comment]
The downloads on php.net normally lag behind the git tags by a day or two.

**Comment by thaJeztah** [comment]
Ah, that explains it. Thanks for the info

**Comment by yosifkit** [comment]
@thaJeztah, should we go ahead and update 5.5 and then circle back when the others become available?

**Comment by GrahamCampbell** [comment]
The php 5.6 update is live now btw. :)

**Comment by yosifkit** [comment]
Thanks @GrahamCampbell for the info.

Bumped 5.5 and 5.6: https://github.com/docker-library/php/commit/c871678cc7c8dbc9277832e35f14f3534f2dd0fb

**Comment by thaJeztah** [comment]
Thanks!

**Comment by thaJeztah** [comment]
PHP 5.4.37 was released as well today

http://php.net/archive/2015.php#id2015-01-22-3

**Comment by yosifkit** [comment]
Done! d506059bc4361bfe9b0ce536c7d94f76a37d2c02

**Comment by thaJeztah** [comment]
Thanks! And thank you @GrahamCampbell; your PR made me aware new versions we're released :)
