### ISSUE TITLE
Loaded Configuration File: None

### ISSUE THREAD

**Issue by BentCoder** [docker-library/php#661]
Hi,

I am copying `www.conf` to `/usr/local/etc/php-fpm.d/` folder but the `phpinfo()` output reads `Loaded Configuration File: None`. Is it not correct place to copy or should I do something else as well?

Thanks

**Dockerfile**

```
FROM php:7.2-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zip \
 && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql

COPY www.conf /usr/local/etc/php-fpm.d/www.conf
COPY php.ini /usr/local/etc/php/conf.d/php.ini
```

**www.conf**

```
user = www-data
group = www-data

listen = nginx:9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```

**Result**

```
# ls -l /usr/local/etc/php-fpm.d
-rw-r--r-- 1 root staff   238 May 25 22:09 docker.conf
-rw-r--r-- 1 root staff 18859 May 25 22:09 www.conf
-rw-r--r-- 1 root root    833 May 29 01:19 www.conf.default
-rw-r--r-- 1 root staff    45 May 25 22:09 zz-docker.conf
```

**Comment by tianon** [comment]
The location you've referenced (`/usr/local/etc/php-fpm.d/`) is the PHP-FPM configuration, _not_ the PHP configuration.  I don't believe `phpinfo()` will display much (if anything) about the PHP-FPM configuration.

If you'd like to modify the PHP configuration, you want to put your `ini` files into `/usr/local/etc/php/conf.d/` instead.
