### ISSUE TITLE
E: Package 'libpng12-dev' has no installation candidate

### ISSUE THREAD

**Issue by jahanzaibasharat** [docker-library/php#662]
I get this error since libpng12-dev is a dependency of zlib1g-dev (which is installed with "--no-install-recommends")
I am using this Image as a base for mediawiki:1.30.0.
Dockerfile (FROM php:7.1-apache).

The correct dependency should be libpng-dev. 
How can we fix this?

**Comment by tianon** [comment]
You might need to change `php:7.1-apache` to `php:7.1-apache-jessie`, but it would be better to simply adjust the dependency in your `Dockerfile`.

**Comment by hsali** [comment]
you can also try libpng-dev instead of libpng12-dev for the new version of Ubuntu.
