### ISSUE TITLE
Is FPM in php:7.x-apache (e.g. php:7.2-apache, php:7.0-apache) ?

### ISSUE THREAD

**Issue by therobyouknow** [docker-library/php#667]
Couldn't see it in the Dockerfile ( https://github.com/docker-library/php/blob/master/7.2/stretch/apache/Dockerfile ) so assuming need to install it on top.

Am aware that there is php-fpm ( https://github.com/docker-library/php/blob/cf5482724142c2c249c7f873b0f7f4910e502b63/7.2/stretch/fpm/Dockerfile ) but looks like this is without apache.

It's fine for me that it's like this, not an issue, but rather a question so that I know what I need to add/not to add. 

Thank you.

**Comment by wglambert** [comment]
FPM isn't in the apache image

**Comment by therobyouknow** [comment]
Thank you @wglambert, I had thought so.  I will close this issue.

I will create a separate container for apache and link it to the php-fgm via settings in the vhosts apache configuration in the apache container. The approach I will use will be similar to that done for nginx:: https://stackoverflow.com/questions/29905953/how-to-correctly-link-php-fpm-and-nginx-docker-containers
