### ISSUE TITLE
cgi missing in php5

### ISSUE THREAD

**Issue by mictadlo** [docker-library/php#668]
Hi,
I tried  `php:5-fpm` and  `php:5-apache` and when I click on a cgi file I see the actual cgi script rather than the HTML file.

What did I miss?

Thank you in advance,

Michal

**Comment by mictadlo** [comment]
https://github.com/docker-library/php/issues/280

**Comment by mictadlo** [comment]
It works after I removed those [lines](https://github.com/docker-library/php/blob/master/5.6/jessie/apache/Dockerfile#L84-L98)

**Comment by hairmare** [comment]
AFAIK the `fpm` and `apache` variants do not support CGI (it's only in new releases of the `cli` variant).

If removing the lines you indicated works for your case then you could also create a derived image that just disables the docker-php config:

```Dockerfile
FROM php:5-apache

RUN a2disconf docker-php
```

I must admit though, that I don't really understand your use-case.

**Comment by tianon** [comment]
We definitely don't enable running of CGI scripts in Apache (and indeed don't see a reason to -- if folks want PHP, they should use `mod_php` as configured in the `-apache` variants or PHP-FPM via the FastCGI protocol), and only include `php-cgi` (the binary) in the `-cli` variants (for folks who need it).  We don't have a variant where CGI itself is enabled, and configuring Apache to support that is an exercise for the reader.
