### ISSUE TITLE
Can't install php-phplibsec

### ISSUE THREAD

**Issue by r3c4ll** [docker-library/php#670]
I'm getting the following error running Osclass:

[Wed Jun 13 00:19:09.506823 2018] [php7:error] [pid 15] [client 172.18.0.2:51030] PHP Fatal error: Class ‘phpseclib\Crypt\Common\BlockCipher’ not found in /var/www/html/oc-includes/phpseclib/Crypt/Rijndael.php on line 66, referer: http://myosclass.reverse.com/

But even when the package is available for Debian Stretch https://packages.debian.org/stretch/php-phpseclib it can’t be installed:

In the web container (php:7.2.5-apache-stretch):

#aptitude install php-phpseclib
No candidate version found for php-phpseclib
Unable to apply some actions, aborting

Any advice?

More about the complete issue here https://forums.docker.com/t/php-7-2-5-apache-stretch-issue-with-php-phpseclib/52433

**Comment by r3c4ll** [comment]
Thank you very much @wglambert !

Do you know why if the image is based on the stable branch/distribution it needs to specify the branch/distribution in the apt command?

**Comment by yosifkit** [comment]
That would be because of https://github.com/docker-library/php/pull/542.
