### ISSUE TITLE
Alpine packages do not seem compatible with built php

### ISSUE THREAD

**Issue by chrissound** [docker-library/php#672]
I had the following dockerfile:

```
FROM php:7.2-fpm-alpine3.7
RUN apk add --update php7-gd
...
``` 

However when running this, it complained it couldn't find the php-gd extension. I then instead changed the dockerfile to:
```
FROM alpine:3.7

RUN apk add --update --no-cache php7 php7-gd
```

Which then worked. So I'm guessing it's do with the way php is built. None the less I find this behavior a bit intuitive. What is the purpose on basing the image on alpine in this case?

**Comment by tianon** [comment]
When you install `php*` packages via `apk`, you're installing Alpine's PHP package (and thus if you're `FROM php:xxx`, you've got _two_ copies of PHP included in the image).  This image provides PHP in the way that PHP upstream recommends and supports, which is downloaded and built from source.  If you want to continue using this PHP image, you'll need to download and compile modules like `gd` from source as well.  For modules which are built-in (like `gd`), you can use the helper scripts we provide to do so (`docker-php-ext-install`, etc).

See the section titled "How to install more PHP extensions" on https://hub.docker.com/_/php/ (https://github.com/docker-library/docs/blob/7aeed6ad70a0ccdce57d42e4a152fa0dfbedbbc4/php/README.md#how-to-install-more-php-extensions).
