### ISSUE TITLE
envsubst command not found

### ISSUE THREAD

**Issue by AiusDa** [docker-library/php#673]
Hi, I need execute envsubst inside php container from docker-compose, but this command not exists, some one have this Issue too or have some option to replace environment variables inside php files?

I have a code like this in my php:

`Configure::write('API_URL', '${API_URL}');`

In my docker-compose.yml:

`command: /bin/sh -c "envsubst < /config-files/env.php > /var/www/html/env.php`

Thanks!

**Comment by yosifkit** [comment]
You could just use PHP to get the variable directly: [`getenv`](https://secure.php.net/manual/en/function.getenv.php).
```php
Configure::write('API_URL', getenv('API_URL'));
```
