### ISSUE TITLE
Was unable to install ant on php:7.2-cli

### ISSUE THREAD

**Issue by tszymanek** [docker-library/php#675]
... probably because of the lacking `/usr/share/man/man1` directory on `stretch-slim`.
I'm leaving this if anyone else encounters the same issue.

Found the solution here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199#15
```
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list \
    && mkdir -p /usr/share/man/man1 \
    && DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && apt-get -t stretch-backports install -y openjdk-8-jre-headless ca-certificates-java

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
    ant
```

**Comment by wglambert** [comment]
Going to prune this PSA, users can still find it sufficiently as it's the second result on google for the query "install ant php cli"
