### ISSUE TITLE
The container and the local file do Bind Mouting, and my superior files and directories cannot be found in the PHP file

### ISSUE THREAD

**Issue by niyaode** [docker-library/php#676]
![tim 20180626144515](https://user-images.githubusercontent.com/27875141/41893829-95b34b04-794f-11e8-82f2-5f4f6097e814.png)
The container and local file do Bind Mouting, -v "$PWD":/var/ WWW/HTML.In the PHP file I need to find my superior files and directories, but it is empty.
![tim 20180626145056](https://user-images.githubusercontent.com/27875141/41894096-726ee35a-7950-11e8-89a0-d2de64c9a1cc.png)

**Comment by wglambert** [comment]
>-v "$PWD":/var/ WWW/HTML

There's a space between `/var/ WWW` also `WWW/HTML/` shouldn't be capitalized.

```console
$ ls
testfile
$ docker run -it -P --rm --name php -v "$PWD":/var/www/html php bash
root@bb2520e13d8b:/# ls /var/www/html
testfile
```

**Comment by wglambert** [comment]
Closing since issue is resolved
