### ISSUE TITLE
E: Package 'libpng12-dev' has no installation candidate

### ISSUE THREAD

**Issue by alexsabau86** [docker-library/php#682]
Trying to install this from a Dockerfile - I've already tried using libpng-dev which in turn is giving the following error: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/gd.so' - libpng16.so.16: cannot open shared object file: No such file or directory in Unknown on line 0

I'm installing gd as well, so not sure what is going on.

Docker file looks like this:

```dockerfile
FROM php:7.1-apache

RUN a2enmod rewrite remoteip

RUN set -ex \
        && buildDeps=' \
                libjpeg62-turbo-dev \
                libpng12-dev \
                libpq-dev \
        ' \
        && apt-get update && apt-get install -y --no-install-recommends $buildDeps mysql-client git unzip && rm -rf /var/lib/apt/lists/* \
        && docker-php-ext-configure gd \
                --with-jpeg-dir=/usr \
                --with-png-dir=/usr \
        && docker-php-ext-install -j "$(nproc)" exif gd mbstring opcache pdo pdo_mysql pdo_pgsql mysqli zip \
        && apt-mark manual \
                libjpeg62-turbo \
                libpq5 \
        && apt-get purge -y --auto-remove $buildDeps

RUN { \
                echo 'opcache.memory_consumption=128'; \
                echo 'opcache.interned_strings_buffer=8'; \
                echo 'opcache.max_accelerated_files=4000'; \
                echo 'opcache.revalidate_freq=60'; \
                echo 'opcache.fast_shutdown=1'; \
                echo 'opcache.enable_cli=1'; \
        } > /usr/local/etc/php/conf.d/opcache-recommended.ini

COPY . /var/www/html
WORKDIR /var/www/html
RUN rm -rf /var/www/html/vendor/* \
    && php /var/www/html/composer.phar config -g github-oauth.github.com k092739874283749823jg732989839283 \
    && php /var/www/html/composer.phar -n install \
    && php /var/www/html/composer.phar -n update \
    && rm -f /var/www/html/composer.phar \
    && chown -R www-data:www-data /var/www/html
```

**Comment by wglambert** [comment]
Is this relevant https://github.com/docker-library/php/issues/662
>You might need to change php:7.1-apache to php:7.1-apache-jessie

**Comment by yosifkit** [comment]
Answered in reply to your other comment in #485:

> @alexsabau86 did you `apt-get purge --auto-remove libpng-dev` after using `docker-php-ext-install`?  Unless you specifically also installed `libpng16-16` it would be removed in the purge and thus the `.so` would be missing.
>
> https://github.com/docker-library/php/issues/485#issuecomment-402896113

So change `libpng12-dev` to `libpng-dev` and add `libpng16-16` to your `apt mark manual`.  Or switch to the `-jessie`version of the image as suggested above.
