### ISSUE TITLE
Minimal Ubuntu image

### ISSUE THREAD

**Issue by d3v1an7** [docker-library/php#686]
Hi! I'd love to use [Minimal Ubuntu](https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released) as a base. Alpine is super great, but I've bumped into glibc issues a few too many times.

I'm happy to help putting together a PR for this, but wanted to get some direction first (I couldn't find any info regarding contributing [here](https://github.com/docker-library/php), or [here](https://hub.docker.com/_/php/))

1. Would Minimal Ubuntu replace Debian? Or be another addition?
2. Should both Minimal Ubuntu LTS builds be supported? Or just the latest?
3. Should all the php versions be supported? Or just the latest?

Thanks for your consideration :)

**Comment by tianon** [comment]
I think https://github.com/docker-library/php/pull/379#issuecomment-282450199 is still an accurate summary of our thoughts on this topic.

See https://github.com/nodejs/docker-node/issues/812 for some discussion of the same topic, particularly the following comparison:

> For comparison:
> 
> ```console
> $ docker images debian:stretch
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> debian              stretch             9a5d7185d3a6        2 weeks ago         101MB
> $ docker images debian:stretch-slim
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> debian              stretch-slim        3e235dbb0ba6        2 weeks ago         55.3MB
> $ docker images ubuntu:bionic
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> ubuntu              bionic              113a43faa138        5 weeks ago         81.2MB
> ```
> 
> So, not exactly a dramatic/compelling difference (especially if compared to `debian:stretch-slim`, which if we're switching/adding for size, I think is only fair).

**Comment by d3v1an7** [comment]
Thanks @tianon, we'd reached the same conclusion after some testing on our end as well. Appreciate the reply, will close this one!

**Comment by ghost** [comment]
love to see ubuntu base php 👍

**Comment by axot** [comment]
Hi, I found these days, ubuntu get lesser size than before.
Could we consider make a ubuntu based image?

There are 3 reasons in my mind,

1. Ubuntu has a longer EOL cycle.
ubuntu: https://ubuntu.com/about/release-cycle/
debian: https://wiki.debian.org/DebianReleases/
alpine: https://alpinelinux.org/releases/

2. Lesser on image size.
```
$ docker images
REPOSITORY                    TAG             IMAGE ID       CREATED         SIZE
alpine                        3.14            bb3de5531c18   3 days ago      5.34MB
debian                        buster-slim     5e8343a069db   13 days ago     63.5MB
debian                        bullseye-slim   0b4cf09e50a3   13 days ago     74.3MB
ubuntu                        20.04           58810d071ecb   5 weeks ago     65.6MB
```

3. More popular. Just take a look for number of image downloads.
```
$ curl -sS https://hub.docker.com/v2/repositories/library/debian/ | jq '.pull_count'
730284970

$ curl -sS https://hub.docker.com/v2/repositories/library/ubuntu/ | jq '.pull_count'
4646472320

$ curl -sS https://hub.docker.com/v2/repositories/library/alpine/ | jq '.pull_count'
6168099225
```

**Comment by jbonnier** [comment]
Also worth mentioning that Ubuntu supports chiseled images which reduce the final image size and attack surface.

https://ubuntu.com/containers/chiseled

**Comment by tianon** [comment]
I was curious, so I did a couple fresh builds:

```console
$ docker buildx build --pull 8.5/trixie/cli --tag php:debian
...
$ docker buildx build --pull --build-context debian:trixie-slim=docker-image://ubuntu:26.04 8.5/trixie/cli --tag php:ubuntu
...
$ docker images php
REPOSITORY:TAG   IMAGE ID       CREATED          SIZE
php:ubuntu       1cdc23a70437   20 seconds ago   619MB
php:debian       4b203165b165   4 minutes ago    573MB
```

(This also shows the approach I'd recommend for any users who need our images, but want them to be Ubuntu-based.)
