### ISSUE TITLE
Production readiness / secure by default

### ISSUE THREAD

**Issue by jaylinski** [docker-library/php#692]
## Describe the problem

I recently noticed that the PHP image `php:7.2-fpm-alpine` comes with the setting `display_errors = On` by default.

This was a bit problematic for me, because this setting exposed the mysqli connection credentials from my Wordpress site by displaying an error with all connection details. (yes, I should have disabled the wordpress debug mode)

## What is the desired behaviour?

I expect the official PHP docker images to ship the `php.ini-production` config in order to be **secure by default** and production ready.

The official production config sets `display_errors` to `Off`: https://github.com/php/php-src/blob/php-7.2.8/php.ini-production#L477

## Possible solutions

* Ship the `php.ini-production` by default
* Leave as is: we want to be developer-friendly and avoid "white-screens-of-death"
  Make it clear in docs to disable `display_errors` if the image is used in production.
* Recommend upstream (php-src) to set `display_errors` to `Off` if no `php.ini` is found (I think that's the case for these docker images, I couldn't find a `php.ini` file)

## Related issues

Relates to https://github.com/docker-library/wordpress/issues/148.

**Comment by tianon** [comment]
We don't currently do _anything_ special with `php.ini` beyond what PHP's own configure/build/install process provides, so our current situation is upstream's own default. :disappointed:

https://github.com/docker-library/php/blob/d6b950cc18b2977a96f472345024bed00cd07814/7.2/stretch/cli/Dockerfile#L125-L172

Perhaps there's more we could do to make it easier to switch to upstream's recommended "production" configuration?

**Comment by jaylinski** [comment]
@tianon Thanks for your quick feedback! (Your open source contributions are impressive!)

I thought about this for a bit. I think it is unrealistic that upstream (php-src) will change anything about their defaults. Shipping the `php.ini-production` by default is a breaking change and would break a lot of existing applications, so this is also a no-go.

I thought about your suggestion on how to make it easier to switch to upstream's production config.
Maybe the two configs (development and production) could be copied into the `PHP_INI_DIR`, so you could do this:
```
FROM php:7.2
# Production container
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
# Development container
RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
```
And of course this should be also documented in the readme.

**Comment by tianon** [comment]
That's a great idea. :+1: (#711)
