### ISSUE TITLE
COPY docker-entrypoint.sh can't boot

### ISSUE THREAD

**Issue by fanybook** [docker-library/php#695]
these files are executable after COPY
```
COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/

ENTRYPOINT ["docker-php-entrypoint"]
```

why i use this image, can't boot after add a 'COPY file'
```
COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["docker-entrypoint.sh"]
```

output error:
exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

must `RUN chmod 775 /usr/local/bin/docker-entrypoint.sh`, why?

**Comment by wglambert** [comment]
See https://github.com/docker-library/postgres/issues/296#issuecomment-308735942, https://github.com/docker-library/wordpress/issues/236

>When copying the files, you need to either use `git clone` (so that the "+x" mode on that script is preserved), or you need to manually "chmod +x" that script file before you build.
