### ISSUE TITLE
[Proposal] Can you add a dev version?

### ISSUE THREAD

**Issue by twose** [docker-library/php#709]
Just add `--enable-debug` arg in your Dockerfile, but I got failed by the docker hub automatic build.
https://hub.docker.com/r/twosee/php/builds/
I want to know how to build it or can you add a dev version image? it's useful when running Travis CI to check some PHP extension memory leak (Valgrind is too slow), just simple memory check.

**Comment by phy25** [comment]
Duplicate of #530.

**Comment by twose** [comment]
I got what I wanted, thank you.
