### ISSUE TITLE
Why php docker images are build from the source not from the packages?

### ISSUE THREAD

**Issue by mahnunchik** [docker-library/php#720]
Does this have a logical explanation especially for `alpine` linux?

https://stackoverflow.com/questions/52459196/why-almost-all-docker-library-images-are-build-from-the-source-not-from-the-pack

**Comment by phy25** [comment]
You can look at https://github.com/docker-library/php/issues/551#issuecomment-355162339.

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/3517

>we defer to upstream's official recommendations on a case-by-case basis.  For example, in the `postgres` image's Debian variants, we consume the `.deb` packages built and published by the upstream project, but in the Alpine variants we have to build from source (since upstream does not publish Alpine packages and instead recommends building from source for platforms for which they do not publish their own packages).

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#why-do-so-many-official-images-build-from-source! :tada:
