### ISSUE TITLE
README missing tags?

### ISSUE THREAD

**Issue by dustinpaluch** [docker-library/php#722]
E.g. I can do `docker run ...` with `php:7.1.1`, `php:7.1.2`, and `php:7.1.3`, but none of these tags can be found in the README.
https://github.com/docker-library/docs/blob/master/php/README.md

edit: am I in the wrong place?

**Comment by yosifkit** [comment]
This is a fine place to report that, but those are old versions and no longer supported. The list on the README is only the latest supported version. We leave old versions available for users who require them.
