### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so'

### ISSUE THREAD

**Issue by zhao459399177** [docker-library/php#726]
docker alpine3.8
php  7.2.11
swoole 4.2.3
pecl install  swoole
exec  docker run --rm my-php-swoole:latest php -m

PHP Warning: PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so (Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so: No such file or directory)) in Unknown on line 0

**Comment by wglambert** [comment]
For installing PECEL extensions: https://github.com/docker-library/docs/tree/master/php#pecl-extensions

Dockerfile
```dockerfile
FROM php:7.2.11-alpine3.8
RUN apk add --no-cache libstdc++ ${PHPIZE_DEPS} \
&& pecl install swoole-4.2.3 \
&& docker-php-ext-enable swoole \
&& apk del ${PHPIZE_DEPS}
```

```console
$ docker build . -t php:test
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.2.11-alpine3.8
 ---> abe2097e5e01
Step 2/2 : RUN apk add --no-cache libstdc++ ${PHPIZE_DEPS} && pecl install swoole-4.2.3 && docker-php-ext-enable swoole && apk del ${PHPIZE_DEPS}
 ---> Using cache
 ---> 2abfc8521c4d
Successfully built 2abfc8521c4d
Successfully tagged php:test

$ docker run --rm php:test php -i | grep swoole
/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
swoole
swoole support => enabled
Author => Swoole Group[email: team@swoole.com]
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => On => On
swoole.use_shortname => On => On
```

**Comment by wglambert** [comment]
There's also this discussion https://github.com/docker-library/php/issues/685#issuecomment-405819156 about configuring swoole with sockets
