### ISSUE TITLE
Sqlite is missing json1 support

### ISSUE THREAD

**Issue by tylergets** [docker-library/php#731]
The sqlite extension that is included with the image is not compiled with json1 extension, is it possible to include this? There is no other way to load the extension until https://github.com/php/php-src/pull/3368 is merged.

**Comment by tylergets** [comment]
@yosifkit please see linked php issue, its not possible to load the extension via pdo. Only via the original sqlite class, which is not really safe.

**Comment by jameswmcnab** [comment]
Ran into this issue running automated testing in which the JSON1 extension is used.

Are there any plans to add this?

**Comment by zerkms** [comment]
Experienced the lack of `rtree` and made up an example on how to build it. It should be almost identical to do the same for json1.
