### ISSUE TITLE
Apache does not include conf-enabled, sites-enabled

### ISSUE THREAD

**Issue by JensErat** [docker-library/php#76]
`apache2.conf` misses include statements for `conf-enabled` and `sites-enabled`.

This is an issue if you install additional packages, that add files to those folders. Manually appending include statements to those solves the issue for the derived image.

Directly including them leads to errors because of unconfigured paths.

Either the image should not contain those folders at all or actually include them (and possibly strip everything enabled by default). The current state is really annoying and cost me quite some time debugging why the application is not loaded. Loading the conf files would definitely be preferred, as this would meet the expectations from an image derived from Debian.

**Comment by EAnushan** [comment]
I just ran into this issue as well. I copied a default-ssl.conf file into sites-enabled for an image that uses this one as it's base. Was wondering for a while why I was getting SSL handshake errors when trying to access the site.

**Comment by EAnushan** [comment]
Why aren't we using /usr/sbin/apache2ctl to start apache rather than /usr/sbin/apache2? The former sets up environment variables and creates log directories that are missing and a whole slew of things that Apache may need.

**Comment by thaJeztah** [comment]
> creates log directories that are missing and a whole slew of things that Apache may need.

Setting up the log directories isn't needed; logs are sent to STDOUT (see [apache2.conf#L51](https://github.com/docker-library/php/blob/master/5.6/apache/apache2.conf#L51)) so that they are handled by the docker daemon

**Comment by JensErat** [comment]
`conf-enabled` contains some vhost-log-configuration which should be disabled for this reason (see my original post). It is also referenced by the included default vhost configuration, so this is to be removed, too.

**Comment by yosifkit** [comment]
@JensErat, you are correct.  We should fix the image to have those includes (and wipe out the contents of those directories).  Care to make a PR :pray:?

**Comment by JensErat** [comment]
The patch removes the symlinks for the enabled configuration, but leaves the original files in place (similar how we keep the original Apache configuration as `apache2.conf.dist`). There are incompatibilities in them, but also in the dist configuration, who ever enables them should know what he's doing anyway. But most of the file's contents is commented out anyway.

The alternative would be to also wipe out the disabled configuration, but I don't see this would do any harm.

Sorry for the two force pushes polluting the issue report, I failed at adding the latest change in the `--amend` commit before pushing it...

**Comment by sskorc** [comment]
@JensErat: could you please make a PR with your change :pray:?

**Comment by JensErat** [comment]
Sure, see #78.

**Comment by sskorc** [comment]
Thanks a lot @JensErat. @yosifkit, the PR is there :)

**Comment by jaredm4** [comment]
Close this issue @JensErat ?
