### ISSUE TITLE
Dockerhub still shows to 7.3-RC

### ISSUE THREAD

**Issue by telemmaite** [docker-library/php#764]
Can you please, update the docker repo so that we can start playing with PHP 7.3 (the GA not RC) ?
https://hub.docker.com/_/php/

**Comment by andreasschroth** [comment]
Yep, came here to create the same issue. Please update to GA version, thanks.

**Comment by OskarStark** [comment]
Jenkins build is done but still no 7.3 available

**Comment by yosifkit** [comment]
> https://github.com/docker-library/php/tree/c88c3d52f41a370f3a62e3ded62b7b223b4cb846#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

We were waiting on the update job to pick up the bumps for all the other versions of PHP before making the PR to https://github.com/docker-library/official-images. (We should be making one shortly)
- https://github.com/docker-library/php/commit/c88c3d52f41a370f3a62e3ded62b7b223b4cb846
- https://github.com/docker-library/php/commit/4fa4c526cf52725f859d7067006e8d4b3c226a52
- https://github.com/docker-library/php/commit/b4319e8f767f1200c9013e08baf2c34b9c84e301
- https://github.com/docker-library/php/commit/fa4ef89d7ce591df63584cb81853db2f5fdd0659

**Comment by OskarStark** [comment]
Hmm, still no 7.3 tag available

**Comment by DRoet** [comment]
@OskarStark 
https://github.com/docker-library/official-images/pull/5162

**Comment by OskarStark** [comment]
@DRoet thank you, but what does it mean? Is there an automatic process to merge the PR or when will we be able to use the new 7.3 ?
