### ISSUE TITLE
configure: WARNING: Libzip >= 1.2.0 needed for encryption support

### ISSUE THREAD

**Issue by acodercat** [docker-library/php#766]
configure: WARNING: Libzip >= 1.2.0 needed for encryption support

**Comment by acodercat** [comment]
https://stackoverflow.com/questions/48700453/docker-image-build-with-php-zip-extension-shows-bundled-libzip-is-deprecated-w/53843510#53843510

**Comment by wglambert** [comment]
From the stackoverflow question you linked it was noted that the `libzip` in the Debian repos is outdated at version 1.1.2, you can either use the alpine variant or `apt-get install -t experimental libzip-dev`

**Comment by tianon** [comment]
Installing a newer version of `libzip` is out of scope for this image -- you could also build it yourself from source if you wanted to, but that's a bit extreme IMO unless it's really critical for your use case.
