### ISSUE TITLE
PHP7.3-fpm - Segfault with xdebug and opcache

### ISSUE THREAD

**Issue by CocoJr** [docker-library/php#772]
Hi,

I have a segfault when using php7.3-fpm with xdebug and opcache (working if i disable xdebug OR opcache).

I've installed opcache using `RUN docker-php-ext-install opcache` in my Dockerfile and xdebug with PECL using `pecl install -f xdebug-2.7.0beta1`.

**Comment by wglambert** [comment]
Can you provide a minimal reproducer for the issue

**Comment by CocoJr** [comment]
Using this Dockerfile:  

```
FROM php:7.3.0-fpm

RUN apt-get update -yqq && apt-get install -yqq wget
RUN pecl install -f xdebug-2.7.0beta1
RUN export XDEBUG_PATH=`find / -name "xdebug.so"` && \
    echo "zend_extension=$XDEBUG_PATH" > /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo "xdebug.remote_host="`hostname -i` >> /usr/local/etc/php/conf.d/ext-xdebug.ini
RUN docker-php-ext-install opcache
```

I using this docker to setup a Symfony project using the default vhost configuration given by SensioLabs. When i using the CLI, all is fine, but after a request through nginx a 502 occurs and php-fpm crash with a segfault.

**Comment by tianon** [comment]
Looks like a known issue with xdebug 2.7.0beta1 and PHP 7.3: https://bugs.xdebug.org/view.php?id=1583

**Comment by CocoJr** [comment]
Just adding `opcache.optimization_level=0xFFFFFBFF` in my php.ini and working fine. Thx a lot @tianon.

**Comment by xpader** [comment]
This issue still exists in php 8.1.27, when set `opcache.optimization_level=0xFFFFFBFF`, the problem solved.

**Comment by xpader** [comment]
> This issue still exists in php 8.1.27 when only present with opcache, that makes php core dump and nginx 502 error. When I set `opcache.optimization_level=0xFFFFFBFF`, the problem solved.

After a day, fpm process still happend core dump,  and I think I found where the problem are. That is JIT.

Disable jit and then look again.
