### ISSUE TITLE
Are there any release plans for 5.6.40?

### ISSUE THREAD

**Issue by nojimage** [docker-library/php#774]
Yesterday, PHP 5.6.40 released. http://php.net/index.php#id2019-01-10-4

Are there any plans for 5.6.40 docker images to be release?

**Comment by tianon** [comment]
Gahhhhhh PHP!

5.6 is EOL 😭

Looks like we need to revert https://github.com/docker-library/php/pull/768 and parts of https://github.com/docker-library/php/pull/773 (unless there's another 7.0 for some bizarre reason also 😩).

**Comment by tianon** [comment]
Ok, let's see what Travis makes of https://github.com/docker-library/php/pull/775. :+1:
