### ISSUE TITLE
Build fails because of invalid/missing GPG key

### ISSUE THREAD

**Issue by Rylab** [docker-library/php#783]
gpg: requesting key 90D90EC1 from hkp server ha.pool.sks-keyservers.net
gpgkeys: key 0BD78B5F97500D450838F95DFE857D9A90D90EC1 can't be retrieved
gpg: no valid OpenPGP data found

Does this need to be updated, or am I missing something? Thanks.

EDIT: I am using the included debian Dockerfile, with no modifications (yet) and it's failing here.

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by Rylab** [comment]
Thanks for the quick response, that's helpful!
