### ISSUE TITLE
PEAR Virus Infection - Please can you confirm whether image is likely to be affected

### ISSUE THREAD

**Issue by toby-griffiths** [docker-library/php#784]
Hi there,
I've just seen [this article about PHP PEAR download being infected](https://arstechnica.com/information-technology/2019/01/pear-php-site-breach-lets-hackers-slip-malware-into-official-download/).  It looks like PEAR is included from source, but please can you confirm that this is the case, and therefore it's not infected?
Thanks

**Comment by wglambert** [comment]
The image itself doesn't use the `pear` functionality during build, there's just a `pecl update-channels` which will work as intended as `pecl` is unaffected to my knowledge.
https://github.com/docker-library/php/blob/ecd7dcc69c76f0e582c2274ecb90dcb7264e245c/7.3/stretch/fpm/Dockerfile#L207-L209

**Comment by tianon** [comment]
See also https://twitter.com/pear/status/1088450567121166341 from the PEAR folks directly that confirms the way we get `pear` installed in this image is not affected:

> 9/10: If you manually installed PHP and it included a PEAR installation during its installation, it is hugely unlikely that go-pear.phar was pulled in for that task (it uses install-pear-nozlib.phar instead)... and even more unlikely that you would have used it on that system.

**Comment by toby-griffiths** [comment]
Thanks for confirming what I expected @wglambert / @tianon
