### ISSUE TITLE
Can't copy HTML to the document root

### ISSUE THREAD

**Issue by glumb** [docker-library/php#79]
I'm new to docker. Running images from the registry works just fine. I'm trying to copy a simple html file into the webroot. My `Dockerfile`looks like this:

    FROM php:5.6-apache

    COPY index.html /var/www/html/
    COPY config/php.ini /usr/local/etc/php/

Unfortunately this does not work. The php.ini gets copied in, but the `var/www/html` dir remains empty.
Am I missing something?

**Comment by md5** [comment]
What command are you running to launch the container?

**Comment by glumb** [comment]
I'm using docker-compose up with the following `docker-compose.yml`

    web:
      build: ./web
      links:
       - db
      ports:
       - "80:80"
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: 1234

The `Dockerfile` from my first post is located in the `/web` directory.
Everything is starting just fine besides the html folder being empty.

The vm including docker was set up using the docker-machine command.

**Comment by tianon** [comment]
Have you done a `docker-compose build` just to make sure the image is up-to-date?

**Comment by glumb** [comment]
yes

**Comment by yosifkit** [comment]
The entrypoint woes look like you need a `chmod +x entrypoint.sh` on your local machine first.

I did a local test of your first two lines of the Dockerfile and an `index.html` and then did `docker run -it --rm my-image cat index.html` and got back the contents that I put there.  I also tested it running the default `CMD` and was able to get the page in a browser.  `COPY` does copy it in as root, but my file was world readable.

**Comment by glumb** [comment]
Thanks for all your replies! `chmod +x entrypoint.sh` fixed the permission denied issue. 
I finally got the COPY to work, too. I had to run `docker-compose rm` and remove the generated images manually. Shouldn`t `docker-compose build` do this for me?

Now im getting ` stdin: is not a tty`...

**Comment by glumb** [comment]
I'm closing this, cause the issues are not related to this particular Docker image.

**Comment by thaJeztah** [comment]
@glumb you can try by adding `tty: true` to your docker-compose.yaml`. Not sure, but worth a try;

```yaml
web:
  build: ./web
  tty: true
  links:
   - db
  ports:
   - "80:80"
```

**Comment by glumb** [comment]
@thaJeztah Thank you for the hint. I tried it, but it did not work unfortunately. The message `stdin: is not a tty` disappeared, but only because the container didn't start at all :hankey:  :D

Removing ENTRYPOINT ["/entrypoint.sh"]  fixed it somehow. I don't need a entrypoint for this container anyways. Good to know that there is a tty flag! Is this a documented feature?

**Comment by thaJeztah** [comment]
>Is this a documented feature?

I think it is documented (it's basically the `docker-compose` implementation of `docker run -t`), however; you'll have to check the documentation.

If it's not documented, *please* open an issue in the docker-compose issue-tracker or (even better) a Pull-request!

**Comment by tianon** [comment]
https://docs.docker.com/compose/yml/#working95dir-entrypoint-user-hostname-domainname-mem95limit-privileged-restart-stdin95open-tty-cpu95shares
:+1:

**Comment by thaJeztah** [comment]
Thanks @tianon!
