### ISSUE TITLE
How to access directory owned by `www-data`?

### ISSUE THREAD

**Issue by skwokie** [docker-library/php#793]
Hi,

Maybe this is not an issue but just my Docker knowledge, I find it impossible to access or chmod any directories created by apache. e.g.,

root@9f8d8206720b:/var/www/aaa/bbb# cd ccc
bash: cd: /var/www/aaa/bbb/ccc/: Permission denied
root@9f8d8206720b:/var/www/aaa/bbb# chmod 777 ccc/
chmod: changing permissions of 'ccc/': Operation not permitted
root@9f8d8206720b:/var/www/aaa/bbb# ls -ld ccc
drwxrwxr-x 4 www-data www-data 4096 Mar 23  2017 ccc
root@9f8d8206720b:/var/www/aaa/bbb# ls -ld ccc/
drwxr-x--- 3 www-data www-data 4096 May  3  2017 ccc/

Thanks very much!

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

Also are you using Docker for Mac/Windows?

**Comment by skwokie** [comment]
Hi, thx for your quick response. Since I don't think I'll be able to gather the info any time soon, I'm closing this.
