### ISSUE TITLE
More modules

### ISSUE THREAD

**Issue by tianon** [docker-library/php#8]
As #6 and #7 help highlight, we really don't have a good solution to accessing the wide array of modules and extensions included with PHP.

My own personal best idea so far is to just compile everything we can as part of the base image, which does feel properly in the "spirit of PHP", but also seems like a pretty hacky solution.  If we can't come up with anything better (or if we get someone from upstream PHP validating that as a properly "OK" solution), then we should run with that, but I'd like to at least leave it open for discussion first for a little while in case someone's got a better idea. :smile:

**Comment by yosifkit** [comment]
Docs have been added for `docker-php-ext-install`, closing.

**Comment by pierrejoye** [comment]
The script seems broken afaict. Using:
FROM php:5.6
RUN docker-php-ext-install pdo_mysql mbstring
RUN echo 'date.timezone = Asia/Bangkok' > /usr/local/etc/php/conf.d/date.ini
VOLUME /app
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["php"]
CMD ["-S", "0.0.0.0:8080", "-t", "web"]


pierre@jessie:~$ docker exec poolleage_web_1 ls /usr/local/etc/php/conf.d/
date.ini

Nothing about new extensions ini settings.

Loudly thinking:

From the make output:
Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20131226/
Installing header files:          /usr/local/include/php/

but in the final image:
pierre@jessie:~$ docker exec poolleage_web_1 ls /usr/local/lib/php/extensions/no-debug-non-zts-20131226/
opcache.a
opcache.so

I am not sure why nothing gets copied or changed. The build seems to be correct.

However I am sure to understand how it is done or why. Bundled extensions should always be built. Default core extensions always be available (loaded). There are some build cases where one should really compile extensions at the same time than the core, not using phpize.

then a simple script to enable or disable extensions at wish can be provided. Something similar to apache enable/disable module script.

docker-php-*-ext can be kept for non core extensions. 

At some point (working on it :), it could use Pickle to install extensions using either pickle directly or composer.

I could spend some time on a PR, how I would like to discuss it before, just to avoid doing double work or something you would not like :)
