### ISSUE TITLE
Apache2 log files are empty

### ISSUE THREAD

**Issue by bluepuma77** [docker-library/php#80]
I am running docker "php:5.6-apache" and I am looking for the Apache2 log files.

According to "/etc/apache2/sites-enabled/000-default.conf" the log files are defined:

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

I enabled the log levels "LogLevel info ssl:warn" and did "service apache2 reload".

Still the files are empty, despite loading html and php files via web browser.

    /var/log/apache2/access.log
    /var/log/apache2/error.log

Any ideas how to enable the logs?

**Comment by yosifkit** [comment]
Logs are actually put to stdout, so `docker logs containerid` should work.  That particular file is not used, see pr #78 to fix this problem.

**Comment by thaJeztah** [comment]
Think this can be closed now that https://github.com/docker-library/php/pull/78 was merged?
