### ISSUE TITLE
 PHP 7.2.16 released

### ISSUE THREAD

**Issue by jelovac** [docker-library/php#800]
Hi,

Security update has been released yesterday for PHP 7.2, consider updating the 7.2 tags.

Best regards,
Vladimir

**Comment by shrasool** [comment]
Second this, new versions for 7.1 and 7.3 also came out with the security updates.

**Comment by PhilETaylor** [comment]
It normally takes a few days before the official docker builds are released after a PHP release :-( I've gone back to building my own by cloning the Dockerfiles in this repo and changing the version numbers and hashes.

**Comment by phy25** [comment]
See docker-library/official-images#5521, thank you!

(Honestly for a community-maintained project, we should be a bit more patient...)

**Comment by yosifkit** [comment]
https://github.com/docker-library/official-images/pull/5521 is done; Should be up on the Docker Hub in the next hour or so (there are quite a few builds to do).
