### ISSUE TITLE
apt-get updating failing 

### ISSUE THREAD

**Issue by peteneville** [docker-library/php#804]
Appears that Debian have moved the repo for jessie packages (see https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html).

Added the following to my Dockerfile that uses this image:
RUN { echo 'deb http://archive.debian.org/debian/ jessie main'; \
 echo 'deb-src http://archive.debian.org/debian jessie main'; } \
 | tee /etc/apt/sources.list

Please can you let me know if the source for this can be updated and updated images pushed to Dockerhub?

Thanks,
Peter

**Comment by wglambert** [comment]
https://github.com/debuerreotype/docker-debian-artifacts/issues/66#issuecomment-476648047
