### ISSUE TITLE
Apache CustomLog overriding

### ISSUE THREAD

**Issue by jaredm4** [docker-library/php#81]
So I need to use a custom CustomLog (hah) in Apache, but if I simply add a separate conf to be included with the CustomLog, it will cause duplicate log entries to be made (this is intended by Apache). So it looks like to solve this, I would need to remove the [CustomLog directive from apaceh2.conf](https://github.com/docker-library/php/blob/master/5.5/apache/apache2.conf#L51), or create a VirtualHost. Both of which I'd really like to avoid.

Any tips for working around this, or is this something we can change in the image? Currently I'm aiming to replace the apache2.conf with a modified copy but that means having to try and keep it updated from upstream.

**Comment by tianon** [comment]
Something like `RUN sed -i 's/^CustomLog/#&/' /etc/apache2/apache2.conf` would probably do the trick, right?

**Comment by jaredm4** [comment]
Works enough. Thanks.
