### ISSUE TITLE
i386/php:7.3-apache broken

### ISSUE THREAD

**Issue by J0WI** [docker-library/php#822]
`i386/php:7.3-apache` crashes on startup. When starting a shell and trying to start from there, I get the following:
```
# apache2-foreground 
Segmentation fault (core dumped)
```

**Comment by tianon** [comment]
I have reproduced this (both on amd64 and on a real i386 kernel).  Not sure what's the cause yet. :disappointed:

**Comment by tianon** [comment]
Doh, I try it again today and everything works fine... :expressionless: :unamused:

**Comment by tianon** [comment]
Can you still reproduce this?

**Comment by J0WI** [comment]
I can still reproduce this on various systems. Same behavior on [Travis CI](https://travis-ci.org/nextcloud/docker).

**Comment by tianon** [comment]
Digging into the backtrace from the core dump, the closest I can find is https://bugs.php.net/bug.php?id=77447 and thus https://github.com/google/sanitizers/issues/342, but the PHP issue is claimed fixed (and I've verified that the code we're building includes the changes from the referenced commits). :confused:

**Comment by tianon** [comment]
I dug into `./configure` output and can't see anything relevant -- also worth noting that Debian builds for `i386` roughly the same way we do (in an `i386` Debian `chroot` on an `amd64` system), so it's worth checking whether they have a similar issue (or perhaps if a clean build of their php7.3 package on a system which can reproduce also reproduces).

**Comment by J0WI** [comment]
`7.4-rc` is also affected

**Comment by J0WI** [comment]
This is still an issue for me and I'm not able to reproduce this on any other platform.

**Comment by asbiin** [comment]
Hi! I have the exact same problem on local and here on this github action run https://github.com/monicahq/docker/runs/1038827032

**Comment by J0WI** [comment]
` i386/php:8.0-rc-apache` is still affected
