### ISSUE TITLE
Unable to pull latest version (7.3.5)

### ISSUE THREAD

**Issue by deguif** [docker-library/php#824]
When I'm trying to pull `php:7.3.5-cli-stretch`, I get this error: `Error response from daemon: manifest for php:7.3.5-cli-stretch not found: manifest unknown: manifest unknown`

When pulling `php:7.3-cli-stretch`, I get the old version (7.3.4) not 7.3.5.

Any idea why?

**Comment by demyxco** [comment]
@deguif you didn't the memo? Pulls may work most of the scheduled down time.

```
You are receiving this communication as a Docker Hub account holder and as a valued member of our community. In our ongoing effort to provide the best possible customer experience and highest level of security, we are taking steps to update Docker Hub.

To do so, we will be performing scheduled maintenance this Saturday May 4, 2019 from approximately 9:00AM to 7:15PM, US Pacific Daylight Time (UTC-7). During this window, Docker Hub will be operating in a read-only mode. Registry logins and image pulls will continue to work for a majority of this time frame. Pushes however will generally be unavailable. Maintenance activities, approximate timelines and FAQ can be found in our knowledge base article, which we will be updating throughout the maintenance window.

We understand that the maintenance process impacts our customers and we apologize in advance for any inconvenience this may cause.

We will also provide updates via status.docker.com.

Thank you for choosing Docker.

Kent Lamb
Director, Global Support
```

**Comment by thaJeztah** [comment]
I think pull access was only interrupted for a few minutes, and service should be fully operational again now; are you still having this issue?

**Comment by deguif** [comment]
Yes, it is working now. Thanks for the explanation, I thought there was something I could have broken with https://github.com/docker-library/official-images/pull/5847
I'm going to close this issue.
