### ISSUE TITLE
argon2id support is missing in the Stretch images

### ISSUE THREAD

**Issue by tehplague** [docker-library/php#827]
The `php:7.3-cli` images do not have libsodium support for argon2id enabled. This is confusing because it basically means that the (Alpine) images which are optimized for size carry more features than the larger Stretch-based ones.

**Quick way to reproduce**
```
$ docker run --rm -it php:7.3-cli php -r 'var_dump(SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13);'

Warning: Use of undefined constant SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 - assumed 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' (this will throw an Error in a future version of PHP) in Command line code on line 1
string(35) "SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13"
$ docker run --rm -it php:7.3-cli-alpine php -r 'var_dump(SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13);'
int(2)
```

**Expected behaviour**
Both invocations are expected to show the numeric constant value indicating that argon2id support is available in both PHP and libsodium.

**Comment by wglambert** [comment]
Different Sodium versions use different default hashing algorithms

The Debian-stretch package is on 1.0.11-2
https://packages.debian.org/stretch/libsodium-dev

Alpine is 1.0.16-r0
https://pkgs.alpinelinux.org/package/v3.9/main/x86/libsodium-dev

```console
$ docker run --rm php:7.3-cli-alpine php --ri sodium

sodium

sodium support => enabled
libsodium headers version => 1.0.16
libsodium library version => 1.0.16
```
```console

$ docker run --rm php:7.3-cli php --ri sodium

sodium

sodium support => enabled
libsodium headers version => 1.0.11
libsodium library version => 1.0.11
```

Looks like `Argon2id` was implemented in 1.0.15, so Stretch is using `Argon2i`
https://github.com/jedisct1/libsodium/releases/tag/1.0.15

**Comment by tianon** [comment]
Yeah, we don't really want to build `libsodium` from source unless we absolutely have to (as in, PHP absolutely requires it), so I think this is unfortunately probably the best we're going to get for now. :disappointed:

**Comment by J0WI** [comment]
Buster will support it:
https://packages.debian.org/buster/libsodium-dev

**Comment by yosifkit** [comment]
`1.0.17` is also in [stretch-backports](https://packages.debian.org/stretch-backports/libsodium-dev) though we will probably migrate to buster in the coming months.

**Comment by wglambert** [comment]
Fixed with upgrade to Buster https://github.com/docker-library/php/pull/861

```console
$ docker run --rm php:7.3-cli php -r 'var_dump(SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13);'
int(2)

$ docker run --rm php:7.3-cli php --ri sodium

sodium

sodium support => enabled
libsodium headers version => 1.0.17
libsodium library version => 1.0.17
```
