### ISSUE TITLE
Installing php extensions in php7-apache

### ISSUE THREAD

**Issue by mcarpenterjr** [docker-library/php#835]
Working on an image that will use php7-apache as it's base. Running into an issue with composer not being able to find some php extensions during its setup phase. If I attempt to programmatically install the php extensions I get an error;
```
Package php-zip is a virtual package provided by:
    php7.3-zip 7.3.4-2 [Not candidate version]
    php7.0-zip 7.0.33-0+deb9u3 [Not candidate version]
```
Light research has led me to believe I might have to specify some more sources, but I'd like to avoid that if possible, figured I'd ask here before going overboard.

**Comment by phy25** [comment]
https://github.com/docker-library/docs/tree/master/php#e-package-php-xxx-has-no-installation-candidate

https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions

**Comment by mcarpenterjr** [comment]
That'll do it!
