### ISSUE TITLE
Creating dummy-packages for PHP-extensions

### ISSUE THREAD

**Issue by JensErat** [docker-library/php#84]
Often PHP applications are also published as Debian packages or repositories, eg. Zabbix. When I put together a Dockerfile for the Zabbix PHP frontend (Dockerfile not published yet), I had the problem that this has dependenices registered for PHP and various PHP extensions.

This conflicts with PHP installed from source.

Any easy workaround was to generate dummy packages using the equivs package. I would propose to generally install a PHP dummy package, and maybe integrate automatic generation of equivs-packages in `docker-php-ext-install`.

I used these lines for generating the equiv-dummy:

    # Create dummy package for php5 and libraries
    COPY equivs-dummy /tmp/
    RUN apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends equivs && \
        cd /tmp && \
        equivs-build equivs-dummy && \
        dpkg -i equivs-dummy*.deb && \
        apt-get purge -y --auto-remove equivs && \
        apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

With `equivs-dummy` containing:

    Section: misc
    Priority: optional
    Standards-Version: 3.9.2
    Provides: php5, php5-gd, php5-pgsql

Keeping `equivs` (for `docker-php-ext-install`) wouldn't hurt too much, it doesn't have too many dependencies not installed anyway. One could even consider pregenerating dummies for all extensions, then the script would just have to install them and equiv could be removed like I did.

I there is consent that this is a good idea, I would put together a patch for this.

**Comment by tianon** [comment]
I've found that if a package is actually published as a real Debian package, it's more useful (and ends up with a better image) to forgo this base entirely and just use `debian` or `ubuntu` directly as appropriate to get the base recommended by the packages being used from upstream.

Where I see this base most useful is cases like Wordpress where all we're given from upstream is source code, and it works really well to drop that source code directly into a PHP image.
