### ISSUE TITLE
PECL not working on php:7.4-rc-fpm-alpine3.9

### ISSUE THREAD

**Issue by ruivoh** [docker-library/php#846]
Hello there.

I'm trying to run pecl from inside the container and that's the output:
/ # pecl install redis
sh: pecl: not found

**Comment by tianon** [comment]
Indeed, this is expected for 7.4+:

- https://github.com/docker-library/php/pull/840#issuecomment-502251019
- https://externals.io/message/103977
- https://github.com/php/php-src/pull/3781
- https://github.com/php/php-src/commit/e93d6d97aab7a5de1f7b8dc750ca9d08214de8c4

**Comment by GrahamCampbell** [comment]
Can we still include pecl by default. It is super useful for installing extensions.

**Comment by tianon** [comment]
Copying part of my comment in https://github.com/docker-library/php/pull/847#issuecomment-505638229 here since it's relevant:

> I think what we should probably do here is revisit https://github.com/docker-library/php/issues/846 by adding `--with-pear` for now and revisit for PHP 8 when it's fully deprecated.  So to recap, that means we don't actually "fix" the problem here, but merely delay it for PHP 8 instead, at which point a replacement installer will be necessary (so if this is important to you or your organization, you should probably strongly consider getting involved in helping maintain the `pecl` utility, the `pickle` utility, or a new tool which solves the same use case in a general way and use this deprecation period in the way it's intended -- as a transitionary one).

(and re-opening this to track the change)

**Comment by tianon** [comment]
Opened a PR: https://github.com/docker-library/php/pull/851
