### ISSUE TITLE
Install re2c and file ?

### ISSUE THREAD

**Issue by xuhdev** [docker-library/php#86]
It seems that if I run `docker-php-ext-install anything`, re2c and file commands are always warned for their noneixstence. Perhaps it's better to install re2c and file in the Dockerfiles?

**Comment by yosifkit** [comment]
It is just warnings, but it seems reasonable to install them, since the [install docs](https://php.net/manual/en/install.unix.php) say that `re2c` "might" be needed.

**Comment by xuhdev** [comment]
I'm actually suggesting to add re2c and file in the Dockerfile in this repository, if I made any confusion....

**Comment by yosifkit** [comment]
Yes, it is agreeable that we should add `re2c` and `file` to these official image.  Care to make a PR to add them to line 7 on each of the versions ([php/5.6/Dockerfile#L7](https://github.com/docker-library/php/blob/master/5.6/Dockerfile#L7))?

**Comment by xuhdev** [comment]
Sure, I'll make a PR tonight

**Comment by jaredm4** [comment]
@xuhdev On the latest image, I'm still getting an error.
```
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
```

**Comment by yosifkit** [comment]
The new commit ids have to be updated in [docker-library/official-images](https://github.com/docker-library/official-images).  I have https://github.com/docker-library/official-images/pull/658 with the update that I am build testing right now.

**Comment by jaredm4** [comment]
Awesome, thanks! Not in a hurry just wasn't sure if it wasn't actually fixed. At least now I know where to look to find the latest image builds.
