### ISSUE TITLE
Breaking change in 7.2.20 & 7.3.7

### ISSUE THREAD

**Issue by EkoMcCloud** [docker-library/php#864]
The latest versions of PHP 7.2 & PHP 7.3 include a breaking change that makes unable to run symfony properly (symfony/symfony#32395). 
This is currently breaking many of our pipelines. 
Apparently PHP made a revert of this change. Could you provide a new version of 7.2.20 & 7.3.7 including the revert ?

**Comment by wglambert** [comment]
https://www.php.net/ChangeLog-7.php#PHP_7_3
Looks like July 4 was the latest update for 7.3 and 7.2

https://github.com/symfony/symfony/issues/32395#issuecomment-510185363
>The issue is already resolved in the upcoming PHP 7.2 and 7.3 releases.

**Comment by EkoMcCloud** [comment]
Yeah this it what I guessed from my reading of this 
http://git.php.net/?p=php-src.git;a=commit;h=22ed362810c1b3a5ecb54ebd1d50d804c7fc3159

I did not find any information regarding the new releases dates though, I was maybe looking in the wrong place. 

I was mainly wondering if it would be possible to include a patch since right now any docker build involving 7.2 & 7.3 images without the full version number and symfony will fail.

**Comment by yosifkit** [comment]
We only pull released PHP source, so until it is in a release I suggest that you use an older image as a workaround (like `php:7.2.19-stretch`, `php:7.3.6-stretch`, and alpine variants).

**Comment by jvanoosterom** [comment]
same with 7.1-apache

**Comment by EkoMcCloud** [comment]
> We only pull released PHP source, so until it is in a release I suggest that you use an older image as a workaround (like `php:7.2.19-stretch`, `php:7.3.6-stretch`, and alpine variants).

We did this on a few builds last week in order to get them to work and I was affraid we have to go through every pipeline & build we have while waiting for the new release. I guess we will update them gradually.

Thanks a lot for the answer.

**Comment by jdreesen** [comment]
> We only pull released PHP source, so until it is in a release I suggest that you use an older image as a workaround (like `php:7.2.19-stretch`, `php:7.3.6-stretch`, and alpine variants).

PHP 7.2.21 and 7.3.8 were released today :tada:

**Comment by wglambert** [comment]
Closing from the update to 7.3.8 https://github.com/docker-library/official-images/pull/6406 
And 7.2.21 https://github.com/docker-library/official-images/pull/6388
