### ISSUE TITLE
Fix: installing gd results in freetype-config not found

### ISSUE THREAD

**Issue by jxlwqq** [docker-library/php#866]
锁定小版本：
```bash
FROM php:7.2.19-apache
```

**Comment by andreasschroth** [comment]
You shouldn't create issues for possible fixes / comments.

And to the content of your suggested fix: No, not really a good idea. You'll end up stuck with 7.2.19 or 7.3.6 and won't receive any security fixes, etc. anymore.

Better use this:

```dockerfile
FROM php 7.2-apache-stretch
```

or:

```dockerfile
FROM php 7.3-apache-stretch
```
