### ISSUE TITLE
Travis master build is broken (update.sh)

### ISSUE THREAD

**Issue by xthiago** [docker-library/php#871]
It is trying to fetch a file that does not exist:

```bash
+ curl -fsSL -o php.tar.xz https://downloads.php.net/~derick/php-7.4.0beta11.tar.xz
curl: (22) The requested URL returned error: 404 Not Found
```

The correct URL is: https://downloads.php.net/~derick/php-7.4.0beta1.tar.xz

Travis build: https://doi-janky.infosiftr.net/job/update.sh/job/php/4187/console

**Comment by tianon** [comment]
Indeed, see https://github.com/php/web-qa/commit/c318632eaf86033dd81497fceeb23a3baf93e5a3#r34450877, fixed via https://github.com/php/web-qa/commit/d86dcf0891172e85442f1bcfd4c943e58ff29357.
