### ISSUE TITLE
Update to PHP 7.3.9

### ISSUE THREAD

**Issue by deguif** [docker-library/php#883]
Hello,

I'm trying to help updating PHP to 7.3.9 on the docker hub but I'm unable to create the pull request on docker official images repository.
https://github.com/docker-library/official-images/compare/docker-library:master...docker-library-bot:php?expand=1 doesn't allow me to create the pull request when clicking on the button. Maybe, because tests failed on travis?

**Comment by tianon** [comment]
Done: https://github.com/docker-library/official-images/pull/6568

**Comment by deguif** [comment]
Thanks a lot @tianon

**Comment by tianon** [comment]
Sure thing! Thanks for trying; I do wonder why it wasn't working for you to open it 😕
