### ISSUE TITLE
Warnings on removing packages in docker-php-ext-enable script

### ISSUE THREAD

**Issue by Ovsyanka** [docker-library/php#885]
When docker-php-ext-enable script removes it's temporary dependencies like `.docker-php-ext-enable-deps` or `.phpize-deps` there is warnings like this in the console:

```
WARNING: Ignoring APKINDEX.00740ba1.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.d8b2a6f4.tar.gz: No such file or directory
(1/1) Purging .docker-php-ext-enable-deps (20190902.233005)
```

As I understand the reason is that in [this del instrunction](https://github.com/docker-library/php/blob/406fcd31e62d633f62ac0d7bc5fc29aa1b3929fc/docker-php-ext-enable#L113) missed option `--no-cache`.

**Comment by tianon** [comment]
Adding `--no-network` would be even better

**Comment by tianon** [comment]
Oh it's already got that -- this warning is harmless. 👍

**Comment by tianon** [comment]
(if we add `--no-cache`, it'll waste time downloading those files to then simply delete them)

**Comment by Ovsyanka** [comment]
I see. Thanks for the explanation. Combining `--no-cache` alongside with `--no-network` discards `--no-network`. Sadly, I don't see easy way to remove this warnings.
