### ISSUE TITLE
Invalid signal: WINCH in Dockerfile

### ISSUE THREAD

**Issue by emircanerkul** [docker-library/php#887]
In this file: https://github.com/docker-library/php/blob/3308ce8ba00c91a15f200aa43295349af97fc931/7.2/buster/apache/Dockerfile

if i use on my dockerfile i get (Invalid signal: WINCH)

`FROM php:7.2-apache
MAINTAINER http://github.com/emircanerkul/cvgen Emircan ERKUL contact@emircanerkul.com

RUN apt-get update
RUN apt-get install wget -y
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
RUN apt-get install ./wkhtmltox_0.12.5-1.stretch_amd64.deb -y
RUN rm ./wkhtmltox_0.12.5-1.stretch_amd64.deb

WORKDIR /var/www/html
COPY / /var/www/html/`

I didn't find any solition on web. Please fix, or give a solition.

**Comment by wglambert** [comment]
That would be due to the [stopsignal](https://docs.docker.com/engine/reference/builder/#stopsignal) being `SIGWINCH`
https://github.com/docker-library/php/blob/d367f7fb843c23f265f732256bb196b160523cd2/7.2/buster/apache/Dockerfile#L272

https://github.com/docker-library/php/commit/9e50ad06426e7de8213ec59ce96dbeab38266dfe

Are you getting an error during triggering a `docker stop` which then sends the stop signal?

**Comment by yosifkit** [comment]
:disappointed:  oops, that's supposed to be "in the format SIGNAME" (or a number). We need to update the image :ship: :rocket:

**Comment by tianon** [comment]
Documentation must be wrong there, because I was able to get it to work with the following:

```dockerfile
FROM bash
STOPSIGNAL WINCH
```

Then running it, doing `trap 'echo hi' WINCH`, and doing `docker stop` and getting `hi` printed.

**Comment by tianon** [comment]
Also, if I do `STOPSIGNAL LOL`, I get `Invalid signal: LOL` while building, as expected.

**Comment by emircanerkul** [comment]
> That would be due to the [stopsignal](https://docs.docker.com/engine/reference/builder/#stopsignal) being `SIGWINCH`
> https://github.com/docker-library/php/blob/d367f7fb843c23f265f732256bb196b160523cd2/7.2/buster/apache/Dockerfile#L272
> 
> [9e50ad0](https://github.com/docker-library/php/commit/9e50ad06426e7de8213ec59ce96dbeab38266dfe)
> 
> Are you getting an error during triggering a `docker stop` which then sends the stop signal?

No, i getting error just on second line via docker build, may docker has new version idk, i'm using 5.6-apache now this is working. But this problem isn't solved yet.

**Comment by emircanerkul** [comment]
> Your Dockerfile builds successfully using version 18.09.6
> 
> ```
> $ docker build . -t php:test
> Sending build context to Docker daemon  2.048kB                                                                                                   
> Step 1/7 : FROM php:7.2-apache                                                                                                                    
> 7.2-apache: Pulling from library/php                                                                                                              
> 1ab2bdfe9778: Pull complete 
> 1448c64389e0: Pull complete 
> 4b8a4e62b444: Pull complete 
> 9eb9d1e8e241: Pull complete 
> d20b2d19292c: Pull complete 
> 023060ea5930: Pull complete 
> a7fa99bc84ac: Pull complete 
> 781dded3ce49: Pull complete 
> c08d9d09fbb0: Pull complete 
> e40dca16a06f: Pull complete 
> 3a2062421a32: Pull complete 
> f22df12230da: Pull complete 
> f024d0e1b0fa: Pull complete 
> d3e7c8f7e403: Pull complete 
> Digest: sha256:0b77d15df95f51c6b743cc0951f203dea18c56a9586cc4bc0a3b9d3c30d15c6b                                                                   
> Status: Downloaded newer image for php:7.2-apache                                                                                                 
>  ---> 35e5c60e1f7d                                                                                                                                
> Step 2/7 : MAINTAINER http://github.com/emircanerkul/cvgen Emircan ERKUL contact@emircanerkul.com
>  ---> Running in ffa3c176c3cb
> Removing intermediate container ffa3c176c3cb
>  ---> 9c5c91156543
> Step 3/7 : RUN apt-get update
>  ---> Running in 48a9aa76d436
> . . .
> Step 7/7 : RUN rm ./wkhtmltox_0.12.5-1.stretch_amd64.deb
>  ---> Running in d7743100cd7a
> Removing intermediate container d7743100cd7a
>  ---> 6eecb1e7fd77
> Successfully built 6eecb1e7fd77
> Successfully tagged php:test
> ```
> 
> ```
> $ docker run --rm --name php php:test
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message                                                                                                   
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message                                                                                                   
> [Wed Sep 11 16:27:03.218202 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.22 configured -- resuming normal operations
> [Wed Sep 11 16:27:03.218256 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> ```

idk, i'm using windows 10 hyper-v. Here my docker about:  http://prntscr.com/p4ufxj

**Comment by wglambert** [comment]
So your error seems related to hyper-v trying to translate syscalls to Windows, and Windows doesn't appear to have a `SIGWINCH` equivalent https://github.com/microsoft/terminal/issues/305

But as for why your build is getting the stop signal I would also attribute to LCOW being experimental https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#work-in-progress 
https://github.com/moby/moby/issues/33850#issuecomment-519493489

I would suggest adding to their master thread on LCOW https://github.com/moby/moby/issues/33850

**Comment by emircanerkul** [comment]
> So your error seems related to Docker Desktop's WSL1 trying to translate syscalls to Windows, and Windows doesn't appear to have a `SIGWINCH` equivalent [microsoft/terminal#305](https://github.com/microsoft/terminal/issues/305)
> 
> There is a tech preview out for Docker Desktop that uses WSL2, which uses Hyper-V as a native VM "with a full Linux kernel so there is no syscall translation occurring."
> https://thenewstack.io/windows-subsystem-for-linux-brings-the-full-4-19-kernel-to-windows/
> https://docs.docker.com/docker-for-windows/wsl-tech-preview/

This will solve this problem. Thank you.
