### ISSUE TITLE
linux/arm/v7 'Command 'install' is not valid, try 'pecl help'

### ISSUE THREAD

**Issue by ohnotnow** [docker-library/php#893]
Slightly odd issue - if I try and build a multiarch image and use a `pecl install redis` as part of it - then it fails on the linux/arm/v7 build.  Example Dockerfile :
```
FROM php:7.3-apache
RUN pecl install redis && docker-php-ext-enable redis
```

Running : 
```
docker buildx build --pull --load --no-cache --platform linux/arm/v7 -t test-pecl -f Dockerfile .
```
Fails with 
```
 => ERROR [2/2] RUN pecl install redis && docker-php-ext-enable redis      1.3s
------                                                                          
 > [2/2] RUN pecl install redis && docker-php-ext-enable redis:                 
#5 0.583 Command 'install' is not valid, try 'pecl help' 
```

Running :
```
docker buildx build --pull --load --no-cache --platform linux/amd64 -t test-pecl -f Dockerfile .
```
Works fine.  The docker version in front of me is `Docker version 19.03.2, build 6a30dfc`.  Let me know if there's any more info I can supply or something to dig into :-)

**Comment by tianon** [comment]
This is definitely related to Docker Desktop's QEMU layer (which is what you get when you `--platform linux/arm/v7`) -- I can reproduce running the command on my `amd64` desktop via QEMU, but running on a real ARM device the `pecl install` runs exactly as intended/designed and works fine.

**Comment by ohnotnow** [comment]
Yeah - I noticed that last night when I tried running the same thing on a raspberry pi.  It's really quite odd.

**Comment by tianon** [comment]
I believe that https://github.com/moby/qemu is an appropriate place to file issues like this.

Given that it's not really an issue we can fix in the PHP image (it's working properly on the real intended hardware), I'm going to close.
