### ISSUE TITLE
/bin/sh: docker-php-source: not found

### ISSUE THREAD

**Issue by nguyendachuy** [docker-library/php#895]
I use  **php/7.1/alpine3.9/fpm**
I use the command `docker-compose build` and get this error
Error:
.....
Executing busybox-1.29.3-r10.trigger
OK: 250 MiB in 66 packages
+ export 'CFLAGS=-fstack-protector-strong -fpic -fpie -O2' 'CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2' 'LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie'
**+ docker-php-source extract
/bin/sh: docker-php-source: not found**
Service 'selfproject' failed to build: The command '/bin/sh -c set -eux;     apk add --no-cache --virtual .build-deps         $PHPIZE_DEPS         coreutils         curl-dev         libedit-dev         libxml2-dev         openssl-dev         sqlite-dev     ;     export CFLAGS="$PHP_CFLAGS"         CPPFLAGS="$PHP_CPPFLAGS"         LDFLAGS="$PHP_LDFLAGS"     ;     docker-php-source extract;     cd /usr/src/php;     gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)";     ./configure         --build="$gnuArch"         --with-config-file-path="$PHP_INI_DIR"         --with-config-file-scan-dir="$PHP_INI_DIR/conf.d"         --enable-option-checking=fatal         --with-mhash         --enable-ftp         --enable-mbstring         --enable-mysqlnd         --with-curl         --with-libedit         --with-openssl         --with-zlib         $(test "$gnuArch" = 's390x-linux-musl' && echo '--without-pcre-jit')         ${PHP_EXTRA_CONFIGURE_ARGS:-}     ;     make -j "$(nproc)";     find -type f -name '*.a' -delete;     make install;     find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true;     make clean;     cp -v php.ini-* "$PHP_INI_DIR/";     cd /;     docker-php-source delete;     runDeps="$(         scanelf --needed --nobanner --format '%n#p' --recursive /usr/local             | tr ',' '\n'             | sort -u             | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }'     )";     apk add --no-cache $runDeps;     apk del --no-network .build-deps;     pecl update-channels;     rm -rf /tmp/pear ~/.pearrc;     php --version' **returned a non-zero code: 127**

==============================================
$ `ls -l`
total 33
-rwxrwx---+ 1 Nguyen Huy Nguyen Huy 7741 Oct  2 14:47 Dockerfile
-rwxrwxr-x+ 1 Nguyen Huy Nguyen Huy  129 Oct  2 11:57 docker-php-entrypoint
-rwxrwxr-x+ 1 Nguyen Huy Nguyen Huy 1485 Oct  2 11:58 docker-php-ext-configure
-rwxrwxr-x+ 1 Nguyen Huy Nguyen Huy 2683 Oct  2 11:58 docker-php-ext-enable
-rwxrwxr-x+ 1 Nguyen Huy Nguyen Huy 2512 Oct  2 11:59 docker-php-ext-install
-rwxrwxr-x+ 1 Nguyen Huy Nguyen Huy  619 Oct  2 11:59 docker-php-source

$ `docker version`
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

=============================
How can i solve it?
Thanks

**Comment by nguyendachuy** [comment]
I have solved the problem by
`awk '{ sub("\r$", ""); print }' docker-php-source > docker-php-source_new`

**Comment by JoelLinn** [comment]
What are you trying to do, do you want to build the image yourself?
Why don't you use `php:7.1-fpm-alpine3.9` or `php:7.1-fpm-alpine` from the public repository?
Can you please post a minimal docker-compose file to outline what your setup is?
