### ISSUE TITLE
php 7.1.4-fpm-alpine - Error loading shared library libpng16.so.16

### ISSUE THREAD

**Issue by ssheduardo** [docker-library/php#896]
When executed: **php --version** show the next error

`
bash-4.3# php --version
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/gd.so' - Error loading shared library libpng16.so.16: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20160303/gd.so) in Unknown on line 0
`
![image](https://user-images.githubusercontent.com/1160138/66226767-e8d4d780-e6db-11e9-846a-edfe1ce1ff2c.png)

This is my DockerFile

https://pastebin.com/pS1ZcinU

**Comment by wglambert** [comment]
```dockerfile
RUN docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
      && docker-php-ext-install gd \
      && apk del --no-cache freetype freetype-dev libpng libpng-dev libjpeg-turbo libjpeg-turbo-dev \
      && rm -rf /tmp/*
```

Remove the `apk del` line, if you're not removing them in the same layer then there's no space saving

**Comment by yosifkit** [comment]
Also, once you install and remove within one layer, only remove the `-dev` packages, you need the others.

**Comment by ssheduardo** [comment]
Yes, I removed 
`
&& apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev \
`

Now work fine

![image](https://user-images.githubusercontent.com/1160138/66241953-a83b8500-e700-11e9-9168-7ef4cc0d3f4c.png)
