### ISSUE TITLE
At least one invalid signature was encountered.

### ISSUE THREAD

**Issue by raquigu** [docker-library/php#898]
I have this issue:

W: GPG error: http://security-cdn.debian.org/debian-security buster/updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security buster/updates InRelease' is not signed.
W: GPG error: http://cdn-fastly.deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
W: GPG error: http://cdn-fastly.deb.debian.org/debian buster-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.

**Comment by yosifkit** [comment]
That usually means the mirror is having issues (possibly partially out of date; i.e. not completely synced from other mirrors) and often clears itself up.  Regardless, there is not anything we can do in the image.

**Comment by raquigu** [comment]
Thank you

**Comment by hacfi** [comment]
Can also happen if your harddrive gets full (experienced on Docker for Mac).

**Comment by rbarrera87** [comment]
> Can also happen if your harddrive gets full (experienced on Docker for Mac).

And not only when you HD is full I had like 50GB free and I had to make some space (removing some images).
Amazing advice!!

**Comment by webdog** [comment]
>Can also happen if your harddrive gets full (experienced on Docker for Mac).

This is partially true and partially false. Docker for macOS runs on a dedicated VM, of which Docker allocates specific/dedicated Disk and RAM to the VM. In my case, 80% of my overall disk was available but the allocated Disk image size was filled to capacity (60gb)

Ref: https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e

You can adjust this in the GUI:  (Screen taken after I cleared out my unused containers and images).
![image](https://user-images.githubusercontent.com/960210/99111214-4f037d80-25b1-11eb-9b60-f0318f2cbe1e.png)

**Comment by juampe** [comment]
I think that is related to some LSM component of the docker official image (in this case armhf) and exec/capabilities permissions. In this simple case sid flavour is unable to handle time corectly. And this, related to the certificate check, is the cause of invalid signature. It happends too in ubuntu focal.

```
# docker run -it debian:buster /bin/date
Sun Nov 15 11:30:44 UTC 2020
# docker run -it debian:sid /bin/date 
Thu Jan  1 00:00:00 UTC 1970
```

**Comment by JoelLinn** [comment]
What is the version of libseccomp on the host? timestamps have been changed to 64bit even on 32bit systems. If there is a mismatch between user space and kernel it needs to be intercepted and converted. I think there was a bug about this but I cant find it right now.

**Comment by juampe** [comment]
Solved, I upgraded raspbian libseccomp2 to debian libseccomp2  2.5.0-3 (sid unstable apt pinning) 
`ii  libseccomp2:armhf                    2.5.0-3                             armhf        high level interface to Linux seccomp filter`
Now it works great
```
docker run -it debian:sid /bin/date
Tue Nov 17 13:09:46 UTC 2020
```

**Comment by divyangjp** [comment]
> > Can also happen if your harddrive gets full (experienced on Docker for Mac).
> 
> This is partially true and partially false. Docker for macOS runs on a dedicated VM, of which Docker allocates specific/dedicated Disk and RAM to the VM. In my case, 80% of my overall disk was available but the allocated Disk image size was filled to capacity (60gb)
> 
> Ref: https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e
> 
> You can adjust this in the GUI: (Screen taken after I cleared out my unused containers and images). ![image](https://user-images.githubusercontent.com/960210/99111214-4f037d80-25b1-11eb-9b60-f0318f2cbe1e.png)

That doesn't make any sense but works!!! 🎉

**Comment by WurmD** [comment]
Worked here after
`docker builder prune`
