### ISSUE TITLE
Apache variant uses invalid STOPSIGNAL 'WINCH'

### ISSUE THREAD

**Issue by jameswmcnab** [docker-library/php#907]
I've recently been testing an image based on `php:7.3-apache-stretch` in Docker and then in k3s (a lightweight k8s which uses containerd as the container runtime), built using `Docker version 19.03.5, build 633a0ea` via Docker Desktop for Mac. 

I'm seeing errors when a pod containing an image based on this apache variant is stopped: 

```
3m37s       Warning   FailedKillPod            pod/app-deployment-844cf75656-mrsmz    error killing pod: failed to "KillContainer" for "app" with KillContainerError: "rpc error: code = Unknown desc = failed to parse stop signal \"WINCH\": unknown signal \"WINCH\""
```

Digging through the logs it seems that containerd is not happy with the `STOPSIGNAL` being set to `WINCH`:

```
k3s[9326]: E1121 09:53:33.844780    9326 remote_runtime.go:295] ContainerStatus "24309ba209a814eeb710e596d2026f553c208fb3ca6aaf3e7820e77457972d4c" from runtime service failed: rpc error: code = Unknown desc = failed to parse stop signal "WINCH": unknown signal "WINCH"
````

The Dockerfile docs would suggest that `WINCH` isn't valid and it should be `SIGWINCH`:

> [...] or a signal name in the format SIGNAME [...]

Source :https://docs.docker.com/engine/reference/builder/#stopsignal

Seemingly Docker is fine with this (it should probably be throwing an error during `docker build` imho) but unless I've missed something its not compliant with the OCI image spec and will likely cause issues when running the image with something other than Docker.

> StopSignal string, OPTIONAL
>
> The field contains the system call signal that will be sent to the container to exit. The signal can  be a signal name in the format SIGNAME, for instance SIGKILL or SIGRTMIN+3.

Source: https://github.com/opencontainers/image-spec/blob/master/config.md

This was added due to #877 and later queried in #887 but not resolved.

Setting `STOPSIGNAL SIGWINCH` in my `Dockerfile` resolves the issue, and the pods are stopped with no errors.

Making this change for the Apache variants would also bring them in line with the others, for example the FPM variants use `STOPSIGNAL SIGQUIT`.

Note: [docker-library/httpd](https://github.com/docker-library/httpd/blob/master/2.4/Dockerfile#L161) would also seem to have the same issue, although I haven't tested with that image.

**Comment by tianon** [comment]
Oh wow, this is really bizarre.  I agree we should update if adding `SIG` magically fixes this downstream issue that Docker is oddly fine with. :sweat_smile:

**Comment by jameswmcnab** [comment]
My read of it was that containerd is doing the right thing here and that Docker shouldn’t be allowing the signal name sans `SIG`?

**Comment by tianon** [comment]
Yeah, it sounds like they intended for the spec to be more strict than the Docker implementation -- if I'd felt otherwise I'd be suggesting a bug filed on `containerd` instead of the two PRs I opened :sweat_smile: (#909, docker-library/httpd#151)

Thanks for the detailed write-up. :+1:
