### ISSUE TITLE
docker pull php:7.3.12-fpm failing in Ubuntu

### ISSUE THREAD

**Issue by aykutersoy** [docker-library/php#908]
When running this
`docker pull php:7.3.12-fpm`
is failing to pull and throws this
`no matching manifest for linux/amd64 in the manifest list entries`

(Running above command in Ubuntu 19.10, kernel 5.3.0-23-generic)

**Comment by rumours86** [comment]
we have same problem

```
Building php
Step 1/23 : FROM php:7.3.12-fpm-buster
7.3.12-fpm-buster: Pulling from library/php
Service 'php' failed to build: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by aykutersoy** [comment]
It seems like images are still baking https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/
will see what'd happen after that.

**Comment by aykutersoy** [comment]
They're now available :)
