### ISSUE TITLE
The php:fpm can't connect to mysql

### ISSUE THREAD

**Issue by xubingtao** [docker-library/php#941]
The database created by the image I pulled down directly can be connected. But I can't connect if I replace the data file of the same version of MySQL, and the database tool can connect normally. What's the situation?
<img width="1231" alt="php没法连mysql" src="https://user-images.githubusercontent.com/6500425/72217049-3b882000-3564-11ea-8bfb-0f07bbb6ff1c.png">
<img width="642" alt="工具可以连" src="https://user-images.githubusercontent.com/6500425/72217051-480c7880-3564-11ea-9052-e8ed75025ba3.png">
<img width="984" alt="phpinfo" src="https://user-images.githubusercontent.com/6500425/72217052-4f338680-3564-11ea-91fb-6d21a28f0dbd.png">
<img width="926" alt="phpinfo2" src="https://user-images.githubusercontent.com/6500425/72217056-55296780-3564-11ea-9d0c-2a225384484a.png">

我直接拉下来的镜像创建的数据库就可以连。但我用相同版本mysql的data文件替换过来就没法连上了，而数据库工具是可以正常连上的，这是什么情况？

**Comment by JoelLinn** [comment]
Although the error doesnt look like that, take a look at the mysql.user table what hosts are allowed to log in as root.

**Comment by xubingtao** [comment]
> Although the error doesnt look like that, take a look at the mysql.user table what hosts are allowed to log in as root.
I had "grant all on *.* to 'root'@'%';"

**Comment by xubingtao** [comment]
<img width="482" alt="更新权限" src="https://user-images.githubusercontent.com/6500425/72217229-83a84200-3566-11ea-9842-8be82dfddfd8.png">

**Comment by kyle4229** [comment]
How do I connect

**Comment by xubingtao** [comment]
> How do I connect
49.235.209.186:3306  root  xubingtao

**Comment by xubingtao** [comment]
> How do I connect

What's going on here? Can I shut down my database now?

**Comment by JoelLinn** [comment]
> > How do I connect
> > 49.235.209.186:3306  root  xubingtao

Have you just exposed a production database to the internet?

**Comment by xubingtao** [comment]
> > > How do I connect
> > > 49.235.209.186:3306  root  xubingtao
> 
> Have you just exposed a production database to the internet?

just my personal website

**Comment by JoelLinn** [comment]
Try changing the authentication plugin for the user to `caching_sha2_password`.
(Add `WITH caching_sha2_password` between `IDENTIFIED BY` in the alter user statement.)
It may be a similar issue to this one:
[https://ansi.23-5.eu/2018/08/caching_sha2/](https://ansi.23-5.eu/2018/08/caching_sha2/)

Apart from that, this is not a support forum - there should be plenty of MySQL and Wordpress support forums and user lists.

**Comment by JoelLinn** [comment]
> > > > How do I connect
> > > > 49.235.209.186:3306  root  xubingtao
> > 
> > 
> > Have you just exposed a production database to the internet?
> 
> just my personal website

!!! Don not expose your database publicly. Afterwards, restore your database to a version before you exposed it here.

**Comment by xubingtao** [comment]
> > > > > How do I connect
> > > > > 49.235.209.186:3306  root  xubingtao
> > > 
> > > 
> > > Have you just exposed a production database to the internet?
> > 
> > 
> > just my personal website
> 
> !!! Don not expose your database publicly. Afterwards, restore your database to a version before you exposed it here.
thks，i change my IP right now！

**Comment by xubingtao** [comment]
Actually, this is my first time to build a website in PHP environment.I'm a Java programmer.
