### ISSUE TITLE
cannot pull php:7.4.2 on macOS.

### ISSUE THREAD

**Issue by nagaho** [docker-library/php#948]
```
$ docker pull php:7.4.2
7.4.2: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

https://hub.docker.com/layers/php/library/php/7.4.1/images/sha256-f9743bf6a23d63431374f7cdbd911e3930c1bbdf970c043e1592d2d4b0e4929f
https://hub.docker.com/layers/php/library/php/7.4.2/images/sha256-c9da793359a4e24973efc7dacf8675e5e89b708e0f798cdbb8d91c783372f627

**Comment by runningman** [comment]
linux/amd64 is missing but all others seem to be ready which is odd.

I'm having the same issue wanting to pull php:7.4.2-fpm
linux/amd64 is still on 7.4.1 all others have been updated and tagged, from what I can see it doesn't look like the dockerbuildbot is still working on anything.

**Comment by rejinka** [comment]
Having the same problem with php:7.4.2-apache-buster on MacOS, ubuntu 16.04 and debian 9.4. So it seems like it is not specifically related to mac.

**Comment by GrahamCampbell** [comment]
Same issue with PHP 7.2 on Linux:

```
7.2.27-fpm: Pulling from library/php
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by GrahamCampbell** [comment]
// cc @tianon

**Comment by runningman** [comment]
linux/amd64 is available now :tada:

**Comment by jordicea** [comment]
I had the same issue few hours ago. Now it's updated correctly! 🎉

**Comment by tianon** [comment]
We had an Alpine security update which clogged the build queue right before the PHP security update, which is the reason for the delay in the builds. 👍
