### ISSUE TITLE
nslookup broke after 7.2 alpine3.8

### ISSUE THREAD

**Issue by SebaGnich** [docker-library/php#950]
We use `7.2-fpm-alpine3.8` and have `nslookup db` in our deployment for the "readiness" state-checking of the container.
At alpine3.11 the deployment broke with:

```
Executing command: nslookup db
Server:         127.0.0.11
Address:        127.0.0.11:53

** server can't find db.workflow.svc.cluster.local: NXDOMAIN
** server can't find db.svc.cluster.local: NXDOMAIN
** server can't find db.cluster.local: NXDOMAIN
** server can't find db.ec2.internal: NXDOMAIN
** server can't find db.workflow.svc.cluster.local: NXDOMAIN
** server can't find db.ec2.internal: NXDOMAIN
** server can't find db.svc.cluster.local: NXDOMAIN
** server can't find db.cluster.local: NXDOMAIN
```

Also after upgrading to `7.4.2-fpm-alpine3.11` the error occures.

How can I see what has changed? Do you have an idea on how to fix that?

Thanks in advance!

**Comment by SebaGnich** [comment]
Before, it was like this:
```
Executing command: nslookup db
nslookup: can't resolve '(null)': Name does not resolve
Name:      db
Address 1: 172.18.0.3 siz0xr9tb_db_1.siz0xr9tb_default
```

**Comment by wglambert** [comment]
https://github.com/gliderlabs/docker-alpine/issues/476

It seems Alpine uses BusyBox's nslookup, which had some issues on Kubernetes 
https://github.com/docker-library/busybox/issues/61#issuecomment-528926762, https://github.com/docker-library/busybox/issues/48#issuecomment-418512106

The upstream bug report https://bugs.busybox.net/show_bug.cgi?id=11161

**Comment by wglambert** [comment]
Going to close since this is an upstream issue with the Alpine package
