### ISSUE TITLE
Overriding entrypoint fails with argument #1 not being empty

### ISSUE THREAD

**Issue by alexander-nitsche** [docker-library/php#953]
Hello,

i am using the PHP-FPM image based on Alpine Linux 3.11 and currently extending the default docker-php-entrypoint script by overriding it with a custom script. Unfortunately the docker container exits immediately after startup with
```shell
php_1 exited with code 0
```

All i did so far was copying the original `docker-php-entrypoint` file to `docker-typo3-entrypoint` and set the new script as my entry point in the Dockerfile. The problem is caused in this [condition](https://github.com/docker-library/php/blob/affbdaf1386876560e287cd7708fafe2a4d246eb/7.3/alpine3.11/fpm/docker-php-entrypoint#L5):
```shell
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
```
when `"${1#-}"` expands to " " and thus the condition is not met when having passed no arguments at all on docker container startup. I assume that this condition should expand to `"-" != ""` when passing no arguments to the startup and thus it would expand the command to `php-fpm` and start the php process in the consequence. I don't know where this argument of 1 whitespace comes from but the default entry point script does not seem to get it.

In detail: This works ..
```shell
FROM php:7.3-fpm-alpine
```
and this does not ..
```shell
FROM php:7.3-fpm-alpine

COPY docker-typo3-entrypoint /usr/local/bin/
RUN chmod 755 /usr/local/bin/docker-typo3-entrypoint
ENTRYPOINT [ "docker-typo3-entrypoint" ]
```
```shell
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
```
where setting `set -ex` in the custom entrypoint script reveals
```shell
php_1      | + '['  '!='  ]
php_1      | + exec
```

**Comment by wglambert** [comment]
Overriding the entrypoint also clears the default command, try adding in `CMD ["php-fpm"] `

**Comment by alexander-nitsche** [comment]
Thank you very much, this has been the solution.

**Comment by phy25** [comment]
You can close the issue if this is resolved.
