### ISSUE TITLE
Need Php Sockets

### ISSUE THREAD

**Issue by JStyle21** [docker-library/php#954]
Hi,

I need the php socket library on my container and i've used the php:7.4.2-apache image which is based on debian 10 (buster), based on my searches i think i need the php-common package but after doing anything possible to try and install it , it just doesn't work, i have no idea why since it's included in the official stable repo and i've tried with other repo's as well...

https://packages.debian.org/buster/php-common

`
root@b9dea2c684f2:/var/www/html# apt install php-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-common' has no installation candidate

`

This is exactly as this thread i found
https://unix.stackexchange.com/questions/542865/cannot-install-debian-packages/542871

**Comment by phy25** [comment]
This is intentional: https://github.com/docker-library/docs/tree/master/php#e-package-php-xxx-has-no-installation-candidate

> The *proper* solution to this error is to either use `FROM debian:XXX` and install Debian's PHP packages directly, or to use `docker-php-ext-install`, `pecl`, and/or `phpize` to install the necessary additional extensions and utilities.

**Comment by JStyle21** [comment]
Thank you! i had no idea this was intentional
I think adding a link to the github wiki on the docker hub page would be a nice move too.

**Comment by phy25** [comment]
This is on the Docker Hub page btw.

**Comment by JStyle21** [comment]
Never Mind, i'm an idiot :)
