### ISSUE TITLE
docker-php-source delete doesnt work on 7.2-fpm-alpine

### ISSUE THREAD

**Issue by fionera** [docker-library/php#970]
When trying to install extensions on 7.2-fpm-alpine it always fails with the following message:

```
rm: can't remove '/usr/src/php/sapi/phpdbg/tests': Directory not empty
rm: can't remove '/usr/src/php/ext/standard/tests/network': Directory not empty
rm: can't remove '/usr/src/php/ext/standard/tests/url': Directory not empty
rm: can't remove '/usr/src/php/ext/mysqlnd': Directory not empty
rm: can't remove '/usr/src/php/ext/phar/tests/tar/files': Directory not empty
rm: can't remove '/usr/src/php/ext/phar/tests/cache_list/files': Directory not empty
rm: can't remove '/usr/src/php/ext/mbstring/oniguruma/src': Directory not empty
rm: can't remove '/usr/src/php/ext/hash/tests': Directory not empty
rm: can't remove '/usr/src/php/ext/gmp/tests': Directory not empty
rm: can't remove '/usr/src/php/ext/xsl/tests': Directory not empty
rm: can't remove '/usr/src/php/ext/gd/libgd': Directory not empty
rm: can't remove '/usr/src/php/ext/soap/tests/soap12': Directory not empty
rm: can't remove '/usr/src/php/ext/soap/tests/interop/Round3/GroupD': Directory not empty
rm: can't remove '/usr/src/php/Zend/tests/return_types': Directory not empty
rm: can't remove '/usr/src/php/tests/output': Directory not empty
```

This can be reproduced by the following steps:

```
docker run -it --rm php:7.2-fpm-alpine /bin/sh
docker-php-source extract
docker-php-source delete
```

**Comment by yosifkit** [comment]
I am unable to reproduce.
```console
$ docker run -it --rm php:7.2-fpm-alpine sh
/var/www/html # docker-php-source extract
/var/www/html # docker-php-source delete
/var/www/html # ls /usr/src/
php.tar.xz      php.tar.xz.asc
```

Are you running this on a CentOS host? Could be issue [27214](https://github.com/moby/moby/issues/27214) in Docker; this [comment](https://github.com/moby/moby/issues/27214#issuecomment-315185785) has a solution.


Possibly related to https://github.com/docker-library/tomcat/issues/123, and https://github.com/docker-library/php/issues/652, or maybe https://github.com/docker-library/busybox/issues/77

**Comment by chrBrd** [comment]
This is _somewhere_ upstream, possibly the XFS implementation in the kernel.

I'm getting the same issue with 7.4-fpm-alpine on openSUSE Tumbleweed with `var` mounted on an XFS LV (which has d_type support enabled). 

Thing work as expected on a Tumbleweed install with `var` mounted on a BTRFS LV.

**Comment by fionera** [comment]
I am currently running it on NixOS with ZFS as filesystem. I am testing now with the related issues. Thanks

**Comment by fionera** [comment]
Ok that was closed too fast :) I just checked my `docker info` and it is running with xfs as backing filesystem...

```
 Server Version: 19.03.5
 Storage Driver: devicemapper
  Pool Name: docker-0:28-730553-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 28.76GB
  Data Space Total: 107.4GB
  Data Space Available: 78.61GB
  Metadata Space Used: 39.76MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.108GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.153 (2018-10-31)
```

**Comment by fionera** [comment]
OK I now cant replicate it anymore after the last system update. So it is probably fixed.

**Comment by HaaseIT** [comment]
This is related to:
https://bugzilla.redhat.com/show_bug.cgi?id=1820944
Kernel 5.5 and 5.6 apparently have issues, if the docker overlay filesystem is on xfs.
My workaround is to add another partition with ext4 and mount it to /var/lib/docker.
