### ISSUE TITLE
Can not find openssl library

### ISSUE THREAD

**Issue by risestar0927** [docker-library/php#972]
I set up docker image with PHP 7.4 IMAP extension and i am getting this error.

checking for IMAP support... yes, shared
checking for IMAP Kerberos support... yes
checking for IMAP SSL support... yes
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE... yes
checking for pam_start in -lpam... yes
checking for crypt in -lcrypt... yes
checking for krb5-gssapi krb5... yes
configure: error: OpenSSL libraries not found.

      Check the path given to --with-openssl-dir and output in config.log)

**Comment by risestar0927** [comment]
I had a look at the similar issue here but that does not make sense to me.
https://github.com/docker-library/php/issues/891
Can anybody give me a little more detailed solution?

**Comment by phy25** [comment]
How did you install IMAP extension (by which command)? Did you try https://github.com/docker-library/php/issues/891#issuecomment-531023107 ?

**Comment by wglambert** [comment]
Were you able to resolve this issue?

If not then if you could give the commands you ran and any relevant contextual information or files for reproducing the issue that would help with troubleshooting
