### ISSUE TITLE
php:7.4.4-apache and installation php7.4-cgi

### ISSUE THREAD

**Issue by krajcikondra** [docker-library/php#976]
I am solving problem with installation php7.4-cgi. Here is dockerfile for demonstate my problem. Image is based on Debian 10

    
    FROM php:7.4.4-apache
    
    RUN apt update
    RUN apt-get install wget lsb-release -y
    RUN apt-get -y install apt-transport-https  ca-certificates curl
    RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/>
    RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) ma>
    RUN apt-get update && apt-get install php7.4-cgi -y

I found out php7.4-cgi is virtual package

    root@3004fd5ee36a:/var/www/html# apt search php7.4-cgi
    Sorting... Done
    Full Text Search... Done
    php7.4-cgi/unknown 7.4.4-1+0~20200320.15+debian10~1.gbpf8dc20 amd64
      (none)
    
    php7.4-cgi-dbgsym/unknown 7.4.4-1+0~20200320.15+debian10~1.gbpf8dc20 amd64
      (none)

    root@3004fd5ee36a:/var/www/html# apt show php7.4-cgi
    Package: php7.4-cgi
    State: not a real package (virtual)
    N: Can't select candidate version from package php7.4-cgi as it has no candidate
    N: There is 1 additional record. Please use the '-a' switch to see it
    N: No packages found

It is some way to install php7.4-cgi?

**Comment by phy25** [comment]
Please read https://github.com/docker-library/php/pull/649 and https://github.com/docker-library/docs/blob/master/php/README.md#e-package-php-xxx-has-no-installation-candidate

Does that help?

**Comment by krajcikondra** [comment]
Great, it helps. Thanks :-)
