### ISSUE TITLE
interbase core extension cannot be installed or enabled

### ISSUE THREAD

**Issue by rimas-kudelis** [docker-library/php#977]
Hi,
I'm using [kafoso/doctrine-firebird-driver](https://github.com/kafoso/doctrine-firebird-driver) in the project I'm working on. It uses `ibase_*` functions for interacting with Interbase and/or Firebird. However, these functions don't seem to be available by default.

I tried installing/enabling the relevant PHP extension, but neither `docker-php-ext-configure interbase`, nor `docker-php-ext-enable interbase` work with the Buster-based 7.4 image. I'm getting this at the end of the error message:
```
Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlrpc xmlwriter xsl zend_test zip
```
As you can see, neither `ibase`, nor `interbase` are in the list (although `pdo_firebird` is). Would it be possible to make `interbase` available too? [PHP documentation](https://www.php.net/manual/en/ibase.requirements.php) says there are no extra dependencies that it needs.

**Comment by tianon** [comment]
Looks like this was intentionally removed in PHP 7.4: https://wiki.php.net/rfc/deprecate-and-remove-ext-interbase

**Comment by rimas-kudelis** [comment]
Oh...
I guess this is a bug in PHP documentation where this fact is not mentioned then.
Thanks!
