### ISSUE TITLE
Unable to install imap extension:Kerberos libraries not found.

### ISSUE THREAD

**Issue by jiahuanle** [docker-library/php#978]
#### My docker file is as below

> FROM php:5.6-nginx

#### The build command response is as below
> RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl  && docker-php-ext-install imap
#### Info
> Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for IMAP support... yes, shared
checking for IMAP Kerberos support... yes
checking for IMAP SSL support... yes
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE...
checking for pam_start in -lpam... yes
checking for crypt in -lcrypt... yes
checking for krb5-config... no
configure: error: Kerberos libraries not found.
 Check the path given to --with-kerberos (if no path is given, searches in /usr/kerberos, /usr/local and /usr )

**Comment by jiahuanle** [comment]
#### attempt
>  mkdir -p /lib/kerberos
ln -s /usr/lib/x86_64-linux-gnu/ /usr/kerberos/lib
ln -s /usr/lib64/x86_64-linux-gnu/ /usr/kerberos/lib64

outcome is the same

**Comment by phy25** [comment]
Have you tried this: https://gist.github.com/shyd/a03bdddb1fe4363d102c4f34822c5be0

```$ apt-get install -y libc-client-dev libkrb5-dev```

**Comment by jiahuanle** [comment]
> Have you tried this: https://gist.github.com/shyd/a03bdddb1fe4363d102c4f34822c5be0
> 
> `$ apt-get install -y libc-client-dev libkrb5-dev`

Thank you. is fine
