### ISSUE TITLE
Can we expect alpine images for apache?

### ISSUE THREAD

**Issue by nimabrownlee** [docker-library/php#981]
Is there any plans to do it or should we do it ourselves? If so, is there any guidelines for someone that has only been in the docker/server world for a short time. I am trying to create a small production image because the current php-apache is around 500 MB.

**Comment by wglambert** [comment]
https://github.com/docker-library/php/issues/259#issuecomment-232489724
>Currently I think it is because the `apache` part is taken directly from Debian and so it has things that users are used to existing in their php/apache world, which would not necessarily be the case in an alpine version.  Also, since the Alpine variants exist mostly for size concerned users, then they would be better served with `fpm` and something like `nginx` in front of it.


https://github.com/docker-library/php/issues/259#issuecomment-353680118
>Given the complexity involved in duplicating Debian's Apache configuration and usage for Alpine, I don't think this is going to be solved any time soon.

>The best advice I can give is to either use the Debian version (since the size difference is not _that_ dramatic, given today's normal storage and bandwidth availability), or to use FPM (which is also much more in the spirit of Alpine's minimalism).  Thanks! :heart:

**Comment by darksaboteur** [comment]
I've just opened a PR with this functionality https://github.com/docker-library/php/issues/981

I have a project that I would prefer to use apache rather than nginx and the debian based apache variant is quite a large image. Given the changes were relatively minor to get this running I hope it can be accepted

**Comment by tianon** [comment]
Sorry for the delay!  Unfortunately, this isn't something we plan to implement/support/maintain.
