### ISSUE TITLE
Keep Apache version up-to-date (use Docker httpd official package)

### ISSUE THREAD

**Issue by laukstein** [docker-library/php#983]
Please keep Apache version up-to-date, same with PHP. Should use [Docker **httpd** official package](https://github.com/docker-library/httpd) always containing the latest version, see its [Dockerfile](https://github.com/docker-library/httpd/blob/master/2.4/Dockerfile).

Current **php:apache** package contains Apache v2.4.38, while the latest version is v2.4.43, can follow-up releases in https://github.com/apache/httpd/releases

Related issue https://github.com/docker-library/php/issues/619#issuecomment-379033685 suggesting same solution.

**Comment by yosifkit** [comment]
> That would be a fairly large breaking change, not to mention a large increase in the already incredibly-long compilation times for our many, many variants of PHP.
>
>Since this repository is focused on providing a PHP experience close to what PHP upstream recommends, we opted for using Debian's Apache packages (especially since the way Debian sets up Apache is very commonly understood by PHP developers in general).
>
> https://github.com/docker-library/php/issues/619#issuecomment-379034707
