### ISSUE TITLE
support for s390x architecture

### ISSUE THREAD

**Issue by Ron-Burg** [docker-library/php#984]
generate-stackbrew-library.sh has the following code to exclude s390x:
`# 7.2 no longer supports s390x
			# #error "Not yet implemented"
			# https://github.com/docker-library/php/pull/487#issue-254755661
			variantArches="$(echo " $variantArches " | sed -r -e 's/ s390x//g')"`
I guess it was fixed in later relases of php because now I was able to successfully run the test/run.sh on all variations on an actual s390x machine.
The script right now blocks the support for this arch.

Could this be removed and tested on the production build servers?

**Comment by yosifkit** [comment]
Oh, nice. Just smoke testing a few and the images I tried are working fine (`7.1/buster/apache`, `7.2/buster/apache`, `7.4/alpine3.11/cli/`, `7.4/buster/cli/`).

Looks like they noticed a while back, but we didn't see the fix: https://github.com/php/php-src/pull/2789. I'm not certain which versions of php it was applied to, but it seems safe to say they all have it.

Let's do this!
