### ISSUE TITLE
Offer "master" php branch build

### ISSUE THREAD

**Issue by mvorisek** [docker-library/php#991]
Important as this images are used a lot for CI and it is desired to test against master/nighty PHP build.

Rebuild every hour or so.

**Comment by wglambert** [comment]
https://github.com/docker-library/php/issues/825#issuecomment-490177232

>https://github.com/docker-library/julia/issues/25#issuecomment-434867037
Similar issues: https://github.com/docker-library/official-images/issues/1281, https://github.com/rust-lang-nursery/docker-rust/issues/5, https://github.com/docker-library/docker/issues/125

> Any `nightly` or `dev` image in the official images would still need to maintain the repeatability aspect.  All builds make heavy use of docker build cache so if the `RUN` line does not change, the image would not change.  Base images get updates and cause dependent images to rebuild and we don't want those situations to cause a version bump to the main software of the image.  The only other time an image gets built is via a commit in official-images that changes the respective `library/` file.  `eggdrop` is one image that has a `develop` build that they update once in a while (like https://github.com/docker-library/official-images/pull/3051).

Nightly builds aren't something we can feasibly maintain

---

https://github.com/docker-library/php/issues/825#issuecomment-492011060
>That's definitely something we're hip about, and have provided in the past (see also https://github.com/docker-library/php/blob/e63194a0006848edb13b7eff5a7f9d790d679428/update.sh#L55-L82 for where in `update.sh` we still have logic for scraping pre-releases).

>Once PHP 7.4.0alpha1 drops, we'll be looking to include it. :+1:

>I'm going to close this though since there's nothing actionable right now given that we really can't do proper nightly builds effectively.  That being said, it shouldn't be too hard for someone to take our `Dockerfile` and create an image that mirrors ours but builds directly from a specific commit from upstream and publish/maintain it under a separate organization for users to consume. :+1:

**Comment by mvorisek** [comment]
@wglambert What is the real issue building image directly from php-src master branch and deploying it if the tests pass?

**Comment by tianon** [comment]
@mvorisek there's not a technical issue with creating a `Dockerfile` which builds from upstream's `master` branch (it's probably pretty easy to adapt our `Dockerfile`s to do so, really) -- the problem is that in the context of the official images program (which this repository's image is part of), that's not something we can maintain

What I would suggest is someone create this as a side project.

I'd recommend embedding a specific commit in your `Dockerfile` so that cache busts on updates happen automatically, but that's not strictly necessary to get something working.

**Comment by mvorisek** [comment]
Currently, 8.0 branch is cut and it seems there is no official way now to test easily against php `master`, aka nighty php.

The should be simply an easy way to add testing against nighty php. We do not have to build the images like after every push to php `master`, but instead we can build/push daily, thus cache can be used for at least 24h.
