### ISSUE TITLE
<Question>are we not going to publish stretch images any more?

### ISSUE THREAD

**Issue by arroyc** [docker-library/php#992]
from 7.4 onward seems like stretch will not be published …

**Comment by yosifkit** [comment]
Historical context and comment:

> We do not want to maintain our PHP images over multiple distro releases in the long term.
>
> \- https://github.com/docker-library/php/issues/504#issue-262626340

Debian Stretch reaches "end of life" this year (probably June, https://wiki.debian.org/DebianReleases) and will then enter "Debian LTS", but we do not want to encourage users to use Stretch at that point, unless they are invested.

> Companies using Debian who are benefitting from this project are encouraged to either help directly or contribute financially. The number of packages which is properly supported depends directly on the level of support that we get.
>
> \- https://wiki.debian.org/LTS

**Comment by mhenke1** [comment]
The 7.4 image based in buster updates some OS dependencies to later versions (libicu and postgresql-server-dev).
Any ideas whether we should upgrade those too ?
