### ISSUE TITLE
<Question>update apache versions embedded in php images

### ISSUE THREAD

**Issue by arroyc** [docker-library/php#993]
php stretch images seems to have apache 2.4.25, php apache images have 2.4.34 but current apache is 2.4.43. What is the best/standard way to keep apache  updated if you are using a stretch/apache based php image.

**Comment by yosifkit** [comment]
The images use Apache httpd from Debian packages, so unless you move to a newer release of Debian you will not get a newer Apache httpd. Currently, the `7.3-apache` tag is Debian Buster based (alternative tag is available as `7.3-apache-buster`) versus the `7.3-apache-stretch` tag which is based on Debian Stretch.

> Since this repository is focused on providing a PHP experience close to what PHP upstream recommends, we opted for using Debian's Apache packages (especially since the way Debian sets up Apache is very commonly understood by PHP developers in general).
>
> https://github.com/docker-library/php/issues/619#issuecomment-379034707
