### ISSUE TITLE
How to disable unused php base extensions

### ISSUE THREAD

**Issue by laukstein** [docker-library/php#995]
`php:fpm-alpine` adds bunch of extensions.
How can I remove or at least disable extension that I don't want to use: ftp, sqlite3, pdo_sqlite and more?

After all extensions disabled in php.ini, here is the list what php modules still are running:

```
# php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]
```

I have noticed that also proposed https://github.com/docker-library/php/issues/220 has been rejected.

Know when installed php with `apk add php` it will result not so long list of php modules:

```
# php -m
[PHP Modules]
Core
date
filter
hash
libxml
pcre
readline
Reflection
SPL
standard
zlib

[Zend Modules]
```

**Comment by yosifkit** [comment]
These are likely not compiled as separate extensions; see the flags to configure for why each is included:

https://github.com/docker-library/php/blob/d8bb468ec3a1e3ff5ad910ee8db02d9a6615d6de/Dockerfile-alpine.template#L116-L154

**Comment by Aielen** [comment]
But why you want to do this?

**Comment by phy25** [comment]
Have you read the template comments to see why those are included?

**Comment by laukstein** [comment]
@phy25 I think clean build shouldn't add any extensions that php couldn't run without, especially not in a way without ability yo remove or disable it. I consider it as docker php package bug.

There are other docker images offering to define list of wished php extensions in docker-compose.yml arguments that would auto install it without breaking on dependencies like this php image, that tries to workaround falling into this issue or in errors by missing dependent packages. Hope we can make things better.

**Comment by tianon** [comment]
The things we enable/include by default are either defaults from PHP itself or are somewhere between _very_ difficult and impossible to install after-the-fact.

If there are specific things that are causing problems or that there is a compelling argument for adding explicit code to remove from that default PHP set, we're willing to consider them, but please keep in mind that we strive to represent/implement upstream's official recommendations as closely as we possibly can, so proposals which remove things from PHP's own default set are going to have to come with some pretty compelling justification. :+1:
