### ISSUE TITLE
[Question] Modifying Apaches Port in Dockerfile?

### ISSUE THREAD

**Issue by GuyMight44** [docker-library/php#997]
I have this very simple Dockerfile here:
`FROM php:7.3-apache `
`
RUN docker-php-ext-install mysqli`

This works well as is but one thing I would like to do is modify the port from WITHIN the Dockerfile. Where is the file located which hosts the port so I could change it?

**Comment by phy25** [comment]
See #771, #174, and [probably more](https://github.com/docker-library/php/issues?q=port).
