### ISSUE TITLE
Update to PHP v7.4.5

### ISSUE THREAD

**Issue by laukstein** [docker-library/php#998]
Yesterday was released PHP v7.4.5, see https://github.com/php/php-src/releases
I recommend you fallow PHP releases feed https://github.com/php/php-src/releases.atom to keep up to date, maybe even can create script that automatically captures and applies the latest version.

**Comment by tianon** [comment]
7.4.5 is tagged, but it isn't released yet (official source bundles are not yet available, see https://www.php.net/downloads for example).

We have a script which scrapes releases automatically (https://github.com/docker-library/php/blob/d8bb468ec3a1e3ff5ad910ee8db02d9a6615d6de/update.sh, https://doi-janky.infosiftr.net/job/update.sh/job/php/), and it uses the official PHP releases API (and QA releases API for pre-releases):

https://github.com/docker-library/php/blob/d8bb468ec3a1e3ff5ad910ee8db02d9a6615d6de/update.sh#L53-L80

As soon as this release is officially published, our automated job will pick it up, do a full build test of all variants, and push a commit here ready for PR to https://github.com/docker-library/official-images.

For more information about our process and automation, see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what.

**Comment by GrahamCampbell** [comment]
> 7.4.5 is tagged, but it isn't released yet (official source bundles are not yet available, see https://www.php.net/downloads for example).

Yes they are?

![image](https://user-images.githubusercontent.com/2829600/79575084-21a52e80-80b9-11ea-97d0-f4651929d3d3.png)

**Comment by laukstein** [comment]
https://www.php.net/releases/index.php?json&max=100 has info about php v7.4.5 while this docker package still has v7.4.4.
Is php/update.sh triggered and working as expected?

**Comment by laukstein** [comment]
Ignore, it is now having v7.4.5 =)
